### ISSUE TITLE
关于文件上传的配置

### ISSUE THREAD

**Issue by gaojunyang666** [Dooy/chatgpt-web-midjourney-proxy#100]
开发者您好，各位朋友好，我已经注册好了R2存储桶并且绑定了自己的域名，但是我把这个域名填写到那个设置窗口中，上传文件一直提示network error,请问是我填写错误导致的吗，应该如何进行填写

**Comment by Dooy** [comment]
自己设置 一个域名进去

<img width="456" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/06936cad-9cd6-4a6c-aa68-3a3ca7876ee9">

**Comment by gaojunyang666** [comment]
请问不能通过UI前端的那个 上传地址来实现吗
![Uploading Image_1706009628240.jpg…]()

**Comment by Dooy** [comment]
可以的
 readme 也有说明 
需要跨域并返回一定的格式
<img width="647" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/81710c3f-b4b8-48b4-9213-ecf9eadcf4b8">

**Comment by gaojunyang666** [comment]
您已经说的很明白了，但是我还是不理解这个上传地址里面究竟要按照什么样的格式填写什么，可以请您再说的具体一些吗，假如我的Cloudflare的R2存储桶已经搭建好了，公开访问链接为https://123.com，我应该如何去设置，感谢您的帮助，祝您新年快乐

**Comment by Dooy** [comment]
R2存储 跟上传地址 是2种上传方式 
你设置好 R2存储 就不管前端的上传地址了
还有 vercel 不支持

**Comment by gaojunyang666** [comment]
是的，我是使用服务器docker搭建的，想求教这个“上传地址”这种方式如何构建或者实现

**Comment by Dooy** [comment]
就上传后端自己来实现 用Java php 或者node.js 都可以

**Comment by gaojunyang666** [comment]
好的，非常感谢您，祝您新年快乐

**Comment by Dooy** [comment]
我自己简单写了 一个

https://hub.docker.com/repository/docker/ydlhero/file-server/general

但是没有配置说明

**Comment by gaojunyang666** [comment]
好嘞，我研究研究

**Comment by ChuckZengxf** [comment]
搞好了吗兄弟  我也是这个情况

**Comment by ChuckZengxf** [comment]
> 看置顶帖 #178

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/86394244/8eaf073d-806f-4689-b87b-cbdb6b16b06e)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/86394244/96cbe2bc-bc9b-4fec-9a24-3b3b681fc55c)
ti好像提示签名不对，但是这几个配置难道不对吗？麻烦给指导一下
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/86394244/59b6c875-38ff-4be7-bf08-0bec2fa9a454)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/86394244/d423c9e6-e377-418d-b7d5-d46b64c5c48e)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/86394244/d7c5ff8f-683b-43c5-8a4c-f1f37304b0f6)
