### ISSUE TITLE
作者您会考虑，下个版本更新gpts里的插件吗

### ISSUE THREAD

**Issue by lalagit1** [Dooy/chatgpt-web-midjourney-proxy#101]
目前的界面真的越来越好用了，但是gpts里的插件有点少，您能不能考虑更新下呀。

**Comment by Dooy** [comment]
可以的 有时间更新下
可以通过 超链模型切换

✅ 支持ChatGPT试的超链模型切换 https://chat.openai.com/g/g-2fkFE8rbu 修改为 https://vercel.ddaiai.com/#/g/g-2fkFE8rbu

**Comment by Dooy** [comment]
gptshunter的或者gpts.works 他们有对外开放接口？

**Comment by Dooy** [comment]
目前定期更新，下线的GPTs 会做下线处理
