### ISSUE TITLE
想问一下为什么我这无法使用gpts，正常gpt可以调用

### ISSUE THREAD

**Issue by sylarrrm** [Dooy/chatgpt-web-midjourney-proxy#102]
正常的gpt 3.5 4 都可以用但是 用了gpts就显示模型不存在呢
{
  "error": {
    "message": "The model `gpt-4-gizmo-g-OJWqJKLiE` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}

**Comment by TiMi518** [comment]
需要你的api支持gpts才行

**Comment by sylarrrm** [comment]
> 需要你的api支持gpts才行

这个要怎么升级呀

**Comment by Dooy** [comment]
找个中转支持GPTs的

你可以参与 这个issue #28 就知道 GPTs咋来的了
