### ISSUE TITLE
AUTH_SECRET_KEY is not defined

### ISSUE THREAD

**Issue by superDaian** [Dooy/chatgpt-web-midjourney-proxy#103]
作者大佬您好，我在尝试部署您的项目时发现出现了一个问题，无法配置AUTH_SECRET_KEY字段来为web前端设置访问密码，报错内容如下：
[eval]:1
AUTH_SECRET_KEY
^
ReferenceError: AUTH_SECRET_KEY is not defined
    at [eval]:1:1
    at runScriptInThisContext (node:internal/vm:144:10)
    at node:internal/process/execution:109:14
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:92:62)
    at evalScript (node:internal/process/execution:123:10)
    at node:internal/main/eval_string:51:3
Node.js v20.11.0

**Comment by Dooy** [comment]
是docker 么？
啥环境

**Comment by superDaian** [comment]
对的，docker环境

**Comment by Dooy** [comment]
解决了否 ？
docker 启动命令 说下

**Comment by superDaian** [comment]
docker run --name chatgpt-web-midjourney-proxy  -d -p 60124:3002 -e OPENAI_API_KEY=<密钥> -e OPENAI_API_BASE_URL=<接口>  -e MJ_SERVER=https://172.17.0.1:6013  -e API_UPLOADER=1  -v /data/uploads:/app/uploads -e MJ_API_SECRET=abc123456  ydlhero/chatgpt-web-midjourney-proxy -e AUTH_SECRET_KEY=hzNwi*dTuU%Eyk1#
报错信息为：

**Comment by superDaian** [comment]
docker run --name chatgpt-web-midjourney-proxy -d -p 60124:3002 -e OPENAI_API_KEY=<密钥> -e OPENAI_API_BASE_URL=<接口> -e MJ_SERVER=https://172.17.0.1:6013/ -e API_UPLOADER=1 -v /data/uploads:/app/uploads -e MJ_API_SECRET=abc123456 ydlhero/chatgpt-web-midjourney-proxy -e AUTH_SECRET_KEY=hzNwi*dTuU%Eyk1#
报错信息为：
[eval]:1
AUTH_SECRET_KEY=hzNwi
^
ReferenceError: hzNwi is not defined
    at [eval]:1:1
    at runScriptInThisContext (node:internal/vm:144:10)
    at node:internal/process/execution:109:14
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:92:62)
    at evalScript (node:internal/process/execution:123:10)
    at node:internal/main/eval_string:51:3
Node.js v20.11.0

**Comment by superDaian** [comment]
尚未解决，排查不出问题所在

**Comment by superDaian** [comment]
docker run --name chatgpt-web-midjourney-proxy -d -p 60124:3002 -e OPENAI_API_KEY=<密钥> -e OPENAI_API_BASE_URL=<接口> -e MJ_SERVER=https://172.17.0.1:6013/ -e API_UPLOADER=1 -v /data/uploads:/app/uploads -e MJ_API_SECRET=abc123456 ydlhero/chatgpt-web-midjourney-proxy -e AUTH_SECRET_KEY=hzNwi
报错信息为：
[eval]:1
AUTH_SECRET_KEY=hzNwi
^
ReferenceError: hzNwi is not defined
at [eval]:1:1
at runScriptInThisContext (node:internal/vm:144:10)
at node:internal/process/execution:109:14
at [eval]-wrapper:6:24
at runScript (node:internal/process/execution:92:62)
at evalScript (node:internal/process/execution:123:10)
at node:internal/main/eval_string:51:3
Node.js v20.11.0


删掉最后的"-e AUTH_SECRET_KEY=hzNwi"部分就正常了

**Comment by Dooy** [comment]
docker run --name chatgpt-web-midjourney-proxy -d -p 60124:3002 -e OPENAI_API_KEY=<密钥> -e OPENAI_API_BASE_URL=<接口> -e MJ_SERVER=https://172.17.0.1:6013/ -e API_UPLOADER=1 -v /data/uploads:/app/uploads -e MJ_API_SECRET=abc123456  `-e AUTH_SECRET_KEY=hzNwi` ydlhero/chatgpt-web-midjourney-proxy

位置放错了
