### ISSUE TITLE
新增提交格式检查处理

### ISSUE THREAD

**Issue by zaohuayudie** [Dooy/chatgpt-web-midjourney-proxy#104]
我新增格式化处理+commit检查格式，是否加我到组让我提交？账号：zaohuayudie或zaohuayudie@gmail.com

**Comment by Dooy** [comment]
能PR上来么？

**Comment by zaohuayudie** [comment]
> 能PR上来么？

提示没权限，我是新建的分支处理的。你设置下看如何让其他能提PR

**Comment by Dooy** [comment]
都能PR呀, 权限我控制不了啊  你找下git相关的文档看看

**Comment by zaohuayudie** [comment]
> 都能PR呀, 权限我控制不了啊 你找下git相关的文档看看

你这个仓库我提交不上去，我自己的就可以，我周末继续看下哈
