### ISSUE TITLE
以后会可能做跨平台的桌面端应用吗？

### ISSUE THREAD

**Issue by paopaotang001** [Dooy/chatgpt-web-midjourney-proxy#107]
做的真好，以后会可能做跨平台的桌面端应用吗？作为一个私人 ChatGPT 应用，很期待

**Comment by Dooy** [comment]
目前没有这样的开发计划

**Comment by Dooy** [comment]
已经支持 桌面版本 
可以到 https://github.com/Dooy/chatgpt-web-midjourney-proxy/releases 下载最新的
