### ISSUE TITLE
我想分享给我同事用, 请问可以设置密码吗

### ISSUE THREAD

**Issue by a0x5b22bbb** [Dooy/chatgpt-web-midjourney-proxy#108]
我想分享给我同事用, 请问可以设置密码吗

**Comment by a0x5b22bbb** [comment]
还没测试, 我是指 设置多个密码, 我不希望我查询的东西被别人看到

**Comment by Dooy** [comment]
可以啊 `AUTH_SECRET_KEY ` 就是设置密码的
2人的对话信息隔离的

**Comment by cyjyyd** [comment]
> 可以啊 `AUTH_SECRET_KEY ` 就是设置密码的 2人的对话信息隔离的

这个密码是只能设置一个密码吗，我试了下用逗号分隔填入多个密码，结果进不去了
