### ISSUE TITLE
docker部署的文件上传问题

### ISSUE THREAD

**Issue by OnePerson2020** [Dooy/chatgpt-web-midjourney-proxy#11]
请问使用docker部署，并且在ui界面设置 OPENAI_API_KEY OPENAI_API_BASE_URL后，如何不修改文件上传地址呢？（使用的代理openai api，这个代理没有文件上传的功能）

**Comment by Dooy** [comment]
后面看看 ；把上传服务单独分开，目前是随着 OPENAI_API_BASE_URL 走的

**Comment by OnePerson2020** [comment]
好的，谢谢！（回复真的好及时hhhh赞！）

**Comment by Dooy** [comment]
v2.12.5 已经更新上来了 ，前端UI的服务器UI设置多了 `上传地址`

**Comment by glhhello** [comment]
> v2.12.5 已经更新上来了 ，前端UI的服务器UI设置多了 `上传地址`

没升级前我还可以上传，升级后我把之前的地址复制进去提示404或者405错误，是怎么回事呀大佬

**Comment by Dooy** [comment]
需要 带上 路径 `https://abc.com/openapi/v1/upload`

**Comment by glhhello** [comment]
> 需要 带上 路径 `https://abc.com/openapi/v1/upload`

带上了也不行，是不是我还得输入那个命令curl -X POST -H "Content-Type: multipart/form-data" -F "file=@/path/to/file" 。。。这个？但是这个命令执行不成功，，上个版本倒是没执行这个任务。

**Comment by glhhello** [comment]
> 需要 带上 路径 `https://abc.com/openapi/v1/upload`

大佬，是因为PUT或者PATCH请求方式的事情么

**Comment by Dooy** [comment]
先用curl 看能上传否
```shell
curl -X POST -H "Content-Type: multipart/form-data" -F "file=@/path/to/file" \
 https://abc.com/openapi/v1/upload 
```
 `https://abc.com/openapi/v1/upload`   你自己的地址 ，
如果是docker的话 把他变为 https://abc.com 变为你的 `http://ip:port/openapi/v1/upload` 


目前只只能是post 不支持 put patch

返回格式
```json
{
"url":"https://xxxxxxx.jpg"
}
```

**Comment by glhhello** [comment]
> 先用curl 看能上传否
> 
> ```shell
> curl -X POST -H "Content-Type: multipart/form-data" -F "file=@/path/to/file" \
>  https://abc.com/openapi/v1/upload 
> ```
> 
> `https://abc.com/openapi/v1/upload` 你自己的地址 ， 如果是docker的话 把他变为 https://abc.com 变为你的 `http://ip:port`
> 
> 目前只只能是post 不支持 put patch
> 
> 返回格式
> 
> ```json
> {
> "url":"https://xxxxxxx.jpg"
> }
> ```

我发现我点了个恢复默认就好使了，所以默认是什么呀。。。大佬

**Comment by glhhello** [comment]
> openapi/v1/upload

解决了，谢谢大佬，我抓了个包抓到了。。。辛苦
