### ISSUE TITLE
求大佬支持tts换音色

### ISSUE THREAD

**Issue by gaojunyang666** [Dooy/chatgpt-web-midjourney-proxy#112]
tts也是咱们的重要功能之一，但是不能换音色属实有写遗憾，恳请大佬适配一下音色切换

**Comment by Dooy** [comment]
已经列入开发计划

**Comment by Dooy** [comment]
v.2.14.10 已经支持
在more 里面 
<img width="651" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/33e74f8b-20fd-4614-acb3-1afd8d34ca4c">

**Comment by gaojunyang666** [comment]
谢谢作者大大！祝您新年快乐！！！
