### ISSUE TITLE
bug出现于上下文识别错误

### ISSUE THREAD

**Issue by zyyint** [Dooy/chatgpt-web-midjourney-proxy#113]
![9d28764c06ebb93c70da619c8e24577](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/1f6650d4-58ef-42d0-8b58-36e00c6d4b65)
卡出了自动吸取了聊天记录上下文的全部，作为提示
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/4e57d648-c65b-4078-9c82-a4e38a456970)

**Comment by Dooy** [comment]
额 这个 咋出现都不清楚 上下文这么大么？

**Comment by zyyint** [comment]
估计是卡了，点进去就这样。，清除对话记录又恢复了。

**Comment by zyyint** [comment]
有复现过两次。

**Comment by Dooy** [comment]
新版是否还会出现？

**Comment by zyyint** [comment]
> 新版是否还会出现？

暂未发现

**Comment by zyyint** [comment]
发现问题复现情况，在重启（或者停止在启动）docker容器之后原上下文会被吸取，之后占用上下文
![a3f66a27e7d5a31a5e6b403e0e0c2fe](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/4646ecf0-505a-43fb-bb6e-27cc841b2a56)

**Comment by Dooy** [comment]
就是在 重启的 时候么？
你默认的模型有设置么？

**Comment by zyyint** [comment]
> 就是在 重启的 时候么？
> 你默认的模型有设置么？

是的，重启容器之后重新打开网站就复现了，默认模型有设置3.5t-1106

**Comment by zyyint** [comment]
![a822b606dda504dd1f628bb46e82243](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/e84221fe-d7e9-4792-8dcf-3fc4d34365ba)

**Comment by Dooy** [comment]
比较难定位到 这边 一直没复现
