### ISSUE TITLE
[ 需求 ] 能否支持开发者自己配置一个 GPTs 列表

### ISSUE THREAD

**Issue by B3nDan** [Dooy/chatgpt-web-midjourney-proxy#115]
# 需求
- 用一个格式化的 JSON 文件，由开发者(站长)自己配置经过挑选的 GPTs
- 格式化的 JSON 文件，可以包括：
-- GPTs 名称
-- 完整链接
-- GPTs ID
-- GPTs 简介
-- 分类/tags
-- 等等
- 这个 JSON 配置的列表如果也可以支持搜索那就更好了
- 当然也可以和现有的这个共存，可以通过环境变量或者什么来切换就好。

## 优点

这样的好处有两点：
1. 市面上很多 GPTs 名字起的可以，但效果很烂。精选过的 GPTs 质量肯定够的（看站长怎么测试了）
2. 之前我在其他 issue 也提到过，目前您用的 GPTs 列表中很多都是不可用的（检查发现是这个 GPTs 已无法访问，可能是作者删了），非常影响用户体验。精选过的 GPTs 肯定是能用的（起码放上去的时候，后期也可以继续维护）
3. 现在的列表里有些 GPTs 虽然能用，但是会有广告，作为站长我觉得有点不好。我如果能筛选肯定不会用这些。（除非是真的很好用，那打广告也是可接受的。）

## 缺点

可能的缺点是 时效性不强（毕竟依赖站长更新），但现在 GPTs 貌似也不是很强调时效性，反而很多 GPTs 得让很多人用了后才知道好不好。

# 另外的需求

考虑到 GPTs 会对于用户来讲有好有坏，也可能一段时间后不可用。
能否加一个 点赞/点踩 的功能呢？也可以实现您现在列表里 热度 这个功能（虽然我还不清楚这个是怎么得来的）。踩的多的 GPTs ，站长也可以考虑去除掉。
当然这个功能看您的想法了，不是什么刚需。

**Comment by Dooy** [comment]
我 也发现这个问题

就让如何更好的维护GPTs，你提的 赞跟踩的功能 挺好的方式方法
另外 如何补新的GPTs进来 你有更好想法么

**Comment by Dooy** [comment]
好的 不错的想法 后面干起来吧

**Comment by zyyint** [comment]
https://www.aishort.top/提示词仓库，望作者笑纳

**Comment by zyyint** [comment]
https://www.aishort.top/提示词仓库，望作者可以笑纳

**Comment by Dooy** [comment]
最新版本已支持自己培训了 看下readme

**Comment by Dooy** [comment]
Vercel 忘记匹配了 下版本补上

**Comment by NEPDream** [comment]
> Vercel 忘记匹配了 下版本补上

老大，我不是Vercel的，我是docker自己部署的，我在docker设置了环境变量，GPT_URL=https://cf-r2.nepzbb.live/gpts.json，但是却显示失败，截图如下，老大有空帮忙看看呗，对了咱有微信群或者qq群不，感觉有时候遇到问题，可以跟其他人讨论一下，不用啥事都麻烦老大
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/31023128/31827406-c486-4e18-a735-d4d5e35a5718)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/31023128/950a8bb3-123c-4915-a27e-de9a4c554104)

**Comment by Dooy** [comment]
v2.15.1 已支持了

**Comment by NEPDream** [comment]
> v2.15.1 已支持了

我配置好跨域规则后，已经正常了，GPT_URL功能正常。对了老大，咱们有没有微信群或者qq群呀~目前找您好像都是在github的issue上~
