### ISSUE TITLE
Run Build过后运行报错

### ISSUE THREAD

**Issue by cyjyyd** [Dooy/chatgpt-web-midjourney-proxy#116]
日志：
root@homeserver:~/chatweb# sh start.sh
Start service complete!
Start front complete!
nohup: 重定向标准错误到标准输出
nohup: 重定向标准错误到标准输出

> chatgpt-web-midjourney-proxy@2.14.9 dev /root/chatweb
> vite

  VITE v4.2.0  ready in 477 ms

  ➜  Local:   http://localhost:1002/
  ➜  Network: http://192.168.3.112:1002/
  ➜  Network: http://172.20.0.1:1002/
Error: The following dependencies are imported but could not be resolved:

  vue-waterfall-plugin-next/dist/types/types/waterfall (imported by /root/chatweb/src/views/mj/aiGalleryItem.vue?id=0)

Are they installed?
    at file:///root/chatweb/node_modules/.pnpm/vite@4.2.0_@types+node@18.14.6_less@4.1.3/node_modules/vite/dist/node/chunks/dep-c167897e.js:44586:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Timeout._onTimeout (file:///root/chatweb/node_modules/.pnpm/vite@4.2.0_@types+node@18.14.6_less@4.1.3/node_modules/vite/dist/node/chunks/dep-c167897e.js:44027:38)
pnpm install 确认过，already up to date
node版本18.19.0和20.11.0都试过了
使用npm install 手动安装依赖后问题依旧，暂时没什么头绪，还请指点一下

**Comment by Dooy** [comment]
`vue-waterfall-plugin-next/dist/types/types/waterfall (imported by /root/chatweb/src/views/mj/aiGalleryItem.vue?id=0)`

这个地方 我写得有问题
我回头更新下

**Comment by Dooy** [comment]
修改这2个地方 就好了 你试下
<img width="648" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/4d35971e-0fa6-43b8-9911-f855b9e676f4">

**Comment by cyjyyd** [comment]
好的，已经跑起来了
