### ISSUE TITLE
[ 建议 ] 清空对话应该把对话标题也清除

### ISSUE THREAD

**Issue by bbb3n** [Dooy/chatgpt-web-midjourney-proxy#117]
![Screenshot_20240127_213335](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129975925/b2f7a6ec-8c5b-48a4-8483-5ac9c24007ea)

点击这个清空对话，只会删除对话内容，这个标题“人”并没有清除。

如果作者您是故意这么设计的，那我猜想您想的是可能有人标题是手动起的，有可能是个标记。

但是我觉得，您或许可以分开成两部分设计。
大部分人这个标题应该都不是自己起的，那可以允许用户点右上角直接删除对话（就和点击左侧列表删除一样，但是手机点右上角更方便）

所以，我觉得可以设计成点右上角删除，分开成删除对话 或 仅删除聊天记录

另外，我觉得这个标题目前采用对话的第一句还不太好吧。 NextChat 的那种让ai总结一下挺好的

**Comment by Dooy** [comment]
标题也清下是不  我看如何实现

**Comment by Dooy** [comment]
v2.15.1 已支持

**Comment by Dooy** [comment]
我这是成功的 首先 应该需要有内容
<img width="543" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/f71d36d1-a80b-48cf-a46e-e3c0296624bb">

**Comment by Dooy** [comment]
好的 我再测试下
