### ISSUE TITLE
[ 需求 ] Midjourney 绘画参数中的版本问题

### ISSUE THREAD

**Issue by bbb3n** [Dooy/chatgpt-web-midjourney-proxy#118]
我看应该是默认要设置一个版本是吧。

1. 有时用户是直接复制的一个完整prompt，里面自带了版本
2. mj proxy 是可以设置默认版本的，即使前端输入的prompt没有版本

所以能否不默认填版本呢？
复制来prompt,每次还得手动删掉那个版本选项，有一点点麻烦

或者说：
能否自动识别填入的prompt，然后自动修改参数选项，输入框只保留prompt的实际内容。
（可能会有点难？）

**Comment by Dooy** [comment]
底下下有一个`清参数` 就是为了你粘贴复制

<img width="339" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/0915056a-013d-4e16-93a9-4a8e0777cdd8">
