### ISSUE TITLE
docker部署成功后，可以调用gpt-4-all模型，但是gpt4v失败

### ISSUE THREAD

**Issue by glhhello** [Dooy/chatgpt-web-midjourney-proxy#12]
"error": {
    "message": "json: cannot unmarshal array into Go value of type string (request id: 20231210124526365723669FNXpLZuA)",
    "type": "one_api_error",
    "param": "",
    "code": "count_token_messages_failed"

**Comment by Dooy** [comment]
`gpt4v` 、 `gpt-4-v` 还是 `gpt-4v`  ？你这提示不是前端问题；是后端没配置 或者你模型写错了

**Comment by glhhello** [comment]
> `gpt4v` 、 `gpt-4-v` 还是 `gpt-4v` ？你这提示不是前端问题；是后端没配置 或者你模型写错了

gpt-4-vision-preview，我在oneapi设置了这个模型，我再去试试谢谢大佬
