### ISSUE TITLE
大佬救命，图片大小限制

### ISSUE THREAD

**Issue by gaojunyang666** [Dooy/chatgpt-web-midjourney-proxy#121]
开发者大大你好，作为一名科研人员，我经常使用4-vision进行文献的图片的帮助阅读，但是我注意到图片大小限制1M，这带来了困扰，我可以找到代码中的限制在哪里，但是我不会修改，恳请开发者大大可以考虑将图片大小限制增加到docker-compose中
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/63088548/e1127960-2b6b-4a71-956f-ddad183b61ad)

**Comment by Dooy** [comment]
可以 后面改成配置选项 ，但是太大 很多服务器 也传不过去

**Comment by gaojunyang666** [comment]
嗯嗯，谢谢开发者大大

**Comment by Dooy** [comment]
2.14.10 已经支持  环境变量 `UPLOAD_IMG_SIZE=10`

**Comment by gaojunyang666** [comment]
谢谢作者大大，太宠粉啦！
