### ISSUE TITLE
使用gpts的时候报这个错误，可能是什么原因导致的

### ISSUE THREAD

**Issue by shundao-haihe** [Dooy/chatgpt-web-midjourney-proxy#125]
{
  "error": {
    "message": "The model `gpt-4-gizmo-g-YL87j8C7S` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}

**Comment by jonathanfan-ee** [comment]
你这个是接口api不支持吧

**Comment by shundao-haihe** [comment]
> 你这个是接口api不支持吧

如何才能让api支持，是需要购买plus会员么？
