### ISSUE TITLE
在微信中，手机tts转语音，无法播放

### ISSUE THREAD

**Issue by yoke1990** [Dooy/chatgpt-web-midjourney-proxy#126]
在微信中，手机tts转语音，无法播放。
电脑没问题，浏览器也可以

**Comment by yoke1990** [comment]
找到原因了，我反馈下
src/api/openapi.ts
export const subTTS = async (tts: ttsType) => {
...
const audioData = await response.arrayBuffer()
const blob = new Blob([audioData], { type: 'audio/mp3' })
...
}
改为
const blob = new Blob([audioData], { type: 'audio/mpeg' })

tts-1返回默认是audio/mpeg，在微信中会导致无法加载播放

**Comment by yoke1990** [comment]
const contentType = response.headers.get('Content-Type')
  const audioData = await response.arrayBuffer()
  const blob = new Blob([audioData], { type: contentType })

这样写更稳妥点

**Comment by Dooy** [comment]
微信没好好测试，后续版本加上你的代码

**Comment by yoke1990** [comment]
微信那个浏览器确实多事，华为浏览器也是

**Comment by Dooy** [comment]
已加入新版本 v2.15.1 再次感谢
