### ISSUE TITLE
MJ 绘画选项组合优化，减少提示词给mj提示错误

### ISSUE THREAD

**Issue by yoke1990** [Dooy/chatgpt-web-midjourney-proxy#127]
src/views/mj/aiDrawInputItem.vue
区分好 参数选项组合，描述词选项组合，用户输入

描述词选项组合=描述词1，描述词2，描述词3，
用户输入可能会是 = 一个女孩 --seed 312341243
参数选项组合= --q 0.2 --ar 3:4
描述词选项组合+用户输入+参数选项组合，减少提示词给mj提示错误
最终得到 ：描述词1，描述词2，描述词3，一个女孩 --seed 312341243 --q 0.2 --ar 3:4

之前会得到
一个女孩 --seed 312341243 ,描述词1,描述词2,描述词3 --q 0.2 --ar 3:4
导致错误

function createPrompt(rz:string){
    if( rz =='') {
        msgRef.value.showError(t('mjchat.placeInput') );
        return '';
    }
     
    let rzp='' //参数组合字符串
    let rzk=''; //描述词组合字符串
    for(let v of farr){
        if( ! f.value[v.k] || f.value[v.k]==null || f.value[v.k]=='' ) continue;
         mlog('k ', rz,  f.value  );
        if(v.k=='quality') rzp +=`  --q ${f.value.quality}`;
        else if(v.k=='styles') { if( f.value.styles ) rzp +=` ${f.value.styles} `;}
        else if(v.k=='version') {
            st.value.bot= '';
           if(['MID_JOURNEY','NIJI_JOURNEY'].indexOf(f.value.version)>-1 ){
                 st.value.bot= f.value.version ;
           } else   rzp +=` ${f.value.version}`;
        }
        else if( f.value[v.k] ) rzk +=`${f.value[v.k]},`;
    }
    
    mlog('createPrompt ', rz,  f.value  );
    if(f.value.bili>-1) rzp +=` --ar ${vf[f.value.bili].label}`;
    rz = rzk + rz +rzp;
    return rz ;
}

**Comment by Dooy** [comment]
感谢 能否pr 上来 ？这样 能体现你的贡献。

**Comment by yoke1990** [comment]
- -不用git。svn党

**Comment by Dooy** [comment]
已加入 v2.15.1 版本
