### ISSUE TITLE
[bug]针对每一个对话分别设置模型无效

### ISSUE THREAD

**Issue by gaojunyang666** [Dooy/chatgpt-web-midjourney-proxy#128]
开发者大大您好，我发现目前的版本的“仅保存会话”功能是无效的
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/63088548/4796ee78-aace-411d-a3a1-ebfc4b9bbef8)
具体而言，就是假如我在A对话中使用的是tts-1,然后我创建了新的B对话，并且对B会话指定gpt-4仅保存会话（而不是选择了保存系统），在我使用完B会话后回到A会话发送消息的时候，调用的就变成了gpt-4,而不再是我一开始对A会话设置的tts-1了。
我确定问题必然会出现而不是偶然，恳请您检查

**Comment by NEPDream** [comment]
> 开发者大大您好，我发现目前的版本的“仅保存会话”功能是无效的 ![image](https://private-user-images.githubusercontent.com/63088548/300544657-4796ee78-aace-411d-a3a1-ebfc4b9bbef8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODgzMDQsIm5iZiI6MTcwNjU4ODAwNCwicGF0aCI6Ii82MzA4ODU0OC8zMDA1NDQ2NTctNDc5NmVlNzgtYWFjZS00MTFkLWEzYTEtZWJmYzRiOWJiZWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA0MTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMjJhMTc4ODM1MzU1ZDBiZDk3OTYxYjUwNTljYzhlYjEzNDY5ZTA4N2YxNzgwZjZjZTY1NzQ0MDI0Y2VhZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CAFKE42gmPVakP5rFuGrT2wyKOwU675zICnKSiVvwSw) 具体而言，就是假如我在A对话中使用的是tts-1,然后我创建了新的B对话，并且对B会话指定gpt-4仅保存会话（而不是选择了保存系统），在我使用完B会话后回到A会话发送消息的时候，调用的就变成了gpt-4,而不再是我一开始对A会话设置的tts-1了。 我确定问题必然会出现而不是偶然，恳请您检查

你不要使用latest版本，用release版本就好了

**Comment by Dooy** [comment]
我再测试一下

**Comment by Dooy** [comment]
我测试出问题 ，应该是新版本部署上去后 
你本地有缓存， 你试下无痕 或者 ctrl+f5

**Comment by gaojunyang666** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/63088548/d9d2090c-94ce-4df3-9433-6460e8ca0375)
好的作者大大，我又进行了测试，无痕模式测试也是一样的，最新的latest镜像，切换对话后的第一次对话还会使用上一个对话的模型，应该不是缓存的问题

**Comment by gaojunyang666** [comment]
嗯嗯，感谢作者大大的帮助！

**Comment by NEPDream** [comment]
> 嗯嗯，感谢作者大大的帮助！

其实不要用latest，用release就没有这个问题了

**Comment by NEPDream** [comment]
> 嗯嗯，感谢作者大大的帮助！

对了，我一直想知道，“仅保存回话”和“保存到系统”的区别是什么呀，您知道不，可否帮忙解释一下

**Comment by gaojunyang666** [comment]
> > 嗯嗯，感谢作者大大的帮助！
> 
> 其实不要用latest，用release就没有这个问题了

请问release 有没有新更新的tts换音色和图片上传自定义大小限制的功能啊

**Comment by gaojunyang666** [comment]
> > 嗯嗯，感谢作者大大的帮助！
> 
> 对了，我一直想知道，“仅保存回话”和“保存到系统”的区别是什么呀，您知道不，可否帮忙解释一下

保存到会话就是只在一个对话框里面生效，保存到系统就是以后你新建的所有对话框都生效

**Comment by NEPDream** [comment]
> > > 嗯嗯，感谢作者大大的帮助！
> > 
> > 
> > 其实不要用latest，用release就没有这个问题了
> 
> 请问release 有没有新更新的tts换音色和图片上传自定义大小限制的功能啊

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/31023128/cdcdacd8-d460-450f-b2b5-5873da047b8a)
看起来是有你说的两个功能的

**Comment by Dooy** [comment]
> > > > 嗯嗯，感谢作者大大的帮助！
> > > 
> > > 
> > > 其实不要用latest，用release就没有这个问题了
> > 
> > 
> > 请问release 有没有新更新的tts换音色和图片上传自定义大小限制的功能啊
> 
> ![image](https://private-user-images.githubusercontent.com/31023128/301063257-cdcdacd8-d460-450f-b2b5-5873da047b8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODM1NTIsIm5iZiI6MTcwNjY4MzI1MiwicGF0aCI6Ii8zMTAyMzEyOC8zMDEwNjMyNTctY2RjZGFjZDgtZDQ2MC00NTBmLWIyYjUtNTg3M2RhMDQ3YjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA2NDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjY2UxMTgxNWY5ODMxN2ZhYTU0ZWEyYjJiOThhZGM3MDYxYmVmNzM2ZWFlMDc5YTQzNmU5M2U0OWMxYjdiYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cAGYu97ItKw0D2-iCX6jsnD0W3w71hVce5z1KbeCuMU) 看起来是有你说的两个功能的，不过我用的.10好像会有你说的模型错位的情况，所以我就又进一步回退到了.9的上一个版本

没事下个版本修复

**Comment by NEPDream** [comment]
> > > > > 嗯嗯，感谢作者大大的帮助！
> > > > 
> > > > 
> > > > 其实不要用latest，用release就没有这个问题了
> > > 
> > > 
> > > 请问release 有没有新更新的tts换音色和图片上传自定义大小限制的功能啊
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/31023128/301063257-cdcdacd8-d460-450f-b2b5-5873da047b8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODM1NTIsIm5iZiI6MTcwNjY4MzI1MiwicGF0aCI6Ii8zMTAyMzEyOC8zMDEwNjMyNTctY2RjZGFjZDgtZDQ2MC00NTBmLWIyYjUtNTg3M2RhMDQ3YjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA2NDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjY2UxMTgxNWY5ODMxN2ZhYTU0ZWEyYjJiOThhZGM3MDYxYmVmNzM2ZWFlMDc5YTQzNmU5M2U0OWMxYjdiYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cAGYu97ItKw0D2-iCX6jsnD0W3w71hVce5z1KbeCuMU) 看起来是有你说的两个功能的，不过我用的.10好像会有你说的模型错位的情况，所以我就又进一步回退到了.9的上一个版本
> 
> 没事下个版本修复

感谢作者大大
