### ISSUE TITLE
mj以及gpt-4-vision-preview的问题

### ISSUE THREAD

**Issue by 6pjj6** [Dooy/chatgpt-web-midjourney-proxy#129]
问题1：转发站已经支持了mjv6，但是选择了v6模型以后出图是这样的
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/114254448/7a295df5-b11c-497c-8b3b-f357d09c5d9a)
问题2：gpt-4-vision-preview使用python是正常调用的，而使用gpt-4-vision-preview模型不能正常调用，我比对了官方key以及逆向的gpt-4-vision-preview模型，发现不支持逆向的gpt-4-vision-preview
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/114254448/1b27d953-1179-4a41-ac6d-1d7abf041a18)

**Comment by Dooy** [comment]
问题1 看不出问题
问题2 你该问下你的逆向gpt4v

**Comment by 6pjj6** [comment]
> 问题1 看不出问题 2 你该问下你的逆向gpt4v

好的，感谢大佬

**Comment by selfboot** [comment]
有啥推荐的逆向代理服务推荐啊
