### ISSUE TITLE
docker的环境变量有问题

### ISSUE THREAD

**Issue by YOURDD** [Dooy/chatgpt-web-midjourney-proxy#131]
在docker里部署的，环境变量如下：

![Snipaste_2024-02-01_00-21-19](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/44996899/d6d5a465-d87f-48a7-b70a-12a6e6fedc0e)

前端的接口地址和api key默认不填，提示以下：

![Snipaste_2024-02-01_00-21-52](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/44996899/fa56b52e-4828-4435-b76a-c0356791c68d)

日志信息：

![Snipaste_2024-02-01_00-23-23](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/44996899/69a2f0a1-b611-4d5f-a600-1182a940bdb9)

默认模型和登入密码是正常的，手动在前端填入接口地址和api key也是正常的，请问下这是什么原因

**Comment by Dooy** [comment]
<img width="571" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/b6c6a6a1-6809-4557-a7ab-c7679d9077a6">

服务器 域名解析有问题，请求地址 应该是 api.openai-hk.com 吧？

**Comment by YOURDD** [comment]
> <img alt="图像" width="571" src="https://private-user-images.githubusercontent.com/3765401/301348003-b6c6a6a1-6809-4557-a7ab-c7679d9077a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTY0OTMsIm5iZiI6MTcwNjc1NjE5MywicGF0aCI6Ii8zNzY1NDAxLzMwMTM0ODAwMy1iNmM2YTZhMS02ODA5LTQ1NTctYTdhYi1jNzY3OWQ5MDc3YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMDI1NjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2UxZDMxZThjMDVmMzhlNzU3ZjU0ZGRjMjVjZDlmMzZiY2ZlYTVhMTZmNDVkNmZhNzU1NGMxYzdmODRkYzRhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fOQdS6w2pyKZs7KHY7p8BBT7sNqS82ktMoyo8maHxNQ">
> 服务器域名解析有问题，请求地址应该是 api.openai-hk.com 吧？

更换地址为api.openai-hk.com，问题还是一样

![Snipaste_2024-02-01_10-58-21](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/44996899/a50d0574-1cd3-471d-9c6a-ec3d6f63066b)

**Comment by Dooy** [comment]
服务器 域名解析有问题

看看dns server 是不是 8.8.8.8

**Comment by YOURDD** [comment]
> 服务器域名解析有问题
> 
> 查看dns服务器不是8.8.8.8

经测试，群晖的dns没指向旁路由的地址，问题已经解决，感谢回复
