### ISSUE TITLE
聊天记录保存问题

### ISSUE THREAD

**Issue by SunTBurst** [Dooy/chatgpt-web-midjourney-proxy#132]
每次重新打开网站都需要重新导入导出聊天记录非常麻烦，能不能自动保存在电脑的固定位置啊，打开的时候自动读取，而不是手动导出。

**Comment by Dooy** [comment]
为何 我每次打开聊天记录都在？

是不是经常换域名？

**Comment by SunTBurst** [comment]
Thank You！可能是我浏览器设置的问题，我应该没换手动换域名。
