### ISSUE TITLE
gpt-4-gizmo-g-v81dNn6np

### ISSUE THREAD

**Issue by TiMi518** [Dooy/chatgpt-web-midjourney-proxy#133]
gpt-4-gizmo-g-v81dNn6np  模型坏了吗
还是下架了
{
  "message": "fetch error, pleace check url",
  "url": "https://api.openai.com/v1/chat/completions",
  "code": "fetch_error"
}

**Comment by Dooy** [comment]
把你的 https://api.openai.com  
修改为 https://api.openai-hk.com  试一试

**Comment by Dooy** [comment]
官网api是没有这个的 中转有
