### ISSUE TITLE
docker部署无法上传文件问题

### ISSUE THREAD

**Issue by jason-xiaobaiai** [Dooy/chatgpt-web-midjourney-proxy#134]
不好意思打扰了，我通过以下命令在服务器使用docker部署项目后：
docker run --name chatgpt-web-midjourney-proxy  -d -p 6015:3002 \
-e OPENAI_API_KEY=sk-xxxxx \
-e OPENAI_API_BASE_URL=https://api.openai.com  \
-e API_UPLOADER=1  -v /data/uploads:/app/uploads \
ydlhero/chatgpt-web-midjourney-proxy
可以正常上传图片使用gpt-4-vision-preview模型进行识图，但是当使用gpt-4-all模型或者gpts时，上传pdf文件无法上传，提示：上传失败:Request failed with status code 404，是我部署步骤有问题嘛，感谢解答🙏

**Comment by Dooy** [comment]
你是不是又在ui的`服务端` 又去设置了 `OPENAI_API_BASE_URL` ？

**Comment by jason-xiaobaiai** [comment]
> 你是不是又在ui的`服务端` 又去设置了 `OPENAI_API_BASE_URL` ？

是的，前端填入的是中转的接口地址和key

**Comment by jason-xiaobaiai** [comment]
> 你是不是又在ui的`服务端` 又去设置了 `OPENAI_API_BASE_URL` ？

大佬，docker部署设置了环境变量 API_UPLOADER=1的

**Comment by Dooy** [comment]
> > 你是不是又在ui的`服务端` 又去设置了 `OPENAI_API_BASE_URL` ？
> 
> 是的，前端填入的是中转的接口地址和key

那上传会跟随 中转走
