### ISSUE TITLE
[需求] 图片上传 可以增加一个 base64 的途径嘛？

### ISSUE THREAD

**Issue by bbb3n** [Dooy/chatgpt-web-midjourney-proxy#135]
我知道 4v 模型有传图片的需求，那其他文件上传是给 gpt-4-all 服务的？

能不能把这俩分开，并且 图片可以转成 base64 传
因为我看像 LobeChat 、 BotGem 都是用 base64 传的，对用户来说很方便，不用单独去做 文件上传服务器，也不用担心恶意攻击

### 解决方案
- 新增一个环境变量
- 开启时。和现在一样，所有文件上传都允许，并且可以设置上传地址
- 关闭时。只允许在 gpt-4-vision-preview 模型下上传图片，并且隐藏上传地址的设置，改为 base64 上传
（或者不设置上传地址时，用base64。设置了用服务器）

**Comment by Dooy** [comment]
4v 一只是 base64 不需要文件服务器

你把模型切换到 4v看看

**Comment by Dooy** [comment]
不会

非gpts的时候 自己会去识别的 
会根据你上传的内容 来定的

你分得那么清楚 才把人搞懵了 

其实 就是 GPTs 传文件
非GPTs 根据你传的内容我会自动使用不同的模型

**Comment by Dooy** [comment]
是的 
开发的时候 4v base64 我是先做的  
后面才来搞 gpts 

文件服务器完全是给 gpts用的
