### ISSUE TITLE
对话log

### ISSUE THREAD

**Issue by zyyint** [Dooy/chatgpt-web-midjourney-proxy#137]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/e68f251b-771f-4413-ab46-c74b6a4568af)
使用gpts模型之后切换模型，log没有切换回来

**Comment by jason-xiaobaiai** [comment]
我也经常遇到这个问题，好像是保存模型到会话和保存模型到系统那里有点问题

**Comment by Dooy** [comment]
对话 logo 没切换过去么？

**Comment by zyyint** [comment]
> 对话标志没切换过去么？

是的

**Comment by Dooy** [comment]
v2.15.2 已修复
