### ISSUE TITLE
希望增加cookie验证

### ISSUE THREAD

**Issue by YBYCS** [Dooy/chatgpt-web-midjourney-proxy#138]
AUTH_SECRET_KEY 设置的密码可以直接用前端元素删除,并且已经抓包得到的接口也可以直接post,能不能加一个cookie验证之类的来防止没有密码的来调用接口,因为我的令牌是直接用OPENAI_API_BASE_URL这些设置在环境里,只要获得了接口就可以不要密码验证来调用我的接口了

**Comment by Dooy** [comment]
后面 我再修复下

**Comment by Dooy** [comment]
v2.15.3 已经修复
