### ISSUE TITLE
希望大佬能够更新几个小问题，非常感谢

### ISSUE THREAD

**Issue by Dayu712** [Dooy/chatgpt-web-midjourney-proxy#139]
1. mj最新的niji6已经更新了，目前选项里还没有，我手敲参数--niji 6上去无法出图，换成别的就可以正常出

2. mj新出了个--sref的功能，可以在描述词结尾输入这个指令加制定上传的图片链接，连续出同风格图片

3. mj的V6支持的2K图目前在四联图显示是2K,最终的单图依然显示1K，不知道是不是API的都这样，也试过其他的站，也是同样情况

4. gpt对话框左侧上传本地文件无法上传pdf等文案类文件，只能传图片，不知道这个是不是不支持

5. 同对话页面调用过gpts模型后切换回普通gpt4消耗的token和金额依然是gpts的，目前只能通过新建对话页解决

6. 绘画里的dall-e不支持对话式连续出图

非常喜欢大佬的作品，目前已经用上瘾了，不知道以上问题大佬是否考虑更新一下，非常感谢

**Comment by Dooy** [comment]
感谢你提的建议

mj的新功能下试下  看看哪些能更新

gpt 读不了 pdf，图片是用模型gpt-4-version 去实现的，如果要读取pdf请使用GPTs

在同一个对话框使用的 token 计算  ，不会去管模型，但是剩余tokens 跟模型有关系 不知道你说的跟随 死那个

绘画里的dell-e 是使用接口，接口中 没有历史功能（就是没有记忆） 只能通过GPTs来实现

**Comment by jason-xiaobaiai** [comment]
> 感谢你提的建议
> 
> mj的新功能下试下 看看哪些能更新
> 
> gpt 读不了 pdf，图片是用模型gpt-4-version 去实现的，如果要读取pdf请使用GPTs
> 
> 在同一个对话框使用的 token 计算 ，不会去管模型，但是剩余tokens 跟模型有关系 不知道你说的跟随 死那个
> 
> 绘画里的dell-e 是使用接口，接口中 没有历史功能（就是没有记忆） 只能通过GPTs来实现

大佬 帮忙看看我那个用docker部署前端又填入了接口地址和key但是用gpts也无法上传文件是啥情况 求指点

**Comment by Dooy** [comment]
看下 readme 
文件上传默认是 关闭的，需要同参数打开
<img width="842" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/5fcb69e1-b8d9-4d85-ae79-97a16c2a905e">
