### ISSUE TITLE
希望调用GPTS的时候模型名可以只保留gizmo_id不会加上额外的模型名称

### ISSUE THREAD

**Issue by xiaosatai** [Dooy/chatgpt-web-midjourney-proxy#14]
![微信截图_20231211095252](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/44671057/c7d4b0a1-2a54-445d-934d-53989a885000)
非默认的GPTS角色会自动加上模型名称
部分中转API可能会识别错误

默认的GPTS角色这样只保留ID即可
![微信截图_20231211095518](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/44671057/d221026b-abf8-43e4-af24-e1cf18da91e8)

仅仅是建议，以供参考，感谢作者开发，致敬！

**Comment by Dooy** [comment]
已调整
