### ISSUE TITLE
希望大佬后续可以新增以下几个功能

### ISSUE THREAD

**Issue by zyjfly** [Dooy/chatgpt-web-midjourney-proxy#140]
1、像官网一样，可以搜索公开的gpts
![企业微信截图_17070970897273](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/b4a0de93-0ae8-42bd-8f03-5d587b5fc820)
![2](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/af5f3315-dccb-43d7-89b8-4db1ce4430a3)
这是gpts的一个搜索网站，不知道是否把这个网站接入
2、
![3](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/a1a25851-392a-4937-baf4-e4aa96931873)
可以像官网一样通过@来在一个gpts下使用另外一个gpts的功能，并且在@下两个gpts会共同保留记忆
3、希望可以收藏自己想用的gpts，之前是通过更改后缀的方式来实现使用他人的gpts，不过每次使用都需要更改后缀，希望可以保存到自己的gpts列表（希望新增这个功能），可以直接使用自己用过的GPTS。

**Comment by Dooy** [comment]
- [x] 搜索本来就有；就是这个更新 没官网及时
 - [x]  gptsHunter 没公开api ;而且他还加了 CF  防止抓取
 - [x]  @和 保存自己使用过的GPS 挺不错的

**Comment by Dooy** [comment]
v2.15.5 版本支持 @触发使用过的GPTs
<img width="532" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/cc55440c-2626-4fd1-b20f-d22b15e1c702">

**Comment by zyjfly** [comment]
太强了！！ 希望后面能增加可以保留自己使用过的gpts模型，有的gpts加了后缀使用完成之后，要使用其他的gpts换了模型，再想使用之前的就还要再次去改后缀才可以使用

**Comment by zyjfly** [comment]
![企业微信截图_17085032665568](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/5fef4963-2d45-4a07-bdba-343c19d800e4)
目前通过自定义模型的方式可以不用每次去复制，但是有的模型没法直接看出来它是哪个gpts，可否给自定义模型加个类似备注的功能吗？

**Comment by Dooy** [comment]
> ![企业微信截图_17085032665568](https://private-user-images.githubusercontent.com/96605090/306546958-5fef4963-2d45-4a07-bdba-343c19d800e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTE1MzYsIm5iZiI6MTcwODUxMTIzNiwicGF0aCI6Ii85NjYwNTA5MC8zMDY1NDY5NTgtNWZlZjQ5NjMtMmQ0NS00YTA3LWJkYmEtMzQzYzE5ZDgwMGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDEwMjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MzIzNTc3ZDYzMmI2ZTI5NDhkNWJhZTdjOTExMTFhNWUzNzhmZWJhNzM0MTJhYzEwZWQyNTUzNmJiNzdkMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.etX_8H75aiEZQyuxcFHM2tmh4C3fIl0gW3TJW45Nts4) 目前通过自定义模型的方式可以不用每次去复制，但是有的模型没法直接看出来它是哪个gpts，可否给自定义模型加个类似备注的功能吗？


看下readme  可能自定义GPTs列表的  `GPT_URL` 适合你的需求
