### ISSUE TITLE
添加简单的登录鉴权功能并将记录等跟随用户同步

### ISSUE THREAD

**Issue by cyjyyd** [Dooy/chatgpt-web-midjourney-proxy#142]
不知道作者是否有这方面的意向？目前我的使用中有部分场合是公共场所，当下所使用的鉴权方式跟随浏览器，对于私人设备是一个很好的选项，但是在不止一个人使用的设备上，似乎并不能避免滥用的问题，清理浏览器缓存的操作又相对复杂。我在想要不要做成一个可选的功能，并通过环境变量决定是否使用，用户名和密码选择数据库存储，数据库选择PgSQL或者Mysql，把历史聊天数据，头像等部分设置为跟随登录的用户同步。
如果作者愿意在此项目中并入此可选功能，我将会抽出自己的空余时间尝试辅助或者自行实现并提交PR，如果作者认为不需要/不妥，我就自己开发自己用，就不来提交PR了

**Comment by Dooy** [comment]
这方面 你可以自行搞一个分支
目前无这方面的计划

**Comment by cyjyyd** [comment]
好的，感谢作者的耐心回复，关闭问题

> 这方面 你可以自行搞一个分支 目前无这方面的计划

**Comment by Cupcc** [comment]
> 好的，感谢作者的耐心回复，关闭问题
> 
> > 这方面 你可以自行搞一个分支 目前无这方面的计划

请问 您开发了吗？可以fork一下吗
