### ISSUE TITLE
请问大佬前端ui设置了api地址和key之后 上传如果配置了R2 文件上传是走R2吗   文件上传一直不知道应该怎么配置

### ISSUE THREAD

**Issue by lyzcodebool** [Dooy/chatgpt-web-midjourney-proxy#143]
希望大佬指点一下，非常感谢

**Comment by Dooy** [comment]
文件服务器 优先
R2> 前端UI设置文件服务> 后端文件服务

**Comment by xiaopaul** [comment]
谢谢，我再试试

**Comment by h1xy** [comment]
我在docker环境变量设置了R2，UI填了api地址，上传的时候从报错信息看还是上传到API地址了。去掉API地址后，可以正常上传到R2。和你说的不一样啊。

另外，可以指定某个模型也可以上传文档格式吗？目前只有gpt-4-all可以。

**Comment by Dooy** [comment]
额 前后顺序不一样？

文档GPTs都支持 不限gpt-4-all, 如果是一般模型图片会去调用gpt-4-version

**Comment by Dooy** [comment]
ui上能设置文件服务器

**Comment by h1xy** [comment]
上传地址设置了R2里面的S3 API 地址： https://c62bb13e1f35exxxxxxx.r2.cloudflarestorage.com/bucket name
还是上传到openai base URL去了。

**Comment by henryhu55** [comment]
> 文件服务器优先 R2> 前端UI设置文件服务> 文件夹文件服务
大佬，请问一下，我设置了r2，前端配置了上传链接，也能解析图片，但是显示用的是base64, 图片在服务器/data/uploads路径和r2存储桶里面都没有是什么问题
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/128961310/ab9a5ba1-e034-49cf-982a-fa80c6eebd84)

**Comment by henryhu55** [comment]
> > > 文件服务器优先 R2> 前端UI设置文件服务> 文件夹文件服务
> > > 大佬，请问一下，我设置了r2，前端配置了上传链接，也能解析图片，但是显示用的是base64, 图片在服务器/data/uploads路径和r2存储桶里面都没有是什么问题
> > > ![image](https://private-user-images.githubusercontent.com/128961310/307220168-ab9a5ba1-e034-49cf-982a-fa80c6eebd84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjQ5ODAsIm5iZiI6MTcwODY2NDY4MCwicGF0aCI6Ii8xMjg5NjEzMTAvMzA3MjIwMTY4LWFiOWE1YmExLWUwMzQtNDljZi05ODJhLWZhODBjNmVlYmQ4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwNTA0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTliOWUzYTRlZWFhNjdmMGQyYmQzNTNlMjk0MzhlNDE5ZGMwYTAzYTZlNGU5OTIzYTZlMzc1ZmY5MzVkNmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jgKp3R0c9IBLhSWN61vOGqcpEfbuXzSvFFGy6Er15Mg)
> 
> 看你截图里用的vison模型，这个是识别图片的，你要画图应该用dall-e3模型

我不是画图呀，我是上传图片，然后用vision模型解释图片，我的意思是，应该是上传文件传到r2桶里面，然后请求vison模型带的地址应该是r2的地址才对吧，但是我这里只有base64

**Comment by Dooy** [comment]
gpt-4-vision 模型都是走base64 因为他支持 ；

图片上传主要是为GPTs服务的 比如gpt-4-all 还有其他

**Comment by henryhu55** [comment]
> gpt-4-vision 模型都是走base64 因为他支持 ；
> 
> 图片上传主要是为GPTs服务的 比如gpt-4-all 还有其他

哦哦，原来如此，那还有新的问题，就是有时候会提示无法解析图片内容，其实参数里没有带base64，我以为是上传没配置好，配置了r2就能解析，但是r2在这里好像也没用呀
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/128961310/b7cde787-2042-414a-9f60-1184f06aa607)

**Comment by Dooy** [comment]
问下你的中转 #175 你们是不是同一拨人？

你这个提示就是逆向没下载到内容的提示

**Comment by bujueone22** [comment]
不是，很多中转连接都不支持文件上传，还是之前上传到部署服务器方便很多。（每天一看发现还没有完美的解决方法

**Comment by Dooy** [comment]
> 不是，很多中转连接都不支持文件上传，还是之前上传到部署服务器方便很多。（每天一看发现还没有完美的解决方法

自己写一个文件服务 也不难啊 ；实在不会请中转帮忙解决 反正也能跟随中转

哪有收钱不干活的？ 哪有不收钱而干活的？

**Comment by ChuckZengxf** [comment]
> 上传地址设置了R2里面的S3 API 地址： [https://c62bb13e1f35exxxxxxx.r2.cloudflarestorage.com/[bucket](https://c62bb13e1f35exxxxxxx.r2.cloudflarestorage.com/%5Bbucket) name] 或https://c62bb13e1f35exxxxxxx.r2.cloudflarestorage.com 还是上传到openai base URL去了。

你r2 搞定了吗

**Comment by h1xy** [comment]
> > 上传地址设置了R2里面的S3 API 地址： [https://c62bb13e1f35exxxxxxx.r2.cloudflarestorage.com/[bucket](https://c62bb13e1f35exxxxxxx.r2.cloudflarestorage.com/%5Bbucket) name] 或https://c62bb13e1f35exxxxxxx.r2.cloudflarestorage.com 还是上传到openai base URL去了。
> 
> 你r2 搞定了吗

没有，换程序了
