### ISSUE TITLE
GPTs 里的 “加载更多” 是指从哪里加载？

### ISSUE THREAD

**Issue by B3n-AI** [Dooy/chatgpt-web-midjourney-proxy#146]
![Screenshot_20240207_144914](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129975925/5d14a9b4-9987-4aee-9922-876ec25e03f7)

通过自定义 JSON 设置了 GPTs 列表后
发现还有个 “加载更多”，请问这个是从哪里加载？我可以控制吗？

**Comment by Dooy** [comment]
你抓包看下 就知道 ，加载更多 目前没配置出来
