### ISSUE TITLE
chatgpt3.5，4.0对话发生{}错误

### ISSUE THREAD

**Issue by tianmingyun** [Dooy/chatgpt-web-midjourney-proxy#147]
vercel后台环境变量添加：
OPENAI_API_BASE_URL：https://uu.ci/（未使用openai官方base_url）
OPENAI_API_KEY：sk-xxxx

对话出现下面的错误：

2024/2/7 15:59:52 
gpt-4

发生错误:
{}

Warning日志：
[HPM] Proxy created: /  -> https://uu.ci/
[HPM] Proxy rewrite rule created: "^/mjapi/" ~> "/"
[HPM] Proxy rewrite rule created: "^/openapi/" ~> "/"

**Comment by Dooy** [comment]
用  https://uu.ci 试试 没有 ‘/’
