### ISSUE TITLE
大佬，请问先前搭建过的，但是版本是旧版的，里面没有nijiv6版，这个要怎么更新啊，求大佬解答

### ISSUE THREAD

**Issue by lhl20045** [Dooy/chatgpt-web-midjourney-proxy#148]
大佬，请问先前搭建过的，但是版本是旧版的，里面没有nijiv6版，这个要怎么更新啊，求大佬解答

**Comment by Dooy** [comment]
docker 更新 问下ChatGPT

**Comment by Dooy** [comment]
docker  pull  ydlhero/chatgpt-web-midjourney-proxy
把你之前的 docker删除
docker rm 你的docker名字
docker 执行命令

**Comment by lhl20045** [comment]
是重新搭建一遍finalshell吗

**Comment by lhl20045** [comment]
docker怎么删除呢

**Comment by lhl20045** [comment]
解决了大佬
谢谢你

**Comment by lhl20045** [comment]
更新完毕服务器进不去了

**Comment by Dooy** [comment]
怎么一个提示？ 截图看下
