### ISSUE TITLE
请教能否设置MJ的生图模式，默认感觉是relax，出图较慢，能否设置为FAST快速模式？

### ISSUE THREAD

**Issue by szansonhuang** [Dooy/chatgpt-web-midjourney-proxy#149]
大大，你好！感谢你制作这么优秀的作品。目前我试用了一下，在使用MJ生图的时候，生图的速度比较慢，感觉默认是relax模式，能否设置为FAST快速模式？我使用openai-hk.com的API KEY和地址来中转，盼复，谢谢！

**Comment by Dooy** [comment]
目前 这个没搞出来，各位都不过年的么？😄

**Comment by szansonhuang** [comment]
哈，工作＋过年，两不误。期待佬大能更新这个功能，谢谢回复！

**Comment by buwanyuanshen** [comment]
建议换个中转站点都解决了

**Comment by iceiccy** [comment]
请教一下这个项目的MJ，是如何从频道信息改成APIkey和地址进行中转昂？

**Comment by freely-boss** [comment]
> 建议换个中转站点都解决了

所以有稳定性价比高的站点吗

**Comment by buwanyuanshen** [comment]
https://6.ccfgpt.cn，进去意思意思，我给你推荐几个(🐶*999)😅😅😅
