### ISSUE TITLE
设置了环境变量key或转发，重新部署后仍未生效

### ISSUE THREAD

**Issue by suger404** [Dooy/chatgpt-web-midjourney-proxy#15]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/101552636/b5d19f91-a739-47a9-91f0-000be32153b6)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/101552636/edcf53fb-f390-48eb-9208-700f400c9868)

**Comment by xiaosatai** [comment]
我也是，新版本 变量又应用不了了

**Comment by suger404** [comment]
@Dooy 帮忙看一下呗

**Comment by Dooy** [comment]
我不知道 如何帮忙看 因为我自己的sk-xxx 加代理没问题？
要不 你提供一个你的key 我帮你试试？还是如何

如果你要 我设置好的 你可以看这个 https://demo.addmao.com

用vercel 的base_url 不能直接是 api.openai.com 因为openai把 vercel的ip封了

**Comment by Dooy** [comment]
访问密码 功能下个版本上

**Comment by Dooy** [comment]
> 是否可以添加一个访问密码的功能

v2.12.7 已经支持

**Comment by suger404** [comment]
在设置-服务器端填写api和key可以正常使用，但是通过环境变量不行。

请问你的邮箱是什么，我通过邮箱向您发送api转发链接以及key。

能否添加两个新功能呢？
1、重试按钮
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/101552636/383c6953-815f-4665-a604-6127f6114708)
2、停止按钮
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/101552636/6c177f23-b420-4381-8a79-f04006d60022)

**Comment by Dooy** [comment]
ydlhero@gmail.com

**Comment by suger404** [comment]
已发送

**Comment by Dooy** [comment]
1、重试按钮
2、停止按钮
====
正在找问题
