### ISSUE TITLE
docker 部署, 如何添加https. 

### ISSUE THREAD

**Issue by a0x5b22bbb** [Dooy/chatgpt-web-midjourney-proxy#150]
如题 docker 部署, 如何添加https. 
之前http裸奔+简单密码 
我的key估计泄露了. 这次想提高保护级别.

**Comment by Dooy** [comment]
更新下 最新版本 v2.15.3 已经修复这个bug

但是 别人应该也搞不到你的key； 主要是因为你的简单密码

https 这个可以问下 ChatGPT 
https 需要域名+需要证书， 腾讯云 阿里云有免费的证书

**Comment by a0x5b22bbb** [comment]
好的 谢谢大佬.  
没理解错的话,  用最新版, 部署之后就是https了嘛?
域名和证书我都有,  在docker 里需要配置什么参数嘛~

**Comment by Dooy** [comment]
搭建了 别去分享 密码

你也不能保证 你分享后 别人不会再分享

**Comment by a0x5b22bbb** [comment]
好的 ,. 我那个朋友也还好, 是个东北大叔, 在武汉做健身房,  可能需要借助这类工具.  他还是信得过的. 一般我都是自己玩,偶然聊天知道他想用chatGPT 做文案.
感谢大佬提醒哈哈   比心~

**Comment by xiaoyucom1** [comment]
> 如题 docker 部署, 如何添加https. 之前http裸奔+简单密码 我的key估计泄露了. 这次想提高保护级别.

用nginx的反向代理，直接创建站点绑证书，然后反向代理指向你内网的docker容器就行
