### ISSUE TITLE
半夜被盗用，请问可能是哪里有问题？

### ISSUE THREAD

**Issue by hkderekliu** [Dooy/chatgpt-web-midjourney-proxy#151]
半夜被盗用，请问可能是哪里有问题？
centos7.8服务器，安装的宝塔，通过nginx反代，只有这一个网站，没其他服务
设置了AUTH_SECRET_KEY、HIDE_SERVER
昨晚1点到6点就把我额度盗用完了。

网络日志出现多个这条记录：
23.94.178.81 - - [08/Feb/2024:06:12:48 +0800] ＂POST /openapi/v1/chat/completions HTTP/1.1＂ 428 121 ＂http://www.xxx.com＂ ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36＂
23.94.178.81 - - [08/Feb/2024:06:12:50 +0800] ＂POST /openapi/v1/chat/completions HTTP/1.1＂ 428 121 ＂https://111.111.111.111＂ ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36＂

请问可能是什么问题，如何被盗用的

**Comment by hkderekliu** [comment]
另外，请问可以如何设置网站title不显示：ChatGPT Web Midjourney Proxy，设置不让搜索引擎抓取

**Comment by Dooy** [comment]
先升级到 `v2.15.3`   后台也会验证 `AUTH_SECRET_KEY `

P/1.1＂ `428` 121 ＂ 应该是没费用提醒了吧？

如果 中转 能禁用的 先全部禁用掉 ，自己想用的时候 解除禁用

**Comment by Dooy** [comment]
> 另外，请问可以如何设置网站title不显示：ChatGPT Web Midjourney Proxy，设置不让搜索引擎抓取

下面的NGINX 是禁用 爬虫的配置 
```
server {
	listen 80;
	server_name  localhost;
	charset utf-8;
	error_page   500 502 503 504  /50x.html;
	
	# Prevent crawlers from crawling
	if ($http_user_agent ~* "360Spider|JikeSpider|Spider|spider|bot|Bot|2345Explorer|curl|wget|webZIP|qihoobot|Baiduspider|Googlebot|Googlebot-Mobile|Googlebot-Image|Mediapartners-Google|Adsbot-Google|Feedfetcher-Google|Yahoo! Slurp|Yahoo! Slurp China|YoudaoBot|Sosospider|Sogou spider|Sogou web spider|MSNBot|ia_archiver|Tomato Bot|NSPlayer|bingbot")
	{
		return 403;
	}
	
	location / {
			root /usr/share/nginx/html;
   		try_files $uri /index.html;
	}

	location /api {
			proxy_set_header   X-Real-IP $remote_addr; #Forward user IP
			proxy_pass http://app:3002;
	}

	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header REMOTE-HOST $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

**Comment by hkderekliu** [comment]
谢谢楼上的提供的方法
我去google搜了下ChatGPT Web Midjourney Proxy还是能找出来以这架设的网站
补充我的费用是在凌晨6点用完的，中间出现多条那个记录

**Comment by Dooy** [comment]
其他补交办法 就是 不要填真的key 进去
想用的时候 直接在ui端填 base_url 跟key

<img width="907" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/7d493275-bdc7-4708-8817-30c04bf1e79f">

**Comment by Dooy** [comment]
> 谢谢楼上的提供的方法 我去google搜了下ChatGPT Web Midjourney Proxy还是能找出来以这架设的网站 补充我的费用是在凌晨6点用完的，中间出现多条那个记录 23.94.178.81 - - [08/Feb/2024:04:24:54 +0800] ＂POST /openapi/v1/chat/completions HTTP/1.1＂ 200 30779 ＂[https://111.111.111.111＂](https://111.111.111.111%EF%BC%82) ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36＂
> 
> 这是可以绕过网站，直接调用我的api吗？

如果自己用 把你站点停了 就好
想用的时候 再 开起来

**Comment by Dooy** [comment]
> 谢谢楼上的提供的方法 我去google搜了下ChatGPT Web Midjourney Proxy还是能找出来以这架设的网站 补充我的费用是在凌晨6点用完的，中间出现多条那个记录 23.94.178.81 - - [08/Feb/2024:04:24:54 +0800] ＂POST /openapi/v1/chat/completions HTTP/1.1＂ 200 30779 ＂[https://111.111.111.111＂](https://111.111.111.111%EF%BC%82) ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36＂
> 
> 这是可以绕过网站，直接调用我的api吗？

你日志都有了 ，还是通过我们这个前端来访问api的

**Comment by hkderekliu** [comment]
我明白了，通过前端改代码就可以了
通过这方式发现了三个网站可以，也不知道咋通知他们
奇怪是为啥我的站点最快让人盯上

**Comment by cageqiu** [comment]
我也是一样的，刚刚充完50，一天就被好几个IP的盗用完了。

**Comment by cageqiu** [comment]
up能否出个教程，我不太会配置，用宝塔搭建的
