### ISSUE TITLE
🔥紧急重大bug修复

### ISSUE THREAD

**Issue by Dooy** [Dooy/chatgpt-web-midjourney-proxy#152]
1 `v2.15.3` 修复`AUTH_SECRET_KEY` 后端验证
2 vercel由于验证复杂 后端也未验证 `AUTH_SECRET_KEY`
3 尽量使用ui来设置服务端 `base_url` 跟`key`
4 保护好你的密码 尽量不分享你的网址、密码 和key
<img width="907" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/7d493275-bdc7-4708-8817-30c04bf1e79f">

**Comment by Dooy** [comment]
最好 别用vercel  目前 后端没去做认证，看看有人pr上来否
docker的后端有做

其实如果 只在ui端填 base_url 跟 key是无所谓的

**Comment by usawjq** [comment]
坐等修复，话说有交流群吗 @Dooy

**Comment by gpxin** [comment]
最近已经被连续两次偷取key了，用的是老版镜像，望周知

**Comment by xixingya** [comment]
请问在ui上面填写baseurl也会被盗吗，为什么我在官方站点填写了baseurl使用，然后今天就被盗用了。

**Comment by 4kShadow4k** [comment]
I don't live in China and I can't upload API KEY via wechat how to use this service please help
