### ISSUE TITLE
这个是什么问题，为什么更新到新版画图就这样了

### ISSUE THREAD

**Issue by lhl20045** [Dooy/chatgpt-web-midjourney-proxy#153]
![微信图片_20240208181751](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/159040184/b8f1fc3f-ea1b-4eff-beb5-86db6ffd0a54)
这个是什么问题，为什么更新到新版画图就这样了

**Comment by Dooy** [comment]
点 重新授权

**Comment by Dooy** [comment]
输入密码是这个 
<img width="475" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/e955b7e5-13d9-4713-90e8-73968a20988f">
