### ISSUE TITLE
AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by TANGXUE0501** [Dooy/chatgpt-web-midjourney-proxy#154]
[
![Screenshot_20240209_113947](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/154055460/e0a450ea-9acf-49b1-a629-d95796be741d)
](url)
请问这个情况一般是什么原因？是API提供商那边不支持whisper模型吗，还是我没有配置相关？

**Comment by Dooy** [comment]
可以先用curl 试下
