### ISSUE TITLE
vercel部署可以使用R2上传？

### ISSUE THREAD

**Issue by h1xy** [Dooy/chatgpt-web-midjourney-proxy#156]
vercel部署，R2环境变量已经设置，但上传文件能提示404。望指点，谢谢

**Comment by Dooy** [comment]
vercel 不支持 R2

**Comment by h1xy** [comment]
> vercel 不支持 R2

想文件上传只能本地部署了？

**Comment by Dooy** [comment]
> > vercel 不支持 R2
> 
> 想文件上传只能本地部署了？

服务器 docker 化 部署
