### ISSUE TITLE
2.15.3上传文件出现423

### ISSUE THREAD

**Issue by NEPDream** [Dooy/chatgpt-web-midjourney-proxy#157]
版本为v2.15.3，使用docker部署，启动参数中有API_UPLOADER=1，选择gpt-4-all模型，然后选择上传附件，这时候会报如下错误，测试回退到v2.15.2后上传文件没有问题，怀疑是v2.15.3中修复后端auth的问题导致的：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/31023128/5265ddb8-6818-43f6-943a-549a5281b2cf)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/31023128/8cf56abc-ebfd-4d94-b8f6-2e33bf7c5c11)

**Comment by Dooy** [comment]
收到，我下个版本 修复下

**Comment by Dooy** [comment]
V2.15.4 已修复

**Comment by cyjyyd** [comment]
docker更新到2.15.4没

**Comment by NEPDream** [comment]
> docker更新到2.15.4没

更新的了呀，昨天我就更新了，你自己去docker hub 上就能看到了
