### ISSUE TITLE
[JSON.parse: unexpected character at line 1 column 1 of the JSON data]

### ISSUE THREAD

**Issue by fredi-python** [Dooy/chatgpt-web-midjourney-proxy#158]
Getting this error always when trying to use Midjourney
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/83492589/ce3a1795-cd38-44e5-b74b-e5731f8bbdfa)

**Comment by Dooy** [comment]
Is your backend installed with mj proxy?

https://github.com/novicezk/midjourney-proxy

**Comment by basimonster** [comment]
＋1，我也遇到了上面的报错。在2.15.3版本没这个报错，升级至2.15.4出现此报错，并且奇怪的是当我回滚至2.15.3依然有这个报错

**Comment by Dooy** [comment]
> ＋1，我也遇到了上面的报错。在2.15.3版本没这个报错，升级至2.15.4出现此报错，并且奇怪的是当我回滚至2.15.3依然有这个报错

需要后端支持
