### ISSUE TITLE
设置/关于页面无法获取使用量等信息

### ISSUE THREAD

**Issue by cyjyyd** [Dooy/chatgpt-web-midjourney-proxy#159]
![2db8ec5521a6bfe05f9224643c58389f](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40909448/cdbcb89b-624d-45b9-b56c-5fa9ff7fe8db)
尝试降低版本，问题依旧存在，通过查看浏览器开发工具中的网络标签可以发现如下错误：
![bffba77a4c3552b810bb6f10c5fea448](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40909448/91d23c81-cae4-4cd7-bb9a-2ab10d9e2e27)
可以看到OPENAPI的返回token如下：
{
  "error": {
    "message": "Your request to GET /v1/dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
已尝试：通过-e参数设置OPENAPI-ACCEESS-TOKEN，问题依然存在
希望作者能抽空看一下

**Comment by cyjyyd** [comment]
Note：APIKey已经预设，聊天等功能是正常的

**Comment by Dooy** [comment]
这个是老版本的使用量了 官网已经屏蔽了
