### ISSUE TITLE
OPENAI_API_MODEL 不生效

### ISSUE THREAD

**Issue by miwoy** [Dooy/chatgpt-web-midjourney-proxy#16]
新版本中，设置的默认 OPENAI_API_MODEL 并不管用。
我想要在新建聊天窗口的时候默认模型为设置的 OPENAI_API_MODEL。
但是现在显示的都是 gpt-3.5-turbo

**Comment by Dooy** [comment]
后面版本加上

**Comment by Dooy** [comment]
v2.12.7 已支持
