### ISSUE TITLE
环境变量配置了R2，前端ui设置了api地址和key之后，上传文件报错

### ISSUE THREAD

**Issue by Dreamy-rain** [Dooy/chatgpt-web-midjourney-proxy#160]
我看到有issue提了，我想的是有什么办法前端设置了中转地址，但文件路径还是R2嘛
这样方便别人用我的站点，可以直接上传文件

环境变量里面配置了R2和api与key，用all模型上传文件都正常
但是把api和key填到前端里面，上传文件就会报错
gpt-4-vision-preview上传图片却是没有问题的
图片打码的地方是前端填写的api接口地址和docker部署的反代域名
![报错](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/116244751/4e119cd9-3e57-4c45-89a6-be1ade369c79)

**Comment by Dreamy-rain** [comment]
我看到有issue提了，我想的是有什么办法前端设置了中转地址，但文件路径还是R2嘛

**Comment by Dooy** [comment]
如果你设置了 R2 ,文件上传会以R2为主

看了下你的贴图错误 是跨域问题

**Comment by Dreamy-rain** [comment]
> 如果你设置了 R2 ,文件上传会以R2为主
> 
> 看了下你的贴图错误 是跨域问题

大佬回复好快，感谢！！！我再去问问GPT研究研究
