### ISSUE TITLE
Mj绘画提示词

### ISSUE THREAD

**Issue by zyyint** [Dooy/chatgpt-web-midjourney-proxy#162]
希望可以增加一个MJ绘画提示词联想

**Comment by Dooy** [comment]
这个是不是GPTs的范畴 ？ ^_^

**Comment by buwanyuanshen** [comment]
画完图需要切回聊天才能出现图片，我之前还以为没画出来，最近才发现😂😂😂

**Comment by zyyint** [comment]
> 这不是 GPT 的星球吗？ ^_^

不对，好像是联合调用GPT来进行提示词优化联想的
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/eab1b6fe-8812-42d4-bee8-edeecbfd501d)
参考地址https://github.com/vastxie/NineAIQuickDeploy

**Comment by Dooy** [comment]
建议 你找个 GPTs,

**Comment by Dooy** [comment]
> 画完图需要切回聊天才能出现图片，我之前还以为没画出来，最近才发现😂😂😂

可能出图慢了些
