### ISSUE TITLE
请教Node版本问题的解决方法

### ISSUE THREAD

**Issue by iceiccy** [Dooy/chatgpt-web-midjourney-proxy#165]
我这边的环境是在宝塔上的docker来部署，主要问题就是node的版本，拉取后创建容器一直提示node版本不否，默认就是20.11.0，昨晚找了一碗更改容器内node版本的方法均无效，弄到第二天下午依然无解，实在不知道该怎么办了，特来求教，有什么办法能解决这个问题么？

**Comment by Dooy** [comment]
有什么错误提示没？贴出来方便判断
docker 应该是自带node版本的

**Comment by basimonster** [comment]
> 有什么错误提示没？贴出来方便判断 docker 应该是自带node版本的

作者你好，我是在sealos上部署的，和上面那位出现一样的问题。报错如下：
(node:18) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by Dooy** [comment]
sealos 没参试过 
研究了下 他的语法；没搞成功

你这个错误 R2文件上传错误，你是不是设置了R2的配置?

**Comment by iceiccy** [comment]
> 有什么错误提示没？贴出来方便判断 docker 应该是自带node版本的

 WARN  Unsupported engine: wanted: {"node":"^16 || ^18 || ^19"} (current: {"node":"v20.11.1","pnpm":"8.15.3"})

> chatgpt-web-service@2.15.5 prod /app
> node ./build/index.mjs

Server is running on port 3002
(node:18) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
我的日志显示如上.

**Comment by Dooy** [comment]
> > 有什么错误提示没？贴出来方便判断 docker 应该是自带node版本的
> 
>  WARN  Unsupported engine: wanted: {"node":"^16 || ^18 || ^19"} (current: {"node":"v20.11.1","pnpm":"8.15.3"})
> 
> > chatgpt-web-service@2.15.5 prod /app
> > node ./build/index.mjs
> 
> Server is running on port 3002 (node:18) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
> 
> Please migrate your code to use AWS SDK for JavaScript (v3). For more information, check the migration guide at https://a.co/7PzMCcy (Use `node --trace-warnings ...` to show where the warning was created) 我的日志显示如上.


这个提示 就说明起来了 没问题啊 

你映射出来的端口是多少？

**Comment by iceiccy** [comment]
> 如果映射出来的端口 是 -p 9015:3002
> 
> 那么直接访问 http://ip:9015 就好了

嗯，我发现问题所在了，其实能用了，但是太执着于日志提示了，后来发现，IP:端口好像访问不了，但是IP:端口/可以成功打开了，所以虽然提示版本不对，但是是可用了

**Comment by Dooy** [comment]
能用 就ok close 了哈
