### ISSUE TITLE
2.15.5上传文件出现423

### ISSUE THREAD

**Issue by FaulknerWu** [Dooy/chatgpt-web-midjourney-proxy#168]
<img width="269" alt="{3F8F04B0-AFBE-4b5d-932D-FA390839301E}" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/74252754/7fdde4ab-e1ef-403c-8590-8a5887a76f01">

<img width="326" alt="{5407BDAA-D122-4f01-A909-563F8D1F3616}" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/74252754/c618efcb-4698-420b-9b14-ad82e4111b9f">

如图，API_UPLOADER=1已正确配置

**Comment by Dooy** [comment]
收到 稍后测试下

**Comment by FaulknerWu** [comment]
> 收到 稍后测试下

谢谢大佬，这也太快了

**Comment by Dooy** [comment]
我这边测试没问题 ；
你能否 ctrl+f5下 然后重新输入 访问密码

或许试着发一个无图无附件消息 会给出重新输入访问密码的按钮

**Comment by Dooy** [comment]
<img width="546" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/9da5fc87-4080-45ec-95c5-24c3efa8fef8">

**Comment by FaulknerWu** [comment]
> 我这边测试没问题 ； 你能否 ctrl+f5下 然后重新输入 访问密码
> 
> 或许试着发一个无图无附件消息 会给出重新输入访问密码的按钮

已经尝试过了，并没有让我重新输入访问密码

**Comment by Dooy** [comment]
你没设置 `AUTH_SECRET_KEY `  ？

**Comment by FaulknerWu** [comment]
> 你没设置 `AUTH_SECRET_KEY ` ？

设置过的，我还是找不出什么问题，然后用r2代替本地储存了
