### ISSUE TITLE
请求后端接口"/openapi/v1/chat/completions"经常出现307跳转现象

### ISSUE THREAD

**Issue by yinhaixiang** [Dooy/chatgpt-web-midjourney-proxy#169]
无论哪个模型, 都偶发会出现307跳转, 然后重新发起请求: 
http://chat.taosha.club/v1/chat/completions?retry=9, 因为没有/openai 所以404了
我断点排查过, 无论正常回答还是307跳转, 以下代码都是正常进入的:
```
//代理openai 接口
app.use('/openapi', authV2, verifyTokenMiddleware, proxy(API_BASE_URL, {
	https: false, limit: '10mb',
	proxyReqPathResolver: function (req) {
		return req.originalUrl.replace('/openapi', '') // 将URL中的 `/openapi` 替换为空字符串
	},
	proxyReqOptDecorator: function (proxyReqOpts, srcReq) {
		proxyReqOpts.headers['Authorization'] = 'Bearer ' + process.env.OPENAI_API_KEY;
		proxyReqOpts.headers['Content-Type'] = 'application/json';
		proxyReqOpts.headers['Mj-Version'] = pkg.version;
		return proxyReqOpts;
	},
	//limit: '10mb'
}));
```
这个现象不是我一个人遇到过, 群里一看到307现象就知道是这个项目
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/10047441/2b719f01-67ad-4d62-b29a-19b1fe3f8118)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/10047441/2b5534de-be76-42fc-9890-4233bf2b0a9a)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/10047441/d15972a4-b4ef-4458-9341-23f4d5502c94)

**Comment by Dooy** [comment]
问下你的中转 应该是中转那边跳转了 

代码是公开的 里面没有跳转

**Comment by Dooy** [comment]
难为你了，我把原来的请求方式改了 

使用 `socketsproxy` 不起效果, 
如果你有时间或者有代码能力 可以pr上来 谢谢
