### ISSUE TITLE
使用MJ进行绘画，如何保证人物的一致性？

### ISSUE THREAD

**Issue by Keenyyang** [Dooy/chatgpt-web-midjourney-proxy#17]
大佬们，用这个MJ绘图，怎么保证角色的一致性呢? 
比如出了1个4宫格的图，然后我看中了第一张图，然后我把第一张图给单独拿出来，想把里面的人物换一个姿势。
里面有seed值，但是不知道怎么应用。 我尝试用--seed XX 参数 保证一致性，但是不起作用。

**Comment by Dooy** [comment]
mj的使用技巧 可以网上找找教程 ；惭愧的是我也不是很懂

你可以试一试 局部重绘

**Comment by Keenyyang** [comment]
> mj的使用技巧 可以网上找找教程 ；惭愧的是我也不是很懂
> 
> 你可以试一试 局部重绘

你好，我在网上看了MJ的技巧，里面有个地方就是 它也可以有个聊天框去聊天，可以持续创作，但是好像这个MJ只能写一篇提示词，没有下面的聊天框能够把上下关联起来。  还有另外1个问题就是，MJ输出4宫格的图片的SEED值和 4宫格图片里面的某1张高清图的SEED值一样，按理说应该不一样。  大佬你可以研究一下。
