### ISSUE TITLE
如何配置让用户的midjourney wsrv 默认打开

### ISSUE THREAD

**Issue by jianwi** [Dooy/chatgpt-web-midjourney-proxy#170]
如何配置让用户的midjourney wsrv 默认打开。

是否可以支持自定义的图片加速代理？

**Comment by Dooy** [comment]
> 如何配置让用户的midjourney wsrv 默认打开。
> 
> 是否可以支持自定义的图片加速代理？

后面加一个参数来控制 wsrv是否默认打开

`是否可以支持自定义的图片加速代理？`=> midjourney-proxy 已经支持做得很好了
