### ISSUE TITLE
图片上传也会随着走BASE_URL走？这个不合理！代理通常不会提供文件上传，导致上传失败。

### ISSUE THREAD

**Issue by qq137321** [Dooy/chatgpt-web-midjourney-proxy#171]
如果是前端ui设置 BASE_URL ; 图片上传也会随着走 OPENAI_API_BASE_URL走。

希望在主站设定上传地址，不要跟随BASE_URL 走，这个要分开。有一个专门设定上传地址的地方吧？
我这个建议不知道合不合理？

**Comment by Dooy** [comment]
上传单独开 也支持啊，你看下readme ；返回相应格式就行

<img width="510" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/b0c690ec-1a4f-4413-a73e-fd5120d15d5b">

**Comment by qq137321** [comment]
为什么我在 .env里面设定的东西一点都不起作用？vercel那边也更新了。
包括OPENAI_API_KEY= 
OPENAI_API_BASE_URL= 
API_UPLOADER= 
FILE_SERVER= 
和 cloudflare r2 存储的全部设置都不起作用

**Comment by Dooy** [comment]
你在vercel搭建？  vercel 不支持

**Comment by qq137321** [comment]
晕啊，竟然没有一个提醒。弄死了：

**Comment by Dooy** [comment]
issue 很多 ；readme 也有提
<img width="868" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/b74dab81-4b93-4a79-b43b-5f220933bc65">
