### ISSUE TITLE
文件上传真是头痛，R2配置了也不行，文件服务器要怎么配置也不清不楚。

### ISSUE THREAD

**Issue by qq137321** [Dooy/chatgpt-web-midjourney-proxy#172]
文件上传真是头痛，R2配置了也不行，文件服务器要怎么配置也不清不楚。
R2配置到了.env里面，也不见任何作用。

能否写一个文件上传的说明，谢谢。

**Comment by qq137321** [comment]
文件服务器 是不是需要自己去建立？

**Comment by qq137321** [comment]
文件服务器 是不是需要自己去建立？
R2 要怎么配置才能起作用？（所有参数都给齐了）

**Comment by Dooy** [comment]
耐心看下readme, 可以直接用 `API_UPLOADER=1` 开启上传

**Comment by qq137321** [comment]
R2配置要怎么才能生效？

**Comment by qq137321** [comment]
设定了中转接口之后，
Failed to load resource: https://中转地址/v1/upload:1
the server responded with a status of 404 ()

**Comment by bujueone22** [comment]
+1，不懂怎么使用这个上传教程，可以捐赠博主，出个教程吗

**Comment by Dooy** [comment]
> +1，不懂怎么使用这个上传教程，可以捐赠博主，出个教程吗

感谢，出个教程是真的

**Comment by QAbot-zh** [comment]
readme不是给了参考吗？
根据这个配置文档 https://zhuanlan.zhihu.com/p/658058503 ，从cloudflare获取这些参数：
```
R2_DOMAIN=
R2_BUCKET_NAME=
R2_ACCOUNT_ID=
R2_KEY_ID=
R2_KEY_SECRET=
```
docker运行的时候按照环境变量的格式填充，我这样做就能用了
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/4a566a13-6805-43b6-9fc3-81240749537c)

另外就是注意：1. vercel 不支持 r2 存储   2. 如果前端配置了key，好像就不走 r2 存储了
文件服务器的内容就不懂了

**Comment by ChuckZengxf** [comment]
搞定了吗

**Comment by tankpanv** [comment]
#文件服务 可选
  fileserver:
    image: ydlhero/file-server:latest
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
      #对外显示的域名
      SERVER_NAME: http://myip:3102
    ports:
      - "3102:3102"
    volumes:
      - /data/uploads:/app/uploads
  用这个镜像创建一个文件服务

**Comment by Ruler27** [comment]
> #文件服务 可选 fileserver: image: ydlhero/file-server:latest restart: always environment: TZ: Asia/Shanghai # 指定时区 #对外显示的域名 SERVER_NAME: http://myip:3102 ports: - "3102:3102" volumes: - /data/uploads:/app/uploads 用这个镜像创建一个文件服务

你这个确实管用，不过貌似前端如果设置了Key，后端填的 FILE_SERVER 就失效了，必须都在前端设置这个地址

**Comment by Dooy** [comment]
用这个 再指定下
<img width="626" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/a82e363f-87b0-46c3-9a96-e92b06d639db">
