### ISSUE TITLE
图片识别问题bug

### ISSUE THREAD

**Issue by YBYCS** [Dooy/chatgpt-web-midjourney-proxy#175]
这个图片上传使用gpt-4v模型会出现"抱歉，我无法直接访问或检索网页链接内容。如果您能提供图片的详细信息或者想要讨论的具体主题，我会很乐意帮助您。"
然后我看了下post的数据发现图片链接是和text一起发送的,但是规范好像是要使用image_url来发送:
![2055c771c63889271a2f904eae03379](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/87234506/197a9645-850e-4918-873c-ba74f71ac240)
我使用lobechat测试确认模型是没问题的而且lobechat也确实是使用了image_url

**Comment by Dooy** [comment]
这里不是 lobechat，如果用的lobechat 出现问题请到 lobechat提 issue

**Comment by YBYCS** [comment]
不是使用lobechat发送的错误,我的意思是你的这个post规范貌似不对,以下是你的post的数据
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/87234506/687416c2-c396-4928-88da-45946ecfa16f)
可以看到图片链接是和text一起发送的但是我看了下openai的规范貌似图片链接要单独放在
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/87234506/e0f8109f-c12d-419b-a22d-0bc576cbbb24)
以下是lobechat的发送数据,可以看到他也是放在了image_url,并且能正确识别图片:
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/87234506/ee65ec9a-fe05-4159-976e-87629756195d)




> 这里不是 lobechat，如果用的lobechat 出现问题请到 lobechat提 issue

**Comment by Dooy** [comment]
没说 里面不能放 url 
能放url 也能放base64啊 

能base64 我为何好多搞一个文件服务器啊？万一图片链接有问题咋办？
https://platform.openai.com/docs/guides/vision

出现识别不出来的问题你问下你中转；大概率是用了逆向

<img width="851" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/7dc72ac3-606e-4c0d-b1a3-eea0eb8fdb18">

**Comment by YBYCS** [comment]
好的,我再研究下,感谢大佬回复

**Comment by KamiPasi** [comment]
我知道问题在哪了, 使用gpt-4-vision-preview不要设置system提示词, 不然很大概率不回答图片内容

**Comment by heiyyint** [comment]
能否支持下gemini-pro-1.5走base64，这url不能识别但是走base64解析图片又能识别出来
