### ISSUE TITLE
反馈一个微信绘图弹窗兼容问题

### ISSUE THREAD

**Issue by yoke1990** [Dooy/chatgpt-web-midjourney-proxy#177]
在一些机型中，微信点开底部绘画按钮，弹窗高度600px会铺满，无法点击空白处关闭弹窗

src/views/mj/aiMobileMenu.vue

  <NDrawer v-model:show="st.show" :height="600" placement="bottom" v-if="goHome=='draw'">
    <NDrawerContent style="--n-body-padding:0" class="h-full">
      <aiDrawInput @draw-sent="drawSent" />
    </NDrawerContent>
  </NDrawer>
改成
  <NDrawer v-model:show="st.show" :height="'90vh'" placement="bottom" v-if="goHome=='draw'">
    <NDrawerContent style="--n-body-padding:0" class="h-full">
      <aiDrawInput @draw-sent="drawSent" />
    </NDrawerContent>
  </NDrawer>

90vh跟画廊h-[90vh]就保持一致了

**Comment by Dooy** [comment]
收到 我再调试下谢谢

**Comment by Dooy** [comment]
v2.15.6 已修复
