### ISSUE TITLE
文件上传有问题

### ISSUE THREAD

**Issue by arelice** [Dooy/chatgpt-web-midjourney-proxy#178]
你好，这个文件上传不能在服务端填写接口地址和key.必须把接口地址和key删了才能上传文件。希望能优化一下。

**Comment by Dooy** [comment]
文件服务器 优先顺序 其他issue有提到 #143 
R2> 前端UI设置文件服务> 后端文件服务

**Comment by nangui2872** [comment]
@Dooy 我上传也是有点问题，我如果选择gpt-4-all，保存到当前会话文件上传不切换（PS切换模型顶部的模型不会变化？bug？），我的理解就是有2种上传，一个是base64直接传，但是只能图片啥的，一个就是all模型用的url，可以传多种文件格式，我只设置了API_UPLOADER=1，正常来说应该上传到后端文件服务（但是这里经常走mj的/v1/upload接口，而不是openapi的/openapi开头的地址，导致我上传404，我没配置mj地址），这个点卡的我很难受

**Comment by Dooy** [comment]
ui的服务端也能配置文件上传服务器啊；可以将你主机的文件服务器配置在那边

<img width="596" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/e179fecf-d532-498e-947d-b78247d79183">

**Comment by nangui2872** [comment]
@Dooy 项目的文件上传接口是多少呢？readme没有看到相关说明（我到时候源码搜下吧），因为我设置了这个隐藏了，然后配置了文件上传，我还寻思他会自动传到容器呢，结果经常404，感觉切换还是有点问题，用的gpt模型怎么会使用mj的上传接口呢/v1/upload,还有一个就是模型切换真的很难用，我明明切换保存了，但是顶部还是显示之前的模型，最后就是有个参数UPLOADER_URL这个是可以配置上传服务器（因为我隐藏了HIDE_SERVER）这个参数我在readme也没找到，自己找源码找到的，希望这几个点大佬能抽空优化下

**Comment by nangui2872** [comment]
上面那个模型问题就是在gpt-4-all模型的时候，上传应当是支持多种上传的那个，但是老是切不到那个上传，一直是图片上传那个
<img src="https://pic.ziyuan.wang/user/guest/2024/02/1708997332387_00607122de92c.png" alt="1708997332387.png" title="1708997332387.png" />

**Comment by Dooy** [comment]
> @Dooy 项目的文件上传接口是多少呢？readme没有看到相关说明（我到时候源码搜下吧），因为我设置了这个隐藏了，然后配置了文件上传，我还寻思他会自动传到容器呢，结果经常404，感觉切换还是有点问题，用的gpt模型怎么会使用mj的上传接口呢/v1/upload,还有一个就是模型切换真的很难用，我明明切换保存了，但是顶部还是显示之前的模型，最后就是有个参数UPLOADER_URL这个是可以配置上传服务器（因为我隐藏了HIDE_SERVER）这个参数我在readme也没找到，自己找源码找到的，希望这几个点大佬能抽空优化下

<img width="828" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/5560e743-f191-49cd-987d-ab9530b8035f">

**Comment by nangui2872** [comment]
我知道的，我HIDE_SERVER=1将服务端隐藏了，现在用UPLOADER_URL配置了下本项目的后端上传接口，然后现在能用了，主要是没有文档说明下UPLOADER_URL，对新手有点不友好，有点bug

**Comment by Dooy** [comment]
更全的说明 https://github.com/Dooy/chatgpt-web-midjourney-proxy/blob/main/docker-compose/docker-compose.yml

可以试一试 一键部署

https://github.com/Dooy/chatgpt-web-midjourney-proxy/tree/main/docker-compose/gpts-mj-file

**Comment by Dooy** [comment]
> 我知道的，我HIDE_SERVER=1将服务端隐藏了，现在用UPLOADER_URL配置了下本项目的后端上传接口，然后现在能用了，主要是没有文档说明下UPLOADER_URL，对新手有点不友好，有点bug

要支持的太多了，新手直接让中转帮忙解决就好

**Comment by nangui2872** [comment]
这里好像依旧没有UPLOADER_URL参数说明，我的意思是加下UPLOADER_URL，修复下gpt-4-all模型，啥都没设置一直走/v1/upload接口，直接404了，我想着gpt-4-all没设置R2也没设置其他上传地址，默认就走服务端的上传好了，但是他不走，这里应该是有bug的

**Comment by Dooy** [comment]
不知道用的那个版本 ？我这边一直没问题
https://vercel.ddaiai.com

<img width="570" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/c67f9d06-5123-4b0a-b657-bd0cb95a9e2b">

**Comment by nangui2872** [comment]
2.15.6，模型切换的bug一直有，你尝试切到别的gpt模型，然后保存本次会话，然后在切到all模型，就会出现上传没切过去，具体bug应该在保存到本次会话中，我测了保存到系统中就正常切换，另外虽然切过去了，但是all模型的上传接口经常是/v1/upload，而不是/openapi/v1/upload 接口，导致all模型文件上传404
<img src="https://pic.ziyuan.wang/user/guest/2024/02/1709028698450_416db9688a64d.png" alt="1709028698450.png" title="1709028698450.png" />

**Comment by Dooy** [comment]
vercel 不支持upload， 但是请求是对的

<img width="1118" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/7432f512-9c9d-4415-acfd-c0dd65756e1c">

**Comment by nangui2872** [comment]
是的，但是我之前没设置url的时候，大概率是错的，直接就是/v1/upload接口。。。。

**Comment by freely-boss** [comment]
> vercel 不支持upload， 但是请求是对的
> 
> <img alt="image" width="1118" src="https://private-user-images.githubusercontent.com/3765401/308127932-7432f512-9c9d-4415-acfd-c0dd65756e1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzM5MzgsIm5iZiI6MTcwOTE3MzYzOCwicGF0aCI6Ii8zNzY1NDAxLzMwODEyNzkzMi03NDMyZjUxMi05YzlkLTQ0MTUtYWNmZC1jMGRkNjU3NTZlMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMDIyNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmZmNGZmMGY3OTJkN2I4MjRkYTc1ZWM0NGMzYjNkOTQ4Njk2YzdiNDMzZTg2YTY0NmFhYzE0N2NmOTQ3YjM4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wxzmo12YFSC0OBNxUtAtQtTVutrohTDf40zp6vVzJno">

其实意思是这个上传文件的方式可以自定义选择而不是系统写死优先级，正常可以设置为4个选项（选项的优先级最高）：[R2]、[API接口]、本地容器、自定义链接

**Comment by Dooy** [comment]
> > vercel 不支持upload， 但是请求是对的
> > <img alt="image" width="1118" src="https://private-user-images.githubusercontent.com/3765401/308127932-7432f512-9c9d-4415-acfd-c0dd65756e1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzM5MzgsIm5iZiI6MTcwOTE3MzYzOCwicGF0aCI6Ii8zNzY1NDAxLzMwODEyNzkzMi03NDMyZjUxMi05YzlkLTQ0MTUtYWNmZC1jMGRkNjU3NTZlMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMDIyNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmZmNGZmMGY3OTJkN2I4MjRkYTc1ZWM0NGMzYjNkOTQ4Njk2YzdiNDMzZTg2YTY0NmFhYzE0N2NmOTQ3YjM4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wxzmo12YFSC0OBNxUtAtQtTVutrohTDf40zp6vVzJno">
> 
> 其实意思是这个上传文件的方式可以自定义选择而不是系统写死优先级，正常可以设置为4个选项（选项的优先级最高）：[R2]、[API接口]、本地容器、自定义链接

不错；给一个默认优先级最高的（就是默认的）

**Comment by nangui2872** [comment]
> > > vercel 不支持upload， 但是请求是对的
> > > <img alt="image" width="1118" src="https://private-user-images.githubusercontent.com/3765401/308127932-7432f512-9c9d-4415-acfd-c0dd65756e1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzM5MzgsIm5iZiI6MTcwOTE3MzYzOCwicGF0aCI6Ii8zNzY1NDAxLzMwODEyNzkzMi03NDMyZjUxMi05YzlkLTQ0MTUtYWNmZC1jMGRkNjU3NTZlMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMDIyNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmZmNGZmMGY3OTJkN2I4MjRkYTc1ZWM0NGMzYjNkOTQ4Njk2YzdiNDMzZTg2YTY0NmFhYzE0N2NmOTQ3YjM4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wxzmo12YFSC0OBNxUtAtQtTVutrohTDf40zp6vVzJno">
> > 
> > 
> > 其实意思是这个上传文件的方式可以自定义选择而不是系统写死优先级，正常可以设置为4个选项（选项的优先级最高）：[R2]、[API接口]、本地容器、自定义链接
> 
> 不错；给一个默认优先级最高的（就是默认的）

UPLOADER_URL是不是没有这个容器的环境变量参数？这个只能前端页面设置吗？不能在容器设置？我上次还以为我容器环境变量设置指定了呢，难怪经常时好时坏，我其实想隐藏前端的设置的，但是这个文件上传地址又必须前端，很不方便呢

**Comment by Dooy** [comment]
v2.15.8 增加了 `UPLOAD_TYPE` 指定上传方式 
[`R2` R2上传] [`API` 跟随UI前端中转]、[`Container` 本地容器]、[`MyUrl` 自定义链接]

**Comment by zyyint** [comment]
> nt

自定义链接如何配置MyUrl把My换成自己的链接地址？

**Comment by Dooy** [comment]
前端自自定义url

<img width="623" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/cae3231d-4498-44f4-a428-d8b3e8382eb0">

**Comment by NEPDream** [comment]
> v2.15.8 增加了 `UPLOAD_TYPE` 指定上传方式 [`R2` R2上传] [`API` 跟随UI前端中转]、[`Container` 本地容器]、[`MyUrl` 自定义链接]

那请问现在环境变量API_UPLOADER还有作用么，API_UPLOADER=0会和UPLOAD_TYPE=API 冲突么

**Comment by Dooy** [comment]
前提是 API_UPLOADER=1啊

**Comment by zyyint** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/3802e15d-7678-42de-8ba6-3ceb165a9d5f)设置自定义上传文件服务器，不生效，设置之后一样走v1，已有按照相应变量环境进行填写，文件服务器项目：https://github.com/AnjanaMadu/FileServer

**Comment by JIANRENWEN** [comment]
> 是的，但是我之前没设置url的时候，大概率是错的，直接就是/v1/upload接口。。。。

我现在就是这个问题，好久了都没解决，不知道该怎么办，你能帮我解决一下吗兄弟
