### ISSUE TITLE
最新版本，vercel部署，将网站密码部分的html代码删掉就能绕过密码😂，哈哈哈

### ISSUE THREAD

**Issue by buwanyuanshen** [Dooy/chatgpt-web-midjourney-proxy#179]
好像设置了，又好像没有

**Comment by Dooy** [comment]
已经明确说了  vercel 不支持
<img width="906" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/a966799f-2a30-4fab-aa8d-c5af39da5d8f">
