### ISSUE TITLE
自定义模型

### ISSUE THREAD

**Issue by QAbot-zh** [Dooy/chatgpt-web-midjourney-proxy#180]
自定义模型能像nextweb那样支持别名吗，以及支持中文，想添加一些常用的gpts，但是光看gpts默认的模型名称是一串字符，不够直观。

**Comment by Dooy** [comment]
GPTs 自定义 列表 看下readme 能支持啊

<img width="867" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/9feaf38c-374f-463e-b56c-ba18cca8d7c6">

**Comment by QAbot-zh** [comment]
使用gpts.json的话gpts商店的模型是不是就看不到了？

**Comment by Dooy** [comment]
是的

**Comment by QAbot-zh** [comment]
就是首页是gpts.json里的模型，但是搜索能搜到商店里的，这样子吗？
