### ISSUE TITLE
请问怎么进网站管理后台呢？

### ISSUE THREAD

**Issue by fuzifeng1** [Dooy/chatgpt-web-midjourney-proxy#181]
网站搭建好了，不知道怎么进网站管理后台

**Comment by Dooy** [comment]
求老板 顾我 帮你开发后台

这个就没有后台，就是一个ChatGPT 网页的UI

**Comment by fuzifeng1** [comment]
多少钱那。我是看他的教程来的https://vi06dd9wb0x.feishu.cn/docx/AL3LdM4SYoMPptx2EtVc8rjAnah

**Comment by Dooy** [comment]
> 多少钱那。我是看他的教程来的https://vi06dd9wb0x.feishu.cn/docx/AL3LdM4SYoMPptx2EtVc8rjAnah

玩笑了，目前没有管理后台

也不知道管理后台需要啥，如果你自己有需求可以请人帮你开发下；
目前的代码都是公开的，任何人都可以在这基础上进行再次开放，有代码能力修改下就好

**Comment by fuzifeng1** [comment]
哦，这样啊，谢谢了
