### ISSUE TITLE
gpt-4-vision-preview模型不识别图片

### ISSUE THREAD

**Issue by yang2202** [Dooy/chatgpt-web-midjourney-proxy#182]
![e7e9ede2740edd6f152a1d218a8765e](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/157776290/0601b250-f636-4bb8-9d14-1cc9fa7595fd)

**Comment by Dooy** [comment]
请联系中转

**Comment by heiyyint** [comment]
看到日志是图片上传到了本地，形成了一个本地链接，导致4v模型无法识别，但是all模型上传却又是走了服务器地址
