### ISSUE TITLE
ydlhero/chatgpt-web-midjourney-proxy 翻墙配置

### ISSUE THREAD

**Issue by zabzd999** [Dooy/chatgpt-web-midjourney-proxy#183]
这个默认的镜像ydlhero/chatgpt-web-midjourney-proxy 启动的时候并未设置翻墙相关的proxy代理配置，是如何实现翻墙的？
docker启动的时候有办法指定翻墙的environment吗？

**Comment by Dooy** [comment]
`OPENAI_API_BASE_URL` 不就为这个而生的么？

**Comment by zabzd999** [comment]
close
