### ISSUE TITLE
提交MJ绘图,报错 [Unexpected token '<', "<!DOCTYPE "... is not valid JSON]

### ISSUE THREAD

**Issue by KimigaiiWuyi** [Dooy/chatgpt-web-midjourney-proxy#184]
已配置`midjourney-proxy 2.5.5`, 通过访问`http://127.0.0.1:6018/mj`可以正常进入doc页, 通过Python调用API可以正常生成图片
使用
```shell
docker run --name chatgpt-web-midjourney-proxy  -d -p 6016:3002 -e OPENAI_API_KEY=sk-gEfPb******il6JJLHw******************Pac2EYs -e OPENAI_API_BASE_URL=https://api.openai.com -e MJ_SERVER=http://127.0.0.1:6018/mj -e MJ_API_SECRET=****** ydlhero/chatgpt-web-midjourney-proxy
```
部署之后, MJ生图显示报错`[Unexpected token '<', "<!DOCTYPE "... is not valid JSON]`,
打开网页控制台测试发现调用了API`http://localhost:6018/mjapi/mj/submit/imagine`(好像API莫名其妙多加了一个`mjapi`), 提示报错
```shell
Error: connect ECONNREFUSED 127.0.0.1:6018
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```
是什么原因呢

**Comment by Dooy** [comment]
看看这个issue #176

**Comment by KimigaiiWuyi** [comment]
> 看看这个issue #176

是这个地方么
https://github.com/Dooy/chatgpt-web-midjourney-proxy/blob/66164797c13c4bfd1ee281349d9a097836ab6065/service/src/index.ts#L112-L116
我不太理解为什么会去调用`/mjapi/mj`, 要修改哪里的代码可以去除`/mjapi`呢

**Comment by Dooy** [comment]
不要去改，配置好 他自己会转过的

**Comment by KimigaiiWuyi** [comment]
> 不要去改，配置好 他自己会转过的

意思是我需要再反代一下我的midjourney-proxy到`/mjapi`这个endpoint?

**Comment by Dooy** [comment]
不需要 按readme搭建就好

**Comment by Dooy** [comment]
F12看下什么错误，如果那边有MJ_SERVER 有套NGINX 看下NGINX的log

**Comment by KimigaiiWuyi** [comment]
> http://localhost:6018/mjapi/mj/submit/imagine

F12看到访问API`http://localhost:6013/mjapi/mj/submit/imagine`报错
```shell
Error: connect ECONNREFUSED 127.0.0.1:6013
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```
我自己用python是能够调用`http://localhost:6013/mj/submit/imagine`的，网页访问多了一个`/mjapi`
MJ_SERVER没有套NGINX，网页调用时候没有看到midjourney-proxy有调用，应该是没有访问到正确的API
`chatgpt-web-midjourney-proxy`项目的ENV：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/55526518/1066a42c-6a89-4087-a030-453b9be18b20)

**Comment by Dooy** [comment]
你有看readme ? readme 带了 /mj ?
<img width="359" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/5d566294-fd30-4e74-b46d-5166cd8bdd37">

**Comment by KimigaiiWuyi** [comment]
> 你有看readme ? readme 带了 /mj ? <img alt="image" width="359" src="https://private-user-images.githubusercontent.com/3765401/307803540-5d566294-fd30-4e74-b46d-5166cd8bdd37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NTM3NDUsIm5iZiI6MTcwODk1MzQ0NSwicGF0aCI6Ii8zNzY1NDAxLzMwNzgwMzU0MC01ZDU2NjI5NC1mZDMwLTRlNzQtYjQ2ZC01MTY2Y2Q4YmRkMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMTMxNzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZlMzUwNDUyYWNlNzljYjFiMjllYzU5ZmIxYzJkMTRiODAyM2MyZjBhOGMwNTI5MzhjZDkxNTQxNjU2Mzk2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VaAQo67V5bh3ZWmmgZ9zBZHTt5JQ89oPYwCivvpaPIw">

不带`/mj`也不行，我两种都试过，第一次是不带`/mj`的，后面擅自改了一下发现还是不行

**Comment by Dooy** [comment]
知道问题所在了  `https://127.0.0.1:6013` 容器内访问不到 换下 172.17.0.1 试一试

**Comment by Dooy** [comment]
这边都已经有提示了
<img width="563" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/29033eb6-8c29-42d1-9715-be1756a8f4f6">
