### ISSUE TITLE
一个交互小建议

### ISSUE THREAD

**Issue by QAbot-zh** [Dooy/chatgpt-web-midjourney-proxy#186]
现在要新开对话需要展开对话栏，展开/关闭对话栏只能通过下图中的小按钮，左上角醒目的“对话”的点击功能有点浪费。如果点击“对话”区域，可以实现展开/关闭对话栏，在交互上会方便和习惯很多。一个小建议，欢迎讨论。
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/9dbe20cb-f52b-47d4-8c76-3736ab9ad957)

**Comment by Dooy** [comment]
人生80% 用来浪费的 ^_^
