### ISSUE TITLE
无法使用 GPTs

### ISSUE THREAD

**Issue by QYQSDTC** [Dooy/chatgpt-web-midjourney-proxy#187]
使用 GPTs 返回
![CleanShot-5cPYkT48@2x](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/15608306/750a349a-aa38-419b-8314-89cbbc38fb98)

**Comment by iceiccy** [comment]
同问，我的提示是{
  "error": {
    "message": "当前分组 svip 下对于模型 gpt-4-gizmo-g-k3IqoCe1l 无可用渠道 (request id: 20240226185931917124625UU3fJW3A)",
    "type": "one_api_error"
  }
}
