### ISSUE TITLE
你好，提一个小建议

### ISSUE THREAD

**Issue by iceiccy** [Dooy/chatgpt-web-midjourney-proxy#188]
感谢作者开源了这么好的一个项目，我就是想建议一下背景色是否可以再丰富一些，现在的颜色只有黑和白，默认的黑色虽然舒服点，但总也感觉怪怪的，而白色，太亮了，能不能考虑加上一个灰色试试，或者能自己选择颜色，要是能自己上传背景图就更完美了，仅仅是个个人的建议。

**Comment by Dooy** [comment]
萝卜青菜 各有所爱，不能讨好100%喜欢

还好代码是开源的 喜欢各自修改
