### ISSUE TITLE
为什么会有积分不足的问题，请问这个怎么解决？如果有充值的地方，那可以发一个链接吗？

### ISSUE THREAD

**Issue by Mongol-bateer** [Dooy/chatgpt-web-midjourney-proxy#190]
![1](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/90378896/875eaeb4-7cb8-480f-bb08-55647082d42d)

**Comment by Dooy** [comment]
谁给你用的 你寻谁去充值 ？
看提示是用了 https://www.openai-hk.com 的中转
