### ISSUE TITLE
MJ默认模型版本问题

### ISSUE THREAD

**Issue by suyunkai** [Dooy/chatgpt-web-midjourney-proxy#191]
MJ的默认模型版本还是v5.2，能否换成最新的v6呀？或者有没有某个地方可以配置成默认v6，我查看了一下代码也没找到在哪儿能改动，求作者指点
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/82149368/09f88690-cba3-4b85-962b-db1eda4af8c5)

**Comment by Dooy** [comment]
下个版本 改下

**Comment by Dooy** [comment]
v2.15.8已更
