### ISSUE TITLE
新开会话的默认模型

### ISSUE THREAD

**Issue by QAbot-zh** [Dooy/chatgpt-web-midjourney-proxy#193]
在修改模型设置的时候，有“仅保存会话”和“保存至系统”两个选项，理论上是不是选择“保存至系统“，修改的模型才会成为新开会话的默认模型？
但是实测的时候，有时候我只是选了“仅保存会话”，聊了一段时间，再开新会话的时候还是会变成新的模型，而不是之前“保存至系统”的模型名称。这是符合设计预期的吗？
（主要是想防止新开会话的时候会话模型不是自己想要的，比如用完gpts后想开个普通对话）

**Comment by yinhaixiang** [comment]
+1

**Comment by Dooy** [comment]
有开发能力的话 自行修改下

**Comment by yinhaixiang** [comment]
> 有开发能力的话 自行修改下

我尝试改了, 发现牵扯的东西比较多, 前端能力有限, 尝试失败了, 大佬能修复下这个小bug吗

**Comment by Dooy** [comment]
今日有时间优化了下 更新到 `v2.16.2` 试一试
