### ISSUE TITLE
建议可以设置自定义地址后只隐藏地址功能

### ISSUE THREAD

**Issue by longkun0203** [Dooy/chatgpt-web-midjourney-proxy#195]
开发者开发的这款功能很强大，提这个建议是可以让服务商作为私有化服务使用，比如我设置好中转地址，前端可以隐藏，然后用户使用时需要从服务商获取密钥才可以，现在是整个服务端隐藏，作者可以考虑一下，如果说服务端隐藏是提供内部使用，那隐藏中转地址将提供更多私有化可能性。

**Comment by Dooy** [comment]
看下 readme 你是不是想要这功能？

<img width="632" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/b9b138cd-7b6c-4360-ad6a-c3d7b60a2d01">

**Comment by longkun0203** [comment]
> 看下 readme 你是不是想要这功能？
> 
> <img alt="image" width="632" src="https://private-user-images.githubusercontent.com/3765401/309539132-b9b138cd-7b6c-4360-ad6a-c3d7b60a2d01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NjEzOTQsIm5iZiI6MTcwOTQ2MTA5NCwicGF0aCI6Ii8zNzY1NDAxLzMwOTUzOTEzMi1iOWIxMzhjZC03YjZjLTQzNjAtYWQ2YS1jM2Q3YjYwYTJkMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMTAxODE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNjMGZiYzY4ZjE2YjY2OGFjMTcxMDUyODMxYjE5Nzk0ZjljYjEzODMzM2ZiNGE3ZTBkMThjMDQzMDBhYmZlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zqkgz1H4uTs4nMSUCV7ASBKhqZFARx_np_PE1VMUEqU">

这是一方面，因为我们服务商群里还有下级代理，涉及不到这个功能，有些用户只是买到一个key，而不是使用平台，也是建议性提一下

**Comment by Dooy** [comment]
喔 个性需求 自己fork 修改下

**Comment by longkun0203** [comment]
> 喔 个性需求 自己fork 修改下

好的 谢谢

**Comment by TiMi518** [comment]
> 喔 个性需求 自己fork 修改下

能加入模型选项不

**Comment by TiMi518** [comment]
> 看下 readme 你是不是想要这功能？
> 
> <img alt="image" width="632" src="https://private-user-images.githubusercontent.com/3765401/309539132-b9b138cd-7b6c-4360-ad6a-c3d7b60a2d01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNDAxMjMsIm5iZiI6MTcxMDAzOTgyMywicGF0aCI6Ii8zNzY1NDAxLzMwOTUzOTEzMi1iOWIxMzhjZC03YjZjLTQzNjAtYWQ2YS1jM2Q3YjYwYTJkMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTBUMDMwMzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjhmY2M0ODlmNjZhYjZmZjhiOTJhZGU0ZmFmMmE2ZjBiN2EwNjlkOGFiZDY4ODgxN2NiYTdkOGYwMzExNTNiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nf--KRv5rLUdlrBQJylyiFWSCOhGlX576TljWfkL1Fw">

就是在这个链接里面添加指定模型
