### ISSUE TITLE
Midjourney使用反馈

### ISSUE THREAD

**Issue by longkun0203** [Dooy/chatgpt-web-midjourney-proxy#196]
升级新版后，Midjourney中转地址已经完成绘画并已经100%，但是这个前端还是等待中，需要刷新后，点击Midjourney模型旁边的刷新图标才能显示，不知道是不是bug。

**Comment by Dooy** [comment]
图片 画出来 载入到本地需要时间啊；检查下mj图片地址 你得去加速下mj的图片

**Comment by longkun0203** [comment]
> 图片 画出来 载入到本地需要时间啊；检查下mj图片地址 你得去加速下mj的图片

已经做了加速，升级前正常，所以点奇怪

**Comment by Poco0v0** [comment]
> 图片 画出来 载入到本地需要时间啊；检查下mj图片地址 你得去加速下mj的图片

真的，我也遇到了，是这次画图提交成功后显示进度0%等待的窗口都没有，只提示任务提交成功。然后请求接口返回100%和按钮了，界面也不会加载图显示按钮。点击刷新按钮，图马上就出来了，应该就不是加载慢的原因，一天会遇到几次左右。

**Comment by Dooy** [comment]
因为图片保存在本地 需要去下载 如果急可以直接点链接 能解决
