### ISSUE TITLE
聊天记录能导出，但是导入没成功

### ISSUE THREAD

**Issue by QAbot-zh** [Dooy/chatgpt-web-midjourney-proxy#197]
如题，聊天记录能导出为json文件，重新导入就不成功，反而是传到R2存储去了
上传截图：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/b7ba9fd4-f57e-49b1-8794-a22a206b49c6)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/c739e9bf-2aa2-4648-bd03-f19b59b03ca3)

R2存储截图：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/7ebe375c-e1ea-4b49-b68f-f28981ef195b)

**Comment by Dooy** [comment]
售后测试下

**Comment by Dooy** [comment]
v2.15.9 已修复 请更新

**Comment by QAbot-zh** [comment]
新镜像有效，问题已解决 👍👍👍
