### ISSUE TITLE
One curious question

### ISSUE THREAD

**Issue by Urmi10799** [Dooy/chatgpt-web-midjourney-proxy#198]
How the message reply is implemented in smooth typing effect?

If anyone one can help to understand the code, where it actually implemented, it will helpful for me.

**Comment by Dooy** [comment]
Are you deploying on Vercel or using docker + nginx?

If NGINX is deployed, please set your configuration `proxy_buffering off;`
If you are deploying on vercel, please set your key at the  ui `Settings`->`Server`

<img width="684" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/39eb843d-f044-41ae-80ef-dca79bf63244">

**Comment by Urmi10799** [comment]
actually I'm talking about how you've made it possible on code. which part of the code giving smooth typing effect?
I'm testing it on localhost.

**Comment by Dooy** [comment]
代码是公开的 可自行观看 谢谢
