### ISSUE TITLE
使用Midjourney  v6遇到的一些问题

### ISSUE THREAD

**Issue by HYC11304** [Dooy/chatgpt-web-midjourney-proxy#199]
使用v6版本生成图片后，没有 “高清2倍” 和 “高清4倍” 的按钮。（v5.2版本正常）
两台电脑之间的导入导出，导入另外一台电脑的记录会覆盖原有的记录，原有的记录丢失，不知道能否改善为合并的。
-----------------------------------------------------
以上问题都是使用Version - 2.15.8过程中遇到的

**Comment by Dooy** [comment]
V6 是否 有出现这个按钮？

**Comment by HYC11304** [comment]
原来如此，discord上的却还没有。感谢答复
