### ISSUE TITLE
midjourney绘图部分功能按钮未出现

### ISSUE THREAD

**Issue by Katou-Kouseki** [Dooy/chatgpt-web-midjourney-proxy#20]
版本：v2.12.7

✅ midjourney 支持1.5倍变焦 2倍变焦
✅ midjourney 支持2倍高清 4倍高清
✅ midjourney 支持左、右、上、下延伸变化

如以上三种类型的功能，在进行绘图的过程中没有看到，不知道是不是我操作不正确

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/30703483/c3adc4e7-298b-4df3-8b4f-d1cdf358f86a)

**Comment by Dooy** [comment]
服务端 需要 支持啊，midjourney proxy plus版本有

**Comment by Katou-Kouseki** [comment]
> 服务端 需要 支持啊，midjourney proxy plus版本有

好的，感谢👌
