### ISSUE TITLE
请问如何设置Gemini pro？

### ISSUE THREAD

**Issue by xiaopaul** [Dooy/chatgpt-web-midjourney-proxy#202]
我看都里面默认有Gemini的引擎，但是参数配置没有看到。请问环境变量名称应该是什么，谢谢。

**Comment by Dooy** [comment]
需要转为 openai api 格式, 建议可以用one-api转下

**Comment by xiaopaul** [comment]
谢谢，转成Open Api格式后，请问环境变量怎么设置?, 直接用Gemini pro吗？程序会认出来吗？

**Comment by Dooy** [comment]
不在这边设置 而是在转的地方设置
