### ISSUE TITLE
关于最大回复数

### ISSUE THREAD

**Issue by HuangRunQiang** [Dooy/chatgpt-web-midjourney-proxy#203]
现在默认是2048，未免也太小了，经常出现回复着就直接停止的现象，及其影响使用体验，建议这个回复数可以放开最大限制或者任意定义

**Comment by Dooy** [comment]
你查下 模型 回复数 很少超过1024的 更别说2048

**Comment by HuangRunQiang** [comment]
可能我对openai的计算方式了解不够，不过在选择同样模型的条件下，用next-chatgpt的回复数明显大于本项目，比如翻译大批量文本的时候。next-chatgpt的回复数默认可以设置到512000

**Comment by HuangRunQiang** [comment]
这个最大限制直接放开给用户自由设置也无妨，没必要限制吧

**Comment by Dooy** [comment]
搞到最大 经常出现max_tokens 超过了的 提示
