### ISSUE TITLE
希望作者增加claude-3-opus-20240229模型的支持

### ISSUE THREAD

**Issue by xiaoyucom1** [Dooy/chatgpt-web-midjourney-proxy#207]
希望作者增加claude-3-opus-20240229模型的支持

**Comment by daluzhongcaoyao** [comment]
+1，现在上传图片默认就调用到gpt-4-vision了，实际上claude-3-opus也能支持图片解析

**Comment by Dooy** [comment]
如果急， 先用 `CUSTOM_MODELS` 自定义增加下
后面我把他加上

**Comment by Dooy** [comment]
请更新 至 `v2.15.10`

**Comment by nangui2872** [comment]
> 请更新 至 `v2.15.10`

我切到claude-3-opus-20240229模型后，默认是all模型的文件上传，cl3貌似不支持URL传文件，只能和4v一样，然后文件传的文件流

**Comment by imlpxgaebm** [comment]
> 用力刷新下

ctrl+f5刷新并没有用，我2个cl3模型切换来切换去才正常了，变成4v的支持图片的，但是好像还是不支持其他文件

**Comment by Dooy** [comment]
claude-3-opus 才支持 
<img width="591" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/b7125d2e-a02e-4a81-aaa3-0c7f07dbbfea">

**Comment by imlpxgaebm** [comment]
> claude-3-opus 才支持 <img alt="image" width="591" src="https://private-user-images.githubusercontent.com/3765401/311698519-b7125d2e-a02e-4a81-aaa3-0c7f07dbbfea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTk1NTIsIm5iZiI6MTcxMDE1OTI1MiwicGF0aCI6Ii8zNzY1NDAxLzMxMTY5ODUxOS1iNzEyNWQyZS1hMDJlLTRhODEtYWFhMy0wYzdmMDdkYmJmZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMTIxNDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU0MTFmMzhlMzIxMDFjMTEzNTQ2MDNmODFlMWU2YjMzYWEwNGRiYTk5YTc3ZjA4ZGQzMWVkMTcxNjhmYWQwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.44PNPsV4CooB9LWEJxbV5cz2aEbGL9PseouUAWo_qXs">

那看来不是bug，我知道这样可以传，但是关键是这个模型貌似不支持url，只能文件流给他，<img src="https://pic.ziyuan.wang/user/guest/2024/03/1710159339380_6512b6d88a954.png" alt="1710159339380.png" title="1710159339380.png" />

**Comment by Dooy** [comment]
得用base64 转过去？

**Comment by freely-boss** [comment]
> 得用base64 转过去？
`import requests
import json

def analyze_image(image_url, api_url, openai_key):
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {openai_key}'
    }

    data = {
        "model": "claude-3-opus-20240229",
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": "What’s in this image?"},
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": image_url,
                        },
                    },
                ],
            }
        ],
        "max_tokens": 4000,
    }

    response = requests.post(api_url, headers=headers, data=json.dumps(data))

    print(response.json())`



别人给的，试试看。
