### ISSUE TITLE
关于文件上传是否强制调用4v的建议

### ISSUE THREAD

**Issue by freely-boss** [Dooy/chatgpt-web-midjourney-proxy#208]
1. 问题场景：目前有多家渠道提供了api聊天接口，比如chatgpt和claude，现状是软件上文件上传功能仅适配了gpt服务，导致使用非gpt服务时无法使用文件上传功能（会强制切换gpt4v模型，实际上目标模型本身就支持分析图片等功能）。并且目前看来后续ai发展是枝繁叶茂，希望大佬在现有基础上进行一定的完善，实现一定程度上的一劳永逸。下面是我的一点建议。
2. 改进建议：提供每个模型（包括自定义模型）的文件上传策略选项（后端和前端UI），支持针对文件上传策略进行自定义模型切换（无需切换就用none填充）。

例如：内置：gpt-3.5-turbo模型，文件上传策略选项默认为：gpt-4-vision-preview
           自定义模型：claude-3-opus-20240229模型，文件上传策略选项默认为：none
           会话过程中上传文件则根据配置的策略进行自动判断，实现多模型无缝切换，功能完整的效果。

**Comment by Dooy** [comment]
claude-3 其他模型支持么？

**Comment by Dooy** [comment]
请更新 至 `v2.15.10`
