### ISSUE TITLE
gpt4-vision无法分析图片

### ISSUE THREAD

**Issue by bobandbrony** [Dooy/chatgpt-web-midjourney-proxy#21]
vercel部署
cloudflare分配域名
报错内容
{
  "error": {
    "message": "json: cannot unmarshal array into Go value of type string (request id: 20231214130451569277952FI84XNUo)",
    "type": "one_api_error",
    "param": "",
    "code": "count_token_messages_failed"
  }
}
这里用的第三方api以及key

**Comment by Dooy** [comment]
请确认下 第三方api  支持 gpt-4-vision-preview 模型否？

最好升级下 oneapi

**Comment by bobandbrony** [comment]
确认支持，隔壁的lobechat都能用

**Comment by Dooy** [comment]
我没法 具体判断因为 我没有你后端

你的提示我之前有碰到过，看起来像逆向的 gpt-4-v

直接用 curl试下 就知道了

用官网的demo

https://platform.openai.com/docs/guides/vision

**Comment by Dooy** [comment]
最好 image_url.url 部分直接用 base64
官网是支持的 看看你的中转支持不

**Comment by bobandbrony** [comment]
az，我不太懂这些。。。
还有就是，dall e默认调用openAI官方的，这似乎改不了

**Comment by Dooy** [comment]
设置下 OPENAI_API_BASE_URL  会随着你设置 OPENAI_API_BASE_URL 请求地址走_

**Comment by Dooy** [comment]
检查出来我的gpt-4-vision-preview 是有格式错误 
在 v2.12.11 已修复

**Comment by bobandbrony** [comment]
> 检查出来我的gpt-4-vision-preview 是有格式错误 在 v2.12.11 已修复

已确认解决
