### ISSUE TITLE
关于重绘的问题

### ISSUE THREAD

**Issue by hugoshao** [Dooy/chatgpt-web-midjourney-proxy#210]
Midjourney Proxy v2.5.5 API后端不接受 index为0的重绘提交
https://github.com/Dooy/chatgpt-web-midjourney-proxy/pull/209

 
但是提交重绘后 Discord里面的重绘按钮虽然被点亮了，但是似乎没有执行操作。不知道这是什么原因，可能是后端API的问题吗？
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/36898061/a0b91453-1a86-4aa1-8a22-075f74a9d820)

**Comment by Dooy** [comment]
已经将你PR 发布了 v2.15.10
