### ISSUE TITLE
反馈一个不知道算不算BUG的问题

### ISSUE THREAD

**Issue by iceiccy** [Dooy/chatgpt-web-midjourney-proxy#211]
先感谢作者大大的问题回复速度和更新速度，在更新了最新版2.15.10后，发现虽然文件上传功能对4和claude进行了区分，但这个区分是跟着当前系统模型走的，而不是根据对话，我试了试先是在gpt-4-0125-preview对话后，再选择claude-3-opus-20240229保存后开启新对话，这时选择之前的4，上传就变成了claude的上传提示，而且也可以上传表格，发送后报错：{
  "error": {
    "message": "You uploaded an unsupported image. Please make sure your image is below 20 MB in size and is of one the following formats: ['png', 'jpeg', 'gif', 'webp']. (request id: 202403072021056154364630234664) (request id: 2024030720210382377666980255816)",
    "type": "invalid_request_error",
    "param": "",
    "code": "invalid_image_format"
  }
}，不知道这算不算BUG，来反馈一下，对了，作者大大啥时候能抽空修复一下仅保存会话和保存至系统功能昂，现在俩功能是一样的效果

**Comment by yinhaixiang** [comment]
是的, 这个问题和 https://github.com/Dooy/chatgpt-web-midjourney-proxy/issues/193
是同样的问题, 我的建议是每个会话窗口的"模型切换"弹窗里的保存的数据应该是单独的, 新开会话窗口时, 就从"保存至系统"这里存的数据里clone一份, 每个会话窗口单独一份模型管理的好处是就算切到已经有的会话窗口, 当前会话窗口的模型也是和自身绑定的模型, 不会有互相串的可能, 而且从面向对象角度来说, 一个会话拥有它自身的new出来的模型管理也是合理的, 每个会话窗口就是一个新的对象, 它的模型管理不应该和其他窗口的模型相耦合。

**Comment by Dooy** [comment]
> 先感谢作者大大的问题回复速度和更新速度，在更新了最新版2.15.10后，发现虽然文件上传功能对4和claude进行了区分，但这个区分是跟着当前系统模型走的，而不是根据对话，我试了试先是在gpt-4-0125-preview对话后，再选择claude-3-opus-20240229保存后开启新对话，这时选择之前的4，上传就变成了claude的上传提示，而且也可以上传表格，发送后报错：{ "error": { "message": "You uploaded an unsupported image. Please make sure your image is below 20 MB in size and is of one the following formats: ['png', 'jpeg', 'gif', 'webp']. (request id: 202403072021056154364630234664) (request id: 2024030720210382377666980255816)", "type": "invalid_request_error", "param": "", "code": "invalid_image_format" } }，不知道这算不算BUG，来反馈一下，对了，作者大大啥时候能抽空修复一下仅保存会话和保存至系统功能昂，现在俩功能是一样的效果

不知道你在搞出这个提示的

**Comment by Dooy** [comment]
> 是的, 这个问题和 #193 是同样的问题, 我的建议是每个会话窗口的"模型切换"弹窗里的保存的数据应该是单独的, 新开会话窗口时, 就从"保存至系统"这里存的数据里clone一份, 每个会话窗口单独一份模型管理的好处是就算切到已经有的会话窗口, 当前会话窗口的模型也是和自身绑定的模型, 不会有互相串的可能, 而且从面向对象角度来说, 一个会话拥有它自身的new出来的模型管理也是合理的, 每个会话窗口就是一个新的对象, 它的模型管理不应该和其他窗口的模型相耦合。

后面看看如何 修复下； 意思是 有消息的 就相互串了呗？

**Comment by yinhaixiang** [comment]
> > 是的, 这个问题和 #193 是同样的问题, 我的建议是每个会话窗口的"模型切换"弹窗里的保存的数据应该是单独的, 新开会话窗口时, 就从"保存至系统"这里存的数据里clone一份, 每个会话窗口单独一份模型管理的好处是就算切到已经有的会话窗口, 当前会话窗口的模型也是和自身绑定的模型, 不会有互相串的可能, 而且从面向对象角度来说, 一个会话拥有它自身的new出来的模型管理也是合理的, 每个会话窗口就是一个新的对象, 它的模型管理不应该和其他窗口的模型相耦合。
> 
> 后面看看如何 修复下； 意思是 有消息的 就相互串了呗？

是的, 经常有这样的场景, 我开了一个会话窗口, 选用DALLE模型, 专门用来画图, 又开了一个会话窗口, 选用gpt-4-turbo-preview, 专门用来文字交流, 当我根据工作需要切换窗口的时候, 我希望的是每个会话的模型就是专属于这个会话的, 而现在的情况是如果切换会话窗口, 模型管理也必须手动换回来, 如果忘了环就会串模型

**Comment by yinhaixiang** [comment]
> > 是的, 这个问题和 #193 是同样的问题, 我的建议是每个会话窗口的"模型切换"弹窗里的保存的数据应该是单独的, 新开会话窗口时, 就从"保存至系统"这里存的数据里clone一份, 每个会话窗口单独一份模型管理的好处是就算切到已经有的会话窗口, 当前会话窗口的模型也是和自身绑定的模型, 不会有互相串的可能, 而且从面向对象角度来说, 一个会话拥有它自身的new出来的模型管理也是合理的, 每个会话窗口就是一个新的对象, 它的模型管理不应该和其他窗口的模型相耦合。
> 
> 后面看看如何 修复下； 意思是 有消息的 就相互串了呗？

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/10047441/307ccae6-47c8-48a9-a149-33862b5ded1a)
我当时基于chatgpt-web的项目自己实现了下, 每次下拉框选择的模型就是这个会话窗口对象的一个属性, 所以每个会话都有自身的模型管理, 不会串, 可惜我前端水平不高, 那个项目还是大量问gpt4才做出来的效果, 惭愧惭愧

**Comment by iceiccy** [comment]
> > 先感谢作者大大的问题回复速度和更新速度，在更新了最新版2.15.10后，发现虽然文件上传功能对4和claude进行了区分，但这个区分是跟着当前系统模型走的，而不是根据对话，我试了试先是在gpt-4-0125-preview对话后，再选择claude-3-opus-20240229保存后开启新对话，这时选择之前的4，上传就变成了claude的上传提示，而且也可以上传表格，发送后报错：{ "error": { "message": "You uploaded an unsupported image. Please make sure your image is below 20 MB in size and is of one the following formats: ['png', 'jpeg', 'gif', 'webp']. (request id: 202403072021056154364630234664) (request id: 2024030720210382377666980255816)", "type": "invalid_request_error", "param": "", "code": "invalid_image_format" } }，不知道这算不算BUG，来反馈一下，对了，作者大大啥时候能抽空修复一下仅保存会话和保存至系统功能昂，现在俩功能是一样的效果
> 
> 不知道你在搞出这个提示的

这个提示就是，用切换对话的方式，我用Claude界面的上传功能，上传了excel文件给gpt-4-0125-preview，但本身你设置的gpt是不能上传excel文件的

**Comment by Dooy** [comment]
> > > 是的, 这个问题和 #193 是同样的问题, 我的建议是每个会话窗口的"模型切换"弹窗里的保存的数据应该是单独的, 新开会话窗口时, 就从"保存至系统"这里存的数据里clone一份, 每个会话窗口单独一份模型管理的好处是就算切到已经有的会话窗口, 当前会话窗口的模型也是和自身绑定的模型, 不会有互相串的可能, 而且从面向对象角度来说, 一个会话拥有它自身的new出来的模型管理也是合理的, 每个会话窗口就是一个新的对象, 它的模型管理不应该和其他窗口的模型相耦合。
> > 
> > 
> > 后面看看如何 修复下； 意思是 有消息的 就相互串了呗？
> 
> ![image](https://private-user-images.githubusercontent.com/10047441/311200260-307ccae6-47c8-48a9-a149-33862b5ded1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDQ0NTcsIm5iZiI6MTcxMDQwNDE1NywicGF0aCI6Ii8xMDA0NzQ0MS8zMTEyMDAyNjAtMzA3Y2NhZTYtNDdjOC00OGE5LWExNDktMzM4NjJiNWRlZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA4MTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNDY0Mzk0NmUwMDJiYzU3ZTIxMzIzM2NjMTYzMGViODIxYzY4MWI1Y2FhNmVjZjBhZTdhZjI1MDM5NzFmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0hLGV0QOXdhivrQZJQNV3d0sdUgk-nShQSlwTLETfc8) 我当时基于chatgpt-web的项目自己实现了下, 每次下拉框选择的模型就是这个会话窗口对象的一个属性, 所以每个会话都有自身的模型管理, 不会串, 可惜我前端水平不高, 那个项目还是大量问gpt4才做出来的效果, 惭愧惭愧

今日有时间优化了下 更新到 2.16.2 试一试
