### ISSUE TITLE
语音功能

### ISSUE THREAD

**Issue by TiMi518** [Dooy/chatgpt-web-midjourney-proxy#216]
作者大大你好，能否在对话页面增加一个自动播报的开关，输出的文字可以自动tts文本转语音读出来
开启这个功能自动播报，不开启，就手动点击tts文本转语音

**Comment by TiMi518** [comment]
还有就是   支持超链更换设置，适合 one-api 部署聊天 https://vercel.ddaiai.com/#/s/t?OPENAI_API_BASE_URL=https://abc.com&OPENAI_API_KEY=sk-xxxxx&MJ_SERVER=https://abc.com&MJ_API_SECRET=sk-xxx&UPLOADER_URL=     这个能否加入指定模型   打开页面  指定跳转到4.0或者其他指定的模型，目前默认是3.5

**Comment by Dooy** [comment]
最近比较忙

**Comment by TiMi518** [comment]
辛苦大佬，没事不急，不是必须，只是问问
有空看看即可。感谢大佬回复
