### ISSUE TITLE
局部重绘功能

### ISSUE THREAD

**Issue by wangr0031** [Dooy/chatgpt-web-midjourney-proxy#217]
我使用chatgpt-web-midjourney-proxy，后端对接的是midjourney-proxy。
在绘图界面并没有**局部重绘**功能，请问是后端对接`midjourney-proxy-plus`才会有这个功能吗

**Comment by TiMi518** [comment]
放大一个图后才有吧

**Comment by wangr0031** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/24863189/c891e05f-9bbc-412d-a0a8-e5a7f1d2d17a)
这是我放大后的，并没有局部重绘功能

**Comment by Dooy** [comment]
去接 midjourney-proxy-plus 免费版本midjourney-proxy 没这个功能
