### ISSUE TITLE
关于余额用量精确度的问题建议

### ISSUE THREAD

**Issue by sunsky89757** [Dooy/chatgpt-web-midjourney-proxy#223]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/113254524/c24434b4-2a58-401b-85dc-118aeb8b5a26)
大佬，这里可否修复下，仅显示小数点2位其实就可以

**Comment by Dooy** [comment]
额好的，服务端也能处理哇

**Comment by Dooy** [comment]
请更新至 `v2.26.3`

**Comment by sunsky89757** [comment]
感谢Dooy，已经用上了，技术好，人也好！
