### ISSUE TITLE
markdown 格式渲染问题

### ISSUE THREAD

**Issue by QAbot-zh** [Dooy/chatgpt-web-midjourney-proxy#224]
版本：Version - 2.16.2
问题描述：特殊格式的文本渲染不换行，内容显示不全。
回复的文本：
```
好的,我直接说一些安慰和鼓励的内容:

$\mathbf{追求自己的理想并非一蹴而就的事情,它需要持之以恒的努力和付出。短期内的得失失之或得,并不能完全代表一个人的价值和贡献。我们应该用长远的眼光来审视问题,相信只要方向正确,坚持下去终会有收获的一天。}$

$\mathbf{金钱的确很重要,但它并不是人生的全部。一个人的价值还在于他为社会做出了什么贡献,创造了什么价值。从事科研和技术创新虽然辛苦,但你们正在为人类文明进步做出自己的一份力量,这种付出是了不起而有意义的。}$

$\mathbf{成功没有捷径可走,它来自于執着和勇气。历史上很多科学家、工程师都曾经历过困难和挫折,但正是因为他们的坚韧和毅力,才最终获得了今天的成就。只要你不放弃,定能战胜眼前的阻碍,实现自己的梦想。}$

$\mathbf{人生最可贵的是拥有自己向往的事业,并为之执着地去追求。即使过程艰辛,但当你真正热爱自己所做的事情时,就会找到快乐和动力。保持初心,坚定理想,相信美好的明天正在前方等待着你。}$
```
网页显示效果：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/8cb9b4ac-4ad1-4d2d-a12f-82d4042dc7ab)

不过这个问题估计不好解决，因为我复制粘贴到nextweb里渲染效果也差不多。
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/9821036e-99c6-49fe-8454-3f6a2608e3cc)

**Comment by Dooy** [comment]
是 输出有问题 `$$\mathbf{我们 = A+B}$$` 前后少了 $

<img width="461" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/e3c4a914-0ecc-46b3-8bbe-ac48d35b03e5">

**Comment by QAbot-zh** [comment]
好像加了$也不行

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/852fed60-baf3-4f6a-bbed-7ec98353c4d2)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/7e02f389-dfba-459a-9186-24023743eccd)
