### ISSUE TITLE
之前的上传文件问题还需要继续反馈一下...

### ISSUE THREAD

**Issue by iceiccy** [Dooy/chatgpt-web-midjourney-proxy#226]
感谢作者的最新更新，成功修复了对话与模型的问题，但我提出的那个问题，好像是表达方式不够清晰，所以发现问题好像没有真正解决，问题的情况是，比如上传图和音频是GPT专属，上传所有文件是Claude专属的话，当用GPT和Claude分别开启不同的旧对话后，如果当前设置的新对话是GPT，那之前的Claude对话，便只能上传图片和音频，不能上传文档，如果新开启的是Claude对话，那之前的旧GPT对话，也能上传所有文档，包括excel和txt，但上传后会报错，整体意思就是，旧对话的上传文件系统，全跟着新对话模型走，而不是各走各的...

**Comment by Dooy** [comment]
你说的是上下文吧？ 一个对话框 肯定不会跟着模型分开走，都当成上下文一起走

如果要修改的符合你的要求的话 你自寻修改吧

**Comment by iceiccy** [comment]
> 你说的是上下文吧？ 一个对话框 肯定不会跟着模型分开走，都当成上下文一起走
> 
> 如果要修改的符合你的要求的话 你自寻修改吧

明白了明白了，原来如此，没需求没需求，就是发现这个情况，如果是这个原因的话，那明白了，感谢
