### ISSUE TITLE
无法使用gpts模型

### ISSUE THREAD

**Issue by zyjfly** [Dooy/chatgpt-web-midjourney-proxy#227]
![企业微信截图_17105554775312](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/7b9ea2c5-6a80-4ebc-8a82-304223d22809)
请问大佬这个是我的api有问题吗 还是什么问题啊

**Comment by iceiccy** [comment]
如果用的是中转API的话，你先确认一下你的API支不支持gpts

**Comment by QAbot-zh** [comment]
大概率是你的中转来源不支持，因为这是逆向模型，中转站未必支持

**Comment by zyjfly** [comment]
之前一直支持的  这两天用的时候突然有问题了

**Comment by QAbot-zh** [comment]
没啥问题，你自定义模型名称错了，把后缀去掉：

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/15c0144c-8690-44d2-be1a-3bc4c0c15c4e)

你要是从gpts商店进的话一切正常：

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40236765/d88b454e-2ed2-4705-a203-e7ad4c125883)

**Comment by zyjfly** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/397285a1-77bc-46b8-b302-f2d31828f23b)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/1d8b5b2c-3043-4094-8b65-85f3e4edfb9f)
去掉后缀可以使用了；不过以前自定义模型是有一个保存至系统，保存后每次直接选择就可以 选择更新之后只有一个保存，每次刷新之后之前保存的自定义模型都会清空，每次使用自定义GPTS就比较麻烦了

**Comment by QAbot-zh** [comment]
那或许你可以通过设置环境变量 `CUSTOM_MODELS`

**Comment by zyjfly** [comment]
自定义模型可以恢复成以前的保存至系统吗，现在只能保存到对话，每次打开新的对话就需要重新输入自定义模型
