### ISSUE TITLE
MJ功能问题反馈

### ISSUE THREAD

**Issue by panzx1222** [Dooy/chatgpt-web-midjourney-proxy#228]
MJ绘画功能中的“视觉”选项，选择“鸟瞰视觉”时自动添加的提示词“Bird view”，会在discord里有概率产生绘画误差，比如提示词：Bird view, pen, writing，生成的图片会带有鸟类生物，与实际提示词不符，测试更换成“aerial view”则没有这个问题，希望作者可以抽空修复下
![微信图片_20240317161458](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/70276812/3541b898-4466-4d3a-8463-4a832aa7f685)
![微信图片_20240317161504](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/70276812/01760578-28ee-43ce-b2c1-766d4f892dc5)

**Comment by Dooy** [comment]
下个版本修复

**Comment by Dooy** [comment]
请更新至 `v2.26.3`
