### ISSUE TITLE
docker搭建使用换脸功能失败

### ISSUE THREAD

**Issue by tuzh6** [Dooy/chatgpt-web-midjourney-proxy#23]
提示如下:

```
提交中
[Unexpected token < in JSON at position 0]
```

另外大佬能否做个访问密码功能，这样就不怕在公网上分享给伙伴用了~

**Comment by Dooy** [comment]
换脸功能需要服务端支持，服务端 需要是 mj proxy plus 版本的


访问密码功能 已经有了 翻下closed的issue

**Comment by tuzh6** [comment]
> 换脸功能需要服务端支持，服务端 需要是 mj proxy plus 版本的
> 
> 访问密码功能 已经有了 翻下closed的issue

看来是我的中转不支持换脸，感谢大佬开发～
