### ISSUE TITLE
2个问题请教下感谢大佬

### ISSUE THREAD

**Issue by wojiaozf** [Dooy/chatgpt-web-midjourney-proxy#230]
问题1，是我这边gpts无法使用
![1710749190379](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/38970192/ddbfa888-7c1b-4e4b-b153-81a9494311e9)
问题2. 我这边使用mj上传图片的时候失败报错了，怎么解决呢
<img width="1097" alt="8f306fc33fd186d346afb7a353518ba" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/38970192/2be96206-fffd-4194-8879-1648d168abe4">
我这边是按文档里docker方式部署的，mj生成图片都没问题，但是上传图片就有问题了，使用的部署脚本是：
docker run --name chatgpt-web-midjourney-proxy  -d -p 6015:3002 \
-e OPENAI_API_KEY=sk-xxxxx \
-e OPENAI_API_BASE_URL=https://api.openai.com  \
-e MJ_SERVER=https://172.17.0.1:6013  \
-e MJ_API_SECRET=abc123456 \
-e API_UPLOADER=1  -v /data/uploads:/app/uploads \
-e AUTH_SECRET_KEY=你的英文密码 -e AUTH_SECRET_ERROR_COUNT=3 \
-e AUTH_SECRET_ERROR_TIME=10 ydlhero/chatgpt-web-midjourney-proxy
这里是哪里不对需要修改吗

**Comment by Dooy** [comment]
用中转吧 https://www.openai-hk.com 这2个问题一套key 都解决了

**Comment by Dooy** [comment]
搞定了没？

**Comment by iceiccy** [comment]
> 搞定了没？

作者，我记得gpts可以单独设定Key和url，再找的时候就找不到具体的文档了，我想问一下是我看错了还是可以单独配置gpts的中转key

**Comment by Dooy** [comment]
<img width="818" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/4e856fe9-aab5-4dc5-8b4d-bb730405dddc">
