### ISSUE TITLE
jwt过期，前端没有提供重新登录的功能

### ISSUE THREAD

**Issue by bigQY** [Dooy/chatgpt-web-midjourney-proxy#231]
后端提示 
{
  "error": {
    "message": "JWT token expired at 1710782448 (request id: 2024XXXX)",
    "type": "upstream_error",
    "param": "403",
    "code": "bad_response_status_code"
  }
}

**Comment by Dooy** [comment]
`JWT token expired at ` 是什么鬼？那门子的登录？

**Comment by bigQY** [comment]
不知道，现在的效果就是我之前的浏览器发送请求都是这样，但是新开一个隐私标签页重新输入AUTH_SECRET_KEY密码就正常了，我也好奇这个403是从哪里来的

**Comment by bigQY** [comment]
> `JWT token expired at ` 是什么鬼？那门子的登录？

不知道，现在的效果就是我之前的浏览器发送请求都是这样，但是新开一个隐私标签页重新输入AUTH_SECRET_KEY密码就正常了，我也好奇这个403是从哪里来的

**Comment by bigQY** [comment]
> > `JWT token expired at ` 是什么鬼？那门子的登录？
> 
> 不知道，现在的效果就是我之前的浏览器发送请求都是这样，但是新开一个隐私标签页重新输入AUTH_SECRET_KEY密码就正常了，我也好奇这个403是从哪里来的

ok，抓包找到了，oneapi的问题，close这个
