### ISSUE TITLE
Upstream sync

### ISSUE THREAD

**Issue by worras2019** [Dooy/chatgpt-web-midjourney-proxy#232]
Please add Upstream Sync in workflow in Actions

**Comment by Dooy** [comment]
老哥  我不会；再者已经兼容不起来了

**Comment by worras2019** [comment]
类似于这样的东西。
[ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/tree/main)/[.github](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/tree/main/.github)/[workflows](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/tree/main/.github/workflows)
/sync.yml
name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: run a standard checkout action
      - name: Checkout target repo
        uses: actions/checkout@v3

      # Step 2: run the sync action
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: ChatGPTNextWeb/ChatGPT-Next-Web
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set

          # Set test_mode true to run tests instead of the true action!!
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#%E6%89%93%E5%BC%80%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0"
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the detailed tutorial for instructions: https://github.com/Yidadaa/ChatGPT-Next-Web#enable-automatic-updates"
          exit 1
