### ISSUE TITLE
本地想二次开发请教一个变量初始化的问题，谢谢

### ISSUE THREAD

**Issue by zfaster** [Dooy/chatgpt-web-midjourney-proxy#234]
在homeStore.ts文件中存放了openai相关配置
`const  getServerDefault=()=>{
let v:gptServerType={
        OPENAI_API_KEY:'',
        OPENAI_API_BASE_URL:'',
        MJ_SERVER:'',
        UPLOADER_URL:'',
        MJ_API_SECRET:'',
        MJ_CDN_WSRV:false
    }
    return v ;
}
const getServerInit= ():gptServerType =>{
    let v:gptServerType=getServerDefault();
    let str = localStorage.getItem('gptServerStore');
    if(str){
        let old = JSON.parse(str);
        if(old) v={...v,...old};
    }
    return v;
}`  我想问下这个是怎么做到初始化的，因为如果我是用docker启动传入环境变量后是可以正常使用的，但是如果我用npm run dev的话，断点看了下这些值都还是空，请问是怎么通过环境变量初始化这些值进去的，前端小白诚心请教下，谢谢~

**Comment by QAbot-zh** [comment]
搜索下关于环境变量设置的内容，比如 linux 你可以到 .bashrc 通过 export 设置

**Comment by Dooy** [comment]
修改下 .env 会不会？

**Comment by zfaster** [comment]
找到问题了，我知道环境变量怎么加，请求一直失败我一开始以为是配置问题，其实是请求没走代理导致的，代码上加了代理配置后请求正常
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/8341790/d2928ddf-4612-4223-a149-e94ef6e4b709)
