### ISSUE TITLE
Bugs in supporing customer models

### ISSUE THREAD

**Issue by worras2019** [Dooy/chatgpt-web-midjourney-proxy#235]
Customer models are not shown in the model menu by adding them on client end and even though I add them on server side, the customer model is not reall called.

**Comment by Dooy** [comment]
不知道 你参数如何设置的，最好带图 不然比较难定位

**Comment by worras2019** [comment]
添加自定义模型后，菜单里没有显示自定义模型。有bug。模型菜单拉到底了已经。
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/52268635/7e39b63a-17e8-4e08-8ca7-2cf519e64dc0)

**Comment by Dooy** [comment]
看到问题了，需要点击保存下 才会更新；下个版本修复

**Comment by Dooy** [comment]
已修复 v2.16.5
