### ISSUE TITLE
请教版主，我们有技术交流群吗？

### ISSUE THREAD

**Issue by sslzhou948** [Dooy/chatgpt-web-midjourney-proxy#236]
请教版主，有几个问题：
1.  我们有技术交流群吗？
2. 这个前端是否支持会员管理、充值计费等模块呢？
3. 我想把它和one-api整合起来，不知是否有人实践过

**Comment by Dooy** [comment]
没时间维护 用issue 就好了

跟 one-api 整合 你可以看下readme

`会员管理、充值计费`需要2开, 要开发预算 邮件我 dooy520@qq.com
