### ISSUE TITLE
关于自定义文件服务器

### ISSUE THREAD

**Issue by heiyyint** [Dooy/chatgpt-web-midjourney-proxy#238]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/3802e15d-7678-42de-8ba6-3ceb165a9d5f)设置自定义上传文件服务器，不生效，设置之后一样走v1，已有按照相应变量环境进行填写，文件服务器项目：https://github.com/AnjanaMadu/FileServer

_Originally posted by @zyyint in https://github.com/Dooy/chatgpt-web-midjourney-proxy/issues/178#issuecomment-2010335551_

**Comment by Dooy** [comment]
没太多时间 知道 项目中写了 几个类部署

你可以参考下 这个 https://github.com/Dooy/chatgpt-web-midjourney-proxy/tree/main/docker-compose/gpts-mj-file

**Comment by zyyint** [comment]
> 没有太多时间知道项目中写了几个类部署
> 
> 你可以参考下这个https://github.com/Dooy/chatgpt-web-midjourney-proxy/tree/main/docker-compose/gpts-mj-file

设置MyUrl参数似乎是不生效

**Comment by zyyint** [comment]
> > 没有太多时间知道项目中写了几个类部署
> > 你可以参考下这个https://github.com/Dooy/chatgpt-web-midjourney-proxy/tree/main/docker-compose/gpts-mj-file
> 
> MyUrl 参数似乎未设置

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/613f5bf1-2394-4461-b3db-fa9985ba5587)
文件上传走的路径并不是文件服务器的，有使用[docker-compose](https://github.com/Dooy/chatgpt-web-midjourney-proxy/tree/main/docker-compose/gpts-mj-file)

**Comment by Dooy** [comment]
> > 没有太多时间知道项目中写了几个类部署
> > 你可以参考下这个https://github.com/Dooy/chatgpt-web-midjourney-proxy/tree/main/docker-compose/gpts-mj-file
> 
> 设置MyUrl参数似乎是不生效

这个url要在前端填写

**Comment by zyyint** [comment]
> > > 没有太多时间知道项目中写了几个类部署
> > > 你可以参考下这个https://github.com/Dooy/chatgpt-web-midjourney-proxy/tree/main/docker-compose/gpts-mj-file
> > 
> > 设置MyUrl参数似乎是不生效
> 
> 这个url要在前端填写

关联前端ui的吗？他不走全局变量吗
