### ISSUE TITLE
MJ绘画，使用中文，绘图结果不符合中文提示，用英文正常，估计是翻译问题

### ISSUE THREAD

**Issue by MoZhuXuanKe** [Dooy/chatgpt-web-midjourney-proxy#239]
<img width="1029" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/16641348/318dcfa1-7641-403d-b481-35b0507dff1c">
<img width="1050" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/16641348/c90f9c85-9e30-45cd-aece-489229953d19">
作者大佬麻烦看下这个问题

**Comment by zyyint** [comment]
你这个是用的别人的MJ-api吧，翻译问题，跟网站没关系的，联系你的api，提供者

**Comment by Dooy** [comment]
翻译问题 自己谷歌翻译就好了 不求人
