### ISSUE TITLE
电脑端：按住回车不放，会一直触发提交刷新页面

### ISSUE THREAD

**Issue by UPman24** [Dooy/chatgpt-web-midjourney-proxy#24]
在输入输入内容，然后按住回车不放，会一直触发提交。期望：在用户正在进行任务的时候，不能再提交下一个任务。GPT还在回答的时候不能让用户继续提问。按钮应该置灰。

**Comment by Dooy** [comment]
收到 下个版本 一并修复

**Comment by Dooy** [comment]
v2.12.9 已修复
