### ISSUE TITLE
出现Cannot GET /

### ISSUE THREAD

**Issue by zhanghs23** [Dooy/chatgpt-web-midjourney-proxy#241]
自行docker构建镜像，然后使用docker-compose部署，使用项目中的是Dockerfile和docker-compose文件。页面访问会出现Cannot GET / 的问题。

**Comment by Dooy** [comment]
项目中好多个 docker-compose 不知道你说的哪个

**Comment by zhanghs23** [comment]
这个  https://github.com/Dooy/chatgpt-web-midjourney-proxy/blob/main/docker-compose/docker-compose.yml

**Comment by Dooy** [comment]
能带图 带下图吧 让我猜 我猜不出来

**Comment by zhanghs23** [comment]
操作步骤如下：
1. git clone https://github.com/Dooy/chatgpt-web-midjourney-proxy.git 项目到服务器
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/128876811/6a85555d-0f08-48b1-a92f-26c9e5fb12d4)

2. 执行 docker build -t zhanghs/chatgpt-web-midjourney-proxy:v1 . 
Dockerfile 如下：
`FROM node:lts-alpine AS frontend

RUN npm install pnpm -g

WORKDIR /app

COPY ./package.json /app

COPY ./pnpm-lock.yaml /app

RUN pnpm install

COPY . /app

RUN pnpm run build

# build backend
FROM node:lts-alpine as backend

RUN npm install pnpm -g

WORKDIR /app

COPY /service/package.json /app

COPY /service/pnpm-lock.yaml /app

RUN pnpm install

COPY /service /app

RUN pnpm run build

# service
FROM node:lts-alpine

RUN npm install pnpm -g

WORKDIR /app

COPY /service/package.json /app

COPY /service/pnpm-lock.yaml /app

RUN pnpm install --production && rm -rf /root/.npm /root/.pnpm-store /usr/local/share/.cache /tmp/*

COPY /service /app

COPY --from=frontend /app/dist /app/public

COPY --from=backend /app/build /app/build

EXPOSE 3002

CMD ["pnpm", "run", "prod"]`

3. docker-compose 编写，填写镜像，OPENAI KEY等，具体如下：
`version: '3'
services:
  gptweb:
    container_name: zhanghs-chatgpt-web-midjourney-proxy
    image: zhanghs/chatgpt-web-midjourney-proxy:v1  # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 6080:3002
    environment:
      TZ: Asia/Shanghai # 指定时区
      # 必选
      OPENAI_API_KEY: xxxxxxxxxxxxxxxxxxxx
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: xxxxxxxxxxxxxxxx
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL:
      # 访问权限密钥，可选
      AUTH_SECRET_KEY: xxxxxxxxxxxxxxxxxxxxxxx
      # midjourney 服务器地址，可选 可用下面的 http://midjourney-proxy:8080
      MJ_SERVER: xxxxxxxxxxxxxxxxxxxxxx
      # midjourney API密钥，可选
      MJ_API_SECRET: xxxxxxxxxx
      #API_UPLOADER 是否可以上传 1 可以其他都不可以，可选
      API_UPLOADER:
      #HIDE_SERVER 隐藏服务端 1，可选
      HIDE_SERVER: 1
      #自定义模型  CUSTOM_MODELS=-gpt-3.5-turbo-0301,gpt-4.5 不显示 gpt-3.5-turbo-0301 新增加 gpt-4.5，可选
      CUSTOM_MODELS:
      #TJ_BAIDU_ID 百度统计ID，可选
      TJ_BAIDU_ID:
      #TJ_GOOGLE_ID 谷歌统计ID，可选
      TJ_GOOGLE_ID:
      #SYS_NOTIFY 系统通知 支持HTML ，可选
      SYS_NOTIFY:
      #FILE_SERVER 文件服务器，可选 可以用下面的 http://fileserver:3012
      FILE_SERVER:
      #DISABLE_GPT4=1 前端限制GPT4调用，可选
      DISABLE_GPT4:
      # cloudflare r2 存储 10 GB/月 免费 https://www.cloudflare.com/zh-cn/developer-platform/r2/
      R2_DOMAIN:
      R2_BUCKET_NAME:
      R2_ACCOUNT_ID:
      R2_KEY_ID:
      R2_KEY_SECRET:
      ## UPLOAD_IMG_SIZE gpt-4-version 图片上传大小 单位是兆 注意别带单位 最好别超过10 
      UPLOAD_IMG_SIZE: 1
      # GPT_URL=/gpts.json  自定义GPTs模型
      GPT_URL:
      # SYS_THEME 主题 theme   light 或者 dark 
      SYS_THEME: dark
      #关闭MD预览  CLOSE_MD_PREVIEW=1
      CLOSE_MD_PREVIEW:
      #爆破：验证次数 注意: vercel 不支持 nginx 请设置  proxy_set_header   X-Forwarded-For  $remote_addr;
      AUTH_SECRET_ERROR_COUNT: 3
      #爆破：验证停留时间 单位分钟 注意: vercel 不支持
      AUTH_SECRET_ERROR_TIME: 10`

4. docker-compose up -d 启动容器

**Comment by Dooy** [comment]
为何 不用 `docker-compose up -d` 或者 `docker compose up -d` 来启动？
readme不够没写明白？
