### ISSUE TITLE
关于GPTs接口数据来源

### ISSUE THREAD

**Issue by Kilig947** [Dooy/chatgpt-web-midjourney-proxy#242]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/46100050/cc4f54c2-d333-41f1-b760-db5b3717f86b)

请问作者，这些数据来源在哪呀？

**Comment by Dooy** [comment]
不都给你抓出来了么？

**Comment by Kilig947** [comment]
> 不都给你抓出来了么？

https://gpts.ddaiai.com/open/gptsapi/search 接口的数据来源，怎么逆向的，有开源的项目不？
