### ISSUE TITLE
为什么使用Midjourney Proxy API的时候，比API 多    "botType": "MID_JOURNEY"  这个字段。导致使用不成功。

### ISSUE THREAD

**Issue by tmall258** [Dooy/chatgpt-web-midjourney-proxy#243]
{
  "error": "TypeError: Failed to fetch",
  "data": {
    "base64Array": [],
    "notifyHook": "",
    "prompt": "cat --v 6.0",
    "state": "",
    "botType": "MID_JOURNEY"
  },
  "code": "fetch_fail",
  "url": "http://172.20.0.188:8081/mj/submit/imagine"
}
Midjourney Proxy API 只有下面几个字段。
{
  "base64Array": [],
  "notifyHook": "",
  "prompt": "Cat",
  "state": ""
}

**Comment by ozil56** [comment]
the same

**Comment by Dooy** [comment]
请到 Midjourney Proxy 的issue提问

**Comment by cyDione** [comment]
用postman测试接口发现"base64Array": [],
"notifyHook": "",
"prompt": "cat --v 6.0",
"state": "",
"botType": "MID_JOURNEY"
