### ISSUE TITLE
建议增加gpts管理功能

### ISSUE THREAD

**Issue by sheongkamyu** [Dooy/chatgpt-web-midjourney-proxy#246]
gpts太多了，一个id一个模型去创建太麻烦，能否直接gpt-4-gizmo直接可以调用所有的gpts。或者有没有更好的使用办法？如果1000个gpts要创建1000个转换模型。或者能否提供下所有gpts的模型一行一个

**Comment by Dooy** [comment]
看下 readme 有解决方案啊 ；可自定义啊

**Comment by QAbot-zh** [comment]
不是有商店可以选gpts吗？直接调用所有gpts，你是不是想多了，官网调用gpts也要选好gpts开对话窗口呀，不给gpts的id，它怎么知道你想调用哪个gpts 😂
