### ISSUE TITLE
请教一下文件上传的问题

### ISSUE THREAD

**Issue by iceiccy** [Dooy/chatgpt-web-midjourney-proxy#247]
你好，我是通过项目模板的方式搭建，命令行为：
services:
  gptweb:
    image: ydlhero/chatgpt-web-midjourney-proxy:latest
    restart: always
    environment:
      OPENAI_API_KEY: sk-1yhiVE7we5VvSRBH0846
      OPENAI_API_BASE_URL: https://api.r/v1
      MJ_SERVER: https://api.op
      MJ_API_SECRET: hk-5yfyn91074b770
      HIDE_SERVER: 1
      API_UPLOADER: 1
      MJ_API_GALLERY: 1
      AUTH_SECRET_ERROR_COUNT: 3
      AUTH_SECRET_ERROR_TIME: 10
      AUTH_SECRET_KEY: Kaix
      UPLOAD_TYPE: R2
      R2_DOMAIN: https://pub-e025a6859e507260caee.r2.dev
      R2_BUCKET_NAME: nfs-pictures-r2
      R2_ACCOUNT_ID: a6e595984a4922ea
      R2_KEY_ID: b55ca6d88382b1018
      R2_KEY_SECRET: 7d1b5694bd96dd
    ports:
      - "16090:3002"
    volumes:
      - /data/cwm_uploads:/app/uploads
其中有几个疑问，
1：MJ画图的cref只能从别的地方上传图片，再获取链接后填入进行绘图么？不能直接通过上传垫图的方式直接进行cref创作么？
2：上述的配置是否正确昂？尤其是R2，如何确定是否配置正确且生效昂？
3： R2_DOMAIN这一项，是填R2里的S3 API，还是自定义域，还是公共 R2.dev 存储桶 URL？
可能问的有点繁杂，辛苦作者了，感谢作者

**Comment by Dooy** [comment]
1 后面再完善吧
2 3 自己试下吧 我很少用 R2

**Comment by iceiccy** [comment]
> 1 后面再完善吧 2 3 自己试下吧 我很少用 R2

好的好的，感谢，对了，MJ画图里可以增加一个翻译的选项么？中英译就行，虽然midjourney-proxy-plus有这个功能，但如果使用的是API中转，API没设置的话，就没法自动翻译，出来的结果就悬殊很大，如图：
![screenshot-141 98 196 185_16090-2024 03 26-10_49_07](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/52325430/1457c622-e3d8-4f8d-8baf-9bf1e95b3669)

**Comment by ChuckZengxf** [comment]
> > 1 后面再完善吧 2 3 自己试下吧 我很少用 R2
> 
> 好的好的，感谢，对了，MJ画图里可以增加一个翻译的选项么？中英译就行，虽然midjourney-proxy-plus有这个功能，但如果使用的是API中转，API没设置的话，就没法自动翻译，出来的结果就悬殊很大，如图： ![screenshot-141 98 196 185_16090-2024 03 26-10_49_07](https://private-user-images.githubusercontent.com/52325430/316711340-1457c622-e3d8-4f8d-8baf-9bf1e95b3669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTk4NzMsIm5iZiI6MTcxMjc5OTU3MywicGF0aCI6Ii81MjMyNTQzMC8zMTY3MTEzNDAtMTQ1N2M2MjItZTNkOC00ZjhkLThiYWYtOWJmMWU5NWIzNjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAxMzkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNGQ5MGFiOWM2YmFkNjIzMTVmNDc4YTcxOTZiNjlhNzQwOGM0OWNkNDUzNDU0ZmY0YzJlN2E0N2ZiZDc5MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dskBk0BIKyhLPL1_lPYN4VOMQmgkDTcUIP1lOhHkFAw)
用第三方接口写一个被，百度、阿里都是免费的

**Comment by Dooy** [comment]
你直接填写英文 他应该不会去走翻译

翻译还是留给 midjourney-proxy-plus 去做；前端实现起来比较繁琐 而且麻烦
