### ISSUE TITLE
[aiCanvas] InPaint image editor sources availability

### ISSUE THREAD

**Issue by Sarkhad** [Dooy/chatgpt-web-midjourney-proxy#248]
Is it known where to get sources of the image editor shown in iFrame from
`https://mj.aibear.com.cn/draw/mitf/index.html` for purposes of customization, especially translation to English?

`<template>
    <iframe @load="loadOk" ref="ifdiv" :src="`https://mj.aibear.com.cn/draw/mitf/index.html?${st.q}`"  class=" h-[80vh] w-full" style="border-width: 0px; border-style: none; overflow: hidden;" v-if="st.q"></iframe>
</template>`

**Comment by Dooy** [comment]
You can save the html of this link, modify it, and put it on your own server; then enter it in the iframe, and that's it.

**Comment by Sarkhad** [comment]
> You can save the html of this link, modify it, and put it on your own server; then enter it in the iframe, and that's it.

Unfortunately, the page is not accessible from my side thus I was looking for the repo

**Comment by Dooy** [comment]
I'll reply later.

**Comment by Dooy** [comment]
https://github.com/Dooy/chatgpt-web-midjourney-proxy/tree/main/src/static/mitf

It's all right now. please update to v2.16.5

**Comment by Sarkhad** [comment]
🤝

**Comment by Sarkhad** [comment]
Thanks 🤝
