### ISSUE TITLE
mj 出错

### ISSUE THREAD

**Issue by JaysonPeng** [Dooy/chatgpt-web-midjourney-proxy#249]
"error": "TypeError: Failed to fetch",
  "data": {
    "base64Array": [],
    "notifyHook": "",
    "prompt": "a boy --v 6.0",
    "state": "",
    "botType": "MID_JOURNEY"
  },
  "code": "fetch_fail",

**Comment by Dooy** [comment]
截图，好像你的服务端不支持

**Comment by JaysonPeng** [comment]
> 截图，好像你的服务端不支持

我用的zeabur部署的midjourney proxy，可用账号数量[1],应该是部署成功了啊

**Comment by JaysonPeng** [comment]
> 截图，好像你的服务端不支持

好像确实不行？我测试接口都不通...看部署和运行日志也没有错误.
