### ISSUE TITLE
请教如何设置多个密码？

### ISSUE THREAD

**Issue by N04LE7** [Dooy/chatgpt-web-midjourney-proxy#250]
AUTH_SECRET_KEY要怎么添加分隔符设置多个密码?

**Comment by Dooy** [comment]
目前不支持

**Comment by N04LE7** [comment]
好的，希望早日增加！另外原版可以通过修改文件实现多个密码，https://github.com/Chanzhaoyu/chatgpt-web/issues/1096

**Comment by Dooy** [comment]
ok

**Comment by haichaojiyi** [comment]
> 好的，希望早日增加！另外原版可以通过修改文件实现多个密码，[Chanzhaoyu/chatgpt-web#1096](https://github.com/Chanzhaoyu/chatgpt-web/issues/1096)

不是和原来一样的，直接改下就可以多用户了

**Comment by old-eight800** [comment]
原版也是通过修改源码的方式支持多个验证码登录,可以尝试修改看看

**Comment by Dooy** [comment]
这个 好像 已经支持了
