### ISSUE TITLE
使用openaihk的key无法使用gpts的功能

### ISSUE THREAD

**Issue by chao1209** [Dooy/chatgpt-web-midjourney-proxy#251]
之前的版本可以使用，现在都是显示未找到这个模型 

{
  "error": {
    "message": "未找到这个模型 (request id: 2024032714554961441390144007229)",
    "type": "openai_hk_error",
    "param": "openai_hk_error",
    "code": "openai_hk_error"
  }
}

**Comment by Dooy** [comment]
gpts 下线了 换一个模型
