### ISSUE TITLE
有个稳定性方面的问题

### ISSUE THREAD

**Issue by yinhaixiang** [Dooy/chatgpt-web-midjourney-proxy#252]
最近我的用户经常反馈接口请求有404情况, 据我观察是因为第一次请求"/openapi/v1/chat/completions"接口, 然后请求失败, 但是openai有重试机制, 于是自动发起第二次请求, 但是在第二次请求过程中, 因为express-http-proxy做了 `proxyReqPathResolver: function (req) {
    return req.originalUrl.replace('/openapi', '') // 将URL中的 `/openapi` 替换为空字符串
  },` 处理, 所以第二次的请求路径变成了"/v1/chat/completions?retry=1", 相比第一次少了"/openapi", 这才会发生404的情况, 我在原来的chatgpt-web项目中用同样的中转API, 原来的请求都是通过"/chat-process"接口给到后端, 如果发生重试也是后端内部自己处理的, 所以没有少"/openapi"这个步骤, 也因此不会产生404的现象, 这个问题其实困扰我好久了, 也不知道从哪方面入手修复比较好
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/10047441/24a9df2a-7ede-42b7-8e35-8a7486f78804)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/10047441/17774b61-f456-4bbd-bf05-fc1e2d9bda7b)

**Comment by yinhaixiang** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/10047441/132359df-723b-4bc6-a4c8-8a83056e2276)
还是存在的

**Comment by yinhaixiang** [comment]
我更新代码了没看到这块逻辑发生什么变化, 如果用稳定性不高的apiKey, 还是会经常产生这种现象(但是chatgpt-web项目不会, 因为可以很好的自己尝试重试)

**Comment by Dooy** [comment]
是 service worker 搞的 
试着下面的这段代码去掉 再编译打包
<img width="603" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/ad8d6768-0cbb-4aee-817e-d001e353a5e4">
