### ISSUE TITLE
咨询个简单的部署问题

### ISSUE THREAD

**Issue by liuHongyang0207** [Dooy/chatgpt-web-midjourney-proxy#254]
我这边为什么部署时代码一直是老的那套代码(前端代码和后端代码都是git下来的这套)，是我执行的不对的吗，之前没用过docker，，求助！！

我是在这个 gpts-mj-file文件目录下(这个应该是功能最全的吧)，执行的./start.sh

![POPO-20240328-195339](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/108056008/4f2f62bd-1bf8-4abe-ab1a-8041a55376ba)

**Comment by Dooy** [comment]
你没安装Docker吧 这个sh  是bash
LInux 体系 或者 mac; 前提是你安装了 Docker

**Comment by liuHongyang0207** [comment]
感谢您的解答，不过我这边是使用了win，桌面版的，安装了docker，是正常运行的；只是代码没有更新...

![Uploading 3973.jpg…]()

**Comment by Dooy** [comment]
先找到 Docker compose 命令来 ；window下 不知道这个命令是什么
