### ISSUE TITLE
重新绘制这个报错事为啥呢

### ISSUE THREAD

**Issue by lzy990321** [Dooy/chatgpt-web-midjourney-proxy#255]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/57216226/ed398948-f14b-4b86-9ea3-9068d8b5c8ce)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/57216226/58dfa2f6-d5c2-4bbb-957e-abc130c076ea)

**Comment by zyyint** [comment]
接口不响应

**Comment by Dooy** [comment]
discord 有的时候会抽风
