### ISSUE TITLE
源码有没有文档使用教程啊，就是二次修改

### ISSUE THREAD

**Issue by hegongniuren** [Dooy/chatgpt-web-midjourney-proxy#258]
想对部分界面拆开改造。

**Comment by Dooy** [comment]
老板 不要那么麻烦，可以请我二开 ^_^

**Comment by hegongniuren** [comment]
可以，留个联系方式


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Dooy/chatgpt-web-midjourney-proxy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月30日(星期六) 晚上9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Dooy/chatgpt-web-midjourney-proxy] 源码有没有文档使用教程啊，就是二次修改 (Issue #258)





 
老板 不要那么麻烦，可以请我二开 ^_^
