### ISSUE TITLE
gemini-1.5-pro模型

### ISSUE THREAD

**Issue by zyyint** [Dooy/chatgpt-web-midjourney-proxy#259]
作者可以新增对gemini-1.5-pro模型支持吗
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/aec98e29-ae47-4025-94b4-5342ed2f3809)

**Comment by Dooy** [comment]
这个 得问问中转了

**Comment by heiyyint** [comment]
能否支持下gemini-pro-1.5走base64，这url不能识别但是走base64解析图片又能识别出来
