### ISSUE TITLE
没有midjourney api 是否支持用discord的user-token?

### ISSUE THREAD

**Issue by gaidan1983** [Dooy/chatgpt-web-midjourney-proxy#26]
看说明有提到参考了novicezk/midjourney-proxy，本项目是否也支持用discord的user-token?
-e mj.discord.guild-id=discord服务ID  \
-e mj.discord.channel-id=discord服务组ID   \
-e mj.queue.timeout-minutes=6 \
-e mj.api-secret=abc123456 \
-e mj.discord.user-token=**********  \

**Comment by Dooy** [comment]
把 novicezk/midjourney-proxy 当后端，直接用你的参数起一个docker

本项目仅是他的前端

**Comment by gaidan1983** [comment]
> 把 novicezk/midjourney-proxy 当后端，直接用你的参数起一个docker
> 
> 本项目仅是他的前端
同时起一个 novicezk/midjourney-proxy 镜像容器？在启动时给我自己的discord参数，-e mj.api-secret=abc123456 保持默认？

**Comment by Dooy** [comment]
是的

**Comment by gaidan1983** [comment]
> 是的
在discord网站添加机器人到服务器过程中，提示“由于需求激增，我们暂时无法提供免费试用。请订阅以创建Midjourney的图片。”给了midjourney的订阅付费网页链接。是不是说我只能购买midjourney，同时在您的项目里直接配置midjourney api，而不用再起novicezk的后端了？

Midjourney Bot
机器人
 — 今天10:27
Subscription required
Due to extreme demand we can't provide a free trial right now. Please /subscribe to create images with Midjourney.
/imagine cat

**Comment by gaidan1983** [comment]
> 是的

在discord网站添加机器人到服务器过程中，提示“由于需求激增，我们暂时无法提供免费试用。请订阅以创建Midjourney的图片。”给了midjourney的订阅付费网页链接。是不是说我只能购买midjourney，同时在您的项目里直接配置midjourney api，而不用再起novicezk的后端了？
Midjourney Bot
机器人
— 今天10:27
Subscription required
Due to extreme demand we can't provide a free trial right now. Please /subscribe to create images with Midjourney.
/imagine cat

**Comment by Dooy** [comment]
大哥 你想白嫖人家么？

**Comment by gaidan1983** [comment]
> 大哥 你想白嫖人家么？
我们没明白，你说的是“人家”是指discord么？
年初时discord是可以自己创建服务器并添加机器人到自己的服务器和频道的，通过网页F12可以抓到discord的user-token

**Comment by Dooy** [comment]
需要起 novicezk 后端，但首先你得有付费的 mj账号

我的前端支持 midjourney proxy 也支持 midjourney proxy plus（就是novicezk的付费软件 ）；
你不要付费买 mj proxy plus ;直接用免费的也支持；首先得有mj付费账号哈

还有现在很多 中转都支持  mj proxy plus 接口了 ；
如果有中转支持 就只需要中转的 api_url 跟  api-secret 就好了 ，不需要  mj proxy 甚至不需要 mj账号

**Comment by gaidan1983** [comment]
> 需要起 novicezk 后端，但首先你得有付费的 mj账号
> 
> 我的前端支持 midjourney proxy 也支持 midjourney proxy plus（就是novicezk的付费软件 ）； 你不要付费买 mj proxy plus ;直接用免费的也支持；首先得有mj付费账号哈
> 
> 还有现在很多 中转都支持 mj proxy plus 接口了 ； 如果有中转支持 就只需要中转的 api_url 跟 api-secret 就好了 ，不需要 mj proxy 甚至不需要 mj账号

收到，您讲得很清楚了，谢谢，我再看一下中转API方案。

**Comment by Dooy** [comment]
收到 那我就close掉了
