### ISSUE TITLE
请教一下我这是哪里没设置对

### ISSUE THREAD

**Issue by 141155** [Dooy/chatgpt-web-midjourney-proxy#261]
![1 (1)](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/117498643/e518a0f6-2e76-481e-96c3-2cd3f40d4b6f)
![1 (2)](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/117498643/f848710b-81f7-4b34-9590-09fd1b4f419e)

**Comment by Dooy** [comment]
你有 openai的key?

**Comment by yiishan** [comment]
需要你自己账号的APIkey，你这SK-XXXX只是默认格式没用的
另外3.5已经免费开放了，不知道开发者能不能设置3.5默认使用不需要key，4.0才需要设置key

**Comment by 141155** [comment]
> 需要你自己账号的APIkey，你这SK-XXXX只是默认格式没用的 另外3.5已经免费开放了，不知道开发者能不能设置3.5默认使用不需要key，4.0才需要设置key

**Comment by QAbot-zh** [comment]
> 需要你自己账号的APIkey，你这SK-XXXX只是默认格式没用的 另外3.5已经免费开放了，不知道开发者能不能设置3.5默认使用不需要key，4.0才需要设置key

不准确，官方web-3.5从来都是免费开放的，api-3.5也一直是收费的，web2api 也只是权宜之计，针对官方的免登录web-3.5，也有一些项目做了转api，如果有需要可以部署他们的项目。

**Comment by XTurnV007** [comment]
上cursor api注册一个账号，复制一个apikey就能用了。便宜好用https://api.cursorai.art/register?aff=xoXg

![Image](https://github.com/user-attachments/assets/e4735ab5-0eb6-4e24-8a9f-d9e8eff279ed)
