### ISSUE TITLE
MJ的使用问题

### ISSUE THREAD

**Issue by weiarnold** [Dooy/chatgpt-web-midjourney-proxy#263]
我连接chatgpt没有问题，但在绘图中使用MJ失败了，检查docker日志显示“The HTTP request to initiate the WebSocket connection to [wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream] failed”，我却不知道如何解决，求大佬指点
![微信截图_20240405020716](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/166056074/8dc6aa5b-ca83-4587-becd-1166ae6b179e)
![微信截图_20240405020822](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/166056074/86c39239-c709-4496-9dad-3746b48e695f)

**Comment by Dooy** [comment]
mj的问题 我也搞不定， 你到  https://github.com/novicezk/midjourney-proxy提issue把
你先手工 或者用postman测试

**Comment by xiazhibin** [comment]
@Dooy https://github.com/novicezk/midjourney-prox 不能提issue [狗头]

**Comment by Dooy** [comment]
重启下 就解决了

**Comment by Dooy** [comment]
或者用中转

**Comment by Javaisno1** [comment]
最后怎么解决的啊，我现在就是这样的

**Comment by xiao-wj** [comment]
想问下最后解决了吗，我也碰到了同样的问题，dev环境可以访问discord服务器，但线上环境报同样的错
