### ISSUE TITLE
403forbidden是什么问题啊。。

### ISSUE THREAD

**Issue by buwanyuanshen** [Dooy/chatgpt-web-midjourney-proxy#264]
vercel部署了环境变量，使用的是newapi,国内服务器，查询余额和对话浏览器控制台都显示403。
但是使用别人的newapi网址和key就没有问题。
不过在前端填写使用都是正常的，而且nextweb和lobechat都没问题。
我的这个域名是挂在cf上的，国外ip打开是会慢点。
百思不得其解啊🤔究竟是什么问题呢？

**Comment by Dooy** [comment]
试下 非vercel 部署； vercel 服务端没去做兼容
