### ISSUE TITLE
DALLE功能能否更新一下

### ISSUE THREAD

**Issue by zyjfly** [Dooy/chatgpt-web-midjourney-proxy#265]
官网的dalle目前已经支持对生成的图片直接进行选择对应的位置通过提示词编辑，可否进行升级？

**Comment by Dooy** [comment]
chat.openai.com 一直支持啊
api 好像不支持吧？

**Comment by zyjfly** [comment]
https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/be23949c-e18e-4105-91a0-bbd4fd55c4dd

我看是openai4天前发的 不知道可以弄不 不支持也没事 就是觉得这个功能挺有意思
