### ISSUE TITLE
mj绘图调用问题

### ISSUE THREAD

**Issue by ye4293** [Dooy/chatgpt-web-midjourney-proxy#266]
请问是对key的长度做了检查吗，我二开接入mj-plus的系统，一样的请求我再apifox能请求，但是在我们项目上，一直报错显示没有提供key
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/137054651/38655a2d-e7df-4bf7-8912-d8ba29cdaaa8)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/137054651/5421fab7-f457-4a43-9b62-577b6e9ea62c)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/137054651/4da8d99e-c872-4793-93d7-4bc6dc373fd7)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/137054651/50f14214-5f67-47a7-adfe-cca2752e8883)

**Comment by ye4293** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/137054651/4fa35d21-8bbc-4418-bddf-72a6a06d81d4)

**Comment by Dooy** [comment]
F12贴下报错信息

**Comment by ye4293** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/137054651/7affdb02-30c1-4a09-94f2-2f8fffbff41d)
报错信息是这个

**Comment by ye4293** [comment]
但是我在apifox上面又没有问题，我有点懵逼

**Comment by Dooy** [comment]
401 认证问题 key 不对吧

**Comment by ye4293** [comment]
打印了这边的传的key值，是空，但是从apifox传的不是空，我改了下我的代码，对空进行了处理。已经兼容了。麻烦了

Dooy ***@***.***> 于2024年4月10日周三 11:34写道：
