### ISSUE TITLE
MJ绘画模式

### ISSUE THREAD

**Issue by heiyyint** [Dooy/chatgpt-web-midjourney-proxy#267]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/360f218e-c187-4958-a137-cb10598a6228)
可以增加这个模式切换吗，对于不需要使用快速模式的人来说挺好

**Comment by Dooy** [comment]
前端ui 服务端处 上自己能切换吧？

**Comment by zyyint** [comment]
> 前端ui 服务端处 上自己能切换吧？

不清楚，但是如果有个开关 兴许会好一点
