### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by liuHongyang0207** [Dooy/chatgpt-web-midjourney-proxy#268]
为什么不论我怎么部署，代码始终是最开始的那一套呢？前端页面为什么一直不变呢？？我前端的页面应该部署在哪？？nginx/html是哪？我本身有docker，，挂在在自己的服务器目录上，有点不太懂为什么前端样式总是不变呢？

**Comment by Dooy** [comment]
看下 这个地方 版本是不是一直不变？
<img width="787" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/fcc14f88-0594-4419-95fa-d4b45031b455">

**Comment by liuHongyang0207** [comment]
嗯嗯，确实一直没变，，但是我项目里面的版本号是都改了的，，我ui也改了些，但是一直没生效，还需要改动哪里吗 @Dooy

**Comment by liuHongyang0207** [comment]
就是不知道前端文件部署在哪了

**Comment by Dooy** [comment]
自己二开了？ 为何不用Docker？

**Comment by liuHongyang0207** [comment]
想自己二开下，想用UI页面，感觉页面很好；
因为用docker发现前端UI修改不了，如果前端页面可以自己修改并部署的话还是会用docker @Dooy
