### ISSUE TITLE
BUG : 对话记录删除全部，会卡死，100%发生，希望大佬抽空处理掉

### ISSUE THREAD

**Issue by sunsky89757** [Dooy/chatgpt-web-midjourney-proxy#269]
![111](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/113254524/e6acc38a-5916-401a-aad0-f92b7ce5301b)
如图所示。

另外，本程序在手机上访问，也有卡顿现象

**Comment by Dooy** [comment]
收到

**Comment by Dooy** [comment]
经过测试 我这 居然不会

**Comment by Dooy** [comment]
手机上 我再测试下

**Comment by Dooy** [comment]
手机也无妨啊 奇怪了

**Comment by sunsky89757** [comment]
我今天好像也复现不到了，等我后面捕捉到再反馈哈~

**Comment by YBYCS** [comment]
同样有这个问题，我删除任意对话都会卡死，公司和自己的电脑的都是，使用的是edge浏览器最新版本，配置放在前端
