### ISSUE TITLE
目前上传图片限制1m，怎么配置大小

### ISSUE THREAD

**Issue by xieshiqi147258** [Dooy/chatgpt-web-midjourney-proxy#27]
目前上传图片限制1m，怎么配置大小

**Comment by Dooy** [comment]
目前 配置没放出来，有代码能力的话自行修改下

**Comment by gaojunyang666** [comment]
这个图片大小也很头疼，现在都要压缩一下再上传哈哈哈

**Comment by gaojunyang666** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/63088548/18037668-40de-4555-a8fe-5d9332ddac41)
这里改吗

**Comment by gaojunyang666** [comment]
好消息是能找到，坏消息是不会改

**Comment by Dooy** [comment]
后面 我把他 改成配置文件吧

**Comment by gaojunyang666** [comment]
> 后面 我把他 改成配置文件吧

好的好的，谢谢开发者大大
