### ISSUE TITLE
大佬大佬，将路由模式WebHashHistory换成WebHistory  ，运行项目切换页面会出现 #/+ 页面路径的情况，如何解决？

### ISSUE THREAD

**Issue by Z-ak349** [Dooy/chatgpt-web-midjourney-proxy#270]
![318400555-0e1778b5-ac55-4753-addf-c527423d0ce0](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129034664/6ee199c4-aa03-4ee7-a2fe-7d888f8371cd)
![318400857-a097eab6-a1f3-4497-a8d1-10eb33572198](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129034664/f0b1d2f3-15da-43d7-bcb5-ef25a0cef554)

**Comment by Dooy** [comment]
用 draw 搜索下 ；应该是我搞的路由不规范
