### ISSUE TITLE
gpts 模型不存在

### ISSUE THREAD

**Issue by chensiwe** [Dooy/chatgpt-web-midjourney-proxy#271]
{
  "error": {
    "message": "The model `gpt-4-gizmo-g-HMNcP6w7d` does not exist or you do not have access to it.",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}
请问这个是官方key不存在这个model吗？ 那么这个model是要自己实现吗？

**Comment by Dooy** [comment]
这个gpts官网下线了
