### ISSUE TITLE
是否可以让TTS的api放在自定义接口上？

### ISSUE THREAD

**Issue by wangasa** [Dooy/chatgpt-web-midjourney-proxy#272]
可以接入其他跟openai格式一致的TTS语音

**Comment by wangasa** [comment]
suno-v3 创建歌曲成功，返回
{
  "message": "fetch error, pleace check url",
  "url": "https://*/v1/chat/completions",
  "code": "fetch_error"
}

**Comment by Dooy** [comment]
TTS 还有哪家呢？
接口不统一比较麻烦

suno-v3 是不是你的中转不支持？

**Comment by wangasa** [comment]
@Dooy 这里，请求格式相同，自定义的接口和模型、角色变量不同。
https://linux.do/t/topic/49556

suno用的这个项目
https://github.com/gcui-art/suno-api

我们项目suno适合用哪个？我可以换个项目

**Comment by Dooy** [comment]
suno用的这个项目
https://github.com/gcui-art/suno-api

我们项目suno适合用哪个？我可以换个项目

> @Dooy 这里，请求格式相同，自定义的接口和模型、角色变量不同。 https://linux.do/t/topic/49556
> 
> suno用的这个项目 https://github.com/gcui-art/suno-api
> 
> 我们项目suno适合用哪个？我可以换个项目

这2个都支持啊，你最好用 用oneapi 把他们两都统一了 对外只有 oneapi
