### ISSUE TITLE
如何设置根据不同的模型使用不同的url和key，如图

### ISSUE THREAD

**Issue by ChuckZengxf** [Dooy/chatgpt-web-midjourney-proxy#273]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/86394244/c86550ba-9c17-4d60-9661-a6fb6d12d9a6)

**Comment by Spensor-Meng** [comment]
我有类似的问题，我想在页面中使用不同的模型，但切换模型的时候需要设置对应的url 和 key 感觉比较麻烦，有没有办法在设置里服务端保存几个不同的url 和key设置，我在使用对应模型的时候可以直接选择？

**Comment by Dooy** [comment]
你们不知道有一个东西 叫 oneapi 是专门干这个事情的么？

**Comment by ChuckZengxf** [comment]
> 你们不知道有一个东西 叫 oneapi 是专门干这个事情的么？

我知道，我的意思是，我有多个中转地址，比如有的有suno模型有的却没有。或者价格不同。根据请求的模型用不同的中转地址。图上的代码没有明白，不知道如何改才能满足我的需求，请指导一下

**Comment by ChuckZengxf** [comment]
已解决
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/86394244/cc38e5d8-29db-4a5c-a854-3c073bf75fb4)
