### ISSUE TITLE
点击局部重绘 打开的是frame 框架

### ISSUE THREAD

**Issue by longkun0203** [Dooy/chatgpt-web-midjourney-proxy#274]
点击点击局部重绘按钮  打开的是整改页面的框架，如图所示
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/55705293/2cb09706-d012-4739-85c8-cfbb9e540e48)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/55705293/a90f2879-ed41-459a-8f3f-449004cd5a42)

**Comment by Dooy** [comment]
看下 是哪个版本，这个只有一个中介的debug版本有这个bug

请更新至最新版本

**Comment by longkun0203** [comment]
> 看下 是哪个版本，这个只有一个中介的debug版本有这个bug
> 
> 请更新至最新版本



> 看下 是哪个版本，这个只有一个中介的debug版本有这个bug
> 
> 请更新至最新版本

好的谢谢
