### ISSUE TITLE
mj绘图代理异常

### ISSUE THREAD

**Issue by wangr0031** [Dooy/chatgpt-web-midjourney-proxy#276]
我通过docker启动，启动命令如下：在启动时指定了mj代理的地址
```
docker run --name chatgpt-web-midjourney-proxy-2  -d -p 6016:3002 \
-e OPENAI_API_KEY="sk-xxxxxx" \
-e OPENAI_API_BASE_URL="https://api.xxxx.com/" \
-e MJ_SERVER="https://api.xxx.com/"  \
-e MJ_API_SECRET="sk-xxxxx"  \
-e API_UPLOADER=1  \
-e DISABLE_GPT4=true \
-v ~/chatgpt-web-midjourney-2/uploads:/app/uploads \
ydlhero/chatgpt-web-midjourney-proxy
```

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/24863189/58698807-c033-4103-bb6f-3e34afca63eb)
如上图所示，我在页面上发起mj的绘图请求时，返回了api路由不存在的问题
实际上应该访问的路径为： /mj/submit/imagine，通过这个地址可以正常访问，我在web页面上配置mj代理，可以正常使用，但是在启动容器是配置mj代理，是不可以正常使用的，麻烦给看下启动容器的命令是不是需要调整

**Comment by Dooy** [comment]
你的中转不支持mj啊；返回的都不是 JSON格式啊 而且是504

可以试下 https://www.openai-hk.com 中转mj gpt suno gpts 都支持

**Comment by wangr0031** [comment]
感谢
