### ISSUE TITLE
部署和记录保存

### ISSUE THREAD

**Issue by anshangtangyuan** [Dooy/chatgpt-web-midjourney-proxy#277]
可以本地部署吗？可以实现你们的网页上相同的功能吗。还有本地部署的话是不是能保存聊天记录。在网页端保存聊天记录有问题，用记事本打开，不是我聊天的内容。

**Comment by anshangtangyuan** [comment]
> 可以本地部署吗？可以实现你们的网页上相同的功能吗。还有本地部署的话是不是能保存聊天记录。在网页端保存聊天记录有问题，用记事本打开，不是我聊天的内容。

利用浏览器缓存  很怕哪天记录给没了

**Comment by Dooy** [comment]
可以本地部署 下载一个Docker 就能满足了

**Comment by anshangtangyuan** [comment]
> 可以本地部署 下载一个Docker 就能满足了

可以直接部署到本地吗？不用docker

**Comment by Dooy** [comment]
可以；
请到这里下载客户端 https://github.com/Dooy/chatgpt-web-midjourney-proxy/releases
