### ISSUE TITLE
请问，"gpt-4-all" 模型是哪里来的？

### ISSUE THREAD

**Issue by core-admin** [Dooy/chatgpt-web-midjourney-proxy#28]
请教下作者，我在设置页面中，看到了“gpt-4-all”模型，这个模型我在官方查询不到，是不是它是非官方模型，同时当我基于项目内的gtps功能进行聊天时，像以下这三个，选择后，均提示模型不正确的问题：

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/77573477/a115651d-b3a8-4479-9bc8-75257283a850)

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/77573477/6c1f2337-6408-45a3-8275-8924e5011857)

这些模型是不是都是自定义的呢？请教一下。

**Comment by Dooy** [comment]
问下 中转供给方，api.openai.com 不直接提供

**Comment by core-admin** [comment]
> 问下 中转供给方，api.openai.com 不直接提供

中转供给方，您是指的这个吗，我查到gpt-4-all与这个项目有匹配关系：https://github.com/nomic-ai/gpt4all?tab=readme-ov-file

**Comment by fl0w1nd** [comment]
这是逆向的官方plus账号的，不是官方提供的API

**Comment by Swordsman007** [comment]
> > 问下 中转供给方，api.openai.com 不直接提供
> 
> 中转供给方，您是指的这个吗，我查到gpt-4-all与这个项目有匹配关系：https://github.com/nomic-ai/gpt4all?tab=readme-ov-file

你好，请问有找着这个中转网站么，我也面临这使用这个商店的问题

**Comment by Dooy** [comment]
可以试一试 https://www.openai-hk.com

**Comment by core-admin** [comment]
> > > 问下 中转供给方，api.openai.com 不直接提供
> > 
> > 
> > 中转供给方，您是指的这个吗，我查到gpt-4-all与这个项目有匹配关系：https://github.com/nomic-ai/gpt4all?tab=readme-ov-file
> 
> 你好，请问有找着这个中转网站么，我也面临这使用这个商店的问题

没继续研究了，作者也说了gpt-4-all 是逆向的chat.openai 官网中使用的模型，和我上面提到的gpt4all那个项目没啥关系

**Comment by Swordsman007** [comment]
> 可以试一试 https://www.openai-hk.com

ok

**Comment by bluepadu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by think007** [comment]
https://one.open-proxy.cn 这个提供gpts和gpt-4-all模型，1:2，可联系群主量大可优

**Comment by 18974266656** [comment]
https://kksj.me提供gpt4all，最低六毛一刀，大额优惠
