### ISSUE TITLE
大佬能给个本地部署的教程吗？

### ISSUE THREAD

**Issue by kbc1118** [Dooy/chatgpt-web-midjourney-proxy#281]
大佬能给个本地部署的教程吗？ 就是在服务器上直接部署的，不需要DOCKER那种。

**Comment by Dooy** [comment]
本地部署 需要修改下代码
 我看看 如何搞下

**Comment by kbc1118** [comment]
谢谢大佬了，主要是本地部署可以修改网页标题CHATGPT字眼，现在好多人都搜这个关键词，怕搭建了被人举报恶搞阿！

**Comment by kbc1118** [comment]
谢谢大佬

**Comment by Dooy** [comment]
本地使用 可以到 https://github.com/Dooy/chatgpt-web-midjourney-proxy/releases 下载自己合适的平台

可以支持跨平台个人客户端了

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/f3e5fd79-affc-4700-9250-22ae121de681)
