### ISSUE TITLE
求教大佬，如果是对接中转的mj，sref cref上传图片功能这里是否可用？

### ISSUE THREAD

**Issue by sunsky89757** [Dooy/chatgpt-web-midjourney-proxy#283]
求教大佬，如果是对接中转的mj，sref cref上传图片功能这里是否可用？目前docker部署提示：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/113254524/6e953e98-b31f-4a78-8494-4e29d09f9e4f)

**Comment by Dooy** [comment]
你得问下 你的中转 不是问我

**Comment by Dooy** [comment]
https://www.openai-hk.com 这中转的mj是可以的 你可以试一试
