### ISSUE TITLE
大佬怎么将ai换脸中画廊里面的图片删掉？

### ISSUE THREAD

**Issue by Codeoyager** [Dooy/chatgpt-web-midjourney-proxy#284]

**Comment by Dooy** [comment]
都是存放在本地 你怕别人看到？

**Comment by Codeoyager** [comment]
大佬~主要是成功和不成功的放在一起看着不舒服~，小白是真不知道存在哪，打扰了。😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月15日(周一) 上午7:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Dooy/chatgpt-web-midjourney-proxy] 大佬怎么将ai换脸中画廊里面的图片删掉？ (Issue #284)




 
都是存放在本地 你怕别人看到？
