### ISSUE TITLE
数学公式识别问题

### ISSUE THREAD

**Issue by 652036** [Dooy/chatgpt-web-midjourney-proxy#285]
数学部分问题一些公式预览不出来

![49b0df7811804eae1b670ab4a2914dbe](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/114277504/dd28e6fd-dd3c-4a7b-8761-b8c1f104aa2c)
大佬能优化一下吗

**Comment by Dooy** [comment]
后面看看 如何优化下 
能否把这段贴出来 ？

**Comment by 652036** [comment]
![95449ddc88ea48099cb6d6271c356720](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/114277504/efdf5e41-cbf9-4c3b-9edc-23da230505b1)
要求解这个极限：

\[
\lim_{x \to +\infty} (\ln{x} - \frac{x}{e} + 1)
\]

我们可以直接分析每一项的行为。随着$x$趋向于无穷大：

- $\ln{x}$增长无界，但是增长速度慢于线性函数。
- $-\frac{x}{e}$项也趋向于无穷大，且由于它是$x$的线性函数，其增长速度快于$\ln{x}$。
- 常数项$+1$对极限的影响可以忽略。

因此，整个表达式的行为主要由$-\frac{x}{e}$这一项决定，它导致整个表达式趋向于负无穷大。所以，这个极限的结果是：

\[
-\infty
\]

**Comment by 652036** [comment]
![95449ddc88ea48099cb6d6271c356720](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/114277504/cd519d7f-c040-46fe-be06-de607888766d)
这个预览公式有时候能正常显示有时候就显示不了

**Comment by 652036** [comment]
![1a00e78df4b0303bb6bd8b7ee5448736](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/114277504/c9931ead-94f4-4f45-a082-5504354ed18d)
![a9b86d42a149e268952ae9cc77986384](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/114277504/c8f59cc3-bdc1-4057-8568-6428fde93dd6)
求<math xmlns="http://www.w3.org/1998/Math/MathML">
  <munder accent="true" accentunder="false">
    <mrow>
      <mo data-mjx-texclass="OP" movablelimits="true">lim</mo>
    </mrow>
    <mrow>
      <mi>x</mi>
      <mo accent="false" stretchy="false">→</mo>
      <mo>+</mo>
      <mi mathvariant="normal">∞</mi>
    </mrow>
  </munder>
  <mrow>
    <mo> </mo>
  </mrow>
  <mi>i</mi>
  <mi>n</mi>
  <mi>x</mi>
  <mo>−</mo>
  <mfrac>
    <mi>x</mi>
    <mi>e</mi>
  </mfrac>
  <mo>+</mo>
  <mn>1</mn>
</math>

**Comment by 652036** [comment]
要求解这个极限：

\[
\lim_{x \to +\infty} (\ln{x} - \frac{x}{e} + 1)
\]

我们可以直接分析每一项的行为。随着$x$趋向于无穷大：

- $\ln{x}$增长无界，但是增长速度慢于线性函数。
- $-\frac{x}{e}$项也趋向于无穷大，且由于它是$x$的线性函数，其增长速度快于$\ln{x}$。
- 常数项$+1$对极限的影响可以忽略。

因此，整个表达式的行为主要由$-\frac{x}{e}$这一项决定，它导致整个表达式趋向于负无穷大。所以，这个极限的结果是：

\[
-\infty
\]
有时候这个公式能显示有时候就显示不了
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/114277504/42d27596-52f7-40dc-8ba1-0a3d1b7e2e9d)

**Comment by 652036** [comment]
> 后面看看 如何优化下 能否把这段贴出来 ？

为了计算极限 \(\lim_{x \to -\infty} \frac{\sqrt{4x^2 - 4x + 5} - 2x}{x}\)，我们首先观察根号内的表达式 \(\sqrt{4x^2 - 4x + 5}\)。

当 \(x\) 趋向负无穷时，\(4x^2\) 是主导项。我们可以通过因式分解 \(4x^2\) 来简化根号内的表达式：

\[
\sqrt{4x^2 - 4x + 5} = \sqrt{4x^2(1 - \frac{1}{x} + \frac{5}{4x^2})} = 2|x|\sqrt{1 - \frac{1}{x} + \frac{5}{4x^2}}
\]

因为 \(x\) 是负数，所以 \(|x| = -x\)，进而有：

\[
\sqrt{4x^2 - 4x + 5} = 2(-x)\sqrt{1 - \frac{1}{x} + \frac{5}{4x^2}}
\]

我们接下来使用 \(1 - \frac{1}{x} + \frac{5}{4x^2}\) 的泰勒展开近似：

\[
\sqrt{1 - \frac{1}{x} + \frac{5}{4x^2}} \approx 1 - \frac{1}{2x} + \frac{5}{8x^2}
\]

所以，

\[
\sqrt{4x^2 - 4x + 5} \approx 2(-x)\left(1 - \frac{1}{2x} + \frac{5}{8x^2}\right) = -2x + 1 - \frac{5}{4x}
\]

代入原极限公式中，

\[
\lim_{x \to -\infty} \frac{\sqrt{4x^2 - 4x + 5} - 2x}{x} = \lim_{x \to -\infty} \frac{-2x + 1 - \frac{5}{4x} - 2x}{x}
\]

\[
= \lim_{x \to -\infty} \frac{-4x + 1 - \frac{5}{4x}}{x} = \lim_{x \to -\infty} \left(-4 + \frac{1}{x} - \frac{5}{4x^2}\right)
\]

因为 \(\frac{1}{x}\) 和 \(\frac{5}{4x^2}\) 在 \(x\) 趋向负无穷时都趋向于 0，所以极限值为：

\[
-4
\]


这种情况也有整个回答都没有公式预览

**Comment by 652036** [comment]
他用的好像是LaTeX格式

**Comment by Dooy** [comment]
集中这里 解决了 #345

**Comment by Dooy** [comment]
请更新到 `v2.17.7` 版本 大部分公式已能正常显示
