### ISSUE TITLE
换脸无法用

### ISSUE THREAD

**Issue by AndyLin2020** [Dooy/chatgpt-web-midjourney-proxy#286]
Docker部署，绘图正常，但是换脸一直提示如下错误：

{
  "error": "Not Found",
  "code": "response_fail",
  "url": "/mjapi/mj/insight-face/swap",
  "status": 404
}

**Comment by Dooy** [comment]
问下 中转；他用的 应该不是 mi plus

**Comment by douyan2662** [comment]
我遇到的换脸功能的问题提示是saveid无效，这个怎么解决？

**Comment by Dooy** [comment]
> 我遇到的换脸功能的问题提示是saveid无效，这个怎么解决？

重启下 mj-proxy-plus 应该就好了
