### ISSUE TITLE
新增的桌面端程序如何使用？

### ISSUE THREAD

**Issue by ChuckZengxf** [Dooy/chatgpt-web-midjourney-proxy#287]
# 2.16.9
- 😄 修复：桌面端程序版本问题

# 2.16.8
- 😄 新增：桌面端程序
新增的桌面端程序如何使用？ 有截图吗

**Comment by Dooy** [comment]
直接在 这里下载啊

https://github.com/Dooy/chatgpt-web-midjourney-proxy/releases


<img width="1116" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/373f2a61-0091-463f-b147-b60ff0a57117">

**Comment by Dooy** [comment]
支持多平台 window mac Linux 都支持

<img width="479" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/b164c38d-98db-4847-8e55-910b7750fd5f">

**Comment by ChuckZengxf** [comment]
这的桌面端可以二开吗？在原来的这个https://github.com/Dooy/chatgpt-web-midjourney-prox项目里生成安装包吗

**Comment by Dooy** [comment]
可以 请保持 github 项目链接就行
遵循 MIT
