### ISSUE TITLE
suno在哪里

### ISSUE THREAD

**Issue by panweiguozhou** [Dooy/chatgpt-web-midjourney-proxy#289]
找不到suno的入口

**Comment by Dooy** [comment]
感谢 老板；在这些地方 
<img width="1117" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/21080dd6-1b1f-4d2b-a703-61a22cdd9313">

**Comment by Dooy** [comment]
目前不支持

**Comment by Dooy** [comment]
请更新至`v2.17.1`
