### ISSUE TITLE
希望实现左侧绘画功能区固定，不随对话界面上下滚动

### ISSUE THREAD

**Issue by jason-xiaobaiai** [Dooy/chatgpt-web-midjourney-proxy#29]
<img width="1436" alt="截屏2023-12-15 20 01 53" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/147799771/e3c1e570-7a1b-4dda-973d-10de463e838f">
<img width="1440" alt="截屏2023-12-15 20 02 02" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/147799771/54be7d8d-3491-4b31-b8c7-f2835272f186">
如图

**Comment by Dooy** [comment]
看到了，下个版本 修复下

**Comment by Dooy** [comment]
v2.12.10 版本已修复
