### ISSUE TITLE
gpt-4-all阅读文件链接时显示无法阅读或者无法直接进入该如何解决

### ISSUE THREAD

**Issue by Cai-zhiji** [Dooy/chatgpt-web-midjourney-proxy#291]
![Snipaste_2024-04-19_09-53-02](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/73809347/284ca197-b24f-40ac-b810-2adc9bfd3dd6)

**Comment by Cai-zhiji** [comment]
说明：
1. 该链接可以正常打开，点击跳转到文件的下载链接
2. 切换到r2存储出现一样的问题，如下图所示：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/73809347/a5db3f37-8fb4-46a1-babc-4c5ba4e357df)

恳请大佬解惑（感谢！）

**Comment by Dooy** [comment]
是不是 文件太大了？ ChatGPT 10分钟没读取到文件 会放弃

**Comment by Cai-zhiji** [comment]
文件不大，测试文件8kb这样，上面都是gpt4-all秒回的，接入的是openhk的中转

**Comment by Dooy** [comment]
联系他们客服 协助解决下

**Comment by Cai-zhiji** [comment]
好的，感谢！有进展会在这个帖子上留下解决方案！

**Comment by Cai-zhiji** [comment]
问题已解决

**Comment by ChuckZengxf** [comment]
> 问题已解决
如何解决的

**Comment by Cai-zhiji** [comment]
> > 问题已解决
> > 如何解决的

更换支持阅读文件的gpt-4-all的中转服务商

**Comment by ChuckZengxf** [comment]
> > > 问题已解决
> > > 如何解决的
> 
> 更换支持阅读文件的gpt-4-all的中转服务商

您用的什么中转服务商，有推荐吗
