### ISSUE TITLE
win7系统无法安装桌面端 安装报错

### ISSUE THREAD

**Issue by zyjfly** [Dooy/chatgpt-web-midjourney-proxy#292]
比如现在是16.9 
那有17.0之后我是需要卸载16.9然后下载17.0重新安装并配置接口吗 还是怎么操作呢

**Comment by Dooy** [comment]
具体 我没实施过 更新；

**Comment by Dooy** [comment]
你看源码是通过这个来更新的

https://github.com/Dooy/chatgpt-web-midjourney-proxy/releases/latest/download/latest.json

**Comment by zyjfly** [comment]
大佬，这个桌面端我发现只能装在win10，装在win7系统会有各种报错。。这个可以有办法解决吗 我下载了运行库也会有报错无法定位程序输入点coincrementmtausage于动态链接库ole32.dll

**Comment by Dooy** [comment]
能否 带图看看

**Comment by zyjfly** [comment]
![企业微信截图_17139466531856](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/a72ae514-ba23-4681-b758-5998e0092054)
a安装会有这个报错，我尝试安装运行库合集后，可以成功安装但是打开会有这个报错
![Uploading 企业微信截图_171400616043.png…]()

**Comment by zyjfly** [comment]
![Uploading 企业微信截图_171400616043.png…]()

**Comment by zyjfly** [comment]
![企业微信截图_171400616043](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/0d783fae-5fab-4ea8-a080-dcc41d7cc3e1)

**Comment by Dooy** [comment]
一时间解决不了 还是升级下 系统吧 ；大清都完了
