### ISSUE TITLE
MJ调用失败，相同参数postman post请求没问题

### ISSUE THREAD

**Issue by cyDione** [Dooy/chatgpt-web-midjourney-proxy#293]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/45588391/1e3b9435-0d43-465e-a267-abb7e8b0455a)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/45588391/839480c7-5ffd-48b4-883e-c0ba57a4361f)

**Comment by cyDione** [comment]
请问下这是哪里的问题

**Comment by Dooy** [comment]
你是不是把自己架mj? 然后有吧链接填写在ui的上？

需要跨域导致的

**Comment by cyDione** [comment]
linux docker部署的mj-proxy
端口映射直接调用，外网http调用报错
反代后，外网https调用报错
本地部署后，局域网ip+端口报错
我也不是很懂，请问下还能如何解决

**Comment by Dooy** [comment]
浏览器 F12 看下 报错

**Comment by Dooy** [comment]
可以改是跨域问题
为何不配置在后端？

<img width="720" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/dad197a0-1490-4b92-9985-618e81a0a0a6">

**Comment by cyDione** [comment]
> 可以改一下跨域问题 为何未配置在遥控器上？
> 
> <img alt="图像" width="720" src="https://private-user-images.githubusercontent.com/3765401/323880432-dad197a0-1490-4b92-9985-618e81a0a0a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTQ5ODMsIm5iZiI6MTcxMzUxNDY4MywicGF0aCI6Ii8zNzY1NDAxLzMyMzg4MDQzMi1kYWQxOTdhMC0xNDkwLTRiOTItOTk4NS02MThlODFhMGEwYTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMDgxODAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNlMTNmNmQ5ZmIyYzBlZGUzMGE2Zjk5ZDU0YjQ2YWFmMzgxOTI5OTBmMzk3NzNiZDEyN2RjYmJjZGFhMjQyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Fgn-Oqlbczv5uNgRSyGKlNfh1vFuFm4LJfliR3ECGQ8">

后端部署时候填好确实没问题了，所以前端修改的话是会引发跨域问题呗
