### ISSUE TITLE
4v模型上传图片的url视乎是本地的地址

### ISSUE THREAD

**Issue by heiyyint** [Dooy/chatgpt-web-midjourney-proxy#296]
看到日志是图片上传到了本地，形成了一个本地链接，导致4v模型无法识别，但是all模型上传却又是走了服务器地址

_Originally posted by @heiyyint in https://github.com/Dooy/chatgpt-web-midjourney-proxy/issues/182#issuecomment-2067656186_

**Comment by heiyyint** [comment]
![1713615577108](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/a888c2b9-1811-4c5a-981b-f2a65c29c708)

**Comment by heiyyint** [comment]
all上传为
![1713615713527](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/b34b39e9-bbc2-461c-a66b-a9326f7a7dc0)

**Comment by heiyyint** [comment]
图一就是4v的

**Comment by Dooy** [comment]
我程序没问题，你的描述也没问题

问题出现在你用的中转是官方的么？ 应该是逆向的吧？
逆向也逆好点吧 至少官方的支持都得支持下啊

**Comment by Dooy** [comment]
你这个问题是老问题了 你参考 #175
