### ISSUE TITLE
是否支持已有模型列表的自定义？

### ISSUE THREAD

**Issue by liaokongVFX** [Dooy/chatgpt-web-midjourney-proxy#297]
我看“CUSTOM_MODELS”是在已有列表后面追加新的模型。现在已有的模型列表有些模型不太想展示了，只想显示几个模型，这个是否可以配置？感谢~

**Comment by Dooy** [comment]
可以用 -; 新增用+

**Comment by liaokongVFX** [comment]
好的，感谢~如果是希望清除掉现在所有模型可以用`-all`吗？还是需要把现在所有的模型都用`-`设置一遍？

**Comment by suidu-pro** [comment]
> 可以用 -; 新增用+

支持别名么？"="号设置模型展示的别名

**Comment by W4ddl3** [comment]
> 可以用 -; 新增用+

实测不支持 "-all"，NextChat 支持这样设置，可以把默认模型全部删除
![Shot 2024-05-19 at 21 24 39@2x](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/141616559/33c25ddd-87e8-4e5a-8bd1-fc636fae23a9)

**Comment by Dooy** [comment]
后面 支持下

**Comment by Dooy** [comment]
请更新到 `v2.17.7` 已经支持 `-all`
