### ISSUE TITLE
关于all和gpts文件上传

### ISSUE THREAD

**Issue by suidu-pro** [Dooy/chatgpt-web-midjourney-proxy#299]
大佬，因为gpt不支持直接打开URL的方式，是否all和gpts的文件上传可以更改支持gpt-4-vision的上传格式

**Comment by Dooy** [comment]
那是你的all跟gpts 没做好，这种逆向哪有不支持url的？ 都是自己逆向处理的

**Comment by suidu-pro** [comment]
啊，我用的github上面开源的，大佬有推荐的项目么
