### ISSUE TITLE
 V1到V4、重绘操作没有效果

### ISSUE THREAD

**Issue by linrb685** [Dooy/chatgpt-web-midjourney-proxy#30]
V1到V4、重绘操作没有效果。只是变了颜色，并没有在mj生成新的命令
![2023-12-15_211006](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/71812150/d5ec460d-ffba-458c-bda3-7a25676bffdb)

**Comment by Dooy** [comment]
变了 颜色 ；
生成内容在底下啊 哥哥

**Comment by linrb685** [comment]
并没有哦。
![2023-12-15_213603](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/71812150/9b252f37-b9d5-4399-8bbe-4eaa4f620616)

**Comment by Dooy** [comment]
搞一个 fast吧；没事啥money 解决不了的事

**Comment by linrb685** [comment]
你的意思是mj账号不支持？
![2023-12-15_214317](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/71812150/ef54f3e4-50a2-4529-8312-60c1f12e7162)

**Comment by Dooy** [comment]
支持 你没看到 进度么？ 0% ？还不是 因为慢了么？

**Comment by Dooy** [comment]
你看下 mj proxy 的任务查询吧；这个 mj proxy的问题 不继续回答了

**Comment by linrb685** [comment]
在mj没有消息记录也没有生成，不管等多久。最后会超时
