### ISSUE TITLE
新上的suno功能使用中转的提交报错；You need to enable JavaScript to run this app.

### ISSUE THREAD

**Issue by ChuckZengxf** [Dooy/chatgpt-web-midjourney-proxy#301]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/86394244/c26469ce-1634-456c-bd65-ede0c7a6e773)

**Comment by heiyyint** [comment]
貌似接口不统一

**Comment by Dooy** [comment]
中转接口不支持吧； 可以先用curl试下

**Comment by JARVISMindEngineer** [comment]
同样碰到了：You need to enable JavaScript to run this app

@Dooy 你使用的中转接口可否分享一下我们做一下响应的比较。

**Comment by Dooy** [comment]
> 同样碰到了：You need to enable JavaScript to run this app
> 
> @Dooy 你使用的中转接口可否分享一下我们做一下响应的比较。

www.openai-hk.com 用试下

**Comment by zsychn** [comment]
https://api.mjdjourney.cn/ 这个辛苦也看下 ，麻烦了
