### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by wdqzdd** [Dooy/chatgpt-web-midjourney-proxy#304]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/27991992/9c238b9a-16a4-472d-bec0-9574ad887821)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/27991992/7dfac5d9-65ad-4f43-b300-7558a56ac382)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/27991992/b0c29eec-41f0-46e4-b3ef-627f9e54a070)

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/27991992/ac80f66f-2385-4662-8a43-465ea8ec4d4f)

midjourney-proxy项目是我本地跑起来的，配置如图3，可以科学上网。

**Comment by wdqzdd** [comment]
跨域问题。

**Comment by wdqzdd** [comment]
#293 已解决。
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/27991992/028f5ad6-9fbc-4894-890a-77903e9f9ca2)

**Comment by Dooy** [comment]
good
