### ISSUE TITLE
填好中转了，使用suno提示，发生错误:Error: 服务器返回错误： 428

### ISSUE THREAD

**Issue by Dragon617** [Dooy/chatgpt-web-midjourney-proxy#305]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/103638567/9b48c6aa-b0ab-4865-afb9-3fa786121530)

**Comment by Dooy** [comment]
已优化 请更新至 `v2.17.1`

**Comment by heiyyint** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/519e9693-57f4-45e1-8ca9-07998180adcc)
报错了字符串

**Comment by heiyyint** [comment]
> ![图像](https://private-user-images.githubusercontent.com/143329494/327179285-519e9693-57f4-45e1-8ca9-07998180adcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1ODIxNTAsIm5iZiI6MTcxNDU4MTg1MCwicGF0aCI6Ii8xNDMzMjk0OTQvMzI3MTc5Mjg1LTUxOWU5NjkzLTU3ZjQtNDVlMS04Y2E5LTA3OTk4MTgwYWRjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxNjQ0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWE2Y2Y0N2Y2M2JhN2U1MTE3MmI5ZDQ4YzgyNjZiNmJhZjAxNmE0YjFmYjY5NDUwMWI1MWM5MmQ3YjRlZjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ddZ7mxgUcJFwmoouLaA9r3qOSw2R0TKlZI8fAPRMZfo) 报错了字符串

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/c1db8869-3e20-4841-a376-807cbef63326)
用的是中转api

**Comment by Dooy** [comment]
明显中转有问题 返回不是JSON啊
