### ISSUE TITLE
建议给左侧的菜单增加自定义选项

### ISSUE THREAD

**Issue by 2guan** [Dooy/chatgpt-web-midjourney-proxy#308]
能否给左侧的菜单按钮增加自定义参数。
比如是否显示“音乐”、“画廊”、“GPTs”。
或者在没有给出MJ proxy和suno API时自动隐藏的对应的按钮？

**Comment by Dooy** [comment]
收到 后续的版本 加上

**Comment by Dooy** [comment]
请更新至 v2.17.2

- 左侧菜单栏可以配置 通过环境变量调整 `MENU_DISABLE="gpts,music,gallery"`
