### ISSUE TITLE
每个服务都是这样 是为啥呢

### ISSUE THREAD

**Issue by onlinedear** [Dooy/chatgpt-web-midjourney-proxy#309]
{
  "error": "TypeError: Failed to fetch",
  "data": {
    "base64Array": [],
    "notifyHook": "",
    "prompt": "Cyberpunk,Wide view,Face Shot (VCU),小鸟  --q 0.25 --v 6.0 --ar 1:1",
    "state": "",
    "botType": "MID_JOURNEY"
  },
  "code": "fetch_fail",
  "url": "https://www.openai-hk.com/mj/submit/imagine"
}

**Comment by onlinedear** [comment]
我咋感觉这个hk的接口跑路了呢

**Comment by Dooy** [comment]
接口是 https://api.openai-hk.com 吧？ 不是 www
