### ISSUE TITLE
换脸怎么用，404

### ISSUE THREAD

**Issue by linrb685** [Dooy/chatgpt-web-midjourney-proxy#31]
[换脸怎么用，404
![2023-12-15_212134](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/71812150/df29056e-0cc6-40f0-a84c-ac15759b4ce3)

**Comment by Dooy** [comment]
需要服务端支持
 
可以参考 这个 issue #26

**Comment by linrb685** [comment]
@@@感谢，我去看看

**Comment by gaidan1983** [comment]
换脸挺有意思，但还生成的还是有点不像。我觉得可以上传多张不同角度自己头像，以让AI充分学习。

**Comment by Dooy** [comment]
> 换脸挺有意思，但还生成的还是有点不像。我觉得可以上传多张不同角度自己头像，以让AI充分学习。

欢迎去跟 mj提需求
