### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by devyujie** [Dooy/chatgpt-web-midjourney-proxy#310]
按照教程搭建的，出现这个问题什么原因。

配置：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48620527/e143dca7-4ff5-4def-9241-d9b8c0d30f58)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48620527/a2de9778-c56e-4ad6-a60d-486404d62b80)
拿的这个token：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48620527/2389bbf1-7351-4001-99cd-ebaad6af8c7d)

问题：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48620527/c4b59b74-141b-4ea4-b821-f5e6577ecf23)

**Comment by Dooy** [comment]
你首先得搭建 mj-proxy 
可以到 https://github.com/novicezk/midjourney-proxy 
看看readme 或者 提issue
