### ISSUE TITLE
对话频道可以生成suno的音乐，但音乐频道进去点创作歌曲没反应，F12没有看到报错

### ISSUE THREAD

**Issue by onlinedear** [Dooy/chatgpt-web-midjourney-proxy#314]
通过GTS的suno也可以生成音乐，在对话切到suno模型也可以生成，但就是在音乐这个频道，无法使用，点击生成歌词也无效，创作歌曲也无效。

**Comment by Dooy** [comment]
需要配置 `SUNO_SERVER` 和 `SUNO_KEY`

<img width="836" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/51780e4e-9b7a-4b71-9567-f9359624de90">

**Comment by yuanjie-ai** [comment]
SUNO_KEY是啥怎么设置
