### ISSUE TITLE
Winodws 桌面版客户端主题设置为跟随系统，客户端重启后依然变回黑夜主题

### ISSUE THREAD

**Issue by Mlearn** [Dooy/chatgpt-web-midjourney-proxy#315]
软件很棒！

打开后默认主题为黑色，不太习惯。设置为跟随系统后变成白天主题（系统主题设置为白天），但是软件关闭后再打开还是会恢复为黑夜主题。
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/7379015/c9715043-94a2-4b51-99c3-e385dd65d5ca)

软件主题设置为白天模式，重启后会保持白天。

系统：Windows 11 23H2

**Comment by Dooy** [comment]
先别跟随系统了 直接 保存为白天模式
