### ISSUE TITLE
请教一下作者为啥要设置service-worker

### ISSUE THREAD

**Issue by Cai-zhiji** [Dooy/chatgpt-web-midjourney-proxy#317]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/73809347/b211ad32-e273-4ccc-ac7c-eeebb4d14f17)
设置pwa，注册了一个service-worker会导致浏览器无法及时获取网站的更新，得清理浏览器缓存才能及时获取网站的更新。

**Comment by Cai-zhiji** [comment]
想请教一下，是否可以自己编写sw.js去控制浏览器缓存的策略等等

**Comment by Dooy** [comment]
我未测试过 ，你测试下试试
