### ISSUE TITLE
用什么指令可以在模型list里不显示GPT某些早期模型

### ISSUE THREAD

**Issue by gaidan1983** [Dooy/chatgpt-web-midjourney-proxy#32]
之前起过[ChatGPT-Next-Web](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web)纯聊天的项目，可以通过 CUSTOM_MODELS=-gpt-3.5-turbo,-gpt-3.5-turbo-0301 来隐藏一些模型选择。

目前看无论3.5还是4.0 的模型，其实我只需要“XXX-1106”这个版本模型即可。
4-1106-preview是最聪明最贵的，
3.5-turbo-1106 是3.5最新性价比最高的。

**Comment by Dooy** [comment]
后续版本 可以 也加一下 这个参数

**Comment by Dooy** [comment]
v2.12.10 版本已支持

**Comment by gaidan1983** [comment]
> v2.12.10 版本已支持

已实现，赞！
