### ISSUE TITLE
画廊中删除不了曾经生成过的图片

### ISSUE THREAD

**Issue by liangmingxian** [Dooy/chatgpt-web-midjourney-proxy#322]
点击画廊，在我的画廊中显示了所有曾经生成过的图片，时间久了之后这里有大量的图片要加载，而且有些是中间产品，也不需要保留了，希望可以增加删除图片的功能。同理，suno音乐创作模块也一样。

**Comment by Dooy** [comment]
如果有开发能力 可以把这个功能自己加下
