### ISSUE TITLE
请问为什么没有局部重绘选项？

### ISSUE THREAD

**Issue by samyeei** [Dooy/chatgpt-web-midjourney-proxy#323]
![111](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/50938541/68fe0a8b-b79c-41f9-b5de-dded4cad1825)
如图，midjourney生成图片后，没有变焦，局部重绘等选项，调用的是midjourney-proxy接口，请问怎么办？谢谢

**Comment by Dooy** [comment]
得需要后端的支持 ，就是后端得用 mj-proxy-plus 才有
