### ISSUE TITLE
建议作者把聊天字体可以自定义大小，默认字体在高分辨率下比较小

### ISSUE THREAD

**Issue by cyxcyx1** [Dooy/chatgpt-web-midjourney-proxy#324]
该项目做的很不错，给作者大大的赞，但是还有部分要改进的地方，比如字体太小，以及整体布局有点不协调，个人认为如图的聊天框比例偏向舒适，也就是说gpt回答的聊天框不必占用太多右边的空间，否则整体看起来阅读比较困难。希望作者大大可以改进，谢谢啦
<img width="1272" alt="屏幕截图 2024-05-03 123317" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/135317324/5ca1dcaa-3508-4ef8-a107-cb7d8e1a34af">
<img width="1280" alt="屏幕截图 2024-05-03 123118" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/135317324/787da47e-e0a1-468f-b464-873f9b014b21">

**Comment by Dooy** [comment]
有开发能力 自行修改下
