### ISSUE TITLE
能否支持下gemini-pro-1.5走base64，这url不能识别但是走base64解析图片又能识别出来

### ISSUE THREAD

**Issue by heiyyint** [Dooy/chatgpt-web-midjourney-proxy#326]
能否支持下gemini-pro-1.5走base64，这url不能识别但是走base64解析图片又能识别出来

_最初由 heiyyint 在 https://github.com/Dooy/chatgpt-web-midjourney-proxy/issues/259#issuecomment-2094052561 发布_

**Comment by heiyyint** [comment]
默认base64走的是4v模型，但是这个1.5也是走base64的

**Comment by Dooy** [comment]
> 能否支持下gemini-pro-1.5走base64，这url不能识别但是走base64解析图片又能识别出来
> 
> _最初由 heiyyint 在 [#259 (comment)](https://github.com/Dooy/chatgpt-web-midjourney-proxy/issues/259#issuecomment-2094052561) 发布_

这可能跟中转有关系吧？

**Comment by heiyyint** [comment]
> > 能否支持下gemini-pro-1.5走base64，这url不能识别但是走base64解析图片又能识别出来
> > 
> > _最初由 heiyyint 在 [#259 (comment)](https://github.com/Dooy/chatgpt-web-midjourney-proxy/issues/259#issuecomment-2094052561) 发布_
> 
> 这可能跟中转有关系吧？

图片上传的关系

**Comment by heiyyint** [comment]
> > 能否支持下gemini-pro-1.5走base64，这url不能识别但是走base64解析图片又能识别出来
> > 
> > _最初由 heiyyint 在 [#259 (comment)](https://github.com/Dooy/chatgpt-web-midjourney-proxy/issues/259#issuecomment-2094052561) 发布_
> 
> 这可能跟中转有关系吧？

图片上传base64默认走了4v，但是gemini-pro-1.5也是走base64

**Comment by Dooy** [comment]
请更新到 `v2.17.2` 已支持

**Comment by heiyyint** [comment]
> 请更新到 `v2.17.2` 已支持

收到，gemini-pro-1.5貌似是支持mp4格式视频识别，，但是默认MP4走了whisper-1，参考https://github.com/google-gemini/cookbook/blob/main/quickstarts/Video.ipynb文档

**Comment by heiyyint** [comment]
> 艹 算球了 视频就算了 
> 先不去支持了 one-api api的数据格式都未必支持

恩

**Comment by heiyyint** [comment]
> 艹 算球了 视频就算了 
> 先不去支持了 one-api api的数据格式都未必支持

视频应该不是简单的mp4链接识别吧
