### ISSUE TITLE
Windows 10 桌面端没有绘画、GPTs等附加功能

### ISSUE THREAD

**Issue by yelanyanyu** [Dooy/chatgpt-web-midjourney-proxy#327]
如题，在我安装最新版的桌面端，不能进行绘画，不知道是不是还没有开发这个功能呢？
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/94947914/222d92a1-5e6a-4e04-bc66-c7750f17fb42)

**Comment by Dooy** [comment]
看下 readme 需要中转 支持

**Comment by Dooy** [comment]
看到bug了 我稍后修复下

**Comment by Dooy** [comment]
已经修复 请更新至 `v2.17.3` 版本
