### ISSUE TITLE
请教下，回答没有打字机效果怎么解决？

### ISSUE THREAD

**Issue by haichaojiyi** [Dooy/chatgpt-web-midjourney-proxy#329]
web端的，开发环境和生产环境都没有打字机效果，生产环境的ng配置了proxy_buffering off;没有效果

**Comment by Dooy** [comment]
试下 中转

**Comment by liaokongVFX** [comment]
可以试试：
```
    proxy_cache off;  # 关闭缓存
    proxy_buffering off;  # 关闭代理缓冲
    chunked_transfer_encoding on;  # 开启分块传输编码
    tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
    tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
    keepalive_timeout 300;  # 设定keep-alive超时时间为65秒
```

**Comment by haichaojiyi** [comment]
> 可以试试：
> 
> ```
>     proxy_cache off;  # 关闭缓存
>     proxy_buffering off;  # 关闭代理缓冲
>     chunked_transfer_encoding on;  # 开启分块传输编码
>     tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
>     tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
>     keepalive_timeout 300;  # 设定keep-alive超时时间为65秒
> ```

感谢回复，试了下依旧不行
![d652133b008868c2482ee12dcfed93c](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/56671192/92abd29a-98be-4bd3-a356-cbaaba2ce0c3)

**Comment by haichaojiyi** [comment]
> 试下 中转

感谢回复，使用的就是它项目推荐的中转openai-hk
