### ISSUE TITLE
提交中 [Unexpected token '<', "<!DOCTYPE "... is not valid JSON]

### ISSUE THREAD

**Issue by Y1Q1REX** [Dooy/chatgpt-web-midjourney-proxy#33]
各位大神，按照步骤试了几遍，为何mj画图都显示如下内容？
“提交中[Unexpected token '<', "<!DOCTYPE "... is not valid JSON]“，忘指导，万分感谢

**Comment by Sarkhad** [comment]
You need to check if your midjourney backend link in the config is correct

**Comment by Dooy** [comment]
你的 mj后端 需要  midjourney-proxy 或者 midjourney-proxy-plus支持
