### ISSUE TITLE
移动端访问没有音乐按钮

### ISSUE THREAD

**Issue by 2guan** [Dooy/chatgpt-web-midjourney-proxy#330]
使用移动端访问时，只有对话、GPTs、绘画、画廊4个按钮，需要补充显示音乐按钮。

![搜狗截图20240508111533](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/59775321/90a8b7ad-2036-4297-84d0-6661085e21fa)

**Comment by Dooy** [comment]
移动端 没适配

**Comment by bearcolin** [comment]
横屏就有了。。。

**Comment by Dooy** [comment]
版本 `v2.22.2` 之后有了
