### ISSUE TITLE
docker后台重启后，gpt对话会提示：504，gateway timeout

### ISSUE THREAD

**Issue by platanus2000** [Dooy/chatgpt-web-midjourney-proxy#331]
需要删除该对话框，使用新的才可以
![企业微信截图_17151539141817](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/29397720/e107e74b-9958-4d4d-957a-51c78d4ffda3)

**Comment by Dooy** [comment]
应该是 后端的服务没起来
