### ISSUE TITLE
CUSTOM_MODELS 环境变量不能设置模型对应的 max_token

### ISSUE THREAD

**Issue by 8u6cherhu** [Dooy/chatgpt-web-midjourney-proxy#333]
我环境变量CUSTOM_MODELS配置了模型，但是不能配置模型的最大token数量，前端滑块只能滑到2048

**Comment by Dooy** [comment]
好的 后面默认改到 4k

**Comment by Dooy** [comment]
现在 自定义默认 到8k可调了

**Comment by wk222** [comment]
> 现在 自定义默认 到8k可调了

大佬您好，我是用的oenapi的claude3.5，这个模型最大回复token可以到8192，但是前端目前还是只能拉到4096，谢谢大佬
