### ISSUE TITLE
关于gpts的模型名称传入问题

### ISSUE THREAD

**Issue by VectorZhao** [Dooy/chatgpt-web-midjourney-proxy#334]
始皇提供了免费的全部接口，但是gpts的传入模型名称为`g-*`，不知道开发者能不能提供一个选项，从`gpt-4-gizmo-g-*`切换到`g-*`
```
我简单糊了下 chat2api: https://api.oaifree.com/v1/chat/completions
把 access token 传进去就开转，模型用chat的模型。

注意限制：

只为ChatGPT Plus提供服务（3.5 + 4），普通账户我就不放资源了。
目前频控 10/10s，将来一定会跟 LINUX DO Connect 挂钩，各位早做打算！
支持以下模型：

text-davinci-002-render-sha 8K
gpt-4 32K
gpt-4-gizmo 32K
gpt-4-magic-create 32K
gpt-4-plugins 32K
任何其他模型等同 text-davinci-002-render-sha
更新：

team账号只需要传递 ChatGPT-Account-ID 头即可实现切换。
支持使用 gizmo，使用 g-xxx 的 id 作为模型名即可。
支持 whisper，使用 https://api.oaifree.com/v1/audio/transcriptions
我限制了 whisper 上传文件大小为：4M 。
已可对话出图。
```

**Comment by Dooy** [comment]
你可以手动填写 或者自定义 gpts 模型改为 `g-*` 即可

**Comment by Dooy** [comment]
我后续加一个选项搞起来

**Comment by VectorZhao** [comment]
> 你可以手动填写 或者自定义 gpts 模型改为 `g-*` 即可

是的，这样子可以使用，但是我们这个项目提供了gpt store，我觉得是使用gpts很方便的一个地方，点一下对话时我发现模型的name是gpt-4-gizmo-g-xxx的形式，就没法直接调用https://api.oaifree.com这个接口了

**Comment by Dooy** [comment]
请更新到 v2.17.6 已经支持了

<img width="961" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/98efa312-70cf-432f-9537-d07e02e602b8">

**Comment by buwanyuanshen** [comment]
你理解错了吧，就是gpt-4-gizmo-g-*的调用方式。。。

**Comment by Dooy** [comment]
有的API 喜欢用 g-* 开头
