### ISSUE TITLE
docker部署MJ接口报错

### ISSUE THREAD

**Issue by owcowc** [Dooy/chatgpt-web-midjourney-proxy#336]
同样一个接口网址和令牌，用docker环境不熟的话就会报错：
{
  "error": "SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON",
  "code": "json_error",
  "url": "/mjapi/mj/submit/imagine",
  "status": 403
}

如果是在页面设置-服务器-里面填写的话就可以正常使用

**Comment by Dooy** [comment]
后端 mj_server 没填对吧

**Comment by owcowc** [comment]
> 后端 mj_server 没填对吧

有大小写之分吗 我用的MJ_SERVER

**Comment by owcowc** [comment]
> 后端 mj_server 没填对吧

应该不是大小写的问题，用同一套地址和密钥，后端设置就是报错，前端设置就可以

**Comment by Dooy** [comment]
得用大写 MJ_SERVER 设置 MJ_API_SECRET

**Comment by owcowc** [comment]
> 



> 得用大写 MJ_SERVER 设置 MJ_API_SECRET

是的 两个都设置了

**Comment by owcowc** [comment]
从api接口那里查，用环境部署的接口和密钥提交时都被默认加上了 --fast
只有我是这样吗？

**Comment by Dooy** [comment]
大部分 默认都是 fast啊
