### ISSUE TITLE
页面优化和功能增加

### ISSUE THREAD

**Issue by civitaic** [Dooy/chatgpt-web-midjourney-proxy#337]
你好，我使用chatgpt-web-midjourney-proxy项目3个月了，我的用户提出了一些优化请求，我觉得非常合理，希望作者考虑更新。
1、MJ垫图增加支持剪切板粘贴功能，拖拽粘贴功能（设计师小伙伴提出的，我觉得棒极了，剪切板垫图对于ps和MJ交互非常友好）。
2、希望对话和绘图的页面分开，每次对话和绘图都有使用时，就会出现图片和对话在一个页面，感觉有点混乱。
感谢作者的辛勤付出！
另外请教下，chatgpt-web-midjourney-proxy，我请朋友增加了一个SD的侧边栏按钮（链接本地sd的web页面：http://localhost:7860），如果我提交代码，能否更新到最新版本中。（我朋友在旧版本给我加的，新版本我不会加进去了，再考虑到每次作者更新，我要想更新都需要重新加SD部分，也不知道怎么办）

**Comment by Dooy** [comment]
1 在提示的地方 粘贴？
2 每次都新开窗口 还是就mj 集中在一页？ 集中在一页太长了

3 能否把你的代码给一个地址github  我把他集成进来

**Comment by civitaic** [comment]
1、再MJ绘图左侧控制台有个上传垫图的地方，哪里点击后从文件夹选一个图上传，能否在这里扩大窗口，然后拖拽图片到这里也可以自动上传，点击粘贴按钮也可以上传剪切板的图片
2、建议MJ的集中在一页，和对话分开（点击对话的页面只有对话，点击绘图的页面只有图片）
3、https://github.com/civitaic/CWMP.git

**Comment by Dooy** [comment]
把有问题的内容 通过复制按钮贴出来

<img width="392" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/ab394f6d-2d4b-4f43-93f0-0f577f96a57d">
