### ISSUE TITLE
上传图片 会自动调用 gpt-4-vision-preview 模型 能把这个默认模型改成gpt-4o吗？

### ISSUE THREAD

**Issue by kirua** [Dooy/chatgpt-web-midjourney-proxy#338]
上传图片会自动调用 gpt-4-vision-preview 模型这个地方在哪里修改？可以改成自定义或者gpt-4o吗？

**Comment by ChuckZengxf** [comment]
gpt-4o 支持上传图片吗？

**Comment by Dooy** [comment]
请更新到最新版本的 v2.17.4 Docker 已经支持了

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/64b408cb-f82c-4164-bb30-98483ea6ecae)

**Comment by Dooy** [comment]
请更新到最新版本 允许自定义默认的了 看readme的环境变量

**Comment by Dooy** [comment]
> > 能否在上传的时候选择让当前模型自身来处理？比如我自定义了`google`这个模型，后端对应的gemini-1.5-pro-latest，本身就有视觉功能，这种情况下希望能有选项让模型自身来处理。谢谢！
> 
> 后面把这个写出来吧，目前我是写死了 几个 包括 gemini-pro-version gemini-pro-1.5 gpt-4-turbo

已经可以用 自定义变量 CUSTOM_VISION_MODELS 规定自己的vision 模型
