### ISSUE TITLE
生成图片能否支持dall-e-3接口的调用？

### ISSUE THREAD

**Issue by vjieshao** [Dooy/chatgpt-web-midjourney-proxy#339]
目前上传图片默认使用gpt-4-vision-preview 模型，能否支持dall-e-3模型的问答？

**Comment by vjieshao** [comment]
目前在这个界面可以用dall-e-3模型。但在对话框手动上传图片，走的还是gpt-4-version-preview。
![Uploading WX20240514-164040.png…]()

**Comment by vjieshao** [comment]
目前在这个界面可以用dall-e-3模型。但在对话框手动上传图片，走的还是gpt-4-version-preview。
![WX20240514-164040](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/9038034/a031c5f4-0774-4905-8030-60784100137a)

**Comment by Dooy** [comment]
需要中转支持 有点不可能 呵呵

你要的功能去问下 始皇 或者xy

**Comment by vjieshao** [comment]
> 需要中转支持 有点不可能 呵呵
> 
> 你要的功能去问下 始皇 或者xy

好的。谢谢。主要是gpt-4-all模型我用的api不支持。

**Comment by Dooy** [comment]
不支持画图的gpt-4-all ? 跟输入有关系吧？ 前面加一个画图 画画 字样
