### ISSUE TITLE
Custom GPTs selected on the store are not working

### ISSUE THREAD

**Issue by Sarkhad** [Dooy/chatgpt-web-midjourney-proxy#34]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/1319532/dafe59ce-ecd8-4b38-b8b0-dadfdf20aac2)

Any ideas on how to make them work?

**Comment by Dooy** [comment]
api.OpenAI.com does not directly provide the api of gpts,
the interface of gpts is actually the GPTs in the reverse chatGpt plus (chat.openai.com).

**Comment by Sarkhad** [comment]
> Api.openai.com does not directly provide the api of gpts, The interface of gpts is actually the GPTs in the reverse chatGPT plus (chat.openai.com).

So currently there's no practical use for the GPTs tab?

**Comment by tuzh6** [comment]
Use an unofficial API relay interface, it must support the reverse functionality of GPTs.
