### ISSUE TITLE
有图片的情况下, 刷新回答或追问, 会丢失图片信息

### ISSUE THREAD

**Issue by yinhaixiang** [Dooy/chatgpt-web-midjourney-proxy#342]
第一个问题上传图片, 会放到image_url这个对象中
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/10047441/f62f0f38-21c7-499e-a7d1-eff0c7c59e0f)
但是, 如果问第二个问题或者刷新第一个问题的回答, 则丢失了image_url相关信息, 导致无法根据图片内容继续交流了
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/10047441/5838917f-6399-4f72-a886-0494440b33db)

**Comment by Dooy** [comment]
故意的，如果你想继续带图片 可能得自己修改下

图片识别得花钱吧
