### ISSUE TITLE
卡死

### ISSUE THREAD

**Issue by heitaokjcr** [Dooy/chatgpt-web-midjourney-proxy#344]
每当我尝试删掉左侧边的一个历史记录时，网页都会卡死，其他操作时都正常。（试过谷歌和edge浏览器，都会这样）

**Comment by Dooy** [comment]
我就是 复现不了

**Comment by q751654992** [comment]
我复现了, 可能是删的比较快, ui更新慢, 会导致删最后一个对话的时候, 实际上已经没有聊天了
😏数据越界报错了?

**Comment by Dooy** [comment]
你们是不是 第一个提问数量都比较大 问题比较长？

**Comment by q751654992** [comment]
> 你们是不是 第一个提问数量都比较大 问题比较长？

并不是, 当时我的电脑使用起来比较卡, 删除对话聊天的时候明显感觉到了卡顿

**Comment by Dooy** [comment]
是哪个按钮？
<img width="352" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/adb6a435-870b-467e-9539-646259ad7449">

**Comment by q751654992** [comment]
> 是哪个按钮？ <img alt="image" width="352" src="https://private-user-images.githubusercontent.com/3765401/331266708-adb6a435-870b-467e-9539-646259ad7449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzI5MjYsIm5iZiI6MTcxNTg3MjYyNiwicGF0aCI6Ii8zNzY1NDAxLzMzMTI2NjcwOC1hZGI2YTQzNS04NzBiLTQ2N2UtOTUzOS02NDYyNTlhZDc0NDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTUxNzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzYwZjA3ZGU4MzBkZDJiZjkxM2E2OTA1MzRjMDU5NDIwODM3OTlmM2E1NjMyMWU1MzU3NDEwY2Y4NmVlNmJiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EpBG-l7uVnjaFfTEkufuXHY0bZzDUkcaaPMd7lTRLd0">

上面这个
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40224144/6833e965-1288-4326-bce6-e076300f5397)

**Comment by Dooy** [comment]
收到

**Comment by heiyyint** [comment]
> 是哪个按钮？ <img alt="image" width="352" src="https://private-user-images.githubusercontent.com/3765401/331266708-adb6a435-870b-467e-9539-646259ad7449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjA2OTcsIm5iZiI6MTcxNTk2MDM5NywicGF0aCI6Ii8zNzY1NDAxLzMzMTI2NjcwOC1hZGI2YTQzNS04NzBiLTQ2N2UtOTUzOS02NDYyNTlhZDc0NDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTdUMTUzOTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVmMmU1OTUwY2JlOTJkZWVjNjFlN2I1YjY5MGExNmVjYjIwY2ZjYzAzZmQ2YjRlMDZlYzQyZDMxMmIwMDQ1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MaipoG6oQdAHcTF1xYbKYW_3Kzt-Gp75YQdl_tLOyWk">

两个按钮清除其实都会卡死

**Comment by heitaokjcr** [comment]
的确，都会卡死，还很常见

**Comment by Dooy** [comment]
使用的操作系统是啥？ 我一直复现不了

**Comment by heitaokjcr** [comment]
<img width="362" alt="e18f49cdc02bd7506ea459ce648bf2b5" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/125453495/727bada3-361c-4664-b0be-b427471b4d0c">

**Comment by heiyyint** [comment]
> 使用的操作系统是啥？ 我一直复现不了

应该更系统关系不大，应该是删除聊天记录时的处理函数问题，我的系统都win11工作站版

**Comment by Dooy** [comment]
用 v2.18.2版本试一试 找到卡死的地方了；再帮忙测试是否有问题

**Comment by Dooy** [comment]
大家更新到  `v2.18.3` 不会卡死了
