### ISSUE TITLE
目前对于公式显示似乎有严重问题

### ISSUE THREAD

**Issue by polaritus9801** [Dooy/chatgpt-web-midjourney-proxy#345]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/153878689/bbb94e3d-8e80-45a3-9288-54a12197f3d2)
图中我的公式用$$包裹因此能正常显示，但GPT的公式用\\(和\\)包裹（似乎因Markdown转义导致），被识别为(和)导致渲染不出来，麻烦解决下这个问题感谢！（识别到后面跟括号就不转义可能能解决？）

**Comment by Dooy** [comment]
我试试

**Comment by polaritus9801** [comment]
哦对，好像行间公式\\[和\\]也会变成[和]

**Comment by lalagit1** [comment]
确实对识别、输出公式有严重问题
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/154950375/7fbd1585-1000-4d6b-933a-7b78e08fd2db)

**Comment by Dooy** [comment]
提问 能否 给我 一个？

提问他能输出公式的问题

**Comment by polaritus9801** [comment]
1. Give me the Cayley-Hamiton theorem in formulas
2. Prove Gram-Schmidt Procedure with formulas only

**Comment by Dooy** [comment]
处理好了 下个版本更新上来 
<img width="1090" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/891745fe-3b92-4b76-810d-44c42b5d41d8">

**Comment by Dooy** [comment]
> 确实对识别、输出公式有严重问题 ![image](https://private-user-images.githubusercontent.com/154950375/331035619-7fbd1585-1000-4d6b-933a-7b78e08fd2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDUyOTMsIm5iZiI6MTcxNTg0NDk5MywicGF0aCI6Ii8xNTQ5NTAzNzUvMzMxMDM1NjE5LTdmYmQxNTg1LTEwMDAtNGQ2Yi05MzNhLTdiNzhlMDhmZDJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwNzM2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzBhOTMxN2UwZTIwMGRmYzFkYjQ4MDViMzFhZmQzY2Y1MGM2YjhlMTM1YjAxODhiM2E4YmI0OGNiMjJhMTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5VXcAK01mHEiXG88CjzMFeC_TEXG3GCQ9lsyZgZjMrk)

这个的提示词汇是什么？

**Comment by Dooy** [comment]
就是 没见到中括号 
<img width="766" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/565a7be2-a120-4c74-a9b7-5b140bb47e52">

**Comment by polaritus9801** [comment]
不过看一元二次方程这张图有行间公式(那两个居中的)，行间公式就是中括号，说不定改小括号的时候中括号也改了……？

**Comment by Dooy** [comment]
请更新至 `v2.17.6` 已解决

**Comment by polaritus9801** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/153878689/fe022057-0fb2-445f-ab97-7c21c60a96d1)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/153878689/9e173f24-3046-472d-97ac-43c6b4942e91)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/153878689/5fd634c8-528d-4c27-bfbb-4529c284c6fb)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/153878689/7be21e1a-3456-4d47-8af7-1cf86e39c092)
……行了一下（图1），然后又不行了（图234）
应该不是GPT的问题(至少官网GPT没出现过公式问题)，添麻烦了

**Comment by Dooy** [comment]
收到 我多测试下 没测试 明白

**Comment by Dooy** [comment]
我修改了下 请大家 先在 https://vercel.ddaiai.com 测试下 
如果没问题我再打包出来

**Comment by Dooy** [comment]
<img width="1112" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/67abd7be-55b6-434e-80da-7904562d9e3e">

**Comment by polaritus9801** [comment]
猜想您使用替换法解决的这个问题，目前单美元与双美元都实测通过了，有空格情况下仍不能显示(md格式)
!，也许可以通过删紧贴美元的空格方式解决（有无紧贴空格不影响公式输出）[image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/153878689/d3740ac1-7c7b-4ba0-ab52-bb8435855988)

**Comment by Dooy** [comment]
```js
 value = value.replace(/\\\((.*?)\\\)/g, '$$$1$$');
    value = value.replace(/\\\[(.*?)\\\]/g, '$$$$$1$$$$');
 
    value= value.replaceAll('\\[',"$$")
    value= value.replaceAll('\\]',"$$")   
   
  ```
  
  有更好的方法 可以提供下

**Comment by polaritus9801** [comment]
拙见认为理想的解决方案是改md渲染器，在非代码块等环境下，最裸露的环境下把`\( ... \)`和`\[ ... \]`中内容当做公式渲染。
我稍后看眼代码，希望能帮上力所能及的忙

**Comment by Dooy** [comment]
改MD渲染 太麻烦了 
而且你还得跟着大部队走

**Comment by polaritus9801** [comment]
意识到了。但看源代码里用了kaTeX，不知道能否使用kaTeX渲染匹配到的小括号和中括号。
如果也比较困难的话，替换法不失为一种选择

**Comment by Dooy** [comment]
当你用 `$$`  `$`  就他接管了啊

**Comment by Dooy** [comment]
其实 你要在外部把 这个做好 就可以了

**Comment by polaritus9801** [comment]
那就退而求其次，把`\(`、`\( `、`\)`、` \)`四个替换成`$`，把`\[`和`\]`替换成`$$`吧，那点微不足道的弊端就不管他了

**Comment by Dooy** [comment]
请更新到 `v2.17.7` 看看最新的修复

如果还有问题 可以将文本通过复制按钮 贴到这里来

<img width="675" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/5c5c9b90-f74a-4b1d-9d43-ce6a40b79c2c">

**Comment by Dooy** [comment]
如果 没啥问题 我就closed 掉了

**Comment by polaritus9801** [comment]
我服务器崩了 先关掉吧 如果发现问题我再开
