### ISSUE TITLE
Windows 10下刚启动exe不能保存自定义模型, 得先新建一个聊天

### ISSUE THREAD

**Issue by q751654992** [Dooy/chatgpt-web-midjourney-proxy#346]
如题
从[这里下载的exe](https://github.com/Dooy/chatgpt-web-midjourney-proxy/releases/download/v2.17.5/ChatGPT-MJ_2.17.5_x64-setup.exe)
启动exe后, 设置里填写自定义模型, 然后保存, 会发现保存没有成功, 角色设定能保存成功
但是只要新建一个聊天, 就能保存自定义模型了, 还只能保存一次, 想再改自定义模型, 还得再新建一个聊天

**Comment by Dooy** [comment]
能否带图 指出问题？

根据文字 我得猜测你的顾虑

**Comment by q751654992** [comment]
> 能否带图 指出问题？
> 
> 根据文字 我得猜测你的顾虑

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40224144/57a067d6-25e1-4636-923a-8f97e6a3a0e6)
- 修改自定义模型再保存, 实际上自定义模型并没有被修改
- 如果新建一个聊天再去修改自定义模型, 这时候就可以保存了
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/40224144/16d141fa-6889-48b8-a2b0-db0a89048df4)

**Comment by Dooy** [comment]
这样操作试下，填上->选择 直接选保存就有
<img width="651" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/10720281-61ae-431f-a8ff-f4aeac32197b">

**Comment by q751654992** [comment]
> 这样操作试下，填上->选择 直接选保存就有 <img alt="image" width="651" src="https://private-user-images.githubusercontent.com/3765401/331172229-10720281-61ae-431f-a8ff-f4aeac32197b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTY3ODYsIm5iZiI6MTcxNTg1NjQ4NiwicGF0aCI6Ii8zNzY1NDAxLzMzMTE3MjIyOS0xMDcyMDI4MS02MWFlLTQzMWYtYThmZi1mNGFlYWMzMjE5N2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTA0ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk2YTQ2ZGUzYzYwZTM1MDM5ZDA0MzVkMjllMTE2YTI3ZjdlNGZlYjE2MjU2Y2M3NmIyMzViMjFkNGUzOTkyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8PpCtmB5OoGE9733VbCLCMXZd2h3l9PSUG4sEgZ99Kw">

这样也只是在当前聊天能用新加的自定义模型, 实际上还是没有保存
