### ISSUE TITLE
使用PM2方式部署教程

### ISSUE THREAD

**Issue by civitaic** [Dooy/chatgpt-web-midjourney-proxy#347]
系统版本：ubuntu 22.04
一、配置环境
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && source ~/.bashrc
nvm install 19
npm install -g pnpm && source ~/.bashrc
npm install -g pm2

二、配置项目
git clone https://github.com/Dooy/chatgpt-web-midjourney-proxy.git
cd /root/chatgpt-web-midjourney-proxy/service && mv .envexample .env
必须要手动配置.env文件

三、安装依赖
cd /root/chatgpt-web-midjourney-proxy/service && pnpm install //安装后端环境node_modules)
cd /root/chatgpt-web-midjourney-proxy && pnpm bootstrap //配置前端

 四、启动项目（必须要手动配置.env文件的key，否则项目无法启动）
cd /root/chatgpt-web-midjourney-proxy && pm2 start pnpm --name "dev-chatgpt-web-midjourney-proxy" -- dev
cd /root/chatgpt-web-midjourney-proxy/service && pm2 start pnpm --name "service-chatgpt-web-midjourney-proxy" -- start
在浏览器输入地址：http://IP:1002/

五、一键安装命令
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && source ~/.bashrc && nvm install 19 && npm install -g pnpm && source ~/.bashrc && npm install -g pm2 && git clone https://github.com/Dooy/chatgpt-web-midjourney-proxy.git && cd /root/chatgpt-web-midjourney-proxy/service/ && mv .env.example .env && cd /root/chatgpt-web-midjourney-proxy/service && pnpm install && cd /root/chatgpt-web-midjourney-proxy && pnpm bootstrap && cd /root/chatgpt-web-midjourney-proxy/service && pm2 start pnpm --name "service-chatgpt-web-midjourney-proxy" -- start && cd /root/chatgpt-web-midjourney-proxy && pm2 start pnpm --name "dev-chatgpt-web-midjourney-proxy" -- dev

**Comment by Dooy** [comment]
牛

**Comment by ChuckZengxf** [comment]
文件多不出来是什么原因啊，图片可以

**Comment by civitaic** [comment]
> 文件多不出来是什么原因啊，图片可以

什么文件多
