### ISSUE TITLE
请教：2.17.5mac 下载哪个呀，试了几个格式都不对？

### ISSUE THREAD

**Issue by MoZhuXuanKe** [Dooy/chatgpt-web-midjourney-proxy#348]
<img width="510" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/16641348/e4c625d0-12c5-4dd4-bb3c-b925332dd25e">

**Comment by Dooy** [comment]
打包失败了 重新打包了
<img width="442" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/b9447e0c-cd0a-49df-89fc-7df3ab161b7d">

**Comment by MoZhuXuanKe** [comment]
好滴，感谢大佬🙏
