### ISSUE TITLE
消息清除时网站卡死

### ISSUE THREAD

**Issue by heiyyint** [Dooy/chatgpt-web-midjourney-proxy#350]
![8454ed9e4b38cd38e0cc7723d40cea6](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/2d48c036-65f9-4c00-8271-066fb992f78e)
单独清除也会卡，全部清除也是会卡死，浏览器为谷歌浏览器

**Comment by Dooy** [comment]
额 好的

**Comment by Dooy** [comment]
我一直 试不出来 就奇怪了 我在mac上

**Comment by superultra01** [comment]
edge和谷歌浏览器都有这个问题，浏览器全是最新版本。Safari、火狐还没试过

**Comment by Dooy** [comment]
操作系统是 window 么？

**Comment by superultra01** [comment]
Windows 10 专业版22H2

**Comment by Dooy** [comment]
> Windows 10 专业版22H2

看来得搞台win来测试下了

**Comment by heiyyint** [comment]
> 我一直 试不出来 就奇怪了 我在mac上

得有聊天记录，清除的时候~~~~才会卡住网页

**Comment by heiyyint** [comment]
> > > 我一直 试不出来 就奇怪了 我在mac上
> > 
> > 得有聊天记录，清除的时候~~~~才会卡住网页
> 
> 都试过 而且是非常多的聊天记录

手机端貌似也会卡住

**Comment by williamjoe** [comment]
@Dooy @heiyyint 我的情况是对话中加载的base64图像太大就会卡死，我调整了src/api/mjsave.ts的两个函数（用chatgpt写的，写的糟糕见笑了），加载图片时也转换成blob对象能够缓解卡的情况：
```js
//本地存储获取
export const localGet = async (key: string): Promise<any> => {
    const value = await localforage.getItem<any>(key);

    if (typeof value === 'string') {
        let base64Data;
        let mimeType;
        let isNested = false;

        if (value.startsWith('["data:image/')) {
            // 数据以 ["data:image/ 开头，处理嵌套的情况

            isNested = true;
            base64Data = value.split('["')[1].split('"]')[0].split(',')[1];
            mimeType = value.split('["')[1].split('"]')[0].split(',')[0].match(/:(.*?);/)[1];
        } else if (value.startsWith('data:image/')) {
            // 数据以 data:image/ 开头，处理非嵌套的情况
            base64Data = value.split(',')[1];
            mimeType = value.split(',')[0].match(/:(.*?);/)[1];
        }

        if (base64Data && mimeType) {
            const byteString = atob(base64Data);
            const ab = new ArrayBuffer(byteString.length);
            const ia = new Uint8Array(ab);

            for (let i = 0; i < byteString.length; i++) {
                ia[i] = byteString.charCodeAt(i);
            }

            const blob = new Blob([ab], { type: mimeType });
            const blobUrl = URL.createObjectURL(blob);

            return isNested ? `["${blobUrl}"]` : blobUrl;
        }
    }

    return value;
}
```

```js
export function url2base64More(url: string, key?: string): Promise<{key: string, blob: Blob}> {
    return new Promise<{key: string, blob: Blob}>((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = "anonymous";
        img.onload = () => {
            const base64 = img2base64(img);
            const mimeType = base64.split(',')[0].match(/:(.*?);/)[1];
            const base64Data = base64.split(',')[1];

            // 将 Base64 数据转换为 Blob 对象
            const byteString = atob(base64Data);
            const ab = new ArrayBuffer(byteString.length);
            const ia = new Uint8Array(ab);

            for (let i = 0; i < byteString.length; i++) {
                ia[i] = byteString.charCodeAt(i);
            }

            const blob = new Blob([ab], { type: mimeType });

            localSaveAny(base64, key).then(d => resolve({key: d, blob})).catch(e => reject(e));
        };
        img.onerror = (e) => reject(e);
        img.src = url;
    });
}
```

**Comment by pugwoo** [comment]
+1，也是清除消息时卡死，经常发生，windows，最新chrome

**Comment by pugwoo** [comment]
> +1，也是清除消息时卡死，经常发生，windows，最新chrome

消息不多时，只有七八条，单独删除一条，也会卡住，经常发生，一天可以发生十来次

**Comment by Cans518** [comment]
windows chrome下这个问题出现频繁，+1

**Comment by Dooy** [comment]
帮忙测试下 v2.18.2 版本找到卡死的地方了

自己测试了 不会了；请大家帮忙在测下

**Comment by williamjoe** [comment]
我更新完以后卡的更频繁了，有人遇到一样的情况么？

**Comment by Dooy** [comment]
额 卡得更频繁？

**Comment by williamjoe** [comment]
> 额 卡得更频繁？

我这边的情况是这样，看看其他人的情况怎么样，我现在临时把deleteChatByUuid(uuid: number, index: number)函数改成了调用clearChatByUuid(uuid: number)，变相先清空对话历史用着。。。

**Comment by Dooy** [comment]
检查出来了 搞了 一个新版本 v2.18.3 版本 再试下

<img width="717" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/39cc3a99-b5f1-4f35-9fad-abac54707335">

**Comment by williamjoe** [comment]
> 检查出来了 搞了 一个新版本 v2.18.3 版本 再试下
> 
> <img alt="image" width="717" src="https://private-user-images.githubusercontent.com/3765401/335848014-39cc3a99-b5f1-4f35-9fad-abac54707335.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjc4NjEsIm5iZiI6MTcxNzMyNzU2MSwicGF0aCI6Ii8zNzY1NDAxLzMzNTg0ODAxNC0zOWNjM2E5OS1iNWYxLTRmMzUtOWZhZC1hYmFjNTQ3MDczMzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDJUMTEyNjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDEyMzEyYWUzYmFmMmMxMjc1ZjczMjQxMmY4NTBjMzA1MGI4ZWI0YWI3NzBlNDcyMDAzZjhiY2E0NzE4YTU1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jqcKjnX4JAkqbf-J--MCDaaI8TOkX9g_RyHIWwzr1nM">

这个我测试了一会儿发现不卡了，感谢感谢，如果发现有卡的情况我再来留言

**Comment by Dooy** [comment]
大家可以 再测试看看
