### ISSUE TITLE
希望增加图片上传体积限制

### ISSUE THREAD

**Issue by heitaokjcr** [Dooy/chatgpt-web-midjourney-proxy#351]
今天上传一张图的时候，发现图片体积限制为1m，但是在官网试了下好像没这个限制

**Comment by Dooy** [comment]
看readme 
<img width="821" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/6ddf295b-868b-4405-afbd-6323b2d759c1">

**Comment by Dooy** [comment]
其实 base64 是没限制的

操作上:直接截图复制 然后粘贴

<img width="567" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/61e21ed3-7e65-4be8-9365-1ebd7c976497">
