### ISSUE TITLE
gpt4o、4o-0513回答资讯类问题时会把会把search信息打印出来，而且提问是中文，回答是英文

### ISSUE THREAD

**Issue by superultra01** [Dooy/chatgpt-web-midjourney-proxy#352]
版本：2.17.7
提问：最新资讯

回答：
search("latest news May 20 2024")mclick(["4", "5", "7", "15", "19"])
Here are some of the latest updates as of May 20, 2024:

International News:

A helicopter crash involving Iranian President Ebrahim Raisi has been reported. The incident occurred near the Azerbaijan border during a dam inauguration project. Investigations are ongoing to determine the cause and the extent of injuries sustained by those on board【6†source】.
In Ukraine, Russian attacks on the Kharkiv region have resulted in at least 11 fatalities. The conflict continues to escalate, impacting civilian areas and causing significant casualties【6†source】.
US Politics:

The 2024 US presidential election is heating up with debates being scheduled between President Joe Biden and former President Donald Trump. The first debate is set to take place on June 27 in Atlanta, Georgia. Additionally, RFK Jr. is actively working to secure ballot access for his campaign【7†source】.
The Supreme Court has recently cleared the way for Louisiana to implement a congressional map with two districts designed to enhance representation for Black voters. This ruling is seen as a potential boost for Democratic candidates in the upcoming elections【7†source】.
Education:

In India, the Central Board of Secondary Education (CBSE) is expected to release the results for Class 10 and 12 examinations shortly after May 20, 2024. Around 39 lakh students are awaiting these results, which will be available on several official websites such as [cbseresults.nic.in](http://cbseresults.nic.in/) and [digilocker.gov.in](http://digilocker.gov.in/)【8†source】.
Sports:

Manchester City has clinched their fourth Premier League title, continuing their dominance in English football. Despite Arsenal's victory, Manchester City's lead in the standings secured their championship【6†source】.
The 2024 Indian Premier League (IPL) is in full swing, with live updates and scores available on the official IPL website. Fans are eagerly following the matches as the tournament progresses towards the finals【8†source】.
For more detailed updates and to follow these stories, you can visit news platforms like Al Jazeera, Politico, and Hindustan Times.

**Comment by Dooy** [comment]
请用中文回答

**Comment by superultra01** [comment]
显示这个search("latest news May 20 2024")mclick(["4", "5", "7", "15", "19"])是预期之内的吗

**Comment by Dooy** [comment]
不清楚啊

**Comment by superultra01** [comment]
额，我现在复现不出那些现象了，现在都是按官方的cut off来回答问题了，试了好几个资讯类问题都一样。您已经修复了？

**Comment by Dooy** [comment]
是的 我修复了？

你相信么？ 我有这么厉害就好了 ^_^

**Comment by superultra01** [comment]
现在确实没问题了，之前问它小米汽车最新情况，它肯定要search("latest news May 20 2024")mclick(["4", "5", "7", "15", "19"])之类的，现在它就按2023-10月的日期回答。还有很多类似的情况。别装了，你就是repair之神。
