### ISSUE TITLE
切换聊天时“角色设定”不会切换

### ISSUE THREAD

**Issue by honeyshine75** [Dooy/chatgpt-web-midjourney-proxy#353]
步骤
1. 新建一个聊天，并设定“角色设定”
2. 再新建一个聊天，发现使用了上一个聊天的设定

期待
每个聊天有不同的设定

**Comment by Dooy** [comment]
之前旧的 就不动了啊 ；
这个逻辑有问题么？

只是新建用了 上次的

**Comment by honeyshine75** [comment]
补充

环境：Mac 客户端
1 新创建后，设定角色
<img width="872" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/7219156/8aae291a-dc29-40ef-a940-b8a6bbbaf931">
2. 再新建后，不能单独为每个聊天设定角色
<img width="889" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/7219156/78cb152a-3770-4575-bd4a-f9be9711b2f4">

**Comment by honeyshine75** [comment]
> 之前旧的 就不动了啊 ； 这个逻辑有问题么？
> 
> 只是新建用了 上次的

已补充，目标是希望为每个聊天设定不同的模型和角色

**Comment by Dooy** [comment]
看不懂么？
<img width="997" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/513a3445-5eff-4bb9-94bf-c1081585e6a4">
<img width="498" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/e8e42951-fe86-4915-8cca-dd1b829cba1b">

**Comment by honeyshine75** [comment]
> 看不懂么？ <img alt="image" width="997" src="https://private-user-images.githubusercontent.com/3765401/331928297-513a3445-5eff-4bb9-94bf-c1081585e6a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzM3ODEsIm5iZiI6MTcxNjE3MzQ4MSwicGF0aCI6Ii8zNzY1NDAxLzMzMTkyODI5Ny01MTNhMzQ0NS01ZWZmLTRiYjktOTRiZi1jMTA4MTU4NWU2YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDI1MTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjAwNTcwMjMwN2ZlZjVhMWVjNGViZWM2MDJkNmI5NzZjM2Q0ZTU3NDAyMjdmZjk2ZjE3ZjczZWQxZDE3ZTFjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sai_tXJiKDdPzprmixOHjLUaBc47VJ6eVLbvoRdTAfw"> <img alt="image" width="498" src="https://private-user-images.githubusercontent.com/3765401/331928402-e8e42951-fe86-4915-8cca-dd1b829cba1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzM3ODEsIm5iZiI6MTcxNjE3MzQ4MSwicGF0aCI6Ii8zNzY1NDAxLzMzMTkyODQwMi1lOGU0Mjk1MS1mZTg2LTQ5MTUtOGNjYS1kZDFiODI5Y2JhMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDI1MTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODMwNTIxZWUxZTMyMWI3NzBkZDc5ZjQxZjY3ZjNkYzgwY2IyZGIwNTVjZDRjMGY3MjVlZmExYjFlMmI3ODVjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.C-_3H_d6BAADuV15lMdPIKSo8EE27__MlRga0sK0X4k">

好像明白了，是不是点击“设定”是一个全局的配置，而点击聊天界面的模型名称进行设置是每个聊天的单独设置？

**Comment by Dooy** [comment]
> 之前旧的 就不动了啊 ； 这个逻辑有问题么？
> 
> 只是新建用了 上次的

读10遍理解下 字面意思

**Comment by honeyshine75** [comment]
> > 之前旧的 就不动了啊 ； 这个逻辑有问题么？
> > 只是新建用了 上次的
> 
> 读10遍理解下 字面意思

“新建用了上次的”。。。。行吧

**Comment by Dooy** [comment]
能达到你的目的就好 呵呵

用得愉快
