### ISSUE TITLE
求助大佬，换脸程序BUG

### ISSUE THREAD

**Issue by zhoufann9188** [Dooy/chatgpt-web-midjourney-proxy#354]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/39208796/e15ca7e2-7061-4560-9253-f4700011a690)

其他画图功能都可以用，唯独换脸不行，我的docker启动如下：
sudo docker run --name chatgpt-web-midjourney-proxy  -d -p 2103:3002 \
-e OPENAI_API_KEY=XXXXXXXXXXXV02Z2V8xBEvkEja \
-e OPENAI_API_BASE_URL=https://api.openai.com  \
-e MJ_SERVER=https://XXXXXXXXXXom.cn  \
-e MJ_API_SECRET=XXXXXXXidjourney \
-e AUTH_SECRET_KEY=XXXXXXdio -e AUTH_SECRET_ERROR_COUNT=3 \
-e AUTH_SECRET_ERROR_TIME=10 ydlhero/chatgpt-web-midjourney-proxy

报错信息如下：
{
"error": "Not Found",
"code": "response_fail",
"url": "/mjapi/mj/insight-face/swap",
"status": 404
}

不知道哪里出了问题，求大佬帮助

**Comment by zhoufann9188** [comment]
我访问应用的完整URL是：
https://www.XXXXX.com.cn:22006/     不知道和网站带端口有没关系

**Comment by zhoufann9188** [comment]
对应nginx配置：
```
server {
    listen 22007 ssl;
    #对应的域名
    server_name  www.XXXXX.cn;
    ssl_certificate /etc/nginx/conf.d/ssl/wwwXXXXXXo.com.cn/biXXXXcom.cn_bundle.crt;
    ssl_certificate_key /etc/nginx/conf.d/ssl/www.XXXXXXn/biXXXXXm.cn.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_prefer_server_ciphers on;

    # 添加内容安全策略头部
    add_header Content-Security-Policy "upgrade-insecure-requests";


    location / {
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://localhost:2103;
   }
```

**Comment by Dooy** [comment]
使用钞能力 去购买mj-proxy-plus

**Comment by spammenotinoz** [comment]
> 使用钞能力 去购买mj-proxy-plus

Hi Dooy, any chance you get discounts\deals on mj-proxy-plus.  I believe the price is $200 USD that's a lot to support FaceSwap.

**Comment by Dooy** [comment]
> > 使用钞能力 去购买mj-proxy-plus
> 
> Hi Dooy, any chance you get discounts\deals on mj-proxy-plus. I believe the price is $200 USD that's a lot to support FaceSwap. Also interested in any PAID gateways.

没有discounts ；我用他们的plus 也需付款；
只是mj-proxy-plus 现在已成mj api 标准 ，
其实之前我与用过其他mj的api 最终还是选择 mj-proxy-plus

**Comment by spammenotinoz** [comment]
> > > 使用钞能力 去购买mj-proxy-plus
> > 
> > 
> > Hi Dooy, any chance you get discounts\deals on mj-proxy-plus. I believe the price is $200 USD that's a lot to support FaceSwap. Also interested in any PAID gateways.
> 
> There are no discounts; I also need to pay for their plus; It's just that mj-proxy-plus has now become the MJ API standard, in fact, I have used other MJ APIs before and finally chose mj-proxy-plus

Thanks had to  ask.. :)
Here is another proxy that is coming along nicely, always good to have a backup.
https://github.com/webman-php/midjourney-proxy
