### ISSUE TITLE
使用GPTs 里面的DALL·E

### ISSUE THREAD

**Issue by tian4546** [Dooy/chatgpt-web-midjourney-proxy#356]
提示这个错误
{
  "object": "error",
  "message": "Only gpt-3.5-turbo-0613 && gpt-3.5-turbo-0125 && gpt-3.5-turbo-16k-0613 && gpt-3.5-turbo-1106 && gpt-3.5-turbo-16k && gpt-3.5-turbo-0301 && gpt-3.5-turbo && text-embedding-ada-002 && text-embedding-3-large && text-embedding-3-small && gpt-4 && gpt-4o && gpt-4o-2024-05-13 && gpt-4-0314 && gpt-4-0613 && gpt-4-0125-preview && gpt-4-1106-preview && gpt-4-vision-preview && gpt-4-turbo-preview && gpt-4-turbo && gpt-4-turbo-2024-04-09 && gpt-4-1106-vision-preview allowed now, your model {g-2fkFE8rbu}",
  "code": 40302,
  "requestId": "b288f7f0095300838228c9c438e71a15"
}
好像GTPs 里面所有的app 都无法使用

**Comment by Dooy** [comment]
不是 已经说明了么？中转不支持 
换一个中转 比如 openai-hk.com

**Comment by tian4546** [comment]
openai-hk.com
这个也不可以 看来只有官方的key了
{
  "error": {
    "message": "当前分组 default 下对于模型 g-2fkFE8rbu 无可用渠道 (request id: 2024052118180692264885955919434)",
    "type": "openai_hk_error"
  }
}

**Comment by Dooy** [comment]
这么设置 
<img width="584" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/a31d116d-c284-4bfc-aaa0-12b8a1314b31">

**Comment by tian4546** [comment]
<img width="616" alt="gpt" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/14542275/7af9e54a-3122-4e3a-a742-c99100fcbf7e">
我是开启的哦

**Comment by Dooy** [comment]
不要去勾选 
<img width="424" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/1df3c64b-9b83-4c6a-86ae-7393f65b82e7">

**Comment by Dooy** [comment]
这么设置会么 ？

![Uploading image.png…]()

**Comment by Dooy** [comment]
这么设置会么 ？
<img width="503" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/9b66c18b-0aff-40b2-b507-2ef9174a93c7">

**Comment by tian4546** [comment]
ok 谢谢可以了
