### ISSUE TITLE
部署不成功

### ISSUE THREAD

**Issue by TerrySiu98** [Dooy/chatgpt-web-midjourney-proxy#357]
docker run --name chatgpt-web-midjourney-proxy -d -p 6015:3002 ydlhero/chatgpt-web-midjourney-proxy
不需要默认key啥的 是不是环境变量都可以删除呢
我部署了报错 没有部署mj那个是不是不能用

**Comment by TerrySiu98** [comment]
是否能部署后自定义接口 mj也是用第三方中转的

**Comment by Dooy** [comment]
> 是否能部署后自定义接口 mj也是用第三方中转的

可以，多看下 readme
