### ISSUE TITLE
使用钞能力 去购买mj-proxy-plus后，局部重绘功能在哪呢？

### ISSUE THREAD

**Issue by osbi-code** [Dooy/chatgpt-web-midjourney-proxy#358]
使用钞能力 去购买mj-proxy-plus

_Originally posted by @Dooy in https://github.com/Dooy/chatgpt-web-midjourney-proxy/issues/354#issuecomment-2120233880_

            好的，已买PLUS果然可以了 感谢！@Dooy 大神！不过到目前还没找到局部重绘功能在哪。。。

            
![image](https://user-images.githubusercontent.com/39208796/332507487-31610a14-7b61-447d-bb73-e935a7cf0e25.png)

请问局部重绘的按钮具体在哪，怎么触发啊？焦虑。。。

**Comment by Dooy** [comment]
先自己 到 discord上用 看看什么时候 会出现 局部重绘
