### ISSUE TITLE
希望导入的提示词可以直接点击使用

### ISSUE THREAD

**Issue by Mr-LiuDC** [Dooy/chatgpt-web-midjourney-proxy#36]
希望导入的提示词可以直接点击使用，目前只能编辑和删除。

**Comment by Dooy** [comment]
![abk](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/66617620-5757-4ab5-b05b-6d9b79d3e025)

这不是能用么？

**Comment by Dooy** [comment]
你想要的姿势是哪种？

**Comment by tuzh6** [comment]
> 你想要的姿势是哪种？

他想要的应该是单独有个模块，比如左边起个模块叫应用啊之类的，页面直接全部展示出来点击直接使用吧

**Comment by Dooy** [comment]
后面 考虑看看 如何搞起来

**Comment by jason-xiaobaiai** [comment]
> 后面 考虑看看 如何搞起来

这块没有问题，很方便，不用改，他应该是没发现不会用

**Comment by Mr-LiuDC** [comment]
之前确实是没发现可以通过聊天框里面切换提示词
