### ISSUE TITLE
自定义模型的tokens配置

### ISSUE THREAD

**Issue by RogerProSelf** [Dooy/chatgpt-web-midjourney-proxy#362]
希望能在环境变量或者UI中增加对自定义模型的默认的max tokens的配置，因为现在越来越多的128k模型了，目前UI内滑块拉满也才4k/2k实在少了点，谢谢！
另外DEFAULT_SYSTEM_TEMPLATE中，建议不要预设模型的KnowledgeCutOffDate的default默认值，prompt也可以换成一个更加通用的，而不是'You are ChatGPT, a large language model trained by OpenAI.'，毕竟使用这个项目的人很多会配合One-API等平台整合多个模型，目前的DEFAULT_SYSTEM_TEMPLATE很容易对自定义模型产生误导，谢谢！

**Comment by Dooy** [comment]
1. 2k 我后面修复下 搞到 默认是 4k来
2. `DEFAULT_SYSTEM_TEMPLATE` 写出来自己定义？
