### ISSUE TITLE
使用 suno 时，输入框内要怎么写才等同于 suno 官网的效果

### ISSUE THREAD

**Issue by Endiaoshuai** [Dooy/chatgpt-web-midjourney-proxy#364]
使用 suno 时，输入框内要怎么写才等同于 suno 官网的效果
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/35101911/019db344-01d2-4071-8990-4822c8e9da92)

官网的：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/35101911/bfc65ead-4084-4ac9-94d3-58004095a503)

**Comment by Dooy** [comment]
入口错了

<img width="613" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/b4bb8616-fa85-482a-8dda-c81469cf23d8">
