### ISSUE TITLE
MJ绘图自动翻译，图片上传图床

### ISSUE THREAD

**Issue by zsjnhfg** [Dooy/chatgpt-web-midjourney-proxy#366]
你好！
1、何实现MJ绘图提示词自动翻译，或者是否可以增加翻译按钮
2、如何实现MJ绘图产生的图片自动上传chevereto图床（或者其他同类产品图床）

**Comment by Dooy** [comment]
这些工作 你不知道 mi-proxy 可以做么？

**Comment by Dooy** [comment]
已经有一个图床了，用户能自己打开 你也可以在Docker通过环境变量打开 请看下 readme

<img width="172" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/7e38555e-4e76-45bf-b63a-35dc4e0ee9cc">
