### ISSUE TITLE
老大，本地测试跑起来后，接openai可以正常返回，接HK的就不行，咋办呀？另外如果要定制怎么联系？

### ISSUE THREAD

**Issue by choufeng2018** [Dooy/chatgpt-web-midjourney-proxy#367]
![C111](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/39671763/c0c22e21-3bda-4c35-a1ef-2e5180bab65f)
![C2222](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/39671763/88fe34ff-31df-4be3-bb2c-a16950d68e93)

**Comment by Dooy** [comment]
能跑起来 不管用谁的都行

可以把 微信发我邮箱 我+你
ydlhero@gmail.com

**Comment by choufeng2018** [comment]
哈哈，昨晚我留过微信了，那么晚睡，但我看你一大早又在回复问题了，厉害。我邮件再发一次

**Comment by choufeng2018** [comment]
哈哈，另外不止是GPT呀，绘画也想要用呀，用中转方便省事呢。现在MJ这些都一样的问题。
