### ISSUE TITLE
无法画图

### ISSUE THREAD

**Issue by bobandbrony** [Dooy/chatgpt-web-midjourney-proxy#37]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129247570/c17e9400-a34b-4c7f-a7d9-fa8bde2e401c)
没有图片只有文字

**Comment by bobandbrony** [comment]
我这边显示api被调用dalle画了一张图

**Comment by Dooy** [comment]
能否 换一个 提示词，比如  “大猫咪” 啥的 ？

**Comment by bobandbrony** [comment]
> 能否 换一个 提示词，比如 “大猫咪” 啥的 ？

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129247570/e9df8d07-0987-4aac-b8cd-754f6767bae1)
换了还是不行，这个dalle调用的是第三方api，没有用官网的

**Comment by Dooy** [comment]
换过一家 比如用 https://www.openai-hk.com

**Comment by bobandbrony** [comment]
> 换过一家吧

ee现在又能画了
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129247570/23303ecb-6313-4dcf-8119-dd1eddc3332f)
可能是网络原因？

**Comment by Dooy** [comment]
问中转 不要问我 我没收你费用
