### ISSUE TITLE
Bug: 设置SYSTEM_MESSAGE后模型依然对KnowledgeCutOffDate有误解

### ISSUE THREAD

**Issue by rdself** [Dooy/chatgpt-web-midjourney-proxy#370]
设置SYSTEM_MESSAGE后，自定义模型依然是认为自己的知识库截止日期是21年9月：
![截屏2024-05-24 11 32 34](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/55005611/4264fb78-b9ec-4028-83c7-500d94f5c2f8)

**Comment by Dooy** [comment]
后面 再想想办法 这个如何处理吧 

我还是加 KnowledgeCutOffDate

**Comment by Dooy** [comment]
现在看看 如果不是gpt 或者规定过的 KnowledgeCutOffDate 不会加了
