### ISSUE TITLE
Bug: 手机版Safari下地址栏遮挡界面

### ISSUE THREAD

**Issue by rdself** [Dooy/chatgpt-web-midjourney-proxy#371]
在手机版的Safari界面下，地址栏遮挡了上半部分，且无法上下滑动页面，导致绘图和画廊界面无法关闭，还请修复一下，感谢！

![IMG_1819](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/55005611/2355f2a1-f631-436d-a63d-edc2c77d116e)
![IMG_1818](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/55005611/9bc629a1-0383-46ee-b63b-457fa4093c6c)

**Comment by Dooy** [comment]
好的 我看下

**Comment by Dooy** [comment]
画廊部分 请更新到 2.18.8 再试一试看
