### ISSUE TITLE
Bug：windows10端点击重新生成的界面上移

### ISSUE THREAD

**Issue by yelanyanyu** [Dooy/chatgpt-web-midjourney-proxy#373]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/94947914/518be517-4c14-4eef-b7c5-6cbecadb0943)

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/94947914/3e71beab-9e83-402a-9a16-4bea0ecf0ac9)
如上图所示，点击重新生成后，界面异常。

**Comment by Dooy** [comment]
可能是 内容导致的 看看在用其他对话看看会不？
还是 100%会？

**Comment by yelanyanyu** [comment]
> 可能是 内容导致的 看看在用其他对话看看会不？ 还是 100%会？

其他的对话暂时没有发现这个问题。

**Comment by Dooy** [comment]
把有问题的 通过复制按钮贴出来
<img width="392" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/20a8bdb6-8345-41b6-a822-7a1c17dec2bd">

**Comment by Dooy** [comment]
用的内容 我这边 测试没问题

**Comment by Dooy** [comment]
试下 最新版本 `v2.18.3`
