### ISSUE TITLE
图片加载很慢

### ISSUE THREAD

**Issue by ggtete3** [Dooy/chatgpt-web-midjourney-proxy#374]
![WX20240527-215828@2x](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/170812646/e50cdc82-8ce2-4487-ad80-d88d66077a80)
加载的时候图片不出来 还有我的画廊图片也是加载不出来 这个是API 问题吗

**Comment by Dooy** [comment]
直接打开链接 就好

<img width="519" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/e5e3570c-95cd-45b4-ae3b-cb3fba031702">

**Comment by Dooy** [comment]
或者 把图床打开 能加速

<img width="859" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/85bac50a-f776-4b6d-9aa7-50c8718c6d30">
