### ISSUE TITLE
我想把绘画页面和对话页面分开该怎么做？

### ISSUE THREAD

**Issue by Superkaoshen** [Dooy/chatgpt-web-midjourney-proxy#376]
就是不共享一个对话窗口，而是重新写一个绘画页面。有没有什么思路提供一个

**Comment by Dooy** [comment]
最新版本；已经会新开聊天记录了 你试下

**Comment by Superkaoshen** [comment]
是的我看到了，但是我还是想把绘画页面独立开来而不使用chat页面来共享聊天窗口，具体应该更改哪部分的代码呢？我改了好久，还是改不对，要崩溃了。

**Comment by Dooy** [comment]
好开放 ^_^
