### ISSUE TITLE
GPTS页面不支持一个页面一个模型

### ISSUE THREAD

**Issue by Superkaoshen** [Dooy/chatgpt-web-midjourney-proxy#378]
当点击gpts页面的任意图标时候，会在当前聊天窗口改变模型，后面新增聊天窗口包括所有的聊天窗口都是是这个模型。然后再次点击图标时，模型又全局改变了一次。

**Comment by Dooy** [comment]
就是 没新建 聊天窗口  是这样意思吧 
我看看 后面怎么修改下

**Comment by Superkaoshen** [comment]
是的，还有gpts创建后，再次新建聊天窗口，新的聊天窗口还是gpts的模型。

**Comment by yinhaixiang** [comment]
> 当点击gpts页面的任意图标时候，会在当前聊天窗口改变模型，后面新增聊天窗口包括所有的聊天窗口都是是这个模型。然后再次点击图标时，模型又全局改变了一次。

我觉得当前的设计没问题啊, 无论我在哪个会话页面, 我选择gpts, 点击某一个我希望切换的模型, 正常自然逻辑就是修改当前会话的模型(这种场景是有的, 我经常在一个会话中切换多个模型问答), 然后新增聊天窗口, 默认模型的赋值就是上一个会话窗口选择的模型, 这也是合理的, 如果你要换模型, 就在新会话窗口里切换你希望要的模型就行了。

**Comment by yinhaixiang** [comment]
> 是的，还有gpts创建后，再次新建聊天窗口，新的聊天窗口还是gpts的模型。

现在的逻辑是"每新建会话窗口, 新会话的模型是上一个窗口的选择模型", 这个逻辑我觉得很自然舒服。

**Comment by yinhaixiang** [comment]
openai官网下拉框有3个模型, 3.5, 4, 4o, 也是同样的逻辑, 你当前会话里也可以随时切换不同的模型, 并不需要新开会话, 如果你新开会话, 则新会话的逻辑就是上个会话当前选择的模型, 这个逻辑完全没问题。

**Comment by yinhaixiang** [comment]
> 就是 没新建 聊天窗口 是这样意思吧 我看看 后面怎么修改下

我觉得没必要gpts里选择一个新模型时, 就要新开一个会话窗口, 有时候用户就希望在当前会话启用新的模型来交流

**Comment by Dooy** [comment]
> > 就是 没新建 聊天窗口 是这样意思吧 我看看 后面怎么修改下
> 
> 我觉得没必要gpts里选择一个新模型时, 就要新开一个会话窗口, 有时候用户就希望在当前会话启用新的模型来交流

嗯自然就帮你开好新聊天窗口 而不是需要去手动 是不？

**Comment by yinhaixiang** [comment]
> > > 就是 没新建 聊天窗口 是这样意思吧 我看看 后面怎么修改下
> > 
> > 
> > 我觉得没必要gpts里选择一个新模型时, 就要新开一个会话窗口, 有时候用户就希望在当前会话启用新的模型来交流
> 
> 嗯自然就帮你开好新聊天窗口 而不是需要去手动 是不？

我觉得"新开窗口"和"切换模型"是两件正交的事, 不应强关联, 用户既有在当前窗口切换模型的可能, 也有新建窗口切换模型的可能
总而言之，我觉得作者大佬现在的处理就是对的，没什么问题。

**Comment by Dooy** [comment]
下载到 新版本 v2.18.1 试一试

**Comment by yinhaixiang** [comment]
> 下载到 新版本 v2.18.1 试一试

现在更新后有问题, gpts里选择一个新的模型后, 页面可能会卡死

**Comment by yinhaixiang** [comment]
当回到某一个已经存在的会话窗口, 点击gpts 然后选择新模型, 就会卡死

**Comment by Dooy** [comment]
我也测到一次 但是后面 就不会了 奇怪

**Comment by Dooy** [comment]
会 我测试到了 我修改下

**Comment by Dooy** [comment]
下载 最新版本 `v2.18.3` 卡死现象解决了
