### ISSUE TITLE
希望能在网页端修改dall e的接口地址

### ISSUE THREAD

**Issue by bobandbrony** [Dooy/chatgpt-web-midjourney-proxy#38]
虽然能通过修改变量的形式来改，但那样还是太麻烦了

**Comment by Dooy** [comment]
我没见过 dall.e 还不跟 openai_base_url 走；
如果有需要 自行修改下 ；您这需求定制化了

**Comment by Dooy** [comment]
![img](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/c2bcf736-a372-49d8-9063-bf23ebf7b9fb)
前端本来 也能修改的

**Comment by Dooy** [comment]
不会的 可能你修改对； 我确定调过了 
你可以在 https://vercel.ddaiai.com 设置试下 我都是在上面调的

**Comment by bobandbrony** [comment]
> 不会的 可能你修改对； 我确定调过了 你可以在 https://vercel.ddaiai.com 设置试下 我都是在上面调的

ee，可以了，但之前确实出现过那种情况（可以聊天，dalle绘画返回无此密钥，让我去openAI），可能是bug吧

**Comment by Dooy** [comment]
ok 那我 close掉了
