### ISSUE TITLE
service worker 有没有方法强制更新

### ISSUE THREAD

**Issue by Jkkoi** [Dooy/chatgpt-web-midjourney-proxy#380]
#379 之后，浏览器无法自动更新 service worker，导致网页仍无法正常显示。需要进入控制台手动注销 service worker。
但这个操作对于普通用户，特别是手机来说基本是无法实现的，甚部分软件内置浏览器不支持强制刷新
因此，在现有的代码中，有没有什么方法可以在网页目前无法正常显示的情况下，强制更新 service worker 呢

**Comment by Dooy** [comment]
我都不记得 代码内有关于  service worker 的处理

**Comment by Jkkoi** [comment]
@Dooy 
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/39653010/4786971a-ac26-4aac-8fc4-2ab2a9dc4628)

**Comment by Dooy** [comment]
可能 需要修改下 代码 可以进vite.config.ts 关闭掉 VitePWA
这个还无法通过环境变量来控制

<img width="675" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/8033e53e-314c-4cfc-b605-9a22b914a98d">
