### ISSUE TITLE
文件指定上传到容器，gpt会获取不到文件

### ISSUE THREAD

**Issue by zhanghs23** [Dooy/chatgpt-web-midjourney-proxy#381]
文件指定上传到容器
![文件上传到容器](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/128876811/c642accb-e275-4bea-ab49-670ae388315e)

对话会获取不到文件，导致gpt无法分析文件内容
![文件获取不到](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/128876811/962b8ef9-a3b6-4632-ae46-c9aff0224303)

是还要设置文件路径吗？

**Comment by Dooy** [comment]
是不是 因为内网的原因？ 你这个地址是内网？

可以用右键看下 附件的地址

**Comment by Cans518** [comment]
> 是不是 因为内网的原因？ 你这个地址是内网？
> 
> 可以用右键看下 附件的地址

我这边似乎也有相同的问题，但是使用的r2服务，发现的问题是：不知道为什么，文件的访问地址前面被加上了主站的访问域名，例子：
主站: mzee.top     r2文件地址： https://pub-*********.r2.dev/**********.pdf
最后会被拼接为： https://mzee.top******.r2.cloudflarestorage.com/*******/5*********.pdf

**Comment by Dooy** [comment]
> > 是不是 因为内网的原因？ 你这个地址是内网？
> > 可以用右键看下 附件的地址
> 
> 我这边似乎也有相同的问题，但是使用的r2服务，发现的问题是：不知道为什么，文件的访问地址前面被加上了主站的访问域名，例子： 主站: mzee.top r2文件地址： https://pub-*********.r2.dev/**********.pdf 最后会被拼接为： https://mzee.top******.r2.cloudflarestorage.com/*******/5*********.pdf

这个是R2在CF设置 没设置 你可以先用curl 或者postman 跑一遍 跑通了 再接入程序试一试

**Comment by moyangdan** [comment]
请问解决了吗，在CF里应该如何设置
