### ISSUE TITLE
suno格式支持

### ISSUE THREAD

**Issue by heiyyint** [Dooy/chatgpt-web-midjourney-proxy#382]
可以支持suno走这个格式吗https://gpt-best.apifox.cn/doc-4344094

**Comment by Dooy** [comment]
我试下 有关于 GoAmz 的文档否？

**Comment by yuanjie-ai** [comment]
文档在这
https://api.chatfire.cn/docs/doc-4422845

**Comment by yuanjie-ai** [comment]
> 可以支持suno走这个格式吗https://gpt-best.apifox.cn/doc-4344094

https://api.chatfire.cn/docs/doc-4422845 1毛

**Comment by heiyyint** [comment]
支持了不

**Comment by heiyyint** [comment]
> 我试下 有关于 GoAmz 的文档否？

https://github.com/goamz/goamz

**Comment by Dooy** [comment]
数据 格式太多了  支持起来费劲

还是以官方的数据格式为准吧

**Comment by heiyyint** [comment]
> 数据 格式太多了  支持起来费劲
> 
> 还是以官方的数据格式为准吧

好的

**Comment by yuanjie-ai** [comment]
api.chatfire.cn/docs



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月7日(周五) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Dooy/chatgpt-web-midjourney-proxy] suno格式支持 (Issue #382)




  
我试下 有关于 GoAmz 的文档否？
  
https://github.com/goamz/goamz
