### ISSUE TITLE
文件上传出现一些问题

### ISSUE THREAD

**Issue by Cans518** [Dooy/chatgpt-web-midjourney-proxy#383]
# 文件上传问题

## 配置内容：
API_UPLOADER = 1
UPLOAD_TYPE = R2
完成R2 的其它配置

## 问题描述
在客户端设定了api和key，发现文件上传默认走了api地址上传
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/52856665/610a89d9-32e9-4ad8-873d-7a33d51ed5df)

**Comment by Cans518** [comment]
补充一下已经看了置顶的那个issue了

**Comment by Dooy** [comment]
按逻辑来说 如果设置了 UPLOAD_TYPE = R2 
会去走 R2的方式啊

**Comment by Cans518** [comment]
> 按逻辑来说 如果设置了 UPLOAD_TYPE = R2 会去走 R2的方式啊

我再去尝试一下重启docker并检查r2配置，如果还是不行我会补充后续报错和详细信息

**Comment by Cans518** [comment]
> 按逻辑来说 如果设置了 UPLOAD_TYPE = R2 会去走 R2的方式啊

很不幸我重新配置了R2以后依旧无法正常访问，我启动docker镜像的命名为：
```bash
docker run --name chatgpt-web-midjourney-proxy  -d -p 3000:3002 \
-e OPENAI_API_KEY=sk-********** \
-e OPENAI_API_BASE_URL=https://api.v3.cm  \
-e R2_DOMAIN=https://pub-****************.r2.dev \
-e R2_BUCKET_NAME=gpt \
-e R2_ACCOUNT_ID=******************* \
-e R2_KEY_ID=******** \
-e R2_KEY_SECRET=******\
ydlhero/chatgpt-web-midjourney-proxy
```

我在自己的网站上查看请求也是并没有进行R2请求而是针对于我自己的api转发商进行的：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/52856665/ceaed2de-3c9d-481b-9156-c12c5a5aba82)

**Comment by Cans518** [comment]
> 按逻辑来说 如果设置了 UPLOAD_TYPE = R2 会去走 R2的方式啊

我尝试了按照知乎里面的R2进行了重新配置，有几个疑问：
1. R2是否需要公开？
2. R2是否能使用默认的.dev?
以下是我自己的启动docker容器命令：
```bash
docker run --name chatgpt-web-midjourney-proxy  -d -p 3000:3002 \
-e OPENAI_API_KEY=sk-***************** \
-e OPENAI_API_BASE_URL=https://api.v3.cm  \
-e VISION_MODEL=gpt-4o \
-e API_UPLOADER=1  -e UPLOAD_TYPE=R2 \
-e R2_DOMAIN=https://pub-*******.r2.dev \
-e R2_BUCKET_NAME=gpt \
-e R2_ACCOUNT_ID=****************** \
-e R2_KEY_ID=************ \
-e R2_KEY_SECRET=************\
ydlhero/chatgpt-web-midjourney-proxy
```

在前端上传也发现调用的是我自己的api转发服务商：
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/52856665/a7825062-97ff-4386-9060-7e6c07da85ef)

**Comment by Cans518** [comment]
> 按逻辑来说 如果设置了 UPLOAD_TYPE = R2 会去走 R2的方式啊

我在写死不使用前端配置服务器的时候可以正常使用R2上传文件，但是遇到了其它的问题：不知道为什么会把主站的url和cf的r2域名拼接起来（似乎是前端的bug？但是我更倾向于是我的设置错误？）
<img width="839" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/52856665/e3c15faa-d698-4194-a0df-299735c9af67">
就是在发送请求的时候似乎是对域名进行了拼接

**Comment by Cans518** [comment]
> 按逻辑来说 如果设置了 UPLOAD_TYPE = R2 会去走 R2的方式啊

我再另外一个issue里面也提供了更加详细的内容说明：#381

**Comment by Cans518** [comment]
或许可以把R2配置选项也放到前端可选？这样似乎就不怕出问题了。

**Comment by Dooy** [comment]
这个地址是从CF的R2来的，你可以看下R2的文档先在postman 跑一下

**Comment by Cans518** [comment]
R2配置需要一些额外测试

**Comment by sumwee** [comment]
> R2配置需要一些额外测试

请问解决了吗
