### ISSUE TITLE
将suno版本更新到chirp v3-5

### ISSUE THREAD

**Issue by hong47** [Dooy/chatgpt-web-midjourney-proxy#385]
目前suno官方已经开放了suno v3.5的使用，最多能生成4分钟的歌曲。建议加一个选择框，允许用户调用v3.5的接口。
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/10756453/b192d513-4b7b-4309-b139-21eabb470aaf)

**Comment by Dooy** [comment]
嗯 是该考虑 3.5了

**Comment by Dooy** [comment]
v2.18.4 升级到 3.5版本了
