### ISSUE TITLE
这个上传地址要填什么才能正常上传文件啊

### ISSUE THREAD

**Issue by miogasuki** [Dooy/chatgpt-web-midjourney-proxy#386]
![Snipaste_2024-06-02_00-08-41](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/119719639/16754fcd-d133-44ef-9e6b-3b5e0959bb93)
这个要怎么填啊（哭）

**Comment by Dooy** [comment]
麻烦看下 readme

**Comment by miogasuki** [comment]
> 麻烦看下 readme

看了，但是没看懂
![A959A7B612035ABFFB13EF2EC4BE03A8](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/119719639/50381d94-b273-4b27-8170-e0ea6a4062ec)

**Comment by miogasuki** [comment]
有没有人救救

**Comment by JIANRENWEN** [comment]
我现在也报错，readme没提这个东西，不知道怎么解决，可能是这个版本有bug吧
