### ISSUE TITLE
在没有任何系统提示词的情况下，大模型回复这个。

### ISSUE THREAD

**Issue by sunsky89757** [Dooy/chatgpt-web-midjourney-proxy#388]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/113254524/2d6e9058-3438-49d3-9b22-a48f06528013)

**Comment by sunsky89757** [comment]
有时候还自曝Latex公式渲染能力。
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/113254524/1870c7ca-b3b2-4408-baef-e82ed70ad7fe)

**Comment by Dooy** [comment]
用F12 看下 如果没有提示词？系统会有一个默认的

可以自己设置
