### ISSUE TITLE
请问这个suno生成是有木有问题咩？我发现以前版本可以生成，这个是拉取最新版本，发现不能生成音乐了。出现发生错误SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by VTSTG233** [Dooy/chatgpt-web-midjourney-proxy#389]
![Screenshot_2024-06-04-18-45-24-644_com.android.chrome.jpg](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/69726942/48dbc047-8fd3-4957-a3d4-39f6508b927f)
发生错误SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON

**Comment by VTSTG233** [comment]
还有，手机浏览器UA界面没有音乐这个选项，是后续会加入还是

**Comment by Dooy** [comment]
问下 中转 或者你自己的后端 支持么

**Comment by VTSTG233** [comment]
待会 我发现，直接切换模型的时候，选suno-v3 可以生成诶![Screenshot_2024-06-04-19-06-20-507_com.android.chrome.jpg](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/69726942/6bd2b7ee-af14-4243-84e2-e4561f579e35)

但是我点左边选项的音乐那，点普通无歌词，好像生成不了

**Comment by VTSTG233** [comment]
我用试了2个中转，是不是suno-v3的这个模型，那个音乐那生成不了，我看了，在对话那切为suno-v3，发送歌词好像就可进行生成

**Comment by Dooy** [comment]
试下  www.openai-hk.com  这个中转吧
