### ISSUE TITLE
如何docker部署但是前端输入key

### ISSUE THREAD

**Issue by sumwee** [Dooy/chatgpt-web-midjourney-proxy#390]
docker部署以后，如果不输入key和url，光输入文件上传地址无效，会导致容器无法运行，

**Comment by Dooy** [comment]
需要输入key 
可以任意 但不能留空

**Comment by sumwee** [comment]
> 需要输入key 可以任意 但不能留空

部署成功以后，R2上传出现了问题，上传失败:"<!doctype html>\n<html lang="en">\n <head>\n <meta charset="utf-8" />\n <link rel="icon" href="/logo.png" />\n <meta name="viewport" content="width=device-width, initial-scale=1" />\n <meta name="theme-color" content="#ffffff" />\n <meta\n name="description"\n content="OpenAI 接口聚合管理，支持多种渠道包括 Azure，可用于二次分发管理 key，仅单可执行文件，已打包好 Docker 镜像，一键部署，开箱即用"\n />\n <title>New API</title>\n <script type="module" crossorigin src="/assets/index-D7IbvYSl.js"></script>\n <link rel="modulepreload" crossorigin href="/assets/react-core-CLwr57uy.js">\n <link rel="modulepreload" crossorigin href="/assets/semi-ui-BHzOf8tD.js">\n <link rel="modulepreload" crossorigin href="/assets/tools-Bia2vmZV.js">\n <link rel="modulepreload" crossorigin href="/assets/react-components-B0-Ya59j.js">\n <link rel="modulepreload" crossorigin href="/assets/semantic-7HezVohW.js">\n <link rel="stylesheet" crossorigin href="/assets/semi-ui-DPNiGiI-.css">\n <link rel="stylesheet" crossorigin href="/assets/index-CF9WWvgQ.css">\n </head>\n <body>\n <noscript>You need to enable JavaScript to run this app.</noscript>\n <div id="root"></div>\n </body>\n</html>\n"

**Comment by Dooy** [comment]
应该是 R2没配置好

**Comment by sumwee** [comment]
> 应该是 R2没配置好

把前端的sk和url去掉上传文件没问题，一输入sk和url就显示这个，上传失败

**Comment by Dooy** [comment]
把sk 跟url 放到 后端去就好啦
