### ISSUE TITLE
自定义模型未生效

### ISSUE THREAD

**Issue by magicdmer** [Dooy/chatgpt-web-midjourney-proxy#392]
我使用了本地安装板exe客户端，版本号 2.18.3
我打开设置，输入自定义模型，点击保存后提示保存成功，但是没有任何效果，列表没有出现添加的自定义模型

**Comment by Dooy** [comment]
你找下 close的issue 有人提过相同的问题

**Comment by Dooy** [comment]
#278 这个

**Comment by magicdmer** [comment]
好的，这个逻辑有点犀利，出乎我意料
![00503E0D](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/5556368/991d0f23-762e-4f04-bc25-a32a5e069389)
