### ISSUE TITLE
本地无法上传文件吗请问

### ISSUE THREAD

**Issue by miogasuki** [Dooy/chatgpt-web-midjourney-proxy#393]
redeme里也没教我怎么上传啊？
光说什么部署什么部署，全是英文单词我看不懂啊（抓狂）
没人能教教吗

**Comment by Dooy** [comment]
可以看这个教程 0基础

https://www.bilibili.com/video/BV1NT421S7D2/?spm_id_from=333.999.0.0&vd_source=00d22137bd7f65f5403dae2a967fd0e2

**Comment by miogasuki** [comment]
> 可以看这个教程 0基础
> 
> https://www.bilibili.com/video/BV1NT421S7D2/?spm_id_from=333.999.0.0&vd_source=00d22137bd7f65f5403dae2a967fd0e2

请问除了自己搭建之外没有别的办法了吗？
发行版里的本地端无法使用文件上传吗

**Comment by Dooy** [comment]
可以，甚至我把 Docker-Compose 都写好了 你都不会搭

**Comment by miogasuki** [comment]
> 可以，甚至我把 Docker-Compose 都写好了 你都不会搭

哥你readme里没写在本地服务端要怎么填啊，那什么Docker部署贴了一堆代码我也看不懂啊，不知道该干啥啊，我只是想从本地上传文件……
![A959A7B612035ABFFB13EF2EC4BE03A8](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/119719639/a1ab7b10-5727-4e3a-914d-a98de048bc5c)

**Comment by miogasuki** [comment]
我实在找不到允许上传文件的其他第三方工具了，哥你行行好吧
![A959A7B612035ABFFB13EF2EC4BE03A8](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/119719639/a43c7410-79ce-4083-9804-e95417db4533)

**Comment by Byelliot** [comment]
可以把redeme 丢给gpt 有问题啥不会直接问gpt 手把手教你

**Comment by Dooy** [comment]
> 我实在找不到允许上传文件的其他第三方工具了，哥你行行好吧 

不用那么麻烦，下载合适你的客户端 https://github.com/Dooy/chatgpt-web-midjourney-proxy/releases

配合 www.openai-hk.com 完美解决

自己架服务器也可以 基本的Docker 知识 花点红包 请人教
这里有各种 docker-compose 包括文件上传，看你自己选择
https://github.com/Dooy/chatgpt-web-midjourney-proxy/tree/main/docker-compose
