### ISSUE TITLE
项目出错了，所有模型无法调用

### ISSUE THREAD

**Issue by AthanaD** [Dooy/chatgpt-web-midjourney-proxy#396]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/125889247/81dcf668-562e-4f15-a668-b1d2f9c85a77)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/125889247/5765f329-5b63-483c-8348-8cf3613c2ddb)

以上为本项目与LOBE项目对比，采用相同的调用地址及模型

**Comment by Dooy** [comment]
能否问下 你的中转？
要不 把你的的 baseurl 跟key给我 ？我帮你测试？

**Comment by AthanaD** [comment]
> 能否问下 你的中转？ 要不 把你的的 baseurl 跟key给我 ？我帮你测试？
帮测试下呢，大佬，以下为接口及api-key，在chatgpt-next和lobe站可以通，就是贵站创建的站上无法接通。

https://chiangma.com
sk-6JSwQhsdVdVBDKG0A6DcC3A4CeA840E3A66473E853D21517

配置如下：
`new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    networks:
      mynet:
        ipv4_address: x.x.x.x
    ports:
      - "3005:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      # - /home/ubuntu/data/new-api:/data
    environment:
      - SQL_DSN=newapi:newsswwsapi@tcp(x.x.x.x:3306)/newapi
      - TZ=Asia/Shanghai
      - THEME=berry
    depends_on:
      - redis1  # 确保在应用服务启动前 Redis 服务已经运行
 
  gptweb:
    container_name: chatgpt-web-midjourney-proxy
    image: ydlhero/chatgpt-web-midjourney-proxy # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 6050:3002
    environment:
      TZ: Asia/Shanghai # 指定时区
      # 必选
      OPENAI_API_KEY: sk-xxxxx
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: https://xxxx.com
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL: gpt-4o
      # 访问权限密钥，可选
      AUTH_SECRET_KEY: 
      # midjourney 服务器地址，可选 可用下面的 http://midjourney-proxy:8080
      MJ_SERVER: 
      # midjourney API密钥，可选
      MJ_API_SECRET: 
      #API_UPLOADER 是否可以上传 1 可以其他都不可以，可选
      API_UPLOADER: 1
      #HIDE_SERVER 隐藏服务端 1，可选
      HIDE_SERVER: 
      #自定义模型  CUSTOM_MODELS=-gpt-3.5-turbo-0301,gpt-4.5 不显示 gpt-3.5-turbo-0301 新增加 gpt-4.5，可选
      CUSTOM_MODELS: -all,gpt-4-s,gpt-4o,gpt-4-o,gpt-4-magic-create,gpt-4-gizmo-*,gpt-4-gizmo,gpt-4-vision-preview,gpt-4-classic,gpt-4,webpilot,chiangma,m/gpt_4_turbo,m/claude_3_opus,m/claude_3_sonnet,m/claude_3_haiku,m/gemini_1_5_pro,m/command_r_plus,m/gpt-4o,deepseek-chat,deepseek-coder,deeplx-EN,deeplx-ZH,copilot4,dall-e-3,whisper-1,tts-1
      #TJ_BAIDU_ID 百度统计ID，可选
      TJ_BAIDU_ID: 
      #TJ_GOOGLE_ID 谷歌统计ID，可选
      TJ_GOOGLE_ID: 
      #SYS_NOTIFY 系统通知 支持HTML ，可选
      SYS_NOTIFY: 
      #FILE_SERVER 文件服务器，可选 可以用下面的 http://fileserver:3012
      FILE_SERVER: 
      #DISABLE_GPT4=1 前端限制GPT4调用，可选
      DISABLE_GPT4: 
      # cloudflare r2 存储 10 GB/月 免费 https://www.cloudflare.com/zh-cn/developer-platform/r2/
      R2_DOMAIN: 
      R2_BUCKET_NAME: 
      R2_ACCOUNT_ID: 
      R2_KEY_ID: 
      R2_KEY_SECRET: 
      ## UPLOAD_IMG_SIZE gpt-4-version 图片上传大小 单位是兆 注意别带单位 最好别超过10 
      UPLOAD_IMG_SIZE: 9
      # GPT_URL=/gpts.json  自定义GPTs模型
      GPT_URL: 
      # SYS_THEME 主题 theme   light 或者 dark 
      SYS_THEME: light
      #关闭MD预览  CLOSE_MD_PREVIEW=1
      CLOSE_MD_PREVIEW: 
      #爆破：验证次数 注意: vercel 不支持 nginx 请设置  proxy_set_header   X-Forwarded-For  $remote_addr;
      AUTH_SECRET_ERROR_COUNT: 3
      #爆破：验证停留时间 单位分钟 注意: vercel 不支持
      AUTH_SECRET_ERROR_TIME: 10
`

**Comment by Dooy** [comment]
跨域问题，要不 你设置在后端吧

<img width="979" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/000289c1-0a4a-4ccc-8114-6d04e7a6d1e5">

**Comment by Dooy** [comment]
```
# 必选
OPENAI_API_KEY: sk-6JSwQhsdVdVBDKG0A6DcC3A4CeA840E3A66473E853D21517
# API接口地址，可选，设置 OPENAI_API_KEY 时可用
OPENAI_API_BASE_URL: https://chiangma.com
```

**Comment by Dooy** [comment]
老板 记得打赏

**Comment by AthanaD** [comment]
> 跨域问题，要不 你设置在后端吧
> 
> <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/3765401/337515866-000289c1-0a4a-4ccc-8114-6d04e7a6d1e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzIwMTksIm5iZiI6MTcxNzczMTcxOSwicGF0aCI6Ii8zNzY1NDAxLzMzNzUxNTg2Ni0wMDAyODljMS0wYTRhLTRjY2MtODExNC02ZDA0ZTdhNmQxZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMDM0MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjMzM2JiZTFkNjI2MGJiMDRmZTRjODNmODE5MzBlYWEzZDU4YzUxYWY0NjA0ZTc2ZGZmYmEwN2JiODIwY2VlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4jIoi4NNdUle0iLi_2b3cFVpUpWfTc7YG7W_nQQ3HTI">

我在cloudflare域名里边加了cors规则的，同时在nginx里边也加了cors规则的，还是出错。
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/125889247/cd3c1792-b9c6-485d-a1c3-92bc55c6357f)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/125889247/289175f5-a778-48e9-9a6a-6e3414040d61)

**Comment by AthanaD** [comment]
v那个位置我就是那样设置的，只是截图的时候换成了xxxx.com

**Comment by Dooy** [comment]
测试 出来是跨域问题 
new-api 默认是支持跨域的 不知道你咋设置搞成不能跨域了

**Comment by Dooy** [comment]
你别自己去加头试下

**Comment by Dooy** [comment]
太多余了

<img width="765" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/28c4d416-8e3e-4d4e-889a-7b3093e44338">

**Comment by Dooy** [comment]
没加全 
<img width="533" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/53b3d5ba-ccbd-4121-a931-2be6aec5c467">

**Comment by AthanaD** [comment]
> 没加全 <img alt="image" width="533" src="https://private-user-images.githubusercontent.com/3765401/337519072-53b3d5ba-ccbd-4121-a931-2be6aec5c467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzQxMzEsIm5iZiI6MTcxNzczMzgzMSwicGF0aCI6Ii8zNzY1NDAxLzMzNzUxOTA3Mi01M2IzZDViYS1jY2JkLTQxMjEtYTkzMS0yYmU2YWVjNWM0NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMDQxNzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFhOTZiOThlODFiOWMxNGIzODlhYjI2MWFmYzk5NzI4NTJiNDFmMDgwM2E3ZjI5NmUwZTI0ZGUyMGE0YTMzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FWf3Mmm2QAhr7IOUzyZYS0-tfwMVTTaHXKi_TwiV2_Q">

应该如何加，我看网络教程是这样加的

**Comment by AthanaD** [comment]
已经在大佬指点下解决了，nginx里边的跨域名cors以下内容全部注释即可：
`        # add_header 'Access-Control-Allow-Origin' '*' always;`
