### ISSUE TITLE
上传文件到底该怎么调试，readme里没有写，哪位大佬帮我解答一下， 有偿

### ISSUE THREAD

**Issue by JIANRENWEN** [Dooy/chatgpt-web-midjourney-proxy#399]
我将UPLOAD_TYPE=Container -v D:\chatgpt-web-midjourney-proxy:/app/uploads加入到命令中，现在文件上传之后能在本地问价夹中看见了，但是GPT分析不了，请问我该怎么该
<img width="343" alt="上传" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/107401757/34c0466f-cfed-4a15-b2a9-449226f3902c">

**Comment by JIANRENWEN** [comment]
快来帮帮哥们吧，我再解决不了要被开除了呜呜呜

**Comment by Swordsman007** [comment]
要上传的文件服务器，拿到文件地址，再给到接口传参

**Comment by JIANRENWEN** [comment]
> 要上传的文件服务器，拿到文件地址，再给到接口传参

哥你加我微信呗，我想请您帮我解决一下。wufeishiwo_，这个是我的微信号

**Comment by lyzcodebool** [comment]
> > 要上传的文件服务器，拿到文件地址，再给到接口传参
> 
> 哥你加我微信呗，我想请您帮我解决一下。wufeishiwo_，这个是我的微信号

加我 ycyjgl3 这个我会 快速解决的方法

**Comment by JIANRENWEN** [comment]
> > > 要上传的文件服务器，拿到文件地址，再给到接口传参
> > 
> > 
> > 哥你加我微信呗，我想请您帮我解决一下。wufeishiwo_，这个是我的微信号
> 
> 加我 ycyjgl3 这个我会 快速解决的方法

不好意思，才看到，我加你了
