### ISSUE TITLE
docker部署配置的环境变量无效

### ISSUE THREAD

**Issue by Katou-Kouseki** [Dooy/chatgpt-web-midjourney-proxy#4]
## 问题描述

环境变量：OPENAI_API_KEY、OPENAI_API_BASE_URL、MJ_SERVER，均已配置

但前端配置界面参数为空，此时进行对话只会提示“思考中”，若在前端配置界面手动填写Openai相关参数则有效。但是Midjourney相关参数填写依旧无效，填写后绘图提示“提交中[Failed to fetch]”，若留空则为“[Unexpected token '<', "<!DOCTYPE "... is not valid JSON]”。

### 日志

日志只有这一段内容
```
> chatgpt-web-service@1.0.0 prod /app
> node ./build/index.mjs

Server is running on port 3002
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "mj-api-secret"
    at ClientRequest.setHeader (node:_http_outgoing:655:3)
    at new ClientRequest (node:_http_client:286:14)
    at Object.request (node:http:103:10)
    at /app/node_modules/.pnpm/express-http-proxy@2.0.0/node_modules/express-http-proxy/app/steps/sendProxyRequest.js:13:51
    at new Promise (<anonymous>)
    at sendProxyRequest (/app/node_modules/.pnpm/express-http-proxy@2.0.0/node_modules/express-http-proxy/app/steps/sendProxyRequest.js:11:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Dooy** [comment]
环境变量 是不是没有配置 `MJ_API_SECRET `  ? 随便填一个123上去看看

**Comment by Katou-Kouseki** [comment]
> 环境变量 是不是没有配置 `MJ_API_SECRET ` ? 随便填一个123上去看看

最新版本重新部署了一下proxy设置了个secret，提供外网地址给环境变量绘图成功了。但是环境变量中配置的OPENAI_API_BASE_URL和OPENAI_API_KEY依旧没有效果，前端对话一直处于“思考中...”。前端设置中手动填写配置项后有效。

**Comment by xiaosatai** [comment]
存在相同问题 MJ这边配置了地址和密码 一直显示错误，需要手动在前端设置

**Comment by Dooy** [comment]
> > 环境变量 是不是没有配置 `MJ_API_SECRET ` ? 随便填一个123上去看看
> 
> 最新版本重新部署了一下proxy设置了个secret，提供外网地址给环境变量绘图成功了。但是环境变量中配置的OPENAI_API_BASE_URL和OPENAI_API_KEY依旧没有效果，前端对话一直处于“思考中...”。前端设置中手动填写配置项后有效。

2.12.4 版本已修复
