### ISSUE TITLE
希望每个聊天可以单独配置 `模型` 和 `角色设定`

### ISSUE THREAD

**Issue by yh4922** [Dooy/chatgpt-web-midjourney-proxy#40]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/18353610/a86d7a08-fe5b-4fab-bd87-78f58f9ccc93)
现在每个聊天好像是公用的一个 没办法单独切换

**Comment by Dooy** [comment]
有开发能力，还是自己搞下吧

**Comment by Dooy** [comment]
v2.14.3 已支持
