### ISSUE TITLE
请求新增逆向模型 gpt-4o-all

### ISSUE THREAD

**Issue by flyzy2005** [Dooy/chatgpt-web-midjourney-proxy#400]
尝试自定义模型 gpt-4o-all，但是左下角无法跟 gpt-4-all 一样传文件，传图片会自动切换到 gpt-4-vision-preview：

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/16304483/a2eb7f30-9fac-4158-9ce6-805f107f0b44)

**Comment by Dooy** [comment]
收到 后面新增上来

**Comment by Dooy** [comment]
已经加进来了 请更新至 v2.18.8
