### ISSUE TITLE
请求添加GPTs

### ISSUE THREAD

**Issue by lightningPro** [Dooy/chatgpt-web-midjourney-proxy#401]
GPTs地址为 https://chatgpt.com/g/g-hRCqiqVlM-tutor-me 在个人版本中 GPTs的名称叫做tutor me

**Comment by Dooy** [comment]
可以自行添加啊

<img width="699" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/50118fe8-e370-432e-8af4-6132337d74b0">

**Comment by lightningPro** [comment]
请问这种添加GPTs 能添加到系统吗？还是只能个人使用

**Comment by Dooy** [comment]
添加到 系统内
只要提供 gid ，系统会自己去抓取更新

**Comment by lightningPro** [comment]
请问咱们这个有docker镜像吗？有相关地址吗？

**Comment by Dooy** [comment]
首页 大大的demo 链接？ 还得等人喂养？
