### ISSUE TITLE
tts支持语速控制，音调控制？

### ISSUE THREAD

**Issue by heitaokjcr** [Dooy/chatgpt-web-midjourney-proxy#402]

**Comment by Dooy** [comment]
后续加上

**Comment by Dooy** [comment]
音调 只说话人?
目前 就后面 2个参数没支持
<img width="682" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/35fa803f-66c1-45a4-9a58-68c6c68f2b84">


<img width="684" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/c7683995-b97e-44de-a445-b9e4975da448">

**Comment by heitaokjcr** [comment]
不好意思，那就当我只提到了语速吧（
