### ISSUE TITLE
重绘一直0%，最后超时

### ISSUE THREAD

**Issue by wdqzdd** [Dooy/chatgpt-web-midjourney-proxy#404]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/27991992/4c98454e-0e1d-44b7-9749-870b3dd87b30)

chatgpt-web-midjourney-proxy:2.18.5 
midjourney-proxy:2.6.2

**Comment by Dooy** [comment]
请到  midjourney-proxy 里面看看 是不是超时了
如果是超时就没问题啊
