### ISSUE TITLE
[Feature Request] Add `Continue` button when ChatGPT message length is reached.

### ISSUE THREAD

**Issue by Sarkhad** [Dooy/chatgpt-web-midjourney-proxy#405]
**Given**

When ChatGPT message length is reached Server-Sent Event contains finish_reason='length' instead of null or 'stop'.

```data.detail.choices[0].finish_reason === 'length'```

**Acceptance criteria**
As a user, when ChatGPT response message length is reached, I wish to have clickable "Continue" button to let ChatGPT complete its response.
As a user, I would like to see the continue button in the same place where the 'Stop Responding' one is seen.

**Comment by Sarkhad** [comment]
> ok, You don't see this sign of `data.detail.choices[0].finish_reason === 'length'` all the time.

Yes, I don't. But when the stream ends with finish_reason=length the button should appear.

```
{"id":"chatcmpl-xxx","object":"chat.completion.chunk","created":1718290711,"model":"gpt-4o-2024-05-13","system_fingerprint":"xxx","choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"length"}]}
```

**Comment by Dooy** [comment]
Можете ли вы привести несколько примеров и моделей ключевых слов?

**Comment by Sarkhad** [comment]
> Можете ли вы привести несколько примеров и моделей ключевых слов?

To trigger this behaviour just ask any OpenAI's model to generate an long response. The only difference is the last chunk contains 'length' instead of 'stop'.

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/1319532/33242796-9447-4896-bf04-91581cddf5f7)
P. S. On the screenshot is a bit modified site.

bject":"chat.completion.chunk","created":1718291604,"model":"gpt-4o-2024-05-13","system_fingerprint":"fp_319be4768e","choices":[{"index":0,"delta":{"content":" effort"},"logprobs":null,"finish_reason":null}]} | 19:13:42.230 |  
  | message | {"id":"chatcmpl-9ZgQeD4GtxTkaLBvU8E89lKIOEXic","object":"chat.completion.chunk","created":1718291604,"model":"gpt-4o-2024-05-13","system_fingerprint":"fp_319be4768e","choices":[{"index":0,"delta":{"content":"."},"logprobs":null,"finish_reason":null}]} | 19:13:42.230 |  
  | message | {"id":"chatcmpl-9ZgQeD4GtxTkaLBvU8E89lKIOEXic","object":"chat.completion.chunk","created":1718291604,"model":"gpt-4o-2024-05-13","system_fingerprint":"fp_319be4768e","choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"length"}]} | 19:13:42.230

**Comment by Dooy** [comment]
ok
