### ISSUE TITLE
在“思考中...."的时候，切换到另一个session，再次切回来之后，不再能收到输出

### ISSUE THREAD

**Issue by kent0113** [Dooy/chatgpt-web-midjourney-proxy#406]
版本：2.18.5

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3895149/03876563-25d5-43b4-bc7e-8c2667a9c77a)

**Comment by Dooy** [comment]
这不正常么？ 你还想切换？

**Comment by kent0113** [comment]
能切换肯定更好。
使用chatgpt和Kimi切换会话也还是可以正常使用的
