### ISSUE TITLE
MJ - 局部重绘 - 远程调用的 ifram 不能用了

### ISSUE THREAD

**Issue by xuewlcn** [Dooy/chatgpt-web-midjourney-proxy#409]
局部重绘好像是远程加载的

https://static.aitutu.cc/res/mitf/index.html?instance_id=1&custom_id=2&channel_id=3&guild_id=4&frame_id=5&platform=desktop&prompt=%E6%8F%90%E4%BA%A4%E6%88%90%E5%8A%9F%EF%BC%81&img_type=png&img_info=%7B%22image_url%22%3A%22%22%2C%22prompt%22%3A%22sunglasses%22%7D

这个网址直接打开没问题，但是在程序里 ifram 好像对方加了 403 限制了

**Comment by Dooy** [comment]
[src/static/mitf](https://github.com/Dooy/chatgpt-web-midjourney-proxy/tree/cb7a097497b7ea8a1a6c0ba76731333172befcf2/src/static/mitf)

你也可以自己搭建

**Comment by xuewlcn** [comment]
单独复制出来后反代么，还是可以通过什么选项来设置前台点按钮时的链接

**Comment by xuewlcn** [comment]
https://static.aitutu.cc 原来的这个域名是在哪里定义或者修改的

**Comment by xuewlcn** [comment]
<iframe @load="loadOk" ref="ifdiv" :src="`https://static.aitutu.cc/res/mitf/index.html?${st.q}`"  class=" h-[80vh] w-full" style="border-width: 0px; border-style: none; overflow: hidden;" v-if="st.q"></iframe>

好像这个被写死了

**Comment by xuewlcn** [comment]
@Dooy 上面这个能不能发个新版，支持个自定义配置 URL 部分

**Comment by Dooy** [comment]
我查了 下 这个 地址是可用的
只是你的 st.q 带有特殊符号 导致403的

需要 我编译搞一个变量出来？

**Comment by xuewlcn** [comment]
我的默认的 docker 部署，没有做任何变动，不知道为什么会有 st.q 这样的。
如果在环境变量里配置一个网站，然后单独配置那个html页面，就更稳定了。

**Comment by Dooy** [comment]
那我关闭了
