### ISSUE TITLE
如何在service层添加接口出错后，自动换模型在尝试（有时候中转通道故障，不希望用户端出现错误），如何修改？

### ISSUE THREAD

**Issue by ChuckZengxf** [Dooy/chatgpt-web-midjourney-proxy#411]
如何在service层添加接口出错后，自动换模型在尝试（有时候中转通道故障，不希望用户端出现错误），如何修改？

**Comment by ChuckZengxf** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/86394244/d0a04917-9832-4313-8571-57e22610bc26)

**Comment by Dooy** [comment]
最好在中转的 地方修改

**Comment by ChuckZengxf** [comment]
每次修改中转地址还要重启服务。比较麻烦不能及时修改啊。有什么好的方案吗？
