### ISSUE TITLE
无法通过?settings={"key":"{key}","url":"{server}"}设置Suno和Luma

### ISSUE THREAD

**Issue by rdself** [Dooy/chatgpt-web-midjourney-proxy#412]
当前通过URL只能配置OpenAI和Midjourney，希望能加入对Suno和Luma的支持，感谢！

**Comment by Dooy** [comment]
后续 完善下

**Comment by Dooy** [comment]
Luma 我文档都还没完善 你们都支持了？

**Comment by ChuckZengxf** [comment]
有没有Suno和Luma的中转地址？

**Comment by xianyu110** [comment]
> 有没有Suno和Luma的中转地址？

https://api.maynor1024.live/

**Comment by spammenotinoz** [comment]
> > 有没有Suno和Luma的中转地址？
> 
> https://api.maynor1024.live/

Thanks, can you validate the pricing please, seems expensive but I must be calculating wrong.

0.45￥ for 1 x Fast Image
(Dialogue (0.25￥) + Fast Image Gen (0.20￥) = 45￥ Image

I typically pay around 0.20￥ per fast image

**Comment by Dooy** [comment]
https://www.openai-hk.com 也支持了

对接文档
https://www.openai-hk.com/docs/lab/luma-video.html

**Comment by spammenotinoz** [comment]
> https://www.openai-hk.com 也支持了
> 
> 对接文档 https://www.openai-hk.com/docs/lab/luma-video.html

Thanks openai-hk works really well for Luma, for some reasons Midjourney images generate quickly, buy take forever to download though.  Like the old days watching a picture download on a dial-up modem, might try it again another day.
Any plans fpr openai-hk to support FaceSwap?

**Comment by Dooy** [comment]
请更新到 `v2.18.8` 已修复
