### ISSUE TITLE
如何屏蔽一些不常用的模型

### ISSUE THREAD

**Issue by lvzhaoxing** [Dooy/chatgpt-web-midjourney-proxy#413]
如图模型选择框，想要屏蔽一些不常用的模型。

<img width="667" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/7759809/c306dc12-16aa-4590-a3a5-f8f6c28a63df">

**Comment by ChuckZengxf** [comment]
注释掉不就行了 
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/86394244/52ced831-1502-4127-b8a4-0fefebbb4793)

**Comment by Dooy** [comment]
看下readme 都能指定有 有一个 -all

**Comment by Dooy** [comment]
> 注释掉不就行了 ![image](https://private-user-images.githubusercontent.com/86394244/341308578-52ced831-1502-4127-b8a4-0fefebbb4793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Njc3MjUsIm5iZiI6MTcxODg2NzQyNSwicGF0aCI6Ii84NjM5NDI0NC8zNDEzMDg1NzgtNTJjZWQ4MzEtMTUwMi00MTI3LWI4YTQtMGZlZmViYmI0NzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjlmMDgyNzBkN2NjZWYyYWY1OWNhNTY3NDg0YmNhNWUwYzFjNTQwMWJlZWFhMGQ2YTZkN2RlYTg1NWFmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GexrMHvSiRZvo-Y2jpK6evWS5U1Cjlzetkct_GKg0ss)

很多人都没代码能力，能配置环境变量

**Comment by ChuckZengxf** [comment]
> > 注释掉不就行了 ![image](https://private-user-images.githubusercontent.com/86394244/341308578-52ced831-1502-4127-b8a4-0fefebbb4793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Njc3MjUsIm5iZiI6MTcxODg2NzQyNSwicGF0aCI6Ii84NjM5NDI0NC8zNDEzMDg1NzgtNTJjZWQ4MzEtMTUwMi00MTI3LWI4YTQtMGZlZmViYmI0NzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjlmMDgyNzBkN2NjZWYyYWY1OWNhNTY3NDg0YmNhNWUwYzFjNTQwMWJlZWFhMGQ2YTZkN2RlYTg1NWFmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GexrMHvSiRZvo-Y2jpK6evWS5U1Cjlzetkct_GKg0ss)
> 
> 很多人都没代码能力，能配置环境变量

有没有Suno和Luma的中转地址？ 你是怎么测试的，我使用的中转都不行估计返回的类型不对

**Comment by lvzhaoxing** [comment]
用docker方式，没怎么看过代码， @Dooy env里面好像没看到 -all 这个值

**Comment by lvzhaoxing** [comment]
找到了，CUSTOM_MODELS=-all，谢谢

**Comment by Dooy** [comment]
> > > 注释掉不就行了 ![image](https://private-user-images.githubusercontent.com/86394244/341308578-52ced831-1502-4127-b8a4-0fefebbb4793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Njc3MjUsIm5iZiI6MTcxODg2NzQyNSwicGF0aCI6Ii84NjM5NDI0NC8zNDEzMDg1NzgtNTJjZWQ4MzEtMTUwMi00MTI3LWI4YTQtMGZlZmViYmI0NzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjlmMDgyNzBkN2NjZWYyYWY1OWNhNTY3NDg0YmNhNWUwYzFjNTQwMWJlZWFhMGQ2YTZkN2RlYTg1NWFmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GexrMHvSiRZvo-Y2jpK6evWS5U1Cjlzetkct_GKg0ss)
> > 
> > 
> > 很多人都没代码能力，能配置环境变量
> 
> 有没有Suno和Luma的中转地址？ 你是怎么测试的，我使用的中转都不行估计返回的类型不对



> > > 注释掉不就行了 ![image](https://private-user-images.githubusercontent.com/86394244/341308578-52ced831-1502-4127-b8a4-0fefebbb4793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Njc3MjUsIm5iZiI6MTcxODg2NzQyNSwicGF0aCI6Ii84NjM5NDI0NC8zNDEzMDg1NzgtNTJjZWQ4MzEtMTUwMi00MTI3LWI4YTQtMGZlZmViYmI0NzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjlmMDgyNzBkN2NjZWYyYWY1OWNhNTY3NDg0YmNhNWUwYzFjNTQwMWJlZWFhMGQ2YTZkN2RlYTg1NWFmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GexrMHvSiRZvo-Y2jpK6evWS5U1Cjlzetkct_GKg0ss)
> > 
> > 
> > 很多人都没代码能力，能配置环境变量
> 
> 有没有Suno和Luma的中转地址？ 你是怎么测试的，我使用的中转都不行估计返回的类型不对

www.openai-hk.com
suno luma 都能行 ，可能luma并发不足
