### ISSUE TITLE
可以正常对话 生成视频报错

### ISSUE THREAD

**Issue by zyjfly** [Dooy/chatgpt-web-midjourney-proxy#418]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/7d532dcc-b473-479a-beeb-9edf39efa203)
这个key没有地方输入 我查了网站的key支持luma 需要在哪里设置呢
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/d9f1e8de-0fdd-48a4-bea5-cdab5e0319fd)

**Comment by Dooy** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/51a7cdad-1d18-44a9-a84e-c92a23a70237)

**Comment by Dooy** [comment]
如果 设置里面 没这个 "服务端"，可以询问下 中转客服

**Comment by spammenotinoz** [comment]
Ensure GPT-4 is not disabled.
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/29272432/d379aa3b-d647-4533-9fff-99c986b547c8)

**Comment by zyjfly** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/b1f736f5-a383-467a-8f4c-f646b7d44470)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/e946b029-9c4a-4d1e-b9ec-55f4866af957)
好的 我问问中转客服

**Comment by zyjfly** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/959e9b0e-37d3-41fa-bda6-fb5b85324bd6)
这这里面是不是要加什么内容呀 我下载的桌面端是有这个服务端配置的 只有网页端没有
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/1e6d8c4e-51b7-41e2-a220-7f53092c13e5)

**Comment by Dooy** [comment]
把这行去掉 就有了
<img width="447" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/1c114ca8-8a62-489a-b433-5112ece32951">

**Comment by zyjfly** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/96605090/e8d46318-1a67-458e-ae18-1fa221b52495)
生成了十多分钟都没有生成出来 是不是哪里有问题呀

**Comment by Dooy** [comment]
现在  应该是 relax版本的得排队

**Comment by Dooy** [comment]
不想等了 关闭后 再次单开 可以重新获取
