### ISSUE TITLE
增加Cloudflare部署选项

### ISSUE THREAD

**Issue by RogerProSelf** [Dooy/chatgpt-web-midjourney-proxy#419]
希望能考虑增加Cloudflare Pages部署教程（目前部署的话会出现无法构建的问题），Vercel在江苏移动的环境下有时候会出现奇奇怪怪的访问问题，只能挂代理。Cloudflare虽然也有被墙的IP，但是有大量优选CDN IP的工具，优化后反而体验是最好的。

感谢！

**Comment by Dooy** [comment]
能否 PR上来 我对 `Cloudflare Pages` 不熟悉
