### ISSUE TITLE
tts

### ISSUE THREAD

**Issue by zyyint** [Dooy/chatgpt-web-midjourney-proxy#42]
是复读机，
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/818c2d12-9b2c-4da9-bcff-575aa0b320d3)

**Comment by Dooy** [comment]
循环播放 还是啥意思？

**Comment by zyyint** [comment]
他说的话是我发的文字

**Comment by zyyint** [comment]
不知道是不是还是我开cdn的问题，大佬测试一下看看是不是复读机

**Comment by Dooy** [comment]
tts 就是将你的文字转语音啊 没毛病啊 仅作为demo

**Comment by zyyint** [comment]
哈哈哈，好吧没理解过来，我以为是对话，tts是合成还有一个是whisper-1

**Comment by Dooy** [comment]
whisper-1 是语音转文字 也支持的

你拖一个mp3 进输入框；会帮你转文字

**Comment by zyyint** [comment]
好

**Comment by zyyint** [comment]
音色可以换不

**Comment by Dooy** [comment]
把tts-1-hd 就变了
如果人物 选择 目前没支持
