### ISSUE TITLE
【BUG】登录密码在前端明文发送

### ISSUE THREAD

**Issue by osbi-code** [Dooy/chatgpt-web-midjourney-proxy#420]
这个软件很好用，感谢作者的辛苦工作

经过调查，发现网页登录密码，以明文的形式加在请求头上在前端发送了(imagine接口，请求标头：X-Ptoken，其它接口应该也是)

当用户部署的环境不太确定时（如非https)，明文请求标头发送密码可能有不安全的因素

请作者核实修复，谢谢

**Comment by Dooy** [comment]
前端害得 带一个 md5 ?

我看看 能集成记录否
