### ISSUE TITLE
NGINX Help for SREF\CREF uploads

### ISSUE THREAD

**Issue by spammenotinoz** [Dooy/chatgpt-web-midjourney-proxy#421]
Looking for some help from the author to team please.
Everything works great except SREF\CREF uploads for Midjourney fail with a 404 error when locally hosted.  Vercel is fine.
NGINX error;
"POST /mjapi/mj/submit/upload-discord-images HTTP/2.0" 404 181

Any suggestions?  I would use vercel except the uploads for Base\Blend ect.. generally fail due to the small upload size but work when locally hosted.

Thank-you

**Comment by Dooy** [comment]
Vercel 不支持吧？

**Comment by spammenotinoz** [comment]
> Vercel doesn't support it, right?

Works fine in Vercel, except I am restricted by the size of the image.
Thanks for the reply worked out what it was, it is an issue with the open source mid journey proxy (which I used locally).
When testing in vercel I used "https://api.openai-hk.com/relax" this endpoint supports uploads.  openai-hk is just slow for me in Australia.  Not the image create, but the download after the create, it's like the old dial-up days.

Excellent project, let me close the issue.

**Comment by spammenotinoz** [comment]
@Dooy fixed the speed issue with https://api.openai-hk.com added a find\replace in nginx.
        sub_filter 'mjimg.open-hk.com' 'cdn.discordapp.com';
        sub_filter_types application/json;
        sub_filter_once off;

**Comment by Dooy** [comment]
中国大陆是被封掉了 cdn.discordapp.com
其实 mjimg.open-hk.com 就是代理 cdn.discordapp.com 而已

老哥真不是中国大陆的？

**Comment by spammenotinoz** [comment]
No Australia, which reminds me it's time for a nap here, almost midnight.
