### ISSUE TITLE
2.18.8重新打包镜像失败，node、npm、yarn、pnpm版本有限制吗？

### ISSUE THREAD

**Issue by andyliu91** [Dooy/chatgpt-web-midjourney-proxy#422]
npm设置为国内阿里云源，node、npm、yarn、pnpm版本有限制吗？
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48175431/b6dfffb3-aeff-47fe-9415-edaf1bb3635c)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48175431/4b8607da-fca0-46e9-aa0e-049a246c74fd)

**Comment by Dooy** [comment]
这个 咋办？用梯子吧

**Comment by andyliu91** [comment]
我换国外服务器试试

**Comment by andyliu91** [comment]
国外主机使用2.18.9打包镜像也失败，node、npm、pnpm也都安装了，报错找不到/app/dist，Dockerfile添加调试信息以确认 /app/dist 目录是否存在，也是报错/app/dist: No such file or directory，是什么原因呀
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48175431/e4341392-f3b6-4606-8ebc-07c6ad4894f0)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48175431/99fe80be-8997-462c-b639-d100cf133401)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48175431/c4a98ad0-03c7-4eae-a178-47cf099e4428)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48175431/4ee38027-6460-4373-8e53-ff841be425c4)

**Comment by Dooy** [comment]
本地 看看 pnpm run build 看看能跑 起来否？

应该没问题 我打包都用 github的 workflow 来打包的

**Comment by Dooy** [comment]
这人 能看到 https://github.com/Dooy/chatgpt-web-midjourney-proxy/actions 流程

流程代码 这儿

https://github.com/Dooy/chatgpt-web-midjourney-proxy/blob/main/.github/workflows/docker-image.yml

**Comment by andyliu91** [comment]
是不是少个空格
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/48175431/d7d9b044-1062-4480-8dac-04752a8f99c5)

**Comment by Dooy** [comment]
先 pnpm install 下
