### ISSUE TITLE
视频按钮提示词，有个小错别字。

### ISSUE THREAD

**Issue by 2guan** [Dooy/chatgpt-web-midjourney-proxy#424]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/59775321/73b93531-aaab-44db-94c8-f6dfa4c86100)

Luma

**Comment by NeverOccurs** [comment]
啥时候支持LUMA PRO？

**Comment by Dooy** [comment]
s

> ![image](https://private-user-images.githubusercontent.com/59775321/342979113-73b93531-aaab-44db-94c8-f6dfa4c86100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzQ2NDEsIm5iZiI6MTcxOTM3NDM0MSwicGF0aCI6Ii81OTc3NTMyMS8zNDI5NzkxMTMtNzNiOTM1MzEtYWFhYi00NGRiLTk0YzgtZjZkZmE0Yzg2MTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAzNTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMzM2NzRkOGVjMzkwNzUzNDYxOGM2MzQ3MDQ1MjBiNWY3MWQ0NTc4OWIzZGY4MGE5YzFmNTU0NDliMWMxZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mvdix7znuSYmI1foICFtVebNami9Nh8m5kunfnUn4K4)
> 
> Luma

收到

**Comment by Dooy** [comment]
> 啥时候支持LUMA PRO？

今儿 已经上线了 可以看下 文档

**Comment by NeverOccurs** [comment]
> > 啥时候支持LUMA PRO？
> 
> 今儿 已经上线了 可以看下 文档

UI啥时候更新？

**Comment by Dooy** [comment]
UI 更新啥？
是否pro版本 不就是是否有水印 是否需要排队么？

这些都是 你用账号去区别

**Comment by NeverOccurs** [comment]
> UI 更新啥？ 是否pro版本 不就是是否有水印 是否需要排队么？
> 
> 这些都是 你用账号去区别

哦哦我傻了没仔细看 设置里接口后面加个pro就行了
