### ISSUE TITLE
3.5sonnet模型 上传图片识别，404，最新的版本测试使用

### ISSUE THREAD

**Issue by Tansuo2021** [Dooy/chatgpt-web-midjourney-proxy#427]
image
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/95366753/0050efbe-7233-4af4-82e9-6e10cacc44b9)
上传图片直接404 最新的版本使用3.5sonnet模型，只有gpt4o能base64解析，3.5sonnet模型不行

**Comment by Dooy** [comment]
我好像 都是用 base64 这个模型

**Comment by vxsqablpz** [comment]
我这边用了您的网站也是跟上面同样的问题
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/162132979/af075d46-2efd-46a5-b0bd-b36f1f9ca894)

**Comment by Dooy** [comment]
请更新至 `v2.18.10` 版本
