### ISSUE TITLE
打字机效果

### ISSUE THREAD

**Issue by zyyint** [Dooy/chatgpt-web-midjourney-proxy#43]
新版本貌似回复响应速度更快，而打字机效果有所下降，嗖的一下就全部出来了，望优化

**Comment by zyyint** [comment]
自查原因是cdn导致缓存

**Comment by jaydong2016** [comment]
> 自查原因是cdn导致缓存

我部署在 vercel 的没有流式输出，也就是打字机效果。在设置里输入 key 就有

**Comment by Dooy** [comment]
是不是 前面还套了 NGINX？ 如果 直接是 vercel是没问题的

**Comment by jaydong2016** [comment]
> 是不是 前面还套了 NGINX？ 如果 直接是 vercel是没问题的
我直接用 vercel 自带网址打开的，没有打字机效果，还有其他的小问题，经常生成 报错

**Comment by jaydong2016** [comment]
我直接用 vercel 自带网址打开的，没有打字机效果，还有其他的小问题，经常生成 报错
