### ISSUE TITLE
claude-3-5-sonnet-20240620模型上传图片不是base64，用大佬的官方网站同复现 Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by vxsqablpz** [Dooy/chatgpt-web-midjourney-proxy#430]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/162132979/838c6b35-ee96-439d-9e61-548b1ea1f679)

**Comment by Dooy** [comment]
后面 我好好看下 他们 支持的格式吧 是不是 只支持url

**Comment by vxsqablpz** [comment]
支持base64，不用特地URL

**Comment by Dooy** [comment]
原来是 base64的 后面修上传了 我改回来试下

**Comment by Dooy** [comment]
支持 base64了 好像没问题了
现在 https://vercel.ddaiai.com 试下 稍后我更新版本
<img width="1157" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/1563d747-0595-48bf-ace9-8bc95fb39c36">

**Comment by spammenotinoz** [comment]
Unsure if it's related but the Anthropic has been overloaded for the last 20 hours, high error rates.
Not related to this project.

**Comment by vxsqablpz** [comment]
感谢大佬的修改，测试正常，太酷了

**Comment by vxsqablpz** [comment]
> 支持 base64了 好像没问题了 现在 https://vercel.ddaiai.com 试下 稍后我更新版本 <img alt="image" width="1157" src="https://private-user-images.githubusercontent.com/3765401/344116552-1563d747-0595-48bf-ace9-8bc95fb39c36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MjIzMDAsIm5iZiI6MTcxOTYyMjAwMCwicGF0aCI6Ii8zNzY1NDAxLzM0NDExNjU1Mi0xNTYzZDc0Ny0wNTk1LTQ4YmYtYWNlOS04YmM5NWZiMzljMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMDA0NjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdmNjVjZGMyOWE5M2Y0NTAxM2RhMGQ0ZGU4NWJkZjY1MzE4ODA3Yjk1ZTA4YzBmMGNhY2JkNTA0NWU0ZGVlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hCoqXp2b2djg0Plc0d4GzmrcYYUf3HFXH5aWHbQmZrg">

现在能更新网站了吗？直接可以更新食用不

**Comment by Dooy** [comment]
请更新至 `v2.18.10` 版本
