### ISSUE TITLE
LUMA不支持竖屏9:16  这个对于短视频 不友好 官方是支持的

### ISSUE THREAD

**Issue by weidiguo** [Dooy/chatgpt-web-midjourney-proxy#431]
LUMA不支持竖屏9:16  这个对于短视频 不友好 官方是支持的

**Comment by weidiguo** [comment]
谢谢啦

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月28日 16:14 |
| 收件人 | Dooy/chatgpt-web-midjourney-proxy ***@***.***> |
| 抄送人 | weidiguo ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Dooy/chatgpt-web-midjourney-proxy] LUMA不支持竖屏9:16 这个对于短视频 不友好 官方是支持的 (Issue #431) |

接口是支持的 要不我把 这个选项做出来

**Comment by NeverOccurs** [comment]
> 接口是支持的 要不我把 这个选项做出来

现在貌似也支持首尾帧上传，一起更新一下？感谢

**Comment by weidiguo** [comment]
对的 我也想说

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月30日 11:44 |
| 收件人 | Dooy/chatgpt-web-midjourney-proxy ***@***.***> |
| 抄送人 | weidiguo ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Dooy/chatgpt-web-midjourney-proxy] LUMA不支持竖屏9:16 这个对于短视频 不友好 官方是支持的 (Issue #431) |

接口是支持的 要不我把 这个选项做出来

现在貌似也支持首尾帧上传，一起更新一下？感谢

**Comment by Dooy** [comment]
> > 接口是支持的 要不我把 这个选项做出来
> 
> 现在貌似也支持首尾帧上传，一起更新一下？感谢

正在搞，不过现在 的难点是 首尾帧的截取 搞了几天都 没搞出来

**Comment by NeverOccurs** [comment]
> > > 接口是支持的 要不我把 这个选项做出来
> > 
> > 
> > 现在貌似也支持首尾帧上传，一起更新一下？感谢
> 
> 正在搞，不过现在 的难点是 首尾帧的截取 搞了几天都 没搞出来

不是只需要上传两张图片就可以了嘛

**Comment by weidiguo** [comment]
辛苦了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月30日 14:21 |
| 收件人 | Dooy/chatgpt-web-midjourney-proxy ***@***.***> |
| 抄送人 | weidiguo ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Dooy/chatgpt-web-midjourney-proxy] LUMA不支持竖屏9:16 这个对于短视频 不友好 官方是支持的 (Issue #431) |

接口是支持的 要不我把 这个选项做出来

现在貌似也支持首尾帧上传，一起更新一下？感谢

正在搞，不过现在 的难点是 首尾帧的截取 搞了几天都 没搞出来

不是只需要上传两张图片就可以了嘛

**Comment by weidiguo** [comment]
看到更新了 感谢

**Comment by Dooy** [comment]
请大家更新到 `v2.18.10`
