### ISSUE TITLE
我用了阿里云服务器创建实例，最终导致服务器被停用。现在已经申请解除停用，有没有什么方法安全使用？

### ISSUE THREAD

**Issue by sanzi8** [Dooy/chatgpt-web-midjourney-proxy#432]
剛解封，改一下前端會有效嗎？

**Comment by Dooy** [comment]
阿里云 香港？

**Comment by Dooy** [comment]
推荐这up主的方法 试一试

【2023最新-ChatGPT-4 Turbo网站搭建保姆级全流程教程-GPT4免费使用方法-智能AI-OpenAI-安装超简单，无保留全分享，100%能搭建成功】 https://www.bilibili.com/video/BV1qa4y1U76i/?share_source=copy_web&vd_source=1bd7f4d3355119431570702505fb896b
