### ISSUE TITLE
其实cluade其他模型也是支持识图

### ISSUE THREAD

**Issue by vxsqablpz** [Dooy/chatgpt-web-midjourney-proxy#433]
其实cluade其他模型也是支持识图，大佬，如题，可以考虑兼容一下，如果有空的话！谢谢！

**Comment by Dooy** [comment]
请更新到 `v2.18.10`

**Comment by baojingyu** [comment]
@Dooy 请问使用claude3 模型,除了通过one-api中转,还有什么方式,chatgpt-web-midjourney-proxy如何配置claude3,配置文档未见到相关配置.

**Comment by Dooy** [comment]
目前 只能通过 one-api 中转

专业的活专业人来干

**Comment by baojingyu** [comment]
> 目前 只能通过 one-api 中转
> 
> 专业的活专业人来干

👌
