### ISSUE TITLE
不允许ip调用

### ISSUE THREAD

**Issue by nickbears** [Dooy/chatgpt-web-midjourney-proxy#436]
演示站最新版不允许ip+端口调用
![微信截图_20240630131545](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/110611675/bf6d7fbc-56a5-4103-a584-7baa1cf2c0c1)
![微信截图_20240630131602](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/110611675/a2b8072e-067e-4a2b-b57e-8e42893f0c20)

**Comment by Dooy** [comment]
中转的问题

**Comment by Dooy** [comment]
ip 支持不了 ui服务端 因为需要 跨域
