### ISSUE TITLE
默认的模型列表很长，很多都用不到，可以增加删除默认模型的环境变量吗

### ISSUE THREAD

**Issue by CHEN1016** [Dooy/chatgpt-web-midjourney-proxy#437]
自己部署了后端服务，很多模型都是自定义，所以默认的模型列表都用不到，但是在选择的时候都会展示，这样选择模型很麻烦，可以增加删除默认模型的环境变量吗

**Comment by Dooy** [comment]
看西下 readme 有个 -all

**Comment by CHEN1016** [comment]
中英readme中我好像都没找到这个

**Comment by Dooy** [comment]
<img width="893" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/6eee9679-4fff-40cd-9baa-e46d33c99311">
