### ISSUE TITLE
Safari下无法显示网站icon

### ISSUE THREAD

**Issue by RogerProSelf** [Dooy/chatgpt-web-midjourney-proxy#438]
![截屏2024-07-01 00 25 06](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/55005611/e2d1cf8f-96a6-4584-a99b-e2f4ed21833a)

小bug，情况如图所示，经过测试，iOS端和macOS端Safari都不能正常的显示网站icon，但是macOS上用Edge就可以正常显示。

**Comment by Dooy** [comment]
我们icon 这么不正式啊
