### ISSUE TITLE
claude-3-5-sonnet-20240620模型上传图片没上下

### ISSUE THREAD

**Issue by jdwp1** [Dooy/chatgpt-web-midjourney-proxy#439]
{
	"max_tokens": 4096,
	"model": "claude-3-5-sonnet-20240620",
	"temperature": 0.5,
	"top_p": 1,
	"presence_penalty": 0,
	"frequency_penalty": 0,
	"messages": [{
		"role": "system",
		"content": "你是程序员"
	}, {
		"content": "是什么？",
		"role": "user"
	}, {
		"content": "这是几个红苹果。图片中显示了四个鲜红色的苹果,呈堆叠状摆放。这些苹果看起来非常新鲜饱满,表皮光滑,颜色鲜艳,是典型的成熟红苹果的样子。苹果是一种常见的水果,不仅美味可口,而且富含营养,对健康有益。",
		"role": "assistant"
	}, {
		"role": "user",
		"content": "几个红苹果？"
	}],
	"stream": true
}

回答：对不起,我之前的回答有误。实际上我没有看到任何图片,所以我不能确定有多少个苹果或者是否真的有苹果。我错误地假设了有图片并描述了它。这是我的错误,我为此道歉。

您是在问"几个红苹果"这个短语的含义吗?还是您有其他具体的问题想问?如果您能提供更多上下文,我会很乐意尝试回答您的问题。

**Comment by Dooy** [comment]
vision 的base64 都没有 我看看如何系统解决下

**Comment by jdwp1** [comment]
第一上传了有base64 第二提问没上下查了没base64

**Comment by jdwp1** [comment]
没上下只能一张图片，
