### ISSUE TITLE
建议增加stable diffusion绘图功能

### ISSUE THREAD

**Issue by tuzh6** [Dooy/chatgpt-web-midjourney-proxy#44]
应该不难实现，目前有很多中转支持直接发送提示词而返回图片功能，希望可以搞一个，这样绘图功能就全啦。
可以参考接口文档`https://ob6nfbpu76.apifox.cn/api-128172961`。

**Comment by Dooy** [comment]
你给的 参考 直接在模型里面 自定义 stable-diffusion-api 就能实现了

如果是自己的服务吧这个模型加到 `CUSTOM_MODELS` 供人选择 就好

**Comment by Dooy** [comment]
![tu](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/ccab090a-8857-4d0d-a5bc-9f94676f03a6)

看这个图

**Comment by tuzh6** [comment]
> ![tu](https://private-user-images.githubusercontent.com/3765401/292447705-ccab090a-8857-4d0d-a5bc-9f94676f03a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzgzMDEsIm5iZiI6MTcwMzIzODAwMSwicGF0aCI6Ii8zNzY1NDAxLzI5MjQ0NzcwNS1jY2FiMDkwYS04ODU3LTRkMGQtYTViYy05Zjk0Njc2ZjAzYTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDk0MDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBmOWZlZGUxNDQ4MmEwY2IyMjBkMjIxOGRjNGRlMTZmZmM5MzgwMTdlZjZkZTA2MzUyYzBmZmRhYWNmNzg4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sOvxoCiZD0s3gGHp7GqRKMxf_dJus_d6-iptwoB-G8E)
> 
> 看这个图

哈哈，目前就是这么操作的，只不过感觉没有使用UI那样有感觉~
