### ISSUE TITLE
求一个本地不用docker部署教程。

### ISSUE THREAD

**Issue by 1825679767** [Dooy/chatgpt-web-midjourney-proxy#440]
求一个本地不用docker部署教程。

**Comment by Dooy** [comment]
直接下载 客户端啊

https://github.com/Dooy/chatgpt-web-midjourney-proxy/releases

**Comment by 1825679767** [comment]
客户端不支持远程，想要在服务器不使用docker搭建，然后其他电脑能远程访问

**Comment by Dooy** [comment]
docker 都难，编译更难了
