### ISSUE TITLE
自己的多模态大模型API如何接入这个前端？

### ISSUE THREAD

**Issue by ErfeiCui** [Dooy/chatgpt-web-midjourney-proxy#441]
自己部署了一个多模态大模型API，但是不懂前端，不知道需要改哪些地方以及接口如何设置，感谢回复

**Comment by Dooy** [comment]
用Docker 部署，多看看readme的环境变量

**Comment by ErfeiCui** [comment]
我本地部署好这个docker了，但是我用API的时候会报错 
{
  "message": "fetch error, pleace check url",
  "url": "http://***.***.**:**/v1/chat/completions",
  "code": "fetch_error"
}

**Comment by Dooy** [comment]
docker run --name chatgpt-web-midjourney-proxy  -d -p 6015:3002 \
-e OPENAI_API_KEY=sk-xxxxx \
-e OPENAI_API_BASE_URL=https://api.openai.com  \
 ydlhero/chatgpt-web-midjourney-proxy
