### ISSUE TITLE
建议mj的图生文功能同时返回已经上传图片的url

### ISSUE THREAD

**Issue by Hazukiaoi** [Dooy/chatgpt-web-midjourney-proxy#442]
没有文件图床的情况下，mj用户可以选择提交图生文。然后会得到一张上传之后的图片。再使用这张图的url进行风格一致化生成。
当前版本的是将这张图片直接转换成了base64，导致了这个方法无法使用。
所以希望可以同时显示原图的URL，更便于使用

**Comment by Dooy** [comment]
请到 mj-proxy  那边提 issue
