### ISSUE TITLE
Luma下载按钮无法下载？

### ISSUE THREAD

**Issue by MoZhuXuanKe** [Dooy/chatgpt-web-midjourney-proxy#443]
<img width="305" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/16641348/9caeb22d-31a0-4569-b2ea-26163a352a91">
点击下载按钮后没有任何反应，是我的API问题还是下载按钮问题？
别人有遇到么？

**Comment by Dooy** [comment]
能否 用f12 看下 是否有啥问题

**Comment by MoZhuXuanKe** [comment]
我是mac 的客户端上，“下载”没反应，不能下载.
网页上的“...”按钮中的下载可以下载；"下载"按钮点击也是没有反应，不能下载。
<img width="1205" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/16641348/70f86cdd-4c7f-41f2-b6d8-1d0432b90fec">

**Comment by Dooy** [comment]
客户端不行啊？
我想想如何 兼容下 客户端

**Comment by Dooy** [comment]
感谢反馈

**Comment by MoZhuXuanKe** [comment]
不客气呀，感谢你做出这么好用的开源项目👍支持你，有开通打赏嘛，支持下发自我的 iPhone在 2024年7月3日，21:13，Dooy ***@***.***> 写道：﻿
感谢反馈

**Comment by Dooy** [comment]
更新至 `v2.19.1` 看看

**Comment by MoZhuXuanKe** [comment]
已经可以了👍
