### ISSUE TITLE
阿里云部署，midjourney 可以出图，但是局部重绘编辑页面显示“403 Forbidden”

### ISSUE THREAD

**Issue by Lovingbio** [Dooy/chatgpt-web-midjourney-proxy#444]

**Comment by Lovingbio** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/59022828/a1b21f76-5d3e-423a-8930-bfe34de2270e)

**Comment by Dooy** [comment]
多试几次看看 用不同的提示词
