### ISSUE TITLE
luma 支持首尾帧吗

### ISSUE THREAD

**Issue by xianyu110** [Dooy/chatgpt-web-midjourney-proxy#445]
![Screenshot_2024-07-07-06-37-34-993_com microsoft emmx-edit](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/53889513/467016c1-ec41-45cd-bb77-5030150efbb8)
在上面没看到首尾帧功能

**Comment by xianyu110** [comment]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/53889513/a38c3152-a2f2-4622-9a1d-4df5a1419318)
viggle目前有api支持了吗

**Comment by Dooy** [comment]
> ![image](https://private-user-images.githubusercontent.com/53889513/346340473-a38c3152-a2f2-4622-9a1d-4df5a1419318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzOTgyNjksIm5iZiI6MTcyMDM5Nzk2OSwicGF0aCI6Ii81Mzg4OTUxMy8zNDYzNDA0NzMtYTM4YzMxNTItYTJmMi00NjIyLTlhMWQtNGRmNWExNDE5MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAwMTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMWNmODI5YTQ5MTU2MjM4NTMxMmUxY2JhNTUyNzM3ZjVkMzhhZWZhZDIxM2MzZTdlMGE2ZDEwNTk0MTY2OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gfekSFNH8avzul4g9FMaQtKMh2vRSdqlUuDkvu97DKI) viggle目前有api支持了吗

https://www.openai-hk.com/docs/lab/viggle-dance.html

**Comment by Dooy** [comment]
> ![Screenshot_2024-07-07-06-37-34-993_com microsoft emmx-edit](https://private-user-images.githubusercontent.com/53889513/346301877-467016c1-ec41-45cd-bb77-5030150efbb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzOTgzMTYsIm5iZiI6MTcyMDM5ODAxNiwicGF0aCI6Ii81Mzg4OTUxMy8zNDYzMDE4NzctNDY3MDE2YzEtZWM0MS00NWNkLWJiNzctNTAzMDE1MGVmYmI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAwMjAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMjIyZWQyNTkwZGNmMmVhYmY5N2RiMzYwNjM1NmYyNzNlYWExZTJjZjVlNTdiMjJlNzNmMzg0ZTNjMjE4NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lGhRO0MWW_m7AE18bo6Iz1jZWC10oygXQbGKKsnQiJE) 在上面没看到首尾帧功能

参考图片是首帧 我再搞一个尾帧吧

**Comment by xianyu110** [comment]
> > ![Screenshot_2024-07-07-06-37-34-993_com microsoft emmx-edit](https://private-user-images.githubusercontent.com/53889513/346301877-467016c1-ec41-45cd-bb77-5030150efbb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzOTgzMTYsIm5iZiI6MTcyMDM5ODAxNiwicGF0aCI6Ii81Mzg4OTUxMy8zNDYzMDE4NzctNDY3MDE2YzEtZWM0MS00NWNkLWJiNzctNTAzMDE1MGVmYmI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAwMjAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMjIyZWQyNTkwZGNmMmVhYmY5N2RiMzYwNjM1NmYyNzNlYWExZTJjZjVlNTdiMjJlNzNmMzg0ZTNjMjE4NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lGhRO0MWW_m7AE18bo6Iz1jZWC10oygXQbGKKsnQiJE) 在上面没看到首尾帧功能
> 
> 参考图片是首帧 我再搞一个尾帧吧

先谢谢大佬了~

**Comment by Dooy** [comment]
`v2.19.5` 更新至这个版本
