### ISSUE TITLE
MJ绘图生成成功，混图功能一致显示提交中，请问是什么原因呢

### ISSUE THREAD

**Issue by z13260641200** [Dooy/chatgpt-web-midjourney-proxy#448]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/88540729/07c178de-ff47-4bdc-b6ba-d069a49ac6ad)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/88540729/2061da50-adec-4b75-a328-c780265b522b)

**Comment by Dooy** [comment]
没返回？ 多试几次 或者问下中转

**Comment by z13260641200** [comment]
多次没有响应，中转没有收到请求
