### ISSUE TITLE
SSL问题

### ISSUE THREAD

**Issue by ioir123ju** [Dooy/chatgpt-web-midjourney-proxy#449]
我请求luma时的报错
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/14951957/ae9d4f31-0636-47ac-9a7b-1f644b5ad047)

**Comment by ioir123ju** [comment]
> 问下 中转 需要 luma api的支持

但是我已经部署了luma api服务，并且通过api工具可以调用成功。

**Comment by Dooy** [comment]
为何 自己编译啊 使用Docker 试下

**Comment by Dooy** [comment]
docker run --name chatgpt-web-midjourney-proxy  -d -p 6015:3002 \
-e OPENAI_API_KEY=sk-luma-key \
-e OPENAI_API_BASE_URL=https://your-luma-server  \
-e MJ_SERVER=https://your-mj-server:6013  \
-e MJ_API_SECRET=your-mj-api-secret

**Comment by Dooy** [comment]
```shell
docker run --name chatgpt-web-midjourney-proxy  -d -p 6015:3002 \
-e OPENAI_API_KEY=sk-luma-key \
-e OPENAI_API_BASE_URL=https://your-luma-server
```

**Comment by ioir123ju** [comment]
我用的这个命令，还是同样的错误：docker run --name chatgpt-web-midjourney-proxy  -d -p 6015:3002 -e OPENAI_API_KEY=sk-luma-key -e OPENAI_API_BASE_URL=https://10.xx.xx.xx:9234  ydlhero/chatgpt-web-midjourney-proxy

**Comment by ioir123ju** [comment]
我试了我的电脑部署和服务器部署两种方式都有问题，
电脑部署：504 Gateway Timeout
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/14951957/7b4e85b0-5d09-4a3f-ac0b-4bcb1c5a523d)
服务器部署就是SSL问题

**Comment by Dooy** [comment]
留个微信 我加你 帮你看看
