### ISSUE TITLE
关于本月使用量的取值

### ISSUE THREAD

**Issue by sunsky89757** [Dooy/chatgpt-web-midjourney-proxy#45]
请教一下作者，这个本月使用量如何才能让其取值呢？我用的是中转API，可以用旧格式调用余额和消耗量

**Comment by Dooy** [comment]
目前查看的月使用量 随在服务器的openai_base_url 走 
我们修改下也能随着前端的UI设置的  openai_base_url 走

**Comment by Dooy** [comment]
v2.13.3 已支持
