### ISSUE TITLE
能否以用户名方式登录，保留聊天记录

### ISSUE THREAD

**Issue by 18945985188** [Dooy/chatgpt-web-midjourney-proxy#450]
目前感觉换IP登录，记录就会消失，我是用在部门5个同事，局域网环境，换机器或者IP就没记录了。能增加一个，用户管理，并每个用户保留记录吗

**Comment by Dooy** [comment]
这个存储是存在 浏览器本地的
所以你换电话 或者 服务器换ip 记录都找不到

需要用户管理看看 社区是否有其他大佬肯贡献

**Comment by spammenotinoz** [comment]
Try LiteLLM passthrough using litellm keys for each user.
