### ISSUE TITLE
GPTS失效了

### ISSUE THREAD

**Issue by gfcq** [Dooy/chatgpt-web-midjourney-proxy#451]
这以后是不是都不可以了
![图片1](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/166496524/90a12e32-ef3d-4ece-91ca-3e461aba1942)

**Comment by Dooy** [comment]
应该可以吧 得问下 中转

**Comment by gfcq** [comment]
> 应该可以吧 得问下 中转

嗷嗷，我还以为有GPT的api直接改模型名就可以了

**Comment by littlekie** [comment]
> > 应该可以吧 得问下 中转
> 
> 嗷嗷，我还以为有GPT的api直接改模型名就可以了

后面你这边还能继续使用吗
