### ISSUE TITLE
后续会有luma尾帧么

### ISSUE THREAD

**Issue by KingDoraa** [Dooy/chatgpt-web-midjourney-proxy#452]
麻烦问下后续会有luma尾帧么

**Comment by Edgar-qiqi** [comment]
luma应该还要做多张参考图片的那种

**Comment by Dooy** [comment]
下个版本上

**Comment by Dooy** [comment]
`v2.19.5` 已经上线

**Comment by NeverOccurs** [comment]
> `v2.19.5` 已经上线

加入尾帧后提示error 413是咋回事

**Comment by Edgar-qiqi** [comment]
> `v2.19.5` 已经上线

感谢你做的贡献，请问luma官方有个选项叫增强提示词(Enhance prompt)能让我们自行选择是否开启吗？

**Comment by Dooy** [comment]
> > `v2.19.5` 已经上线
> 
> 加入尾帧后提示error 413是咋回事

是不是 没支持？

**Comment by Dooy** [comment]
> > `v2.19.5` 已经上线
> 
> 感谢你做的贡献，请问luma官方有个选项叫增强提示词(Enhance prompt)能让我们自行选择是否开启吗？

`expand_prompt` 默认是开启的

**Comment by NeverOccurs** [comment]
> > > `v2.19.5` 已经上线
> > 
> > 
> > 加入尾帧后提示error 413是咋回事
> 
> 是不是 中转 没支持？

应该不会 用的就是openai-hk

**Comment by NeverOccurs** [comment]
> > > `v2.19.5` 已经上线
> > 
> > 
> > 加入尾帧后提示error 413是咋回事
> 
> 是不是 中转 没支持？

刚看了一下，单纯尾帧可以，同时加入参考图和尾帧就不行，是不是因为目前还不支持首尾帧？

**Comment by NeverOccurs** [comment]
> > > `v2.19.5` 已经上线
> > 
> > 
> > 加入尾帧后提示error 413是咋回事
> 
> 是不是 中转 没支持？

破案了，两张图加起来太大了。。

**Comment by NeverOccurs** [comment]
请问runway有可能支持首尾帧同时上传吗
