### ISSUE TITLE
about pinia

### ISSUE THREAD

**Issue by itenl** [Dooy/chatgpt-web-midjourney-proxy#453]
It does not comply with the pinia usage specifications and will exist issues "getActivePinia was called with no active Pinia. Did you forget to install pinia?"

https://github.com/Dooy/chatgpt-web-midjourney-proxy/blob/9c3e3b32005fb4fc7f3e5ef4b29b6428b257ad60/src/store/modules/auth/index.ts#L7

**Comment by Dooy** [comment]
Can you provide screenshots of the error? I debugged and compiled without any problems.

**Comment by itenl** [comment]
![image](https://github.com/user-attachments/assets/e4a181d9-0eba-4d1a-870b-b6126c10be0c)
![image](https://github.com/user-attachments/assets/18673d20-5749-4b62-9042-6c83a8efa603)

The error occurs because I loaded useAuthStore and useUserStore in App.vue
