### ISSUE TITLE
Docker 部署中设置的 suno 环境变量没有生效，前台设置可以用，设置环境变量就报错了。

### ISSUE THREAD

**Issue by alanblogooo** [Dooy/chatgpt-web-midjourney-proxy#454]
Docker 部署中设置的 suno 环境变量没有生效，前台设置可以用，设置环境变量就报错了。

**Comment by Dooy** [comment]
报什么错误？

**Comment by alanblogooo** [comment]
![62d03fecdb7b99006016711b59825858](https://github.com/user-attachments/assets/a3568fcd-e921-41fd-9a1e-f4588b9926ca)
提示这个错误

**Comment by Dooy** [comment]
用f12 看下 你请求的地址

问下你的中转支持  /suno/xxxxx 的请求否？

**Comment by zhangmuyuan** [comment]
你好，最新发布的版本，4o-mini,在识图的时候自动调用了gpt4-vison,希望修复一下

**Comment by Dooy** [comment]
> 你好，最新发布的版本，4o-mini,在识图的时候自动调用了gpt4-vison,希望修复一下

收到

**Comment by Dooy** [comment]
> 你好，最新发布的版本，4o-mini,在识图的时候自动调用了gpt4-vison,希望修复一下

已经修复 请下载到最新版本
