### ISSUE TITLE
为什么无法兼容通义百炼的API调用，一直提示跨域

### ISSUE THREAD

**Issue by COSWINNER** [Dooy/chatgpt-web-midjourney-proxy#455]
部署方式：使用源码构建docker镜像
在使用通义的api接口时就一直提示fetch error，控制台提示跨域。做了多种尝试都没有解决，目前推测因为通义的API比openai的多了一级目录  https://dashscope.aliyuncs.com/**compatible-mode**  导致的，kimi这种完全跟openai层级一样的就没问题。可能是做跨域或代理的时候没有适配阿里的地址结构，还请各位大佬看一下，能不能把通义API适配上。
![image](https://github.com/user-attachments/assets/a9ee7eb1-8e36-48bf-939d-63dddf7a6913)

**Comment by Dooy** [comment]
建议用 one-api 转下

**Comment by COSWINNER** [comment]
好吧，谢谢大佬，不过还是希望原生支持下

**Comment by Dooy** [comment]
> 好吧，谢谢大佬，不过还是希望原生支持下

用钞能力 可以在社区 请人开发啊
