### ISSUE TITLE
想在源码里做一些自定义的修改后，如何打成mac安装包？

### ISSUE THREAD

**Issue by 29745560** [Dooy/chatgpt-web-midjourney-proxy#456]
如题，急求跪求方案，谢谢

**Comment by Dooy** [comment]
https://github.com/Dooy/chatgpt-web-midjourney-proxy/blob/main/tauri_debug.sh 
调试

编译
```shell
pnpm tauri build 
```

批量打包看工作流

**Comment by Dooy** [comment]
https://github.com/Dooy/chatgpt-web-midjourney-proxy/blob/main/.github/workflows/desktop.yml

**Comment by 29745560** [comment]
>  1.调试

https://github.com/Dooy/chatgpt-web-midjourney-proxy/blob/main/tauri_debug.sh 

>  2.编译

```shell
pnpm tauri build 
```

>  3. 批量打包看工作流

https://github.com/Dooy/chatgpt-web-midjourney-proxy/blob/main/.github/workflows/desktop.yml


啊哈哈哈！简直太爱你了，完美解决。
