### ISSUE TITLE
“设置-关于”选项卡无法正确显示本月用量、订阅总额和API余额

### ISSUE THREAD

**Issue by niucaidi** [Dooy/chatgpt-web-midjourney-proxy#459]
<img width="465" alt="PixPin_2024-07-20_16-19-56" src="https://github.com/user-attachments/assets/60650bf1-fc1b-4e44-b3bc-09a28766eb13">
希望可以告知如何解决这个问题，使用的是OpenAi-HK，因为OpenAi-HK可以建立子key很方便用于开链接给他人使用所以已将其作为长期方案，但目前遇到问题为在“设置-关于”选项卡中无法正确显示本月用量、订阅总额和API余额，这样的话如果想知道用量信息就必须人工登录OpenAi-HK控制台查询，非常麻烦，可否解决一下这个问题？即让“设置-关于”选项卡正确显示本月用量、订阅总额和API余额三个信息

**Comment by Dooy** [comment]
联系下 他们客服 请客服帮忙开启下
