### ISSUE TITLE
请问支持模型里面是否有计划增加国内大模型的支持

### ISSUE THREAD

**Issue by gatieme** [Dooy/chatgpt-web-midjourney-proxy#461]
如题，模型的选项都是国外的模型。

![image](https://github.com/user-attachments/assets/c716755e-fdd2-4658-8f98-5ed112f499cf)

有没有计划支持国内的 通义千问，KIMI,文心一言，智谱清言等

**Comment by Dooy** [comment]
看下 readme 可以子定义

**Comment by gatieme** [comment]
好的，感谢
