### ISSUE TITLE
MJ上传不了参考图片了？

### ISSUE THREAD

**Issue by laitianwen** [Dooy/chatgpt-web-midjourney-proxy#462]

**Comment by Dooy** [comment]
现在好了 你可以试下

**Comment by laitianwen** [comment]
确实可以了，感谢🥹





------------------ 原始邮件 ------------------
发件人: Dooy ***@***.***&gt;
发送时间: 2024年7月24日 16:55
收件人: Dooy/chatgpt-web-midjourney-proxy ***@***.***&gt;
抄送: laitianwen ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Dooy/chatgpt-web-midjourney-proxy] MJ上传不了参考图片了？ (Issue #462)





 
现在好了 你可以试下
