### ISSUE TITLE
 2.19.6 版本手机端上传图片后会出现卡死情况

### ISSUE THREAD

**Issue by owcowc** [Dooy/chatgpt-web-midjourney-proxy#463]
2.19.6 版本手机端上传图片后
点击发送会出现卡死情况

**Comment by Dooy** [comment]
能否 带图下   不知道是哪个地方 传图

**Comment by ChuckZengxf** [comment]
图片太大了吧

**Comment by owcowc** [comment]
> 能否 带图下 不知道是哪个地方 传图

![微信图片_20240725164705](https://github.com/user-attachments/assets/ce29bc53-041a-41a8-9e0f-1e1fcf74a91e)
这里，上传图片后点击发送就卡住了。
是图片尺寸原因吗？以前好像没出现过

**Comment by rocky-ren** [comment]
图片不能超过1m, 但是手机拍照一定会大于1m

**Comment by Dooy** [comment]
环境变量 能修改
