### ISSUE TITLE
docker部署的，局部重绘经常出现403

### ISSUE THREAD

**Issue by wangr0031** [Dooy/chatgpt-web-midjourney-proxy#469]
在点击图片做局部重绘时，会出现下面的异常
请问应该怎么修复？
![image](https://github.com/user-attachments/assets/97977452-e098-4cb5-a97a-d0479eb1bbdd)

**Comment by Dooy** [comment]
后面 我修复下 看看要如何 处理

**Comment by Dooy** [comment]
已经修复
