### ISSUE TITLE
建议增加弹窗公告功能

### ISSUE THREAD

**Issue by tuzh6** [Dooy/chatgpt-web-midjourney-proxy#47]
建议在打开页面时增加弹窗之类的公告，方便在出现各类问题或更新可用模型是能够给分享使用的人一个简单提示~

**Comment by tuzh6** [comment]
> 我们没数据 没地方存哟

是否可以简单点，比如加个系统变量之类的，在docker部署的时候就写上~反正每次更新都会重新部署容器哈哈

**Comment by Dooy** [comment]
v2.13.5 已支持

![v2.13.5](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/682e0694-b6a0-4433-9f88-508457aa41d0)
