### ISSUE TITLE
请问VERCEL上面部署的还是2.18版本，如果在VERCEL同步你的最新版本

### ISSUE THREAD

**Issue by fubaobao2023** [Dooy/chatgpt-web-midjourney-proxy#471]
请问VERCEL上面部署的还是2.18版本，如果在VERCEL同步你的最新版本

**Comment by fubaobao2023** [comment]
你有微信吗 留一个或者你加我 我的微信17729643177

**Comment by fubaobao2023** [comment]
还有一个 拖入GPT的文件不能高于 1M 请问如何调高，PDF word PPT等文件能不能 直接拖给 gpt让它处理呢？

**Comment by Dooy** [comment]
多看下 readme 参数 都能调

**Comment by fubaobao2023** [comment]
> 多看下 readme 参数 都能调

价格微信吧 可以吗

**Comment by fubaobao2023** [comment]
我是一键同步到VERCEL上面的，当时也是 勾选了自动同步的 我现在遇见的问题是没办法自动同步，以及没办法改上传的参数 现在超过1M的 都没办法传 可以付费求助
