### ISSUE TITLE
【功能建议】能否在环境变量中加入头像链接和名称的选项？

### ISSUE THREAD

**Issue by xun666** [Dooy/chatgpt-web-midjourney-proxy#472]
目前头像链接和名称虽然可以自定义，但是初始的头像并不具备严肃性，如果部署的对象包含长辈、领导、老师等，会稍显不合适。所以希望能修改初始的头像和名称，感谢！

![image](https://github.com/user-attachments/assets/703c6e47-e5d2-4b86-b092-f3f67aafbccc)

**Comment by Dooy** [comment]
有开发能力 可自行修改下

**Comment by xun666** [comment]
> 有开发能力 可自行修改下

确实，不太有😢

**Comment by xun666** [comment]
> 有开发能力 可自行修改下

能麻烦您给一下默认的头像和名称在哪里吗？找了好几个地方没找到

**Comment by xun666** [comment]
以及默认的prompt的地方。现在的prompt好像是告诉模型它是GPT，我加载了llama3.1的模型，它就自我介绍是gpt。我自己用“你是一名优秀且耐心的助手”把默认的prompt覆盖后它就知道它是llama了

**Comment by xun666** [comment]
> 有开发能力 可自行修改下

好的，找到修改地方了

**Comment by Dooy** [comment]
ok
