### ISSUE TITLE
如何修改默认的Prompt？

### ISSUE THREAD

**Issue by xun666** [Dooy/chatgpt-web-midjourney-proxy#476]
默认的prompt似乎包含模型是ChatGPT的暗示。
当我在界面中没设置角色时，LLama说它是ChatGPT。
![image](https://github.com/user-attachments/assets/c9c354d0-cf64-482e-bf00-a2cc25cbf9a7)

当我设置一个简要的“角色设定”，覆盖掉默认的prompt时，它就知道它是LLama了。
- `你是一名优秀且耐心的助手`
![image](https://github.com/user-attachments/assets/ea5a05cf-4f83-4fc3-97c4-237378c58b92)

所以想请问默认的Prompt设定是在项目的哪个位置？找了很久没找到。

**Comment by Dooy** [comment]
<img width="814" alt="image" src="https://github.com/user-attachments/assets/3d53d2da-c18b-4f1b-b46e-10e97a7d97a7">

**Comment by xun666** [comment]
> <img alt="image" width="814" src="https://private-user-images.githubusercontent.com/3765401/354904720-3d53d2da-c18b-4f1b-b46e-10e97a7d97a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDEwMTYsIm5iZiI6MTcyMjg0MDcxNiwicGF0aCI6Ii8zNzY1NDAxLzM1NDkwNDcyMC0zZDUzZDJkYS1jMThiLTRmMWItYjQ2ZS0xMGU5N2E3ZDk3YTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMDY1MTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE4YzIxNjQ2MGI2MWVhYjYzYjkxMjA5ZjQ4MGM4YzA0YjhkZGYyMmEwNDY5NzEyMDRiNTdlZjYxYzZhNTNkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5eN3VMMr6x_cC_EmcDd0ax0xsRgWK0KJ_9Qww5oTZQY">

好嘞！感谢
