### ISSUE TITLE
多语言问题

### ISSUE THREAD

**Issue by H-huihui** [Dooy/chatgpt-web-midjourney-proxy#478]
首先感谢大佬开发者，我有两个语言的问题要反馈一下
1.切换为英文后，作图这里的显示仍然是中文
<img width="319" alt="image" src="https://github.com/user-attachments/assets/4d479024-ec05-47b7-b08c-7ee862b292b7">
 2.怎么设置默认语言为英文呀？

求帮忙指教一下呀

**Comment by Dooy** [comment]
需要  ctrl+f5下

**Comment by Dooy** [comment]
默认 英文 需要动开发了
或者 后面我搞个环境变量出来

**Comment by H-huihui** [comment]
> 默认 英文 需要动开发了 或者 后面我搞个环境变量出来

搞个环境变量太有需要啦👍

还yo有默认名称：AI 绘画，也建议搞到环境变量里
<img width="605" alt="image" src="https://github.com/user-attachments/assets/c9efbdb8-7bde-4ec9-bd42-fa90666deee2">
