### ISSUE TITLE
希望优化对话交互

### ISSUE THREAD

**Issue by Kadxy** [Dooy/chatgpt-web-midjourney-proxy#48]
1. 支持实时以**markdown 格式**预览用户即将发送的内容
2. 用户发送的消息以**Markdown 格式**显示
3. 重试的时候,应该使用当前模型,而不是重发被重试的消息
4. 允许修改历史消息内容,便于优化 prompt 重新提问

**Comment by Dooy** [comment]
老板，基本把 next web的功能搬过来了 😭

**Comment by jason-xiaobaiai** [comment]
> 老板，基本把 next web的功能搬过来了 😭

不用弄这些，现在已经非常简洁优雅了
