### ISSUE TITLE
Docker部署，Suno API调用出错：SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by ImcwjHere** [Dooy/chatgpt-web-midjourney-proxy#480]
假设：
API站：api.xxx.com
chatgpt-web-midjourney-proxy所在网站：chat.abc.com

直接在网页里填写api.xxx.com就可以正常使用，F12结果：
调用：https://api.xxx.com/suno/generate/lyrics/
返回：JSON

在Docker里填写api.xxx.com无法正常使用，F12结果：
调用：https://**chat.abc.com**/**sunoapi**/generate/lyrics/
报错：发生错误SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
返回：HTML
内容：You need to enable JavaScript to run this app.

看起来是项目里代理sunoApi接口的地方出了问题，望修复。

**Comment by ImcwjHere** [comment]
应该和：
[Docker 部署中设置的 suno 环境变量没有生效，前台设置可以用，设置环境变量就报错了。 #454](https://github.com/Dooy/chatgpt-web-midjourney-proxy/issues/454)
[新上的suno功能使用中转的提交报错；You need to enable JavaScript to run this app. #301](https://github.com/Dooy/chatgpt-web-midjourney-proxy/issues/301)
是一个问题

**Comment by Dooy** [comment]
中转不支持 
先用 https://www.openai-hk.com 调通下

文档在这儿

https://www.openai-hk.com/docs/lab/suno-v3.html
