### ISSUE TITLE
在绘图中 sref或cref一栏进行上传图片时，选择图片，显示上传中，之后会跳出显示[object Object]提示，并无法生成图片url链接。

### ISSUE THREAD

**Issue by Code-WSY** [Dooy/chatgpt-web-midjourney-proxy#481]
docker-compose.yml文件如下，已做脱敏处理，目前生成MJ图片等正常，就是无法上传图片。
```docker
services:
  chatgpt-web-midjourney-proxy:
    image: ydlhero/chatgpt-web-midjourney-proxy:latest
    container_name: chatgpt-web-midjourney-proxy
    ports:
      - "3002:3002"
    volumes:
      - /home/username/project/chatgpt-web-midjourney-proxy/data/uploads:/app/uploads    
    environment:
       OPENAI_API_KEY: *****
       OPENAI_API_BASE_URL: https://*****
       MJ_SERVER: https://*****
       MJ_API_SECRET: *****
       LUMA_SERVER: *****
       LUMA_KEY: *****
       SUNO_SERVER: *****
       SUNO_KEY: *****
       # - UPLOAD_TYPE=Container  
       API_UPLOADER: 1  #支持上传
       UPLOAD_IMG_SIZE: 100 #上传大小限制
       AUTH_SECRET_KEY: ***** #访问授权密码
       #爆破：验证次数 注意: 数字 ；nginx 请设置  proxy_set_header   X-Forwarded-For  $remote_addr;
       AUTH_SECRET_ERROR_COUNT: 3
       #爆破：验证停留时间 单位分钟 注意: 是数字
       AUTH_SECRET_ERROR_TIME: 1
       OPENAI_API_MODEL: gpt-4o #默认模型
       VISION_MODEL: gpt-4o
       CUSTOM_MODELS: -all,gpt-4o,gpt-4o-mini,gpt-3.5-turbo #自定义模型
       # r2
       R2_DOMAIN: https://*****
       R2_BUCKET_NAME: *****
       R2_ACCOUNT_ID:*****
       R2_KEY_ID: *****
       R2_KEY_SECRET: *****
    restart: unless-stopped
```
上传图片显示如下：
![7a35f6bdaabfad3fc8f4182dc6b45cb](https://github.com/user-attachments/assets/2a7536b2-0576-4fe7-8a83-52e6545a93af)

**Comment by Dooy** [comment]
中转 可能不支持导致的

**Comment by Dooy** [comment]
是下 https://www.openai-hk.com 的中转

<img width="809" alt="image" src="https://github.com/user-attachments/assets/b0548795-0feb-4007-bcc6-58632b9b30e5">

**Comment by Code-WSY** [comment]
> 中转可能不支持导致的

可以实现这样的逻辑吗：上传文件先上传到r2这类云对象存储服务（或本地存储如minio），然后返回生成url的链接。以避免这类错误。

**Comment by Dooy** [comment]
> > 中转可能不支持导致的
> 
> 可以实现这样的逻辑吗：上传文件先上传到r2这类云对象存储服务（或本地存储如minio），然后返回生成url的链接。以避免这类错误。

可以自己实现下，不过最好是传到 discordapp 不然下载难免有问题

**Comment by Code-WSY** [comment]
> > > 中转可能不支持导致的
> > 
> > 
> > 可以实现这样的逻辑吗：上传文件先上传到r2这类云对象存储服务（或本地存储如minio），然后返回生成url的链接。以避免这类错误。
> 
> 可以自己实现下，不过最好是传到 discordapp 不然下载难免有问题

好的谢谢，我想请问就是项目中的本地或者r2存储，这类配置之后是用来存储哪类文件的，目前我配置之后，gpt识图的图片并没有上传到这些存储服务或者本地服务器

**Comment by Dooy** [comment]
> > > > 中转可能不支持导致的
> > > 
> > > 
> > > 可以实现这样的逻辑吗：上传文件先上传到r2这类云对象存储服务（或本地存储如minio），然后返回生成url的链接。以避免这类错误。
> > 
> > 
> > 可以自己实现下，不过最好是传到 discordapp 不然下载难免有问题
> 
> 好的谢谢，我想请问就是项目中的本地或者r2存储，这类配置之后是用来存储哪类文件的，目前我配置之后，gpt识图的图片并没有上传到这些存储服务或者本地服务器

GPTs 才会用到 gpt识图走的是 base64图片
