### ISSUE TITLE
Vercel部署，代码拉取到了最新，但是还是显示需要更新

### ISSUE THREAD

**Issue by sunsky89757** [Dooy/chatgpt-web-midjourney-proxy#483]
![image](https://github.com/user-attachments/assets/81980d27-8dec-44aa-a741-243329ee4ada)
您好大佬，问题如图，我已经把代码合并到了最新版本，但是部署完成后还是会显示落后一个版本，这个需要怎么解决？

**Comment by Dooy** [comment]
ctrl+f5 试下

**Comment by sunsky89757** [comment]
试过了，以前升级完都是这样清理缓存后生效，这次却不行，因为我上一个版本也不是2.20.1，好久没更新过了，但是刷新后他就显示了2.20.1，实际是2.20.2，就很奇怪。

**Comment by Dooy** [comment]
这版本 是从 package.json 获取的version 
你看下  里面的这个 更新到位了否？

**Comment by sunsky89757** [comment]
![image](https://github.com/user-attachments/assets/4b32e665-e9a4-48cd-9442-8423df0bf2da)
显示是最新的版本

**Comment by Dooy** [comment]
我也搞不清了 呵呵

**Comment by Dooy** [comment]
vercel 重新编译一遍试试

**Comment by Dooy** [comment]
<img width="767" alt="image" src="https://github.com/user-attachments/assets/e6065003-0060-43c6-afcc-4419b22426c1">

这个也是部署在 vercel上的 没问题

**Comment by sunsky89757** [comment]
找到问题了大佬，我加模型到文件里的时候，少写了逗号，打扰了，谢谢哈~
