### ISSUE TITLE
[feat] 修改了一下文件上传的样式，不知能否pr上去

### ISSUE THREAD

**Issue by Yanyutin753** [Dooy/chatgpt-web-midjourney-proxy#485]
### Mobile

<img width="259" alt="4594b268c447b7a0c8de1ca6da6d567" src="https://github.com/user-attachments/assets/6dccd7ba-a924-45f6-966f-6b466e880188">

### Desktop

![image](https://github.com/user-attachments/assets/9aa1e3c9-aaef-486c-9600-7e5fdc2c2d45)

### 感谢作者的无私奉献

**Comment by Dooy** [comment]
可以的 感谢PR

**Comment by Dooy** [comment]
等你的PR 发版^_^
