### ISSUE TITLE
更新了背景图版本后。聊天窗口内容上下滚动有时候会失效，要重新刷新页面才能滚动

### ISSUE THREAD

**Issue by ChuckZengxf** [Dooy/chatgpt-web-midjourney-proxy#490]
更新了背景图版本后。聊天窗口内容上下滚动有时候会失效，要重新刷新页面才能滚动

**Comment by Dooy** [comment]
这么可怕？

**Comment by GNX001** [comment]
已经遇到了，我是edge浏览器，win10，相同问题，无论是docker部署的网页端还是下载的EXE都有这个问题！
我这是直接刷新都不管用，看运气偶尔鼠标滚动键才有效果！
----
话说docker部署能不能不用在编排的时候填写key？

**Comment by Dooy** [comment]
> ## 已经遇到了，我是edge浏览器，win10，相同问题，无论是docker部署的网页端还是下载的EXE都有这个问题！
> 我这是直接刷新都不管用，看运气偶尔鼠标滚动键才有效果！
> 话说docker部署能不能不用在编排的时候填写key？

更新至 2.20.4版本已修复

**Comment by Dooy** [comment]
<img width="1563" alt="image" src="https://github.com/user-attachments/assets/c3db419f-9e7b-44ad-b5cd-5f8e993e9dae">

**Comment by Yanyutin753** [comment]
我好像忘记把消息的class修改的提交上去了😭 其实在消息页面类加个z-10就可以了

**Comment by Yanyutin753** [comment]
这样全透明会不会出现字看不清的情况
