### ISSUE TITLE
claude-3-5，maxtoken问题

### ISSUE THREAD

**Issue by wk222** [Dooy/chatgpt-web-midjourney-proxy#495]
版本：2.20.4
问题：claude3.5目前是支持8K回复的，但是我用oneapi转发的claude35在前端最大只能拖动到4096的token，希望能增加上限

**Comment by wk222** [comment]
能够有个环境变量设置最好了，谢谢

**Comment by Dooy** [comment]
收到 我看看 如何搞下

**Comment by Dooy** [comment]
更新至 `2.20.5` 以上版本

**Comment by wk222** [comment]
> 更新至 `2.20.5` 以上版本

测试已解决，claude3.5最大token现在能拖到8K了

**Comment by wk222** [comment]
还有点小问题，用新电脑开网页的话，只看claude设置max token还是4096，需要切换到一个支持8192的模型，比如gemini，然后cladue才变成8192了。
![屏幕截图_7-9-2024_13015_52 175 229 168](https://github.com/user-attachments/assets/0dcaa24f-056d-46d0-a007-c915fe5e210d)
![屏幕截图_7-9-2024_13036_52 175 229 168](https://github.com/user-attachments/assets/e57dd65a-e4ea-4399-88b4-859a4b7ab1bf)
