### ISSUE TITLE
默认模型设置

### ISSUE THREAD

**Issue by wenlinwwww** [Dooy/chatgpt-web-midjourney-proxy#496]
想问一下，怎么修改才能每次打开网站都是选择设置的默认模型，而不是上次使用的模型？
比如，默认模型是gpt-3.5-turbo，我使用的时候换成gpt-4o或者别的，关掉网站，下次打开还是显示默认模型（gpt-3.5-turbo）这种
麻烦大佬了，十分感谢

**Comment by Dooy** [comment]
看 readme 啊 

环境变量 `OPENAI_API_MODEL`  默认模型

**Comment by wenlinwwww** [comment]
加了默认模型环境变量，但是我换了别的模型之后，关闭网站，再打开，除非我把localstorage都清了，不然还是显示我换了之后的模型，不是我的默认模型

**Comment by Dooy** [comment]
用无痕试下啊

**Comment by wenlinwwww** [comment]
那如果不用无痕浏览的话，有办法改吗？
