### ISSUE TITLE
提示500错误，日记显示

### ISSUE THREAD

**Issue by keithhu1982** [Dooy/chatgpt-web-midjourney-proxy#498]
WARN  Unsupported engine: wanted: {"node":"^16 || ^18 || ^19"} (current: {"node":"v20.17.0","pnpm":"9.9.0"})

> chatgpt-web-service@2.15.6 prod /app
> node ./build/index.mjs

Server is running on port 3002
(node:18) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

应如何解决Node.js问题，环境已经配置了Node.js的18版本

**Comment by Dooy** [comment]
这个地方 没显示 500啊

500错误 应该是 中转来的吧？

**Comment by xiafengWang** [comment]
我的也出现这个相似的问题，我感觉应该是中转来的

**Comment by liyf1** [comment]
我也遇到了，同问

**Comment by keithhu1982** [comment]
node版本可以如何解决

**Comment by Dooy** [comment]
这个 500不用太理会  可以忽略
