### ISSUE TITLE
OPENAI o1系列模型对接使用OpenrouterAPI报错

### ISSUE THREAD

**Issue by itdsee** [Dooy/chatgpt-web-midjourney-proxy#499]
其它模型都正常，docker版本升级到2.20.10后出现该问题，确认个人张宝拥有o1系列模型全部权限；

![没有错误代码](https://github.com/user-attachments/assets/d602dfc7-fe48-44e9-a711-d050d4f03c24)

**Comment by Dooy** [comment]
o1 不支持流输出了
如果支持流输出 那可能是逆向的

**Comment by Dooy** [comment]
用 f12 看下 network 请求是否成功

**Comment by Dooy** [comment]
<img width="958" alt="image" src="https://github.com/user-attachments/assets/56dd5943-dfe1-4d0d-a245-1caa869b1218">

**Comment by itdsee** [comment]
好像没有
![1](https://github.com/user-attachments/assets/6d1eb969-230f-44d4-a099-01caf1bb7b3f)
![2](https://github.com/user-attachments/assets/a74b7866-bf67-4bc1-aa9f-63a7594c7c3a)

**Comment by Dooy** [comment]
<img width="373" alt="image" src="https://github.com/user-attachments/assets/a1dfadea-27a2-436b-b4f1-8f6460fb9b0b">
网址填做了 不要 过多的 /v1/chat/compl...

**Comment by itdsee** [comment]
thanks 貌似是one-api的问题 我直接填写openrouter之后是正常的，但是o1和之前模型还是有点区别；请关闭这个问题
