### ISSUE TITLE
MJ绘图新版本bug

### ISSUE THREAD

**Issue by xiaosatai** [Dooy/chatgpt-web-midjourney-proxy#50]
现版本MJ绘图界面选择对应选项（如镜头，风格）可能不会自动添加上，最重要的是绘图模型（V6,V5.2,NIJI 5）也无法自动添加，
使用起来不是那边方便(老版本是直接会附上）

**Comment by xiaosatai** [comment]
![微信截图_20231226144448](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/44671057/4d9084af-f8bc-498f-8476-358a948fb0d0)
![微信截图_20231226144524](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/44671057/f9bc26c8-07f1-4cb6-a516-d8d9c478958c)

**Comment by Dooy** [comment]
下个版本修复

**Comment by Dooy** [comment]
v2.13.4  已修复
