### ISSUE TITLE
o1-mini与o1-preview无法使用

### ISSUE THREAD

**Issue by Edgar-qiqi** [Dooy/chatgpt-web-midjourney-proxy#500]
使用docker+caddy部署版本自动更新latest
![2e105653e085a357019ed090eb9ac56b](https://github.com/user-attachments/assets/d19514c7-d44f-4d8f-910d-9917af589988)
![6f7d172364d9af8c2da4547681b7b7c8](https://github.com/user-attachments/assets/fe1ebfdc-569b-433d-a5ef-2f5abeddcac3)
无法使用gpt4最新o1模型

**Comment by Dooy** [comment]
用F12 查下 network(网络) 看下 是不是 openai/openai 重复了 如下图

如果是重复了 请再次更新下
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/fa454d6f-b2c2-4ce8-a887-f4adc2682d62">

**Comment by Edgar-qiqi** [comment]
> 用F12 查下 network(网络) 看下 是不是 openai/openai 重复了 如下图
> 
> 如果是重复了 请再次更新下 <img alt="image" width="1059" src="https://private-user-images.githubusercontent.com/3765401/367551668-fa454d6f-b2c2-4ce8-a887-f4adc2682d62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTA0NTEsIm5iZiI6MTcyNjM5MDE1MSwicGF0aCI6Ii8zNzY1NDAxLzM2NzU1MTY2OC1mYTQ1NGQ2Zi1iMmMyLTRjZTgtYTg4Ny1mNGFkYzI2ODJkNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMDg0OTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWMxMjdiZmU1NDhiMDUxY2QyZThmYWJlMWRhMzQ2M2Q3NjNhZjUxNzlkN2ViYWE5YTBkNWZkMjRhOGIxOTY0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mVFbeShpRpdfs44iGSIEPyI_Nak8SLUzgoJwGzGTaxA">

![image](https://github.com/user-attachments/assets/317dfcf7-3b01-4717-ad28-2497d4df4a7b)
没有出现你说的那个问题

**Comment by douyan2662** [comment]
感觉是反问权限的问题，也奇怪，这次版本没有访问权限的弹窗了是为什么？

**Comment by Dooy** [comment]
可能是你的 中转不支持
可以用curl先试下

**Comment by Dooy** [comment]
o1 参数改了 几个；可能中转没支持上

**Comment by Edgar-qiqi** [comment]
> o1 参数改了 几个；可能中转没支持上

找到触发以上bug的原因，我清理浏览器缓存和cookie再打开内网网址进行o1的使用，没有以上bug的发生

**Comment by Richter2024** [comment]
![无标题](https://github.com/user-attachments/assets/b0f9a74a-8e78-47c5-a094-dc2412759b16)
o1报错临时方案
top_p=1
presence_penalty=0
frequency_penalty=0
使用这组参数就可以使用了，但是因为参数会影响性能，还是要等作者更新更彻底的解决吧。
