### ISSUE TITLE
公式渲染bug

### ISSUE THREAD

**Issue by popjane** [Dooy/chatgpt-web-midjourney-proxy#501]
使用o1系列模型提问

```
你是一个数学能力非常强的数学老师，帮我完成这道题：$f(u)=u^{2}+au+b-2,u=(x+\frac{1}{x})$，若f(u)有零点，求$a^2+b^2$的最小值
```

会无法渲染结果，只显示一个空白结果，而实际已经回复成功。

**Comment by Dooy** [comment]
能否 截图看看？

**Comment by Dooy** [comment]
把输出 调大些 很大的可能是 思考已经把你的token用完了

<img width="386" alt="image" src="https://github.com/user-attachments/assets/e5ea6c9a-4cd6-425c-8b8e-85dec57564d7">
