### ISSUE TITLE
请问，生成的视频的删除？

### ISSUE THREAD

**Issue by heitaokjcr** [Dooy/chatgpt-web-midjourney-proxy#510]
删除记录选项好难找

**Comment by heitaokjcr** [comment]
还是说没有删除选项？。

**Comment by Dooy** [comment]
后面加上

**Comment by ArcaneWhispers** [comment]
同求删除功能 一堆不需要的绘画、音乐、视频记录

**Comment by Dooy** [comment]
收到 后面加到开发计划中 
这周一直在搞 realtime 是个新东西花时间比较长

**Comment by Dooy** [comment]
v2.21.5 已经修复 请更新至到这个版本

**Comment by houlangs** [comment]
v2.21.9，请问如何删除画廊中的图片？没找到按钮😅

**Comment by houlangs** [comment]
> v2.21.5 已经修复 请更新至到这个版本
v2.21.9，请问如何删除画廊中的图片？没找到按钮😅
