### ISSUE TITLE
Luma Fail with HK Station  with other providers I get invalid JSON error.

### ISSUE THREAD

**Issue by spammenotinoz** [Dooy/chatgpt-web-midjourney-proxy#511]
Hi is Luma broken on HK station or just my setup?

![image](https://github.com/user-attachments/assets/be35c0dc-b373-4361-ad61-4773bb8035fe)

Tried with other providers and get invalid JSON so perhaps it is me.

**Comment by Dooy** [comment]
please use pro

<img width="602" alt="image" src="https://github.com/user-attachments/assets/81019648-ae8f-4e90-80e9-1db2076d47d8">

**Comment by spammenotinoz** [comment]
Thank-you for responding so quickly.  Thanks Pro works.
