### ISSUE TITLE
能否支持清除上下文的功能

### ISSUE THREAD

**Issue by hp0912** [Dooy/chatgpt-web-midjourney-proxy#512]
使用场景：

作为开发者，向 GPT 问问题的时候，大部分都是一问一答就完了，少部分需要继续追问，问下一个问题的时候清除上一个问题的上下文就是一个比较好的方式。

在全局设置里面设置上下文数量感觉也不是很好，每个绘画单独设置也挺麻烦的，右上角的删除聊天记录也不是很合适，像`ChatGPT-Next-Web`这种交互方式我觉得体验就很好，希望这个特性能跟上

<img width="905" alt="image" src="https://github.com/user-attachments/assets/38d043e4-2333-480f-8913-f088660562d4">

**Comment by Dooy** [comment]
<img width="654" alt="image" src="https://github.com/user-attachments/assets/98d0077b-6a3f-4abd-b6e6-1e52cd94b25f">

调整下 就能达到你的要求

**Comment by hp0912** [comment]
> <img alt="image" width="654" src="https://private-user-images.githubusercontent.com/3765401/371988106-98d0077b-6a3f-4abd-b6e6-1e52cd94b25f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODIwMDMsIm5iZiI6MTcyNzY4MTcwMywicGF0aCI6Ii8zNzY1NDAxLzM3MTk4ODEwNi05OGQwMDc3Yi02YTNmLTRhYmQtYjZlNi0xZTUyY2Q5NGIyNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMDczNTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjA3MzEzY2FjMmQ3OGRkMjQzODc4YTYxNDU3YmU4NTkxYzU5ZWQ5NmY1MDY3NmZiNjNlOTdkNmQ5NzI4ZGVlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.i2LEXtQ1u3woJCZjRYrEoxAyLhD9q77BxfVmMxSI-DU">
> 调整下 就能达到你的要求

感谢回复，这个其实不是很方便，大部分场景下可以设置成 0，但是还是有追问的场景的。

**Comment by Dooy** [comment]
明白了 你的需求了
