### ISSUE TITLE
你好，UI部分很NICE，但是试用后完全不是一回事啊。

### ISSUE THREAD

**Issue by Changego** [Dooy/chatgpt-web-midjourney-proxy#52]
你好，UI部分很NICE，但是试用后完全不是一回事啊。功能缺失太多了啊。
测试了很多功能不能用啊。
比如换脸的。
{
  "timestamp": "2023-12-28T07:11:03.949+00:00",
  "status": 404,
  "error": "Not Found",
  "path": "/mj/insight-face/swap"
}

**Comment by Dooy** [comment]
大哥 需要你后端支持
你后端支持不了 你怪我前端？

**Comment by Changego** [comment]
哦哦。了解了，需要midjourney-proxy-plus。。哈哈
我的。
