### ISSUE TITLE
我想知道GPT Store中的数据是怎么来的

### ISSUE THREAD

**Issue by guanzhenxing** [Dooy/chatgpt-web-midjourney-proxy#520]
发现 GPT Store中的数据来自于接口https://gpts.ddaiai.com/open/gpts。这个应该是作者的自己部署的接口吧，有个问题就是，这里的数据是从哪边来的呢？谢谢

**Comment by Dooy** [comment]
网上抓的 那么多收集gpts的站点

这边也能新增
<img width="724" alt="image" src="https://github.com/user-attachments/assets/ef6a136d-b4ef-479d-b46f-a3dee15209f1">

**Comment by guanzhenxing** [comment]
明白了。谢谢哈！
