### ISSUE TITLE
用户未拥有转发API权限

### ISSUE THREAD

**Issue by kuhubmk** [Dooy/chatgpt-web-midjourney-proxy#524]
{
  "error": {
    "message": "用户未拥有转发API权限：1. 通过github登录，且github账户注册时间>=31天，且至少含有1个公开仓库及3个关注便可使用；2.通过linuxdo登录，且等级>=1级便可使用 (request id: 20241012231555134725894ugR2y7DZ)",
    "type": "voapi_error"
  }
}

条件我应该都是满足的，注册几年了，公开仓库也有啊，关注也不止3个！为什么无法使用？？

**Comment by Dooy** [comment]
请问你的中转 而不是问我
