### ISSUE TITLE
使用realtime还要额外填写地址和密钥

### ISSUE THREAD

**Issue by Qin-shun-Li** [Dooy/chatgpt-web-midjourney-proxy#525]
尽管在部署的时候已经设置过OPENAI_API_KEY和OPENAI_API_BASE_URL
但使用realtime的时候还要重新填一遍

能否将realtime的OPENAI_API_KEY和OPENAI_API_BASE_URL 与 配置docker compose文件的OPENAI_API_KEY和OPENAI_API_BASE_URL同步 ？

或者在docker环境中，单独为realtime 加上一个url 和 key

**Comment by Dooy** [comment]
realtime 需要websocket 支持，目前的express 框架支持得不好 需要单独搞

**Comment by itdsee** [comment]
docker 环境下有什么办法可以单独加一个url和Key 呢
