### ISSUE TITLE
上传和默认模型问题

### ISSUE THREAD

**Issue by lbersl** [Dooy/chatgpt-web-midjourney-proxy#527]
已经设置
 -e API_UPLOADER=0 
但是还是可以上传图片
![image](https://github.com/user-attachments/assets/44009ac1-f73c-40c3-a029-25edbce2a836)

-e OPENAI_API_MODEL=gpt-4o-mini
但是打开网页以后还是3.5是默认
![image](https://github.com/user-attachments/assets/a56fed21-2b38-430d-86cf-8a216eea7f74)

**Comment by Dooy** [comment]
问题2  请用 无痕浏览器 打开试一试

因为这个是 最最开始 的默认模型

**Comment by Dooy** [comment]
直接去掉 `-e API_UPLOADER=0`  试下
