### ISSUE TITLE
openai realtime 是否支持docker传参

### ISSUE THREAD

**Issue by itdsee** [Dooy/chatgpt-web-midjourney-proxy#528]
内部使用，没办法把key给到大家，那个参数可以复用openai的地址和key

**Comment by LovelyGuYiMeng** [comment]
> 目前不支持 目前的Docker是 express 对websocket 支持不好 还有 Realtime的录音 需要 https 需要ssl证书 就需要域名支持

realtime一直websocket无法链接是怎么回事，怎么解决呢

**Comment by Dooy** [comment]
直接填写中转的接口地址 和key啊
