### ISSUE TITLE
调用 GPTS 里的模型会为什么说没有权限

### ISSUE THREAD

**Issue by littlekie** [Dooy/chatgpt-web-midjourney-proxy#529]
{
  "error": {
    "message": "The model `g-OhCVT2jDy` does not exist or you do not have access to it.",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}
但是调用公有模型能正常响应，有人碰到这个问题吗

**Comment by Dooy** [comment]
最好 别用 g-* 模型 ，下图的地方设置，而是用 gpt-4-gizmo-g-*

<img width="621" alt="image" src="https://github.com/user-attachments/assets/25d56021-d846-45d7-ad63-12490d4593f5">

**Comment by Dooy** [comment]
还有联系你下你的中转，  确认下gpts 是 g-***开头的么？

**Comment by littlekie** [comment]
> 还有联系你下你的中转， 确认下gpts 是 g-***开头的么？

我是直接直接用官方gpts ，直接从回话id取的
你这边可以使用官方的模型吗

**Comment by littlekie** [comment]
> 最好 别用 g-* 模型 ，下图的地方设置，而是用 gpt-4-gizmo-g-*
> 
> <img alt="image" width="621" src="https://private-user-images.githubusercontent.com/3765401/376653473-25d56021-d846-45d7-ad63-12490d4593f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDI4OTksIm5iZiI6MTcyOTA0MjU5OSwicGF0aCI6Ii8zNzY1NDAxLzM3NjY1MzQ3My0yNWQ1NjAyMS1kODQ2LTQ1ZDctYWQ2My0xMjQ5MGQ0NTkzZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDEzNjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDMwODEzNTRkMDQyY2RjNDNkMjQxZjZjZmE4YzA1MGJlYTYyOTM1NGRhMzVhZDU5ZDAxNDgwZjU4MGNiZTZkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-ufCc_lEBezhzmAkfqTEo6TYe_8Brs6jhtQCsDaGSmw">

**Comment by littlekie** [comment]
> 最好 别用 g-* 模型 ，下图的地方设置，而是用 gpt-4-gizmo-g-*
> 
> <img alt="image" width="621" src="https://private-user-images.githubusercontent.com/3765401/376653473-25d56021-d846-45d7-ad63-12490d4593f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDI4OTksIm5iZiI6MTcyOTA0MjU5OSwicGF0aCI6Ii8zNzY1NDAxLzM3NjY1MzQ3My0yNWQ1NjAyMS1kODQ2LTQ1ZDctYWQ2My0xMjQ5MGQ0NTkzZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDEzNjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDMwODEzNTRkMDQyY2RjNDNkMjQxZjZjZmE4YzA1MGJlYTYyOTM1NGRhMzVhZDU5ZDAxNDgwZjU4MGNiZTZkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-ufCc_lEBezhzmAkfqTEo6TYe_8Brs6jhtQCsDaGSmw">

我打勾和没有打勾都试了，都不行
