### ISSUE TITLE
官方 GPTS 还能用接口调用吗？

### ISSUE THREAD

**Issue by littlekie** [Dooy/chatgpt-web-midjourney-proxy#530]
我是用官方 gpts id 没有用中转，目前一定是要用中转才能用吗？还是都不能用了
![image](https://github.com/user-attachments/assets/7aa84bb4-241e-40fe-8b1e-1360b094d877)

**Comment by Dooy** [comment]
不需要 ，等问下你的中转  这个错误值中转的服务端 抛出来的
