### ISSUE TITLE
希望能增加一键切换多组服务器和API Key的功能

### ISSUE THREAD

**Issue by JasonxlxCharles** [Dooy/chatgpt-web-midjourney-proxy#531]
现在只能在设置中一次填写一条，可是我这里有很多商家的，需要根据使用不同模型切换（比如有的商家用语音比较便宜，有的用4o比较便宜）

希望能添加一键切换功能，而不是现在这样在设置中一项服务只能填写一组服务器与API Key

谢谢！

**Comment by Dooy** [comment]
你不知道 有个开源在 叫 one-api 就做这个事的？
