### ISSUE TITLE
部署后绘图舞蹈文件上传均出现报错

### ISSUE THREAD

**Issue by TerLand0berver** [Dooy/chatgpt-web-midjourney-proxy#535]
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
使用gpt-mj-file部署全套,使用new-api调用前端传入key
https://example.new-api.com/#/?settings={\"key\":\"{key}\",\"url\":\"{address}\"}"

**Comment by Dooy** [comment]
需要中转支持
