### ISSUE TITLE
设置UPLOAD_TYPE=R2不起作用

### ISSUE THREAD

**Issue by Zhuying-Net** [Dooy/chatgpt-web-midjourney-proxy#537]
配置了R2，在不配置OPENAI_API_BASE_URL的情况下，上传文件显示状态为成功。
但是如果配置了OPENAI_API_BASE_URL和R2，那么上传文件的请求地址就会变成OPENAI_API_BASE_URL，并不会上传到R2。我尝试设置UPLOAD_TYPE=R2，但是完全不起作用

**Comment by Dooy** [comment]
相应的R2 有设置了没？
要设置了 才会过去

**Comment by Zhuying-Net** [comment]
> 相应的R2 有设置了没？ 要设置了 才会过去

R2_DOMAIN=
R2_BUCKET_NAME=
R2_ACCOUNT_ID=
R2_KEY_ID=
R2_KEY_SECRET=

按照要求，已经设置了以上的信息，并且在没有配置OPENAI_API_BASE_URL的情况下测试通过，配置了OPENAI_API_BASE_URL就上传不了

**Comment by Rebellce** [comment]
xd, 解决了没？我也是配了r2完全不起作用，我不知道是不是我的r2哪填错了。我看f12（仅测试md的上传文件）一直是走前端填的Midjourney的接口地址。我删除以后又变成当前的域名了，就是死活不走r2
