### ISSUE TITLE
Pika貌似有个小bug

### ISSUE THREAD

**Issue by suyunkai** [Dooy/chatgpt-web-midjourney-proxy#538]
大佬，Pika的使用，是不是加了一个检测HK KEY的逻辑，非HK KEY不能用？
但是貌似这个逻辑加在了Runway上，我如果只填pika的api参数，不能用。runway也要加上，才能用

**Comment by Dooy** [comment]
其他非HK的key 需要中转支持

需要相应的逆向的api

runway 参数已经很乱但 逻辑比较简单些， 你可能直接用 runway的api 就可以了

pika 参数更乱 所以后端就改了改吧
