### ISSUE TITLE
 模型生成的文字不到1000字符就中断，怎么设置？

### ISSUE THREAD

**Issue by ok5288** [Dooy/chatgpt-web-midjourney-proxy#539]
模型生成的文字不到1000字符就中断，在模型设置里面调整“回复数”(max_tokens)到“4096”，还是不能长文本回复？怎么办？谢谢！
![Uploading output.png…]()

**Comment by ok5288** [comment]
![output](https://github.com/user-attachments/assets/d9a7913d-efd0-4254-a72b-060c32ff51b5)

**Comment by ok5288** [comment]
多次实测，大约700-800个tokens就中断了。

**Comment by ok5288** [comment]
在文件“service/src/chatgpt/index.ts”文件L56后添加修改成下面内容,还是没有改善：
else if (/-4o-mini/.test(model.toLowerCase())) {
        options.maxModelTokens = 128000
        options.maxResponseTokens = 16384
      }
     // if use GPT-4 Turbo or GPT-4o
      else if (/-preview|-turbo|o/.test(model.toLowerCase())) {
        options.maxModelTokens = 128000
        options.maxResponseTokens = 4096
      }
      else {
        options.maxModelTokens = 8192
        options.maxResponseTokens = 2048
      }
    }
    else if (model.toLowerCase().includes('gpt-3.5')) {
      if (/16k|1106|0125/.test(model.toLowerCase())) {
        options.maxModelTokens = 16384
        options.maxResponseTokens = 4096
      }
    }
    
    希望能得到指导！谢谢！

**Comment by Dooy** [comment]
这儿调整，openai的模型 应该都有设置好了 用户可自己调节
<img width="805" alt="image" src="https://github.com/user-attachments/assets/75f6f64d-de90-4a8a-9dca-4fcd44c000d2">

**Comment by ok5288** [comment]
对的，在模型设置里面调整“回复数”(max_tokens)到“4096”，但是，还是没作用。

**Comment by ok5288** [comment]
回复到1000不到的字符后就中断，要不停的输入【continue】,继续。

**Comment by Dooy** [comment]
大模型 就喜欢你 continue 蛤蛤
