### ISSUE TITLE
Improve Usability and UI in Maker v6.1 - Focus on Sidebar, MidJourney Explore, Session Persistence, and Language Selection 改进Maker v6.1的可用性和UI - 侧边栏、MidJourney Explore、会话持久性和语言选择

### ISSUE THREAD

**Issue by fisforfaheem** [Dooy/chatgpt-web-midjourney-proxy#541]
默认版本：目前，Maker默认选择的是6.1版本。若用户可以选择自己偏好的版本并在会话中记住该选择，将极大提升用户体验。

UI改进：左侧面板（侧边栏）可以更具视觉吸引力且更便于使用。增强其布局和设计将有助于用户更高效地浏览。

MidJourney Explore功能：如果可能，添加MidJourney Explore功能，使用户可以直接从应用内浏览midjourney.com上的所有公开图片。

会话持久性：登录用户在5-10分钟不活跃后会被注销，需要重新登录。若增强会话持久性将极大改善用户体验。此外，意外重置和删除cookies也会中断工作流程，修复这些问题会使体验更佳。

**语言选择：可以优化英语语言的选择体验，使其更直观，更便于英语用户使用。**

Default Version: Currently, Maker version 6.1 is always selected by default. It would enhance usability if users could select their preferred version, and have the app remember this choice across sessions.

UI Improvements: The left panel (sidebar) could be more visually appealing and user-friendly. Enhancing its layout and design would help users navigate more efficiently.

MidJourney Explore Feature: If feasible, adding an Explore feature for MidJourney would allow users to browse all public images on midjourney.com directly from the app.

Session Persistence: Logged-in users are logged out after 5-10 minutes of inactivity, which requires re-login. Enhancing session persistence would greatly improve the user experience. Also, resetting and deleting cookies unexpectedly disrupts workflow—addressing this would be beneficial.

Language Selection: The English language selection experience could be streamlined and made more intuitive, making the app more accessible to English-speaking users.

**Comment by Dooy** [comment]
Default Version:  You mean MidJourney version?
UI Improvements: Do you have any reference? Otherwise, I don't know how to improve it.
MidJourney Explore Feature: good idea
Session Persistence: It may be related to the browser, I have no restrictions. please retry
Language Selection: The next version will resolve this issue

**Comment by fisforfaheem** [comment]
Session Persistence & Login Timeouts: I’m still experiencing session timeouts after around 5 minutes of inactivity, which requires frequent logouts and re-logins. Reducing the frequency of these timeouts would make the app much smoother to use. Additionally, any solutions to prevent unexpected logouts from cookie resets or timeouts would be appreciated.

Wait Times for Image Prompts: The waiting time between image prompts is currently quite long, which interrupts workflow. If possible, reducing or disabling this delay would significantly improve the experience for users who rely on rapid image generation.

Language Selection, UI Improvements, and Default Version: Thank you for the updates on these areas! Excited to see the improved English language selection experience in the next version, as well as any UI refinements for the sidebar.

MidJourney Explore Feature: Happy to know this is under consideration—an Explore feature would be a fantastic addition!

**Comment by Dooy** [comment]
Session Persistence:  Our authentication is not through cookies, but by storing the key in localStorage.

> Session Persistence: While it may partly depend on browser settings, implementing a longer session duration within the app itself could be beneficial. Users being logged out due to brief inactivity disrupts the workflow, so a more robust approach might help. Also, ensuring that unexpected cookie resets or deletions don't impact session persistence would further improve the experience.
> 
> UI Improvements: If there are no specific references for the sidebar, I’d suggest a cleaner, more spacious layout that organizes options in a way that’s visually easier to navigate. Perhaps increasing the contrast or adding icons might make it more user-friendly.
> 
> MidJourney Explore Feature: Glad you like the idea! This feature could attract more users interested in browsing public MidJourney images within the app.

**Comment by fisforfaheem** [comment]
kidnl just imrpove the Ui and add full english support
