### ISSUE TITLE
ideogram跨域无解

### ISSUE THREAD

**Issue by ArcaneWhispers** [Dooy/chatgpt-web-midjourney-proxy#544]
在go后端路由中间件开放了跨域。其它绘画视频模型都正常，就ideogram死活跨域，vite.config配置了也无用，环境变量设置了IDEO_SERVER也没用

大佬看下咋解决下

**Comment by Dooy** [comment]
自己分析下header 就好了
如果你是 逆向 看下 是不是 你后端的后端 有带header过来 你的后端没过滤

带图看下你的header 就好了

**Comment by ArcaneWhispers** [comment]
> 自己分析下header 就好了 如果你是 逆向 看下 是不是 你后端的后端 有带header过来 你的后端没过滤
> 
> 带图看下你的header 就好了

感谢，是上游的问题
