### ISSUE TITLE
客户端无法使用麦克风

### ISSUE THREAD

**Issue by chiguabaobao** [Dooy/chatgpt-web-midjourney-proxy#545]
老板，报个问题，windows版本的程序无法使用麦克风，截图如下。
感觉像是浏览器内核的https权限限制导致的，但EXE程序没有办法添加对应浏览器的白名单，还请老板看看能不能在程序哪里设置，谢谢！
<img width="724" alt="1" src="https://github.com/user-attachments/assets/2e377db0-b659-40d1-b7f9-1925eb8b6c1a">
<img width="716" alt="2" src="https://github.com/user-attachments/assets/cccd127c-a195-40e0-9936-104477386baa">

**Comment by Dooy** [comment]
windows 下  Chrome 试下网页行么？

https://vercel.ddaiai.com/

**Comment by chiguabaobao** [comment]
老板抱歉，已确认是本地麦克的问题，给您添麻烦了
