### ISSUE TITLE
按照ChenZhaoYu的测试环境配置后仍然无法打开前端

### ISSUE THREAD

**Issue by YukiOvOb** [Dooy/chatgpt-web-midjourney-proxy#547]
![1](https://github.com/user-attachments/assets/e49ac4cd-11dc-4bf6-acfe-ead9ab8da830)
![2](https://github.com/user-attachments/assets/3d8e1d25-05c9-4aa7-ab4a-fffc9fa7e4b1)
![3](https://github.com/user-attachments/assets/fe76efed-6810-4c6a-b42f-0f176263b7cf)
如图，前端后端已经env都已经配置好了，能够启动，API与API链接都已经填在了env里，但是前端打开仍然是error500
![image](https://github.com/user-attachments/assets/447bdd3d-e3cd-4685-b747-fa26add6d819)
防火墙da端口3002和1002都打开了

**Comment by Dooy** [comment]
前端的 .env 改下
VITE_APP_API_BASE_URL=http://127.0.0.1:3002 
#VITE_APP_API_BASE_URL=http://192.168.31.186:3002

**Comment by YukiOvOb** [comment]
谢谢大佬，已经改好了！
