### ISSUE TITLE
前台npm 安装运行报错

### ISSUE THREAD

**Issue by nels20000** [Dooy/chatgpt-web-midjourney-proxy#548]
Error: The following dependencies are imported but could not be resolved:

  @openai/realtime-api-beta/dist/lib/client.js (imported by E:/aiapi2/src/views/wav/realtime.vue?id=0)
  vue-waterfall-plugin-next/dist/types/types/waterfall (imported by E:/aiapi2/src/views/kling/kgList.vue?id=0)

以为是版本太新了，waterfall降级以后依然报这个错误

**Comment by Dooy** [comment]
import { ItemType } from '@openai/realtime-api-beta/dist/lib/client.js';

这个引起的

**Comment by nels20000** [comment]
那请问应该怎么解决呢

**Comment by Dooy** [comment]
应该是 npm 版本的问题 ，其他地方都能编译过去

比如我本地， 比如github打包

**Comment by Dooy** [comment]
在vite.conf.ts

```ts
 '@': path.resolve(process.cwd(), 'src'),
         'openai-realtime-api-beta-client': '@openai/realtime-api-beta/dist/lib/client.js',
         'vue-waterfall-plugin-next-waterfall': 'vue-waterfall-plugin-next/dist/types/types/waterfall',
      },
    },
```
<img width="818" alt="image" src="https://github.com/user-attachments/assets/84a6b148-0313-4df1-b72f-88cf34c28d6f">

然后在 相应的地方 替换下 就好
```ts
import { ItemType } from 'openai-realtime-api-beta-client';
```
