### ISSUE TITLE
本地部署IdeoGram一直404报错，docker部署就没问题

### ISSUE THREAD

**Issue by YukiOvOb** [Dooy/chatgpt-web-midjourney-proxy#549]
![image](https://github.com/user-attachments/assets/4f89df20-01d2-4d5b-a8da-7f8b76e8a90e)

**Comment by Dooy** [comment]
你的后端中转支持么？

**Comment by YukiOvOb** [comment]
大佬，怎么看中转支持不，或者怎么操作才能让中转支持？我在网上搜了这个问题也没有答案。目前我就只部署了一个香港的服务器在跑这个项目，也没有中转服务器。如果需要中转那要怎么设置呢？

**Comment by Dooy** [comment]
用 www.openai-hk.com 支持 我readme里有写

**Comment by YukiOvOb** [comment]
![image](https://github.com/user-attachments/assets/c5b551e8-846a-40c5-b68e-803e19df030d)
是的，我是用的www.openai-hk.com，api_key也是用的openai-hk里买的

**Comment by Dooy** [comment]
你后端没起来
```shell
cd service
#先 pnpm install 
pnpm run dev
```
