### ISSUE TITLE
Some suggestions that can be optimized

### ISSUE THREAD

**Issue by Hellen20030926** [Dooy/chatgpt-web-midjourney-proxy#55]
1.On the left side of the interface, "GPTs" are changed to "GTPs".
2.I don't know how to create my own ChatGPT (GPTs), I only know that I can use other people's ChatGPT through the GPT store.
3.I don't know how to create my own ChatGPT (GPTs), I only know that I can use other people's ChatGPT through the GPT store, so I hope to be able to add this feature

**Comment by Hellen20030926** [comment]
bug


{
  "error": {
    "message": " (request id: 20240101161750287279076jQh2rLXA)",
    "type": "upstream_error",
    "param": "503",
    "code": "bad_response_status_code"
  }
}

**Comment by Dooy** [comment]
> 1.On the left side of the interface, "GPTs" are changed to "GTPs". 2.I don't know how to create my own ChatGPT (GPTs), I only know that I can use other people's ChatGPT through the GPT store. 3.I don't know how to create my own ChatGPT (GPTs), I only know that I can use other people's ChatGPT through the GPT store, so I hope to be able to add this feature

1 .  `GTPs` ?  Is it my spelling error, `chatGPT` or `chatGTP`? 
2 .  This project only supports `how to use GPTs`;  and GPTs API are interfaces obtained through reverse engineering , you can review the issue #28  and #34

**Comment by Hellen20030926** [comment]
yeah~
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/152983484/24f3532b-296b-4a8d-9a53-76642309a1db)

**Comment by Dooy** [comment]
The v2.13.7 has resolved this issue

**Comment by Hellen20030926** [comment]
The word limit for midjourney, V6 prompt input is too small, and the normal midjourney prompt word input is more than 500 letters in our view

**Comment by Hellen20030926** [comment]
V6对比V5.2提示词数量是有提升的，希望能优化，我们正常放在midjourney里面的提示词，放在了这里则显示超量

**Comment by Dooy** [comment]
> The word limit for midjourney, V6 prompt input is too small, and the normal midjourney prompt word input is more than 500 letters in our view

Ok, I will upgrade in the next version.
