### ISSUE TITLE
对话生成过程中，无法选中文本，且“复制代码”按钮失效

### ISSUE THREAD

**Issue by aloha-neko** [Dooy/chatgpt-web-midjourney-proxy#550]
复现方法：对 LLM 说“用 python 写个 splay”，在 LLM 回答中途：
- 试图选中 LLM 回答的文本，则零点几秒后会失去选中。
- “复制代码”按钮无效。

![image](https://github.com/user-attachments/assets/82139224-1c31-436a-a69a-45a3bf7ef08a)

**Comment by Dooy** [comment]
在回调的时候 复制有问题吧 
这个过程中 复制不了 因为web一直在渲染
