### ISSUE TITLE
实时通话的使用问题

### ISSUE THREAD

**Issue by magicdmer** [Dooy/chatgpt-web-midjourney-proxy#552]
软件版本：2.21.10
API后端：newapi

我打开语音通话后，显示连接成功，然后接下来我说话也成功录制了，然后直接显示断开，没有听到回复语音
通过newapi的后端日志，显示是调用成功了：
![image](https://github.com/user-attachments/assets/468f1991-5676-4906-8480-c4fb8d54ddc7)

**Comment by Dooy** [comment]
是 https 吧

**Comment by magicdmer** [comment]
> 是 https 吧

是的，另外我下的windows本地客户端

**Comment by magicdmer** [comment]
今天又试了一下，偶尔能成功对话一句，然后随之断开。能用，但是很不稳定

**Comment by Dooy** [comment]
能否问下 你中转？大部分是因为网络问题

**Comment by magicdmer** [comment]
> 能否问下 你中转？大部分是因为网络问题
我是搬瓦工CN2线路，美国，网络应该还不错，newapi就搭建在上面。我看日志也都有回复。
ps：不过也没事，我试了一下，感觉它中文语音回复贼生硬，老外说中文的感觉，我就尝尝鲜，一般也不用这功能，随缘了
