### ISSUE TITLE
文件上传和识图

### ISSUE THREAD

**Issue by zu-ke** [Dooy/chatgpt-web-midjourney-proxy#555]
### 尊敬的作者
   你好，最新版本中：
- 上传文件，似乎只能使用gpt-4-all和gpt-4o-all，能否自己指定可以上传文件的模型？或者自动检测当前模型是否支持文件上传，不局限于上述两个模型。
- 识图模型，能不能让用户自行选择，不使用默认的识图模型？我已认真阅读readme，但是没找到解决我上述两个问题的办法。

**Comment by Dooy** [comment]
-all 模型 或者gpts里面的模型 都支持文件上传

**Comment by Dooy** [comment]
gpt-4-all和gpt-4o-all 跟识图是不一样的

gpts 只得用url链接，识图都是base64

**Comment by zu-ke** [comment]
> -all 模型 或者gpts里面的模型 都支持文件上传

![QQ20241115-201616](https://github.com/user-attachments/assets/d55eb4a0-671f-4f18-9516-c60d9564da74)
你好，我选择了gpts中的这个模型，但是这个提示的还是上传图片。意思是只能给模型类似阿里云oss某个文件的访问链接，来实现文件上传吗？

**Comment by Dooy** [comment]
<img width="855" alt="image" src="https://github.com/user-attachments/assets/86a98c2e-5caf-41a8-a87e-649f994469b9">

**Comment by zu-ke** [comment]
哈哈，这是我的docker-compose.yml，看来是我的问题
![QQ20241115-202234](https://github.com/user-attachments/assets/239d9e65-af21-4d84-b860-3949b4ddf206)
