### ISSUE TITLE
如何增加上传文件/图片的大小限制，（包括本地部署）

### ISSUE THREAD

**Issue by dapengai135** [Dooy/chatgpt-web-midjourney-proxy#556]
图片上传的大小限制是1mb，影响清晰度，尤其是图生成视频的清晰度，可否增加或者自主设置大小？或者有什么解决方式呢？

**Comment by Dooy** [comment]
看下 reamde 能设置的

<img width="852" alt="image" src="https://github.com/user-attachments/assets/14fe2ae7-e5a1-455d-a074-6287439ccec7">
