### ISSUE TITLE
runway视频生成错误

### ISSUE THREAD

**Issue by qzkingjz** [Dooy/chatgpt-web-midjourney-proxy#557]
在使用runway的api生成视频的时候，为什么会提示跨域|CORS error

**Comment by Dooy** [comment]
可能你得联系下 中转是否支持

如果支持请他解决下服务端跨域的问题

<img width="656" alt="image" src="https://github.com/user-attachments/assets/d5802410-17ed-4cf3-823f-5ec12b9ed3e4">
