### ISSUE TITLE
chatgpt支持流式输出吗？如何设置

### ISSUE THREAD

**Issue by catninelife** [Dooy/chatgpt-web-midjourney-proxy#56]
感谢提供这么好的工具。我使用vercal部署的，现在是“正在思考”，然后一次性输出，如何改成流式输出？

**Comment by Dooy** [comment]
你是不是 前面 vercal 套了一层是么？ vercal 是支持流输出的
如果是你前面套了 一层NGINX,配置 需要 `proxy_buffering off;`

**Comment by catninelife** [comment]
谢谢大佬解答。没有做其他的，我是直接vercal部署的...

**Comment by Dooy** [comment]
你可以 直接在前端ui的设置里面吧 base_url 填上去试下
<img width="460" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/1352325b-088f-47ab-90b8-87ccbe19e0b4">

**Comment by catninelife** [comment]
在前端填入base_url和key是流式输出...  这是什么原因? 谢谢大佬

**Comment by Dooy** [comment]
vercal 不支持流输出 相关配置 没见过如果有 
你可以提供下
