### ISSUE TITLE
请教 O1模型报错是什么原因呀？最新4o模型多久可以更新一下呀

### ISSUE THREAD

**Issue by zyjfly** [Dooy/chatgpt-web-midjourney-proxy#561]
![image](https://github.com/user-attachments/assets/f78b2dca-1105-46c6-9acb-7a67ec5ee911)
![image](https://github.com/user-attachments/assets/52529c35-b417-48cd-a77f-c0aa1ae59c89)

**Comment by Dooy** [comment]
中转不支持导致的吧

**Comment by Rebellce** [comment]
右下角的max-token设置大一点试试呢，o1好像max-token太小了就生成不出来
