### ISSUE TITLE
局部重绘这几天好像都出现问题

### ISSUE THREAD

**Issue by ttfes888** [Dooy/chatgpt-web-midjourney-proxy#562]
局部重绘这几天好像都出现问题

**Comment by ttfes888** [comment]
![微信截图_20241125172714](https://github.com/user-attachments/assets/251bafd3-333a-4369-80fc-3994ac2f49a9)
![微信截图_20241125172937](https://github.com/user-attachments/assets/85fd64e2-164c-4c82-b044-ca67e36a807b)
![微信截图_20241125172954](https://github.com/user-attachments/assets/9d7716c0-c094-48f3-89e8-35ce02bf893f)

**Comment by Dooy** [comment]
恢复了

**Comment by ttfes888** [comment]
> 恢复了
好的，谢谢。请问这个问题是什么原因导致的？好像隔一段时间就会出现一次。

**Comment by Dooy** [comment]
要不 支持下项目 买好点的服务器 和cdn
