### ISSUE TITLE
微软Azure的openai支持

### ISSUE THREAD

**Issue by dragon0629** [Dooy/chatgpt-web-midjourney-proxy#563]
请问对白是否可以选择使用微软Azure的openai的节点和KEY，而不是必须使用chatgpt？

**Comment by Dooy** [comment]
可以用 oneapi 转下
前端没去做匹配了

**Comment by dragon0629** [comment]
啊，感谢回复
我之前尝试填入azure的edpoint 和key，url和key是正确的，在python中可以正常调用
但在本web里，他会返回

{
  "error": {
    "code": "404",
    "message": "Resource not found"
  }
}

请问您说的用oneapi转下是指这个项目吗？
用azureai的key和节点转成openai的格式？

**Comment by dragon0629** [comment]
> 可以用 oneapi 转下 前端没去做匹配了

啊，感谢回复
我之前尝试填入azure的edpoint 和key，url和key是正确的，在python中可以正常调用
但在本web里，他会返回

{
"error": {
"code": "404",
"message": "Resource not found"
}
}

请问您说的用oneapi转下是指这个项目吗？
https://github.com/songquanpeng/one-api
通过one-api去调azureai的配置
但是似乎这边后台也没有找到填写oneapi的地方
