### ISSUE TITLE
为何Mj用6.1模型没有了放大功能？但是用6.0就有

### ISSUE THREAD

**Issue by Joshua19770704** [Dooy/chatgpt-web-midjourney-proxy#569]
如图，6.0的有放大功能：
![image](https://github.com/user-attachments/assets/683cfd78-7907-4b90-8cc8-8c69a2e1cc8d)

6.1的就没有了放大功能：
![image](https://github.com/user-attachments/assets/b4473afc-fdc7-4ef2-9f2d-7e6ae0b9d984)

**Comment by Dooy** [comment]
你在  discord.com 试下
