### ISSUE TITLE
api key 不能保存

### ISSUE THREAD

**Issue by ideatechfr** [Dooy/chatgpt-web-midjourney-proxy#570]
是在ui界面保存了key信息，保存后测试可以访问返回信息。换设备访问后就出现key和服务器地址信息都是空，要重新填写。
麻烦这个问题要怎么处理？ 

感谢@

**Comment by Dooy** [comment]
是客户端么？

**Comment by ideatechfr** [comment]
是不同的客户端会出现这个问题

**Comment by ideatechfr** [comment]
另外，我在电脑端登录设置了新的头像、名称、描述这些内容后，在另外一个手机端登录发现还是默认的初始信息。

**Comment by Dooy** [comment]
信息都是保存在 本地的 所以客户端A 不能与客户端B同步
