### ISSUE TITLE
运行日志提示警告

### ISSUE THREAD

**Issue by ideatechfr** [Dooy/chatgpt-web-midjourney-proxy#572]
在dock运行日志里有下面的提示信息
`> node ./build/index.mjs

(node:18) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server is running on port 3002
(node:18) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).`

这个是否会影响运行？谢谢

**Comment by Dooy** [comment]
不影响 就是一些提示
