### ISSUE TITLE
gpt-4o-mini-realtime出了，期待适配

### ISSUE THREAD

**Issue by ArcaneWhispers** [Dooy/chatgpt-web-midjourney-proxy#579]
gpt-4o-mini-realtime出了，期待适配，同时希望可以支持realtime模型切换，辛苦~

**Comment by Dooy** [comment]
v2.22.9 已经适配

<img width="652" alt="image" src="https://github.com/user-attachments/assets/45cad0d6-1446-44c4-aa3e-df9f5039b21b" />

**Comment by ArcaneWhispers** [comment]
感谢，新年快乐！
