### ISSUE TITLE
gpt-4-all上传文件但是提示Invalid URL (POST /v1/upload)

### ISSUE THREAD

**Issue by QHLK** [Dooy/chatgpt-web-midjourney-proxy#58]
有哪位遇到过吗，需要怎么设置
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/132737474/5723d5f7-d7f8-4f05-8e41-682578ba55f9)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/132737474/ac6fbf17-3b7f-4e6b-95c5-c658fb72ef78)

**Comment by Dooy** [comment]
需要你的 中转支持 
如果中转不支持 可以自己设置 `上传地址` （需要跨域支持）
格式可以看readme
