### ISSUE TITLE
手机端的页面绘画不出图，pc页面出图，是BUG

### ISSUE THREAD

**Issue by think007** [Dooy/chatgpt-web-midjourney-proxy#59]
手机端绘画页面不出图，pc绘画页面出图，是BUG

**Comment by Dooy** [comment]
能否提供多些信息
在微信内 还是手机浏览器内？
iphone 还是安卓
是mj 还是dall-e-3

**Comment by think007** [comment]
在微信内 和手机浏览器内，苹果没测试。mj dall-e-3都有，切换到绘画那里然后提交绘画不出图，等半分钟切换到对话显示图片。就是要切换到对话才出图。手机端H5

**Comment by Dooy** [comment]
收到 我回头测试下

**Comment by think007** [comment]
> 收到 我回头测试下

还是没修复这个问题

**Comment by wingjoezhou** [comment]
iphone 8p， Safari  和 google chrome 浏览器都不行， 就是提交了，但不返图，刷新，就变成了 提交中。 电脑可以。
![12681705571541_ pic](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143068873/58b75e14-cecb-4466-9a72-73176434f58b)

**Comment by think007** [comment]
bug提下

**Comment by Dooy** [comment]
我测试了在手机上 确实有bug 
还不好调，用浏览器模拟没问题

**Comment by Dooy** [comment]
v2.14.4 已经修复好 请更新
