### ISSUE TITLE
使用宝塔Docker compose部署出现问题

### ISSUE THREAD

**Issue by jason-xiaobaiai** [Dooy/chatgpt-web-midjourney-proxy#6]
** WARN  Unsupported engine: wanted: {"node":"^16 || ^18 || ^19"} (current: {"node":"v20.10.0","pnpm":"8.11.0"})

> chatgpt-web-service@1.0.0 prod /app
> node ./build/index.mjs

file:///app/build/index.mjs:49
  throw new Error("Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable");
        ^

Error: Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable
    at file:///app/build/index.mjs:49:9
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.10.0
 ELIFECYCLE  Command failed with exit code **

**Comment by Dooy** [comment]
需要 派发一个环境变量 给他 OPENAI_API_KEY=sk-xxxxx 
看看宝塔如何设置环境变量

**Comment by jason-xiaobaiai** [comment]
> 需要 派发一个环境变量 给他 OPENAI_API_KEY=sk-xxxxx 看看宝塔如何设置环境变量

大佬，环境变量那个应该是小问题，关键是这个不知道怎么解决：
WARN Unsupported engine: wanted: {"node":"^16 || ^18 || ^19"} (current: {"node":"v20.10.0","pnpm":"8.11.0"}): 这是一个警告，指示当前 Node.js 的版本（v20.10.0）不符合项目中定义的版本要求（期望是 ^16 || ^18 || ^19）。
用终端直接部署也是同样的报错，部署后docker容器停止运行的状态。

**Comment by jason-xiaobaiai** [comment]
> 这是warn 不太影响使用 ; 这个打包系统用的是 github Actions workflows 提供的 ，可能哪儿设置版本不对

已配置成功，但还有个小问题就是如何将MJ_SERVER和MJ_API_SECRET写进后台设置，写到docker compose里一键部署后MJ变量没有生效，还需要前端填入MJ_SERVER和MJ_API_SECRET；在终端使用docker一键部署运行后也是同样的问题。

**Comment by sunsky89757** [comment]
最新的docker镜像不可用，提示错误：
node:internal/modules/cjs/loader:1147
throw err;
^

Error: Cannot find module '/app/curl'
[90m at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)[39m
[90m at Module._load (node:internal/modules/cjs/loader:985:27)[39m
[90m at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)[39m
[90m at node:internal/main/run_main_module:28:49[39m {
code: [32m'MODULE_NOT_FOUND'[39m,
requireStack: []
}

Node.js v20.10.0
node:internal/modules/cjs/loader:1147
throw err;
^

Error: Cannot find module '/app/curl'
[90m at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)[39m
[90m at Module._load (node:internal/modules/cjs/loader:985:27)[39m
[90m at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)[39m
[90m at node:internal/main/run_main_module:28:49[39m {
code: [32m'MODULE_NOT_FOUND'[39m,
requireStack: []
}

**Comment by Dooy** [comment]
> 最新的docker镜像不可用，提示错误： node:internal/modules/cjs/loader:1147 throw err; ^
> 
> Error: Cannot find module '/app/curl' �[90m at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)�[39m �[90m at Module._load (node:internal/modules/cjs/loader:985:27)�[39m �[90m at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)�[39m �[90m at node:internal/main/run_main_module:28:49�[39m { code: �[32m'MODULE_NOT_FOUND'�[39m, requireStack: [] }
> 
> Node.js v20.10.0 node:internal/modules/cjs/loader:1147 throw err; ^
> 
> Error: Cannot find module '/app/curl' �[90m at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)�[39m �[90m at Module._load (node:internal/modules/cjs/loader:985:27)�[39m �[90m at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)�[39m �[90m at node:internal/main/run_main_module:28:49�[39m { code: �[32m'MODULE_NOT_FOUND'�[39m, requireStack: [] }

解决了 么？
