### ISSUE TITLE
转发Key的余额无法正常显示

### ISSUE THREAD

**Issue by sunsky89757** [Dooy/chatgpt-web-midjourney-proxy#61]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/113254524/1fb544f8-68fc-4c6a-81e7-7400f9a147cb)

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/113254524/1801c257-7baf-49b2-b999-db7d07cbd77e)

本月使用量 = 总使用量

余额匹配不上，希望大大解决，谢谢

**Comment by Dooy** [comment]
这个 仅供参考 
各家中转的虽然都按 openai 的api格式给出 
但是给出的数据都不同 仅靠我前端也搞不定啊

**Comment by sunsky89757** [comment]
可否参考ChatGPT-Next-Web的方式，那边用的老版请求方式，查的是总订阅额度和已使用额度。
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/113254524/a35f4366-d047-4072-aa83-93988ae4eb5b)
``

**Comment by Dooy** [comment]
这个是查询中转的额度么？
新版本好像线下了

**Comment by sunsky89757** [comment]
NextChat（ChatGPT-Next-Web）新版我一直在用，给你截图的就是新版：v2.10.1，挺准确

**Comment by Dooy** [comment]
> NextChat（ChatGPT-Next-Web）新版我一直在用，给你截图的就是新版：v2.10.1，挺准确

收到 谢谢 我参考看看 下个版本 修复下

**Comment by sunsky89757** [comment]
新版本已验证解决，感谢大大
