### ISSUE TITLE
GPTs相关代码

### ISSUE THREAD

**Issue by Bensonlam168** [Dooy/chatgpt-web-midjourney-proxy#62]
你好！请问代码中和GPTs相关的是在哪里？我找了半天没找到，主要是想知道如何增删GPTs的内容？

**Comment by Dooy** [comment]
GPTs的内容是统一远程的，你把缓存清了 
你可以看下 网络请求

**Comment by Dooy** [comment]
> GPTs从商店抽样测过一些，有一些不包含的GPTs，另外，可否加个全部的标签？

把搜索清了 就回到全部了

目前收录的GPTs 可能不全
