### ISSUE TITLE
增加token使用量的显示

### ISSUE THREAD

**Issue by bobandbrony** [Dooy/chatgpt-web-midjourney-proxy#63]
类似这种
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129247570/f0d77da8-a09e-4091-bfe1-8d0e5ffe2fcc)

**Comment by Dooy** [comment]
v2.13.10版本 已支持请更新
<img width="466" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/1f1e7b24-2f59-4151-a67e-72cbdb54f0ec">

**Comment by bobandbrony** [comment]
已确认
