### ISSUE TITLE
能不能不要让上传地址跟着中专地址走

### ISSUE THREAD

**Issue by zhubao12378** [Dooy/chatgpt-web-midjourney-proxy#64]
中专好像都不支持，直接默认写死在网站地址可以么，然后有需要在自己填上传地址，然后限制1m上传能不能改大点

**Comment by Dooy** [comment]
设置里面 能有上传相关的服务地址 
设置了之后 就不会随着中转走了
<img width="560" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/40c0b764-1974-4611-9d06-2aba0435e73d">

**Comment by Dooy** [comment]
v2.14.2 已支持 `cloudflare r2 存储` 免费10G上传
