### ISSUE TITLE
CUSTOM_MODELS的参数设置

### ISSUE THREAD

**Issue by Y1Q1REX** [Dooy/chatgpt-web-midjourney-proxy#65]
你好，请问设置了CUSTOM_MODELS=gpt-3.5-turbo，但是依然可以使用gpt4，并且dallE绘图的关闭是否也是在这里设置。谢谢

**Comment by Dooy** [comment]
这边仅是前端，设置了后 前端没显示了

最好通过 后端（中转）来控制

**Comment by Y1Q1REX** [comment]
刚刚又看了下，参数设置是否和ChatGPT-Next-Web项目一致，其中DISABLE_GPT4=1，及不使用 GPT-4，可能应该能解决。
我使用www.openai-hk.com中转，问了客服，暂时不支持后端限制调用Dall.e。

**Comment by Dooy** [comment]
OK 后续的版本支持下

**Comment by Y1Q1REX** [comment]
辛苦，麻烦了，谢谢

**Comment by Dooy** [comment]
> 刚刚又看了下，参数设置是否和ChatGPT-Next-Web项目一致，其中DISABLE_GPT4=1，及不使用 GPT-4，可能应该能解决。 我使用www.openai-hk.com中转，问了客服，暂时不支持后端限制调用Dall.e。

`DISABLE_GPT4=1` 前端已支持 请更新
