### ISSUE TITLE
token使用量显示错误

### ISSUE THREAD

**Issue by bobandbrony** [Dooy/chatgpt-web-midjourney-proxy#66]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129247570/cdf4cf7f-e8cf-411b-aae1-7a79c4584a06)
1106的上下文有128k，而且这里可用的token为什么这么少？

**Comment by Dooy** [comment]
sorry gpt-4-1106-preview 没单独去处理
下个版本 更新下

**Comment by bobandbrony** [comment]
> sorry gpt-4-1106-preview 没单独去处理 下个版本 更新下

嗯，没事

**Comment by zaohuayudie** [comment]
> sorry gpt-4-1106-preview 没单独去处理 下个版本 更新下

你好，我也在你基础上改加多用户登录，结果发现你代码写完没格式化，升级你的代码冲突太严重，能否加入格式化配置并在保存的时候统一下标准，价格.prettierrc配置。

**Comment by Dooy** [comment]
> > sorry gpt-4-1106-preview 没单独去处理 下个版本 更新下
> 
> 你好，我也在你基础上改加多用户登录，结果发现你代码写完没格式化，升级你的代码冲突太严重，能否加入格式化配置并在保存的时候统一下标准，价格.prettierrc配置。

我试一试

**Comment by Dooy** [comment]
v2.14.1 已修复

**Comment by bobandbrony** [comment]
> v2.14.1 已修复

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129247570/f825c7fe-7828-4b74-8687-f39273bc3d7d)
emmmm好像还是不大对

**Comment by Dooy** [comment]
怎么个不太对？
请把鼠标放上去 有说明

**Comment by bobandbrony** [comment]
> 怎么个不太对？ 请把鼠标放上去 有说明
就是左边的剩余token比右边多，而右边不是总共可用的token吗

**Comment by bobandbrony** [comment]
> 怎么个不太对？ 请把鼠标放上去 有说明

还有vision模型的token没改
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129247570/b01883fd-a4cd-49b6-8091-24a612489e90)

**Comment by Dooy** [comment]
openAI 真是跟人概念 号称128K 居然是 128x1000 不是 128x1024
<img width="848" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/5a132307-e113-4677-aad4-4372193c7097">

**Comment by Dooy** [comment]
v2.14.2 已修复

**Comment by bobandbrony** [comment]
> v2.14.2 已修复

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129247570/4c68002a-b9d5-40a0-9543-7a10348aba50)
似乎还是不大对
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129247570/891c1420-b2ea-47b6-a5a4-016222a94960)
这是我在第三方api网站看到的调用记录，但与本网站显示的token使用量不同

**Comment by Dooy** [comment]
本来 就对不上啊
你现在这个状态 原来都是历史 包含历史了 
86+17 只是上下文历史了
但是除上下文历史还有很多 回复数就去掉 2048 直接就大于（86+17）
好好看剩 咋算出来的
<img width="346" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/55b69b1c-18e1-431b-a09a-22bee115e35d">

**Comment by Dooy** [comment]
修复的 128k变为 128000 其他都没问题了
你指的问题是计算公式跟后台对不上 
回复数：是你预算设的max_tokens 指gpt回答 只会比这个数少 是小于等于的关系

**Comment by bobandbrony** [comment]
> 修复的 128k变为 128000 其他都没问题了 你指的问题是计算公式跟后台对不上 回复数：是你预算设的max_tokens 指gpt回答 只会比这个数少 是小于等于的关系

原来如此，感谢解答
