### ISSUE TITLE
上传失败:Request failed with status code 404

### ISSUE THREAD

**Issue by WhitorS** [Dooy/chatgpt-web-midjourney-proxy#67]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/156129638/fb997310-d4ba-4995-930e-8e0c92c54d81)
无论是上传docx文档还是图片，都提示“上传失败:Request failed with status code 404”

**Comment by WhitorS** [comment]
不好意思，我是个纯小白。
我使用了自定义API接口和Key（国内的转发API）
在其他的工具中是可以正常使用这些功能的，但是在您的工具中无法正常使用。请问我应该怎么做？

**Comment by Dooy** [comment]
> 不好意思，我是个纯小白。 我使用了自定义API接口和Key（国内的转发API） 在其他的工具中是可以正常使用这些功能的，但是在您的工具中无法正常使用。请问我应该怎么做？

国内的中转 需要自己配置下，readme 里面都有upload的格式；
实在不行 你自己`docker run` 把key放环境变量 把upload打开`API_UPLOADER =1`
