### ISSUE TITLE
Vercel部署环境变量未生效

### ISSUE THREAD

**Issue by jason-xiaobaiai** [Dooy/chatgpt-web-midjourney-proxy#7]
fork仓库后使用Vercel部署，填入的环境变量API_UPLOADER、MJ_SERVER、OPENAI_API_BASE_URL前端未生效，仍需在网页填入MJ_SERVER、OPENAI_API_BASE_URL变量

**Comment by Dooy** [comment]
API_UPLOADER 是不成功的 因为Vercel 不提文件 存放路径啊，
但是MJ_SERVER、OPENAI_API_BASE_URL 是有效果的啊

还有 openai 已经把 Vercel的ip封了；最好搞一个代理或者中转

**Comment by suger404** [comment]
我也是一样的问题，这些都没有生效

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/101552636/6d5adc3c-88d1-419f-a047-6230a81b0993)

**Comment by Dooy** [comment]
vercel 支持的环境变量有限 看这个issue  #9

**Comment by sunsky89757** [comment]
+1，作者大大，MJ_SERVER、OPENAI_API_BASE_URL这两个环境变量vercel部署也是无效的哦~

**Comment by Dooy** [comment]
> +1，作者大大，MJ_SERVER、OPENAI_API_BASE_URL这两个环境变量vercel部署也是无效的哦~

早都解决了 看下 readme的`env环境变量`
