### ISSUE TITLE
后续可以增加读取gpts共享link吗？可以自己训练gpts吗？

### ISSUE THREAD

**Issue by zyjfly** [Dooy/chatgpt-web-midjourney-proxy#70]

**Comment by zyjfly** [comment]
后续更新会完善gpts功能吗，想使用别人分享的gpts的link，或者自己训练gpts

**Comment by Dooy** [comment]
就是增加一个收录接口呗？

**Comment by Dooy** [comment]
记起来了 这个是支持的
你可以参试下 https://vercel.ddaiai.com/#/g/g-2fkFE8rbu

把 https://chat.openai.com/g/g-2fkFE8rbu
修改为 https://vercel.ddaiai.com/#/g/g-2fkFE8rbu
