### ISSUE TITLE
关于mj生图后的seed无法正常获取的问题

### ISSUE THREAD

**Issue by sunsky89757** [Dooy/chatgpt-web-midjourney-proxy#73]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/113254524/12daafc1-8760-4fdf-b74b-df4c64176172)
大佬这里只显示获取中，无法复制到seed，我使用的vercel部署。

**Comment by Dooy** [comment]
需要后端支持，可能后端不支持获取 seed
