### ISSUE TITLE
Support New-api like api ?

### ISSUE THREAD

**Issue by panxiaoguang** [Dooy/chatgpt-web-midjourney-proxy#74]
Hi, Do you have plans to support the new-api format, which merges the midjourney proxy API into the uniform API? That would be highly easy because users never need to build another server to proxy midjourney.

this is new-api project:https://github.com/Calcium-Ion/new-api
The similar service that has similar api: https://www.openai-hk.com/docs/midjourney/guide.html

**Comment by Dooy** [comment]
这个new-api 的后端也是 `midjourney-proxy-plus`  api的格式
应该是支持的 目前我们的midjourney 前端就是  `midjourney-proxy-plus`  api的格式啊

你试过是有问题么？

**Comment by panxiaoguang** [comment]
> 这个new-api 的后端也是 `midjourney-proxy-plus` api的格式 应该是支持的 目前我们的midjourney 前端就是 `midjourney-proxy-plus` api的格式啊
> 
> 你试过是有问题么？

<img width="1104" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/43256809/a069acf7-e986-47a5-858a-d6545c4cf314">
It will raise errors"[Unexpected token 'A', "A server e"... is not valid JSON]"

**Comment by panxiaoguang** [comment]
> > 这个new-api 的后端也是 `midjourney-proxy-plus` api的格式 应该是支持的 目前我们的midjourney 前端就是 `midjourney-proxy-plus` api的格式啊
> > 你试过是有问题么？
> 
> <img alt="image" width="1104" src="https://private-user-images.githubusercontent.com/43256809/296550912-a069acf7-e986-47a5-858a-d6545c4cf314.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzcwODQsIm5iZiI6MTcwNTIzNjc4NCwicGF0aCI6Ii80MzI1NjgwOS8yOTY1NTA5MTItYTA2OWFjZjctZTk4Ni00N2E1LTg1OGEtZDY1NDVjNGNmMzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDEyNTMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MjAwOTZhZmUxZDkyY2M1MjhiYmYwNDNjNjlkMDE1MmNiNDQyM2RlMDRjY2ZkODEzNzI1YzFkMGFhZmM4Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iGtrjU1OtST9Ke9j56Vl-0caWquAL3gaRl7D0keCins"> It will raise errors"[Unexpected token 'A', "A server e"... is not valid JSON]"

<img width="658" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/43256809/0c20ef7b-8880-4606-a911-73f8237bd654">
I can only set openai secreat and api-base

**Comment by Dooy** [comment]
需要在 `Midjourney相关`的地方 也设置下
 api-base 跟 secreat 跟`OpenAI相关`一样的
<img width="637" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/e238a591-ebaf-4df8-9638-c1174230ddf1">

**Comment by panxiaoguang** [comment]
> 需要在 `Midjourney相关`的地方 也设置下 api-base 跟 sercet 跟`OpenAI相关`一样的 <img alt="image" width="637" src="https://private-user-images.githubusercontent.com/3765401/296551113-e238a591-ebaf-4df8-9638-c1174230ddf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzczOTYsIm5iZiI6MTcwNTIzNzA5NiwicGF0aCI6Ii8zNzY1NDAxLzI5NjU1MTExMy1lMjM4YTU5MS1lYmFmLTRkZjgtOTYzOC1jMTE3NDIzMGRkZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTI1ODE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjdlYjQ3MTNmZDhjOTY2OTExNjJjOGI0MGIwOGQ3NjBmMjZlNTI5MzU0MjgxNmFkYjE1ZTM0NTg3NjAzZDdhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n_JAUO_z95fhkV55lvNo_-sweMD0_UI7tzFgmVKLbmQ">

Thank you so much!
