### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by sunsky89757** [Dooy/chatgpt-web-midjourney-proxy#75]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/113254524/60dae8bc-5a9c-4713-a207-25ec34ac1f7e)
此处目前实现方式是共享预设，可否做成每个对话独享形式？这样对话内容可以作为单独的案例长期存储使用。

**Comment by Dooy** [comment]
收到 后续版本加上

**Comment by sunsky89757** [comment]
已看到新版功能，谢谢大大
