### ISSUE TITLE
I don't have the  whisper-tts model

### ISSUE THREAD

**Issue by panxiaoguang** [Dooy/chatgpt-web-midjourney-proxy#76]
I have upgrade to the latest version and rebuilt in vercel, But I don't have a voice function.
<img width="529" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/43256809/0e1a11cf-9a28-43e7-ba54-62357ceb06f8">

**Comment by Dooy** [comment]
please check the version is `Version - 2.14.2`

<img width="716" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/2a4ea9eb-4ecb-4832-aeb0-02178f347ebc">

**Comment by panxiaoguang** [comment]
> please check the version is `Version - 2.14.2`
> 
> <img alt="image" width="716" src="https://private-user-images.githubusercontent.com/3765401/296822583-2a4ea9eb-4ecb-4832-aeb0-02178f347ebc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzg2NzgsIm5iZiI6MTcwNTMzODM3OCwicGF0aCI6Ii8zNzY1NDAxLzI5NjgyMjU4My0yYTRlYTllYi00ZWNiLTQ4MzItYWViMC0wMjE3OGYzNDdlYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMTcwNjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUzZGE2YjYzOWJiMzBhNGE1NzE5OTMzM2YxZGM5NmJhMDhiYmNiN2UzOWQ5ZGFjMGVlZmIyZWE2ODljMzZiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V0njqjk1bDB8OkAMBR6EapSgjmuS6qbx67d8kpk3co8">

Yes, it is. this is my link. https://www.testaigc.shop/

**Comment by Dooy** [comment]
Can you rebuid it again? It could be my code from yesterday

**Comment by panxiaoguang** [comment]
> Can you rebuid it again? It could be my code from yesterday

Actually I fork your latest code and build again and again.

<img width="924" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/43256809/d0cbee35-3444-411e-ab72-eb6ce8fe3a41">

**Comment by Dooy** [comment]
https://my-test-v2-14-2.vercel.app/#/chat/1002

No problem， This is the vercel project which I just built.

**Comment by panxiaoguang** [comment]
> https://my-test-v2-14-2.vercel.app/#/chat/1002
> 
> No problem， This is the vercel project which I just built.

ok, that's very wiered
