### ISSUE TITLE
使用Vercel部署，配置了环境变量没有生效

### ISSUE THREAD

**Issue by superhikers** [Dooy/chatgpt-web-midjourney-proxy#77]
使用Vercel部署，配置了环境变量没有生效
![1705378032435](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/45871093/2f9e4ba8-fc83-4f54-bb7c-33e28968484a)

**Comment by panxiaoguang** [comment]
重新启动了吗？配置玩环境变量要重新deploy一下

**Comment by superhikers** [comment]
> 配置环境变量要重新deploy一下

重启了，我发现设置的访问密码是生效的，但是设置的OPENAI_API_BASE_URL和OPENAI_API_KEY，重启进入后还是没有默认值，直接访问还是提示错误
![1705394433030](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/45871093/fd9e9d53-0820-439d-a847-4d05024ed64e)
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/45871093/f8a1c11e-853a-4b86-baf6-2727c141ce38)

**Comment by panxiaoguang** [comment]
> > 配置环境变量要重新deploy一下
> 
> 重启了，我发现设置的访问密码是生效的，但是设置的OPENAI_API_BASE_URL和OPENAI_API_KEY，重启进入后还是没有默认值，直接访问还是提示错误 ![1705394433030](https://private-user-images.githubusercontent.com/45871093/296983675-fd9e9d53-0820-439d-a847-4d05024ed64e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTQ4OTEsIm5iZiI6MTcwNTM5NDU5MSwicGF0aCI6Ii80NTg3MTA5My8yOTY5ODM2NzUtZmQ5ZTlkNTMtMDgyMC00MzlkLWE4NDctNGQwNTAyNGVkNjRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4NDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MjBmMjQ4NmU0NTY1NzE2OWUwNmVjN2ZjZGQwYzQ3YmE3MDgzMDdmOGNkZjVjNDE4Mjg4MGNkZmFkNmQ3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._toisbvMI6KfdSjF8qHD54v0rP5AH0cnJK7xQjjKUTQ) ![image](https://private-user-images.githubusercontent.com/45871093/296983909-f8a1c11e-853a-4b86-baf6-2727c141ce38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTQ4OTEsIm5iZiI6MTcwNTM5NDU5MSwicGF0aCI6Ii80NTg3MTA5My8yOTY5ODM5MDktZjhhMWMxMWUtODUzYS00Yjg2LWJhZjYtMjcyN2MxNDFjZTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4NDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YWFhODQ5NTE4ZjBhNWJlYjJiOWY3NjczYTlhMjhjZjk2ZDQzODdkMjI0NjJiYTM1MzhiNGM0NjcxZWMyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3J13pqPwRPsa9YPe1BSTEcaAw013b2-5qDJHtdBYKpg)

在你页面的设置里如果有填地址的话，要去掉，因为会覆盖。另外可以在页面设置的服务端填写你的地址和key测试一下是否是你的key有问题。我觉得可以这么拍出错误

**Comment by tenglei87** [comment]
我也是同样的问题，openai key没生效

**Comment by Dooy** [comment]
> 我也是同样的问题，midjounery可以使用，chatgpt就有问题，只能前端再设置下

贴下`提示`+ `F12的返回network的返回`

**Comment by Dooy** [comment]
ok 我再测试下

**Comment by xiaoyucom1** [comment]
> ok 我再测试下

![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/21190029/25db342f-149e-48d9-b867-ea666ee514ea)大佬我用vercel部署的，发现服务从这个节点发起的时候，就会超时，感觉是vercel的问题吧

**Comment by Dooy** [comment]
我测试 没问题
https://my-test-tau-teal.vercel.app/
大家可以用下 只是发现 vercel 不支持流输出
你们的 环境变量应该是app建立后，然后重新编辑的吧？
重新编辑需要 redeploy 自己找下 这个按钮

**Comment by tenglei87** [comment]
> 我测试 没问题 https://my-test-tau-teal.vercel.app/ 大家可以用下 只是发现 vercel 不支持流输出 你们的 环境变量应该是app建立后，然后重新编辑的吧？ 重新编辑需要 redeploy 自己找下 这个按钮

是redeploy 的，但是同样新增的访问密码却生效了的，midjounery同样也生效，就chatgpt不行

**Comment by Dooy** [comment]
你是不是 直连 api.openai.com ？
OPENAI_API_BASE_URL 是 api.openai.com 
vercel的ip 好像被 openai 禁用了

**Comment by Dooy** [comment]
我这个demo 你们能用吧？

**Comment by xiaoyucom1** [comment]
用的别家的中转，发现有的请求会超时，应该是vercel的问题

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月20日(周六) 晚上6:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Dooy/chatgpt-web-midjourney-proxy] 使用Vercel部署，配置了环境变量没有生效 (Issue #77)




 
你是不是 直连 api.openai.com ？
 OPENAI_API_BASE_URL 是 api.openai.com
 vercel的ip 好像被 openai 禁用了

**Comment by xiaoyucom1** [comment]
> 我这个demo 你们能用吧？
可以用的，大佬

**Comment by tenglei87** [comment]
> 你是不是 直连 api.openai.com ？ OPENAI_API_BASE_URL 是 api.openai.com vercel的ip 好像被 openai 禁用了

都是第三方代理的，但是前端界面设置API跟地址是可以用的，暂时就先这样了，重新删掉再部署都一样~~~

**Comment by Dooy** [comment]
504是timeout  是 vercel 连不上你们的第三份代理

**Comment by xiaoyucom1** [comment]
> 504是timeout 是 vercel 连不上你们的第三份代理

所以已经舍弃vercel了,时好时坏...跑去拿docker跑了
