### ISSUE TITLE
如何获取customId?

### ISSUE THREAD

**Issue by cll0129** [Dooy/chatgpt-web-midjourney-proxy#78]

**Comment by cll0129** [comment]
<img width="486" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/37129401/c32d06ee-cdef-4e6f-92e4-27f27f2c333a">
缺少customId，请问怎么获取呢

**Comment by Dooy** [comment]
有提示？ 看你JSON 好像是在做 局部绘图

**Comment by cll0129** [comment]
> 有提示？ 看你JSON 好像是在做 局部绘图

是的，局部绘图传给后端的参数需要一个customId，但是没找到这个是怎么生成的
