### ISSUE TITLE
上传文件可以用那些存储服务呢

### ISSUE THREAD

**Issue by lyzcodebool** [Dooy/chatgpt-web-midjourney-proxy#79]
这个上传文件很需要，但是使用中转基本都不支持，可以配置或者修改为上传到服务器本地吗

**Comment by Dooy** [comment]
看下 readme.md 可以配置用 `cloudflare R2存储`

**Comment by zhubao12378** [comment]
可以固定配置么，比如取消上传设置的up地址，或者取消遵循上传跟随中专的逻辑，改为部署时固定设置一个上传地址不因设定改变，因为现在One-api跳转的话，不会去设置上传地址，就会直接填入base url,这样用户无法知己体验上传功能

**Comment by Dooy** [comment]
<img width="624" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/51db8279-526f-4a7f-955f-a5ec538f7ac7">

**Comment by panxiaoguang** [comment]
> <img alt="image" width="624" src="https://private-user-images.githubusercontent.com/3765401/297249848-51db8279-526f-4a7f-955f-a5ec538f7ac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODI5NjMsIm5iZiI6MTcwNTU4MjY2MywicGF0aCI6Ii8zNzY1NDAxLzI5NzI0OTg0OC01MWRiODI3OS01MjZmLTRhN2YtOTU1Zi1hNWVjNTM4ZjdhYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMTI1NzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVhOGZmMmMzOWMxZDM5ZjMyOTAzMjllYTU5NzM0M2Y1ZjI4NWY3OWE3NjQzZDM5NDExNjQwZjUzZDRjYjk2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6Pxb160lgukJWPTE_LssyZ83rIr5JmHp4-svs4w-ovc">

大佬，为啥我设置了R2要求的那些环境变量特别是R2_DOMAIN，还设置了API_UPLOADER为空字符串。为啥控制台显示上传的链接总是这个啊？https://我的vercel应用域名/openapi/v1/upload。看您的代码，如果isUpload为false的话，应该跳过这个直接去R2upload啊

**Comment by Dooy** [comment]
1. 确定下版本 是不是 `v2.14.2` 以上
2. vercel目前不支持

**Comment by panxiaoguang** [comment]
> 只要你设置上 R2_DOMAIN 就他最大了，都有随这 R2_DOMAIN 走了

#82 #77 这里遇到的是相同的问题，在vercel部署的项目，虽然环境变量设置了openai_base_url, 但是如果在前端页面的服务端不设置的话，我F12看到访问的都是我自己域名为前缀的API（显然我不是API中转商，我自己的域名只是这个开源项目用的域名而已）。DALLE是这样，R2上传也是这样，即使环境变量添加了R2_DOMAIN，也无济于事。除非就是您README写的Vercel不支持任何文件上传。否则很难理解这个。

**Comment by Dooy** [comment]
R2 文件服务不支持 vercel

**Comment by panxiaoguang** [comment]
> R2 文件服务不支持 vercel

怪不得😏
