### ISSUE TITLE
超链配置

### ISSUE THREAD

**Issue by zyyint** [Dooy/chatgpt-web-midjourney-proxy#80]
貌似超链配置之后影响了本地文件上传，模型4.0all,文件类型：pdf,不使用超链配置不受影响

**Comment by Dooy** [comment]
<img width="624" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/55edb69c-929a-4dc5-aa83-a0bd0427131e">

可以自己设置

**Comment by zyyint** [comment]
本地上传如何设置？

**Comment by zyyint** [comment]
你这个是网盘上传的方式吧？

**Comment by Dooy** [comment]
看下readme 可以配置文件上传支持 `cloudflare r2 存储` `免费10G`
