### ISSUE TITLE
[Unexpected token 'A', "An error o"... is not valid JSON]

### ISSUE THREAD

**Issue by panxiaoguang** [Dooy/chatgpt-web-midjourney-proxy#82]
<img width="1102" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/43256809/4ed89b90-0ce3-4f54-ad7b-17bd2b69058f">
<img width="1343" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/43256809/9b5acd4f-f9f3-4f77-8b6c-046b7ae5f8f0">
<img width="1320" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/43256809/c084ce16-a945-4edf-b3b3-dfe09da9f9da">

明明API也调用了，但是页面却报错
请勿关闭! 图片生成中...
[Unexpected token 'A', "An error o"... is not valid JSON]

**Comment by Dooy** [comment]
你F12 看看 网络请求 返回来是什么

**Comment by panxiaoguang** [comment]
> 你F12 看看 网络请求 返回来是什么
这个，但我去看了vercel的building log，没有任何报错啊
An error occurred with your deployment

FUNCTION_INVOCATION_TIMEOUT

**Comment by Dooy** [comment]
就用浏览器看 不用到 vercel 后台看

<img width="684" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/246ec796-0945-411a-9dc4-75455c42e5b3">

**Comment by panxiaoguang** [comment]
找到原因了，必须在前台的服务端设置base_url 和 api_key, 在环境变量设置的无效。
<img width="797" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/43256809/0d536f24-0488-40c4-ac77-ac66b470ee6c">
设置在环境变量里的值请求的链接是不对的，https://{我应用的url}/openapi/v1/images/generations。他应该请求的是API的URL。这个和我在另一个里面提的R2上传似乎是一个问题。
