### ISSUE TITLE
绘图提交报错

### ISSUE THREAD

**Issue by chenwei39094342** [Dooy/chatgpt-web-midjourney-proxy#83]
{
  "error": {
    "type": "invalid_request_error",
    "code": "unknown_url",
    "message": "Unknown request URL: POST /mj/submit/blend. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.",
    "param": null
  }
}
这什么意思？

**Comment by Dooy** [comment]
需要后端  `midjourney-proxy` 支持
看下readme
