### ISSUE TITLE
网络代理的参数怎么设置？是哪个字段？

### ISSUE THREAD

**Issue by chenwei39094342** [Dooy/chatgpt-web-midjourney-proxy#84]
我用http_proxy和https_proxy都不行

**Comment by Dooy** [comment]
目前不支持这种方式 建议用中转

**Comment by chenwei39094342** [comment]
补充一下我是通过docker部署的啊，midjourney-proxy都有相应参数可以设置啊？

**Comment by Dooy** [comment]
这些都用不到 `http_proxy` `https_proxy`
