### ISSUE TITLE
temperature 和 top_p的设置能加入下吗？

### ISSUE THREAD

**Issue by wendaleruan** [Dooy/chatgpt-web-midjourney-proxy#86]
temperature 和 top_p的设置能加入下吗？
changelog里面有，但是设置里面没有

**Comment by Dooy** [comment]
确实被我写死了 下个版本我再加进来

**Comment by Dooy** [comment]
v2.14.7 已修复

<img width="612" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/0b9e2264-1f44-4dc1-8ccc-cad119485229">
