### ISSUE TITLE
为什么识别不到我上传的文件？

### ISSUE THREAD

**Issue by dejavuhuh** [Dooy/chatgpt-web-midjourney-proxy#87]
<img width="1195" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/65352984/2344a683-fc92-4c31-94e3-2e459a21ddae">
Cloudflare R2的桶里面已经能看到上传的文件了。。

**Comment by Dooy** [comment]
R2 最好选美洲地区的服务器 ；我发现openai 下载文件超过10秒 就不下了

**Comment by dejavuhuh** [comment]
<img width="401" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/65352984/c22783ea-a9b8-4272-9032-a4b1b9eeb3e9">
是美洲的

**Comment by NEPDream** [comment]
R2里面的内容需要key和secret才能访问，openai如果没有r2的token，key和secret的话，是不是无法看到我们上传的文件内容了

**Comment by NEPDream** [comment]
哦，我发现这个项目是使用的R2的custom domain来访问文件的，所以R2_DOMAIN变量，你不要填那个cloudflare的s3的endpoint，而是去填对应的custom domain地址就不会出现读取不到你的文件内容的问题了。

**Comment by Dooy** [comment]
不知道 兄台解决了否？ 我先关闭哈
