### ISSUE TITLE
画面显示不完整

### ISSUE THREAD

**Issue by zyyint** [Dooy/chatgpt-web-midjourney-proxy#89]
手机端![Screenshot_2024-01-19-23-36-42-330_com.android.browser.png](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/143329494/121bf79c-a2c3-46d7-8a33-d0dbf97a1bff)

显示收入右下角蓝色显示字符的字体只有半截

**Comment by Dooy** [comment]
收到 下个版本 更新

**Comment by Dooy** [comment]
v2.14.6 已经修改好了 请更新
