### ISSUE TITLE
vercel环境变量未生效，请问该怎么设置

### ISSUE THREAD

**Issue by suger404** [Dooy/chatgpt-web-midjourney-proxy#9]
![image](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/101552636/729c0265-e7ce-4d17-a622-08e0f0959fa9)

**Comment by Dooy** [comment]
vercel 仅支持 4个环境变量
OPENAI_API_KEY，OPENAI_API_BASE_URL，MJ_SERVER，MJ_API_SECRET

可以点这个 直接一键部署

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://github.com/Dooy/chatgpt-web-midjourney-proxy&env=OPENAI_API_BASE_URL&env=OPENAI_API_KEY&env=MJ_SERVER&env=MJ_API_SECRET&project-name=chatgpt-web-midjourney-proxy&repository-name=chatgpt-web-midjourney-proxy)
