### ISSUE TITLE
[ BUG ] 设置了 OPENAI_API_BASE_URL 和 MJ_SERVER 但没起作用

### ISSUE THREAD

**Issue by bbb3n** [Dooy/chatgpt-web-midjourney-proxy#90]
我在 Vercel 变量里设置了 OPENAI_API_BASE_URL 和 MJ_SERVER ，如下图所示
![Screenshot_20240121-173759_Edge](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129975925/1de183ec-c1fa-42ee-b027-0f018ad0b90c)

但是部署成功后，网页上没有显示。如下图所示
![Screenshot_20240121_173844](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129975925/d268183c-f4f5-45a1-bc41-d66d6d798db2)

实际测试发现：不填key，直接发送请求，会返回中转的错误，也就是变量生效了。但是前端没显示，而且如果直接填入key，base url还是空着的话，直接发送请求，还是会报没填key的错误。

**Comment by Dooy** [comment]
#77 建议你看下这个issue #77，我这里面留有测试demo

**Comment by Dooy** [comment]
你的设想是 环境变量的url跟 前端的key 要混用？
但是这2套没法混用 设计是为满足不同需求的

环境变量的url 与key 是为了隐藏自己的key 就是一套key多人使用 但是不想给使用的人知道我的key
前端设置的url 与key 更多是为了满足 有自己的key但不想搭建web服务的客户

这2套有优先顺序 就是先满足前端设置的 如果没有就走环境变量的路线

环境变量路线：客户->web服务->中转或者openai服务
前端设置路线：客户->中转或者openai服务

关于你说的验证是有缺陷
