### ISSUE TITLE
语音对话bot会重复用户的话

### ISSUE THREAD

**Issue by LeoLin4258** [Dooy/chatgpt-web-midjourney-proxy#91]
选择TTS-1后，用户语音输入，bot只会重复用户的话

**Comment by Dooy** [comment]
新版本换到这个地方 
<img width="492" alt="image" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/3765401/73515268-93ca-498a-99a9-18cb4e263c6a">

**Comment by LeoLin4258** [comment]
![17948da4aa436e019f7b0ab20ea7b65](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/146353430/8094d1a3-6251-4b44-8117-87bfab4867a9)
已经是最新版本，貌似是用户输入的语音转文字后，直接将这个文字传给了speech。最终bot只会重复用户的话

**Comment by Dooy** [comment]
你别选tts-1 选择gpt-3.5 就好

**Comment by LeoLin4258** [comment]
了解，感谢！
