### ISSUE TITLE
API响应问题

### ISSUE THREAD

**Issue by Bensonlam168** [Dooy/chatgpt-web-midjourney-proxy#92]
你好，我发现一个很奇怪的问题，如果在代码里把URL和key绑好直接用，那无论写不写那个"modes":["fast"]，mj从发任务到显示图片都是10分钟，无论是用你的API还是别人的，但在客户端的服务设置里填，就一分钟左右，也无论是用你的API还是别人的，请问这是什么情况？

**Comment by Dooy** [comment]
试下 `"modes":["FAST"]`

**Comment by Bensonlam168** [comment]
<img width="407" alt="截圖 2024-01-21 下午10 04 58" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/117271809/39aa5d48-44f1-41fc-bf12-6f56252fe6bb">
试过了，不行哦

**Comment by Dooy** [comment]
mj 如果是10分钟 一般都超时了 也不知道 哪儿设置有问题

**Comment by Dooy** [comment]
服务端里填 没问题 是不？

**Comment by Bensonlam168** [comment]
嗯嗯，服务端里填就没问题，其实前天还是好好的，今天突然就这样了，非常奇怪

**Comment by Dooy** [comment]
你是用docker 还是用 vercel ?

**Comment by Dooy** [comment]
回头 我检查下

**Comment by Bensonlam168** [comment]
之前部署的时候代码里是先填了别人的，然后前天发现你的API站，就在服务端填了，感觉不错，今天就填了代码重新发布，然后就发现问题了

**Comment by Dooy** [comment]
UI服务端 跟后端 其实 代码都是一样的
但是请求路线不一致

UI服务端：你的web浏览器->中转
后端：你的web浏览器->后端的docker->中转  

你可能需要检查下 这其中的线路

**Comment by Bensonlam168** [comment]
<img width="651" alt="截圖 2024-01-21 下午10 15 55" src="https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/117271809/8f7a6012-0ea3-49ab-9623-04eedc4579bb">
它就一直这样，5秒一跳，直到9-10分钟左右，就提升“重新载入”，点击后大概1分钟就显示出来

**Comment by Bensonlam168** [comment]
我都放在一起容器里，按理没有这转来转去的问题呀

**Comment by Dooy** [comment]
这么奇怪

**Comment by Bensonlam168** [comment]
对啊，我也是觉得很纳闷，按理UI服务端填了，走的也是后端一样的路线，但为什么会有区别，这个就很纳闷

**Comment by Dooy** [comment]
这边测试 没有问题

这个是有人搭建在 后端请求的 https://web.addmao.com  你可以测试下
