### ISSUE TITLE
请问Vercel部署支持cloudflare r2 存储吗，以及一些其他问题

### ISSUE THREAD

**Issue by wdc63** [Dooy/chatgpt-web-midjourney-proxy#94]
1 Vercel部署支持cloudflare r2 存储吗，具体应该如何配置，有没有相关教程
2 如何自定义一些界面，例如能不能在GPTs中自定义可以用哪些gpts、能不能关闭midjourney等

**Comment by Dooy** [comment]
1 不支持
2 直接可以用超链 readme有说

✅ 支持ChatGPT试的超链模型切换 https://chat.openai.com/g/g-2fkFE8rbu 修改为 https://vercel.ddaiai.com/#/g/g-2fkFE8rbu

**Comment by Dooy** [comment]
1. 有一个`cloudflare r2 ` 私密请求 这个需要cloudflare的库支持 Vercel不支持
2. GPTs 控制显示 具体可以自己实现 格式看下请求就能看到

**Comment by wdc63** [comment]
> 1. 有一个`cloudflare r2 ` 私密请求 这个需要cloudflare的库支持 Vercel不支持
> 2. GPTs 控制显示 具体可以自己实现 格式看下请求就能看到

谢谢，我试试，请问GPTs 控制显示需要自己改代码吗，具体是哪些代码负责这个页面的？

**Comment by wdc63** [comment]
> 1. 有一个`cloudflare r2 ` 私密请求 这个需要cloudflare的库支持 Vercel不支持
> 2. GPTs 控制显示 具体可以自己实现 格式看下请求就能看到

后面可以考虑阿里云、腾讯云、七牛云这些对象存储服务呢

**Comment by Dooy** [comment]
我的经验是 别考虑国内的云了 

因为我们传的文件给ChatGPT读的； ChatGPT过来下载文件 超过10秒 就不工作了

**Comment by wdc63** [comment]
> 我的建议是 别考虑国内的云了
> 
> 因为我们传的文件给ChatGPT读的； ChatGPT过来下载文件 超过10秒 就不工作了

国内大厂云的服务器和存储服务都有外国的，像是美国硅谷这些地方的啊

**Comment by Dooy** [comment]
目前没这方面的开发计划，

如果有开发能力帮忙实现 并PR上来
