### ISSUE TITLE
生成图片，提示 “提交中 [Unexpected token '<', "<!DOCTYPE "... is not valid JSON]”

### ISSUE THREAD

**Issue by elenno** [Dooy/chatgpt-web-midjourney-proxy#96]

**Comment by Dooy** [comment]
需要你的中转后端支持

**Comment by potus2030** [comment]
提交中
[Unexpected token 'A', "A server e"... is not valid JSON], 同样问题。 都是部署在海外服务器，应该不需要中转吧？

**Comment by Dooy** [comment]
需要 midjourney-proxy 后端支持
看下 readme如何部署 midjourney-proxy

**Comment by duhd1993** [comment]
点重绘也会出现这个错误，这个不应该吧，重绘只是把请求重新提交一次。@Dooy

**Comment by Dooy** [comment]
局部重绘 跟重绘 感念不一样
