### ISSUE TITLE
[BUG] 剩余 token 的框框被挡住了

### ISSUE THREAD

**Issue by bbb3n** [Dooy/chatgpt-web-midjourney-proxy#98]
如下图所示
![Screenshot_20240123_124613](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129975925/f55c9807-8223-4e09-aff1-259cda1170b2)

我自己看了一下代码，但是技术有限，还是没搞明白为啥

**Comment by Dooy** [comment]
下个版本 我搞出来

**Comment by Dooy** [comment]
v2.14.6 已经改好了
