### ISSUE TITLE
[BUG] 在聊天界面时，点击 绘图 ，第一次会打不开，需要点2-3次

### ISSUE THREAD

**Issue by B3nDan** [Dooy/chatgpt-web-midjourney-proxy#99]
https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/129975925/63765b5e-137a-4611-8b1f-8fba1edee794

试了 Edge Chrome Safari 的手机浏览器，都会这样：
- 第一次点击后，聊天框会收下去，但是 绘图 的框不会弹出来
- 再点一次，它才会弹出来

**Comment by Dooy** [comment]
收到 我查看看何原因

**Comment by Dooy** [comment]
v2.14.7 看是否 合适你的预期

**Comment by Dooy** [comment]
下个版本 根据下

**Comment by Dooy** [comment]
我明白 我意思是下个版本 修复 然后你再更新

**Comment by Dooy** [comment]
v2.14.8 版本已经更新
